.github/PULL_REQUEST_TEMPLATE
api-microservice/package-lock.json
ux-microservice/package-lock.json
ux-microservice/package.json

Description of PR...
- Item 1
- Item 2
Fixes #85, Fixes #22, Fixes username/repo#123
Connects #123

chore(setup): Add gov-uk frontend and restify dependencies

---

README.md
api-microservice/Dockerfile
api-microservice/package.json

- Added a multi-stage dockerfile to compile and run the app.
- Updated the README with a brain dump of info.

Add a Dockerfile for Containerization of REST API.

---

api-microservice/.eslintrc
api-microservice/jest.config.js
api-microservice/package-lock.json
api-microservice/package.json
api-microservice/tests/config/Config.spec.ts
api-microservice/tsconfig.json

- Configured Jest for TypeScript
- Tweak config and runners

chore(setup): Add Jest for unit testing

---

README.md
ux-microservice/package.json

Added info on how to get the apps configured and running.
- Made changes to the README
- Small big fix to node-sass cli call.

chore(setup): Update README

---

ux-microservice/.eslintrc
ux-microservice/.prettierrc
ux-microservice/app.js
ux-microservice/bin/www
ux-microservice/package-lock.json
ux-microservice/package.json
ux-microservice/routes/index.js
ux-microservice/routes/users.js

Add code style checking, formatting and husky for formatting on pre-commit hook.

chore(setup): Add linting for UX service

---

services/forms-web-app/src/views/layouts/main.njk

- Removed include of broken cookie banner template in layout file.

fix(no-decision) - Removed broken cookie banner

---

services/forms-web-app/src/controllers/eligibility.js
services/forms-web-app/src/controllers/index.js
services/forms-web-app/src/routes/eligibility.js
services/forms-web-app/src/routes/index.js

- Add controller for eligibility router.
- Add controller for index router.

fix(no-decision) - Create controllers for routes

---

.github/workflows/appeals-service-api.yml
.github/workflows/forms-web-app.yml

chore(setup): update app builds to generate a versioned image

---

.github/workflows/forms-web-app.yml
forms-web-app/package-lock.json
forms-web-app/package.json
forms-web-app/tests/unit/controllers/eligibility.test.js
forms-web-app/tests/unit/mocks.js

- Created tests in controllers/eligibility.tests.js to check we're calling the correct template.
- Create small mock library to mock the express req, res.

fix(eligibility-controller-unit-tests) - Added starter unit tests for eligibility controller

---

.github/workflows/appeals-service-api.yml
.github/workflows/commit.yml
.github/workflows/forms-web-app.yml
README.md
commitlint.config.js
forms-web-app/package-lock.json
forms-web-app/package.json
package-lock.json
package.json

Configure commit lint for the CI. Also added commit hooks.
Hard-coded the earliest commit ID to check to 38b2eaa which is the last commit before this was implemented. #34 has been added on the off-chance it becomes necessary, but this should be fine.

Commit lint

---

.prettierrc
Makefile
commitlint.config.js
data/index.js
data/init.js
infrastructure/k8s/setup.sh
package-lock.json
package.json

Allow Flux releases to validate through commitlint

---

forms-web-app/src/controllers/eligibility.js
forms-web-app/src/views/eligibility/decision-date.njk

- Added a check for date in the future.

fix(future-date): entering a date later than today will now throw error

---

releases/dev/app.yml

Change from thesausage.blog to planninginspectorate.gov.uk

fix(dev): change dev url to pins domain

---

forms-web-app/src/views/eligibility/decision-date.njk

- Added 'novalidate' for <form> tag to remove the js validation on submit.

fix(remove-js-form-validation): added 'novalidate' to decision-date form

---

forms-web-app/package-lock.json
forms-web-app/package.json
forms-web-app/src/app.js
forms-web-app/src/views/eligibility/decision-date-expired.njk

- Installed 'nunjucks-date-filter' dependency.
- Used the 'date' filter to format the date on the 'expired' page.

fix(deadline-date): date formatting added

---

forms-web-app/src/views/eligibility/decision-date.njk

- Fixed link padding
- Fixed size of year field

fix(link-padding): removed the duplicate form-group div

---

.github/workflows/infra-environments.yml
.github/workflows/terraform-validate.yml
appeals-service-api/Dockerfile
charts/app/templates/appealsServiceApi.yaml
charts/app/templates/service.yaml
charts/app/values.yaml
docker-compose.yml
environments/dev.tfvars
infrastructure/environments/README.md
infrastructure/environments/mongodb.tf
infrastructure/environments/output.tf
infrastructure/environments/variables.tf
infrastructure/k8s/setup.sh
infrastructure/modules/mongodb-database/README.md
infrastructure/modules/mongodb-database/main.tf
infrastructure/modules/mongodb-database/output.tf
infrastructure/modules/mongodb-database/variables.tf
releases/dev/app.yml

See tickets UCD-865 and UCD-808

Add MongoDB and set up appeals-api-service in deployed infrastructure

---

forms-web-app/package.json
forms-web-app/src/controllers/appeal-statement.js
forms-web-app/src/controllers/listed-building.js
forms-web-app/src/lib/express-validation-errors-to-govuk-error-list.js
forms-web-app/src/routes/eligibility.js
forms-web-app/src/routes/validators/listed-building.js
forms-web-app/src/views/eligibility/appeal-statement.njk
forms-web-app/src/views/eligibility/listed-building.njk
forms-web-app/src/views/eligibility/listed-out.njk
forms-web-app/tests/unit/controllers/listed-building.test.js
forms-web-app/tests/unit/lib/express-validation-errors-to-govuk-error-list.test.js
forms-web-app/tests/unit/routes/validators/listed-building.test.js
forms-web-app/tests/unit/routes/validators/validation-middleware-helper.js

Adds listed building form happy & sad paths, express validator, and template for next step

feat(forms-web-app): add Listed Building form

---

Makefile
infrastructure/.terraform-docs.yml
infrastructure/common/README.md
infrastructure/common/main.tf
infrastructure/environments/README.md
infrastructure/environments/main.tf

Bit of housekeeping to autogenerate the Terraform Docs

chore: add command to auto-generate Terraform Documentation

---

forms-web-app/src/app.js
forms-web-app/src/controllers/appeal-statement.js
forms-web-app/src/controllers/task-list.js
forms-web-app/src/routes/eligibility.js
forms-web-app/src/routes/task-list.js
forms-web-app/src/views/eligibility/appeal-statement.njk
forms-web-app/src/views/task-list/index.njk
forms-web-app/tests/unit/controllers/appeal-statement.test.js
forms-web-app/tests/unit/controllers/task-list.test.js
forms-web-app/tests/unit/mocks.js

Adds "your appeal statement" page and placeholder for next step - /task-list

feat(forms-web-app): add "your appeal statement" page

---

.github/workflows/e2e-tests-on-PR.yml
.github/workflows/publish-cucumber-on-merge.yml
Makefile
README.md
e2e-tests/.gitignore
e2e-tests/cypress.json
e2e-tests/cypress/fixtures/README.md
e2e-tests/cypress/integration/PageObjects/PO_EligibilityDecisionDate.js
e2e-tests/cypress/integration/PageObjects/PO_EligibilityNoDecision.js
e2e-tests/cypress/integration/README.md
e2e-tests/cypress/integration/UCD745-EligibilityNoDecision.feature
e2e-tests/cypress/integration/UCD745-EligibilityNoDecision/EligibilityNoDecision.spec.js
e2e-tests/cypress/plugins/README.md
e2e-tests/cypress/plugins/index.js
e2e-tests/cypress/support/README.md
e2e-tests/cypress/support/commands.js
e2e-tests/cypress/support/index.js
e2e-tests/package-lock.json
e2e-tests/package.json
e2e-tests/reporter.js
package.json

Description of PR...
- add /e2e-tests to hold all things Cypress
- pull-requests trigger the Cypress tests
- pushing to master triggers the Cypress tests and publishes the results to https://foundry4.github.io/appeal-planning-decision/
- NB this PR contains some loose ends in terms of the specs themselves, but I would rather get a process in place quickly and then spend time understanding the tests we're writing/want to write.. hope a couple of rough edges are ok on that basis?

Wire cypress into ci

---

forms-web-app/src/views/eligibility/decision-date.njk

fix(decision-date): rebrand planning authority into planning department

---

releases/dev/app.yml

chore: release forms-web-app v1.3.1 to dev

---

.github/workflows/document-service-api.yml
Makefile
charts/app/templates/appealsServiceApi.yaml
charts/app/templates/documentServiceApi.yaml
charts/app/templates/formsWebApp.yaml
charts/app/templates/service.yaml
charts/app/values.yaml
docker-compose.yml
document-service-api/.eslintrc
document-service-api/.prettierrc
document-service-api/Dockerfile
document-service-api/README.md
document-service-api/package-lock.json
document-service-api/package.json
document-service-api/src/lib/config.js
document-service-api/src/lib/healthchecks.js
document-service-api/src/lib/logger.js
document-service-api/src/main.js
document-service-api/src/routes/index.js
document-service-api/src/schemas/documents.js
document-service-api/src/schemas/documentsMethods.js
document-service-api/src/schemas/documentsMethods.spec.js
document-service-api/src/server.js
environments/dev.tfvars

UCD-809
Create the base application of the Document Service API, add to the Helm chart and configure the new infrastructure

Create base Document Service API microservice + infra changes

---

forms-web-app/src/controllers/eligibility/planning-department.js
forms-web-app/src/lib/appeals-api-wrapper.js
forms-web-app/src/views/eligibility/planning-department.njk
forms-web-app/tests/unit/controllers/eligibility/planning-department.test.js

UCD-959
Add API call to get LPA list from Appeals Service API

fix(lpa-list): get lpa list from appeals service api

---

clusters/dev/app.yml

UCD-809
Add Document Service API

chore: add document service to release manifest

---

charts/app/templates/documentServiceApi.yaml
charts/app/values.yaml
docker-compose.yml
document-service-api/package-lock.json
document-service-api/package.json
infrastructure/environments/README.md
infrastructure/environments/output.tf
infrastructure/environments/storage.tf
infrastructure/environments/variables.tf

UCD-809
Add a local version of Azure Blob Storage to Docker Compose and add to infra

Add Azure Blob Storage

---

.github/workflows/forms-web-app.yml
appeals-service-api/src/server.js
common/src/utils.js
docker-compose.yml
document-service-api/src/server.js
forms-web-app/Dockerfile
forms-web-app/package-lock.json
forms-web-app/package.json
forms-web-app/src/app.js
forms-web-app/src/config.js
forms-web-app/src/lib/appeals-api-wrapper.js
forms-web-app/src/middleware/fetch-existing-appeal.js
forms-web-app/src/server.js
forms-web-app/src/views/error/not-found.njk
forms-web-app/src/views/error/unhandled-exception.njk
forms-web-app/tests/unit/lib/appeals-api-wrapper.test.js
forms-web-app/tests/unit/middleware/fetch-existing-appeal.test.js
forms-web-app/tests/unit/mocks.js

UCD-961
- Added some logging around the app
- Refactored the call to Appeals Service API to a handler function, with a timeout, logging etc
- Created base handlers for 404 and 500 errors inside Express
- Add fix in common to always `clearTimeout`

Improve logging and site reliability checks

---

forms-web-app/.eslintrc
forms-web-app/src/app.js
forms-web-app/src/controllers/confirmation.js
forms-web-app/src/controllers/eligibility/decision-date.js
forms-web-app/src/controllers/eligibility/listed-building.js
forms-web-app/src/controllers/eligibility/planning-department.js
forms-web-app/src/controllers/submission.js
forms-web-app/src/controllers/your-details.js
forms-web-app/src/routes/confirmation.js
forms-web-app/src/routes/submission.js
forms-web-app/src/validators/submission.js
forms-web-app/src/views/confirmation/index.njk
forms-web-app/src/views/submission/index.njk
forms-web-app/tests/unit/controllers/confirmation.test.js
forms-web-app/tests/unit/controllers/eligibility/decision-date.test.js
forms-web-app/tests/unit/controllers/eligibility/listed-building.test.js
forms-web-app/tests/unit/controllers/eligibility/planning-department.test.js
forms-web-app/tests/unit/controllers/submission.test.js
forms-web-app/tests/unit/validators/submission.test.js

feat(forms-web-app): confirm information to be submitted
UCD-793

feat(forms-web-app): confirm information to be submitted

---

forms-web-app/jest.config.js
forms-web-app/tests/unit/routes/application-name.test.js
forms-web-app/tests/unit/routes/application-number.test.js
forms-web-app/tests/unit/routes/check-answers.test.js
forms-web-app/tests/unit/routes/eligibility/appeal-statement.test.js
forms-web-app/tests/unit/routes/eligibility/decision-date.test.js
forms-web-app/tests/unit/routes/eligibility/index.test.js
forms-web-app/tests/unit/routes/eligibility/listed-building.test.js
forms-web-app/tests/unit/routes/eligibility/planning-department.test.js
forms-web-app/tests/unit/routes/index.test.js
forms-web-app/tests/unit/routes/router-mock.js
forms-web-app/tests/unit/routes/task-list.test.js
forms-web-app/tests/unit/routes/your-details.test.js

N/A - fixup broken build due to one-off PR merge order
Adds tests for router setup. Adjust Jest thresholds to new minimums.

fix(forms-web-app): add unit tests for router setup

---

clusters/dev/app.yml

UCD-995
Add the key vault name to the dev cluster

chore: add the dev keyVault name to the release manifest

---

README.md
docker-compose.yml

UCD-988
Added Redis Commander to docker-compose.yml file so that it is available for local development including preparation of tests.

chore(docker-compose.yml): added Redis Commander

---

forms-web-app/src/config.js
forms-web-app/src/controllers/appellant-submission/upload-application.js
forms-web-app/src/controllers/appellant-submission/upload-decision.js
forms-web-app/src/lib/views.js
forms-web-app/src/routes/appellant-submission/index.js
forms-web-app/src/routes/appellant-submission/upload-application.js
forms-web-app/src/routes/appellant-submission/upload-decision.js
forms-web-app/src/validators/appellant-submission/upload-application-schema.js
forms-web-app/src/validators/appellant-submission/upload-application.js
forms-web-app/src/views/appellant-submission/appeal-statement.njk
forms-web-app/src/views/appellant-submission/upload-application.njk
forms-web-app/src/views/appellant-submission/upload-decision.njk
forms-web-app/tests/unit/controllers/appellant-submission/upload-application.test.js
forms-web-app/tests/unit/controllers/appellant-submission/upload-decision.test.js
forms-web-app/tests/unit/routes/appellant-submission/index.test.js
forms-web-app/tests/unit/routes/appellant-submission/upload-application.test.js
forms-web-app/tests/unit/routes/appellant-submission/upload-decision.test.js
forms-web-app/tests/unit/validators/appellant-submission/appeal-statement.test.js
forms-web-app/tests/unit/validators/appellant-submission/upload-application-schema.test.js
forms-web-app/tests/unit/validators/appellant-submission/upload-application.test.js
forms-web-app/tests/unit/validators/custom/file-size.test.js
forms-web-app/tests/unit/validators/custom/mime-type.test.js
forms-web-app/tests/unit/validators/eligibility/decision-date.test.js
forms-web-app/tests/unit/validators/eligibility/listed-building.test.js
forms-web-app/tests/unit/validators/eligibility/planning-department.test.js
forms-web-app/tests/unit/validators/submission.test.js
forms-web-app/tests/unit/validators/validation-error-handler.test.js
forms-web-app/tests/unit/validators/your-details.test.js

UCD-1050
add upload planning application form

feat(forms-web-app): add upload planning application form

---

forms-web-app/src/config.js
forms-web-app/src/controllers/appellant-submission/upload-decision.js
forms-web-app/src/controllers/submission.js
forms-web-app/src/routes/appellant-submission/upload-decision.js
forms-web-app/src/validators/appellant-submission/upload-decision-schema.js
forms-web-app/src/validators/appellant-submission/upload-decision.js
forms-web-app/src/views/appellant-submission/upload-application.njk
forms-web-app/src/views/appellant-submission/upload-decision.njk
forms-web-app/src/views/check-answers/index.njk
forms-web-app/tests/unit/controllers/appellant-submission/upload-application.test.js
forms-web-app/tests/unit/controllers/appellant-submission/upload-decision.test.js
forms-web-app/tests/unit/routes/appellant-submission/upload-decision.test.js
forms-web-app/tests/unit/validators/appellant-submission/upload-decision-schema.test.js
forms-web-app/tests/unit/validators/appellant-submission/upload-decision.test.js

UCD-884
Adds Upload the decision letter form functionality

feat(forms-web-app): add Upload the decision letter

---

clusters/dev/app.yml

This is a manual build because I misnamed the commit. This will be updated in due course when the next forms-web-app build is made
UCD-872

chore: create manual build for mongodb

---

forms-web-app/jest.config.js
forms-web-app/src/controllers/appellant-submission/application-number.js
forms-web-app/src/lib/views.js
forms-web-app/src/routes/appellant-submission/application-number.js
forms-web-app/src/routes/appellant-submission/index.js
forms-web-app/src/validators/appellant-submission/application-number.js
forms-web-app/src/views/appellant-submission/application-number.njk
forms-web-app/tests/unit/controllers/appellant-submission/application-number.test.js
forms-web-app/tests/unit/routes/appellant-submission/application-number.test.js
forms-web-app/tests/unit/routes/appellant-submission/index.test.js
forms-web-app/tests/unit/validators/appellant-submission/application-number.test.js

UCD-892
Adds "provide planning application number" form w/ backend integration

feat(forms-web-app): add provide planning application number

---

.github/workflows/publish-cucumber-on-merge.yml
e2e-tests/package.json
package.json

ci: we should publish cypress videos as part of our documentation run

---

forms-web-app/jest.config.js
forms-web-app/tests/unit/controllers/appellant-submission/application-number.test.js

UCD-892
Fixup test title - no code change here folks

test(forms-web-app): fix test title for application number redirect

---

appeals-service-api/src/routes/api-docs.js

n/a
Output the Swagger JSON at /api-docs/swagger.json. Have been asked for this a couple of times so worth putting into the app.

chore: publish raw swagger docs at /api-docs/swagger.json

---

e2e-tests/cypress/integration/appellant-submission-your-details.feature
e2e-tests/cypress/integration/appellant-submission-your-details/appellant-submission-your-details.js
e2e-tests/cypress/support/appellant-submission-your-details/confirmDetailsWasAccepted.js
forms-web-app/src/validators/appellant-submission/your-details.js
forms-web-app/tests/unit/validators/appellant-submission/your-details.test.js

fix(forms-web-app): fix of the email regex to match more examples

---

infrastructure/clusters/dev.tfvars
infrastructure/environments/README.md
infrastructure/environments/mongodb.tf
infrastructure/environments/variables.tf
infrastructure/modules/mongodb-database/main.tf

UCD-891
Updates to MongoDB instance following call with Microsoft
- write failover
- zone redundancy

Mongo updates from MS call

---

appeals-service-api/api/openapi.yaml
appeals-service-api/src/routes/api-docs.js

UCD-1108
docs(appeals-service-api): updated api spec doc to include local planning authorities endpoints
Configured service to serve new api at /api-docs endpoint

Updated Appeals api spec doc to include LPA endpoints

---

appeals-service-api/src/schemas/appeals.js
appeals-service-api/src/schemas/fileUpload.js
e2e-tests/cypress/support/appellant-submission-appeal-statement/uploadFile.js
e2e-tests/cypress/support/appellant-submission-upload-application/uploadPlanningApplicationFile.js
e2e-tests/cypress/support/appellant-submission-upload-decision/uploadUploadDecisionFile.js
forms-web-app/jest.config.js
forms-web-app/src/controllers/appellant-submission/appeal-statement.js
forms-web-app/src/controllers/appellant-submission/upload-application.js
forms-web-app/src/controllers/appellant-submission/upload-decision.js
forms-web-app/src/lib/appeals-api-wrapper.js
forms-web-app/src/validators/appellant-submission/appeal-statement-schema.js
forms-web-app/src/validators/appellant-submission/upload-application-schema.js
forms-web-app/src/validators/appellant-submission/upload-decision-schema.js
forms-web-app/src/views/appellant-submission/appeal-statement.njk
forms-web-app/src/views/appellant-submission/upload-application.njk
forms-web-app/src/views/appellant-submission/upload-decision.njk
forms-web-app/src/views/check-answers.njk
forms-web-app/tests/unit/controllers/appellant-submission/appeal-statement.test.js
forms-web-app/tests/unit/controllers/appellant-submission/applicant-name.test.js
forms-web-app/tests/unit/controllers/appellant-submission/application-number.test.js
forms-web-app/tests/unit/controllers/appellant-submission/upload-application.test.js
forms-web-app/tests/unit/controllers/appellant-submission/upload-decision.test.js
forms-web-app/tests/unit/controllers/appellant-submission/who-are-you.test.js
forms-web-app/tests/unit/lib/appeals-api-wrapper.test.js
forms-web-app/tests/unit/validators/appellant-submission/appeal-statement-schema.test.js
forms-web-app/tests/unit/validators/appellant-submission/appeal-statement.test.js
forms-web-app/tests/unit/validators/appellant-submission/upload-application-schema.test.js
forms-web-app/tests/unit/validators/appellant-submission/upload-application.test.js
forms-web-app/tests/unit/validators/appellant-submission/upload-decision-schema.test.js
forms-web-app/tests/unit/validators/appellant-submission/upload-decision.test.js

UCD-830
* application upload 
* decision upload
* appeal upload
all single file uploads.

fix(forms-web-app): file data posted to appeals service api

---

appeals-service-api/api/openapi.yaml
appeals-service-api/src/routes/index.js
forms-web-app/src/lib/appeals-api-wrapper.js
forms-web-app/tests/unit/lib/appeals-api-wrapper.test.js

UCD-1176
Minimal changes for appeals service and web app to use new LPA endpoint.

feat(appeals-service-api, forms-web-app): update to use new LPA endpoint

---

e2e-tests/cypress/integration/appellant-submission-planning-application-number.feature

UCD-1040 ( UCD-892 )
Candidate feature file describing planning application number 
- [ x ] New features have tests

feat: candidate description of planning application number feature

---

clusters/preprod/app.yml

UCD-1174
Configure the Pre Prod environment in PINS Azure subscription

feat(preprod): create preprod environment

---

.github/workflows/infra-common.yml
.github/workflows/infra-environments.yml
.github/workflows/terraform-validate.yml
appeals-service-api/src/lib/config.js
charts/app/templates/appealsServiceApi.yaml
charts/app/templates/documentServiceApi.yaml
charts/app/templates/formsWebApp.yaml
charts/app/values.yaml
docker-compose.yml
document-service-api/src/lib/config.js
forms-web-app/package-lock.json
forms-web-app/package.json
forms-web-app/patches/connect-mongodb-session+2.4.1.patch
forms-web-app/src/config.js
infrastructure/clusters/preprod.tfvars
infrastructure/common/.terraform.lock.hcl
infrastructure/common/README.md
infrastructure/common/containers.tf
infrastructure/common/main.tf
infrastructure/common/variables.tf
infrastructure/environments/.terraform.lock.hcl
infrastructure/environments/main.tf
infrastructure/environments/output.tf

UCD-1174
Configure the new PINS Azure subscription and create the PreProd environment in there.
- Upgrade Terraform to v0.14.0.
- improve the Cosmos DB connection. Remove the creation of databases inside Terraform and let the individual services create their own databases (as is the Mongo way) - Azure confirmed this would replicate correctly in my call with them last week.
- ~Apply partial-fix for [issue](https://github.com/mongodb-js/connect-mongodb-session/issues/90) in Connect MongoDB Session. Fixes error in Cosmos when creating a time-based expiry index. This removes the expiry index - I will raise a PR and fix independently (and apply patch to the repo when done if not applied in a timely manner).~ Applied the fix that I've [raised a PR …

Configure Pre Prod environment in PINS Azure subscription

---

clusters/preprod/app.yml

UCD-1174
Lock the artefact releases to the patch versions of the latest. This environment is now under the control of @danWatkinson and @karunak21 

chore(preprod): lock the preprod environment to fix releases

---

clusters/dev/app.yml

UCD-1174
Update the dev cluster with the new Azure subscription details

chore: update the dev environment to use new subscription

---

forms-web-app/tests/unit/routes/appellant-submission/applicant-name.test.js

N/A
Fix a typo in applicant name route test

test(forms-web-app): correct test name for routes/applicant-name

---

appeals-service-api/api/openapi.yaml

UCD-1198
Fixup typos in appeals service api openapi documentation

test(appeals-service-api): fix up typos in openapi.yaml

---

clusters/dev/app.yml

UCD-985
Update release for appeals service API v2 from #185 @frank-dodion please merge when you want this deploying to dev

chore: change appeals-service-api to v2 range

---

e2e-tests/cypress/integration/appeal-submission-tasklist.feature

UCD-766
Candidate Feature file for Your Details section in Task List page
- [ X] New features have tests

feat: candidate Feature File for Task List

---

e2e-tests/cypress/integration/appeal-submission-appeal-site-address.feature

New feature file with test scenarios for appeal site address
UCD-886
Introduced new feature file for appeal site address behaviour

feat: new Feature File for Appeal Site Address

---

e2e-tests/cypress/integration/appeal-submission-access-to-appeal-site.feature

UCD-887
Candidate Feature File for Access to Appeal Site

feat: Candidate Feature file for UCD 887 Access to Appeal Site

---

appeals-service-api/src/__tests__/appeals.spec.js
appeals-service-api/src/controllers/appeals.js
appeals-service-api/src/middleware/validateAppeal.js

UCD-1213
implemented business logic validation for appeal statement file upload

feat(appeals-service-app): appeal statement business validation

---

e2e-tests/cypress/integration/appellant-submission-check-your-answers.feature
e2e-tests/cypress/integration/appellant-submission-check-your-answers/appellant-submission-check-your-answers.js
e2e-tests/cypress/support/appellant-submission-check-your-answers/confirmSubmissionPage.js
e2e-tests/cypress/support/appellant-submission-check-your-answers/goToCheckYourAnswersPage.js
e2e-tests/cypress/support/commands.js

feature(e2e-tests): add glue code for check your answers page

---

e2e-tests/cypress/integration/appeal-submission-save-and-continue-navigation.feature

UCD-754
Candidate Feature File for Appeal Submission Save and Continue Navigation
- [X ] New features have tests

feat: candidate Feature File for UCD-754 Save and Continue Navigation

---

e2e-tests/cypress/integration/appeal-submission-tasklist.feature
e2e-tests/cypress/integration/appeal-submission-tasklist/appeal-submission-tasklist.js
e2e-tests/cypress/integration/appellant-submission-who-are-you.feature
e2e-tests/cypress/integration/appellant-submission-who-are-you/appellant-submission-who-are-you.js
e2e-tests/cypress/integration/appellant-submission-your-details.feature
e2e-tests/cypress/integration/appellant-submission-your-details/appellant-submission-your-details.js
e2e-tests/cypress/support/appeal-submission-tasklist/checkStatusForTask.js
e2e-tests/cypress/support/appeal-submission-tasklist/goToTaskListPage.js
e2e-tests/cypress/support/commands.js
forms-web-app/src/controllers/appellant-submission/task-list.js
forms-web-app/tests/unit/controllers/appellant-submission/task-list.test.js

feat(e2e-tests): add step definitions for task list feature

---

clusters/preprod/app.yml

chore
Update tracking versions for preprod environment

chore: update preprod version to track

---

infrastructure/k8s/nginx-ingress/common.yaml

Bugfix
This allows a user to upload anything of any size to the cluster. This may require some additional
tweaking in future but the website has a max file size check on it anyway and it will be difficult
to get this tied into the same value.

fix(nginx-ingress): set the proxy-body-size to 0

---

e2e-tests/cypress/integration/appeal-statement-submission.feature

UCD-991 (UCD-830)
test(e2e-tests): extend feature file for appeal statement upload
Added scenario to make explicit full coverage of acceptance criteria for UCD-830

test(e2e-tests): extend feature file for appeal statement upload

---

.github/PULL_REQUEST_TEMPLATE.md

docs(forms-web-app): add entry to GitHub PR template for env var changes

---

.github/PULL_REQUEST_TEMPLATE.md

docs(forms-web-app): fix typo in GitHub request template

---

e2e-tests/cypress/integration/appellant-submission-decision-letter.feature
e2e-tests/cypress/integration/appellant-submission-decision-letter/appellant-submission-decision-letter.js
e2e-tests/cypress/integration/appellant-submission-upload-application.feature
e2e-tests/cypress/integration/appellant-submission-upload-application/appellant-submission-upload-application.js

feat(e2e-tests): extends planning and decision upload features

---

e2e-tests/cypress/integration/appeal-statement-submission.feature
e2e-tests/cypress/integration/appeal-statement-submission/appeal-statement-submission.js

UCD-991
Extend appeal statement feature file to include scenarios that cover when user has uploaded a valid file then had an invalid file rejected and finally proceeded with or without another valid file.

test(e2e-tests): extend appeal statement feature file

---

.github/workflows/e2e-tests-on-PR.yml
.github/workflows/publish-cucumber-on-merge.yml

Bugfix
Update GH Actions config to trigger Cypress on `develop` branch

chore: change cypress triggers for develop branch

---

e2e-tests/cypress/integration/appellant-submission-who-are-you.feature

chore(e2e-tests): update the who-are-you feature

---

e2e-tests/cypress/integration/appellant-submission-planning-application-number.feature

UCD-1037
Updated feature file to include max character constraint example

test(e2e-tests): updated Planning Application Number submission feature

---

e2e-tests/cypress/integration/appellant-submission-applicant-name.feature
e2e-tests/cypress/integration/appellant-submission-applicant-name/appellant-submission-applicant-name.js
e2e-tests/cypress/support/appellant-submission-applicant-name/confirmApplicantNameValue.js
e2e-tests/cypress/support/appellant-submission-applicant-name/confirmApplicantNameWasAccepted.js
e2e-tests/cypress/support/appellant-submission-applicant-name/confirmApplicantNameWasRejected.js
e2e-tests/cypress/support/commands.js
forms-web-app/src/validators/appellant-submission/applicant-name.js
forms-web-app/src/views/appellant-submission/applicant-name.njk

feat(e2e-tests): update applicant name feature

---

e2e-tests/cypress/integration/appellant-submission-who-are-you.feature
e2e-tests/cypress/integration/appellant-submission-who-are-you/appellant-submission-who-are-you.js
e2e-tests/cypress/support/appellant-submission-who-are-you/confirmAnswered.js
e2e-tests/cypress/support/commands.js
forms-web-app/src/views/appellant-submission/who-are-you.njk

chore(e2e-tests): update of step definitions for who-are-you feature

---

e2e-tests/cypress/integration/appellant-submission-your-details.feature
e2e-tests/cypress/integration/appellant-submission-your-details/appellant-submission-your-details.js
e2e-tests/cypress/support/appellant-submission-your-details/confirmDetailsWasAccepted.js
e2e-tests/cypress/support/appellant-submission-your-details/confirmEmailValue.js
e2e-tests/cypress/support/appellant-submission-your-details/confirmNameValue.js
e2e-tests/cypress/support/commands.js

chore(e2e-tests): update feature and step definitions of your details

---

e2e-tests/cypress/integration/appeal-submission-tasklist-planningApplicationNumber.feature
e2e-tests/cypress/integration/appeal-submission-tasklist-planningApplicationNumber/appeal-submission-tasklist-planningApplicationNumber.js
e2e-tests/cypress/support/appeal-submission-tasklist/confirmUserPresentedWithProvidePlanningApplicationNumber.js
e2e-tests/cypress/support/appeal-submission-tasklist/selectToProvidePlanningApplicationNumber.js
e2e-tests/cypress/support/commands.js

UCD-1038
Added feature file and steps to test navigation from task list to planning application page.

test(e2e-tests): test nav to Planning Application Number

---

forms-web-app/src/controllers/appellant-submission/site-access-safety.js
forms-web-app/src/controllers/appellant-submission/site-access.js
forms-web-app/src/controllers/appellant-submission/task-list.js
forms-web-app/src/lib/appeal-site-address-to-array.js
forms-web-app/src/services/task.service.js
forms-web-app/src/views/appellant-submission/site-access-safety.njk
forms-web-app/src/views/appellant-submission/site-access.njk
forms-web-app/tests/unit/controllers/appellant-submission/task-list.test.js
forms-web-app/tests/unit/lib/appeal-site-address-to-array.test.js

feat(forms-web-app): add site access safety

---

e2e-tests/cypress/integration/appellant-submission-planning-application-number.feature
e2e-tests/cypress/integration/appellant-submission-planning-application-number/appellant-submission-planning-application-number.js
e2e-tests/cypress/support/appellant-submission-planning-application-number/confirmPlanningApplicationNumberHasNotUpdated.js
e2e-tests/cypress/support/appellant-submission-planning-application-number/confirmPlanningApplicationNumberHasUpdated.js
e2e-tests/cypress/support/appellant-submission-planning-application-number/confirmPlanningApplicationNumberRejectedBecause.js
e2e-tests/cypress/support/appellant-submission-planning-application-number/promptUserToProvidePlanningApplicationNumber.js
e2e-tests/cypress/support/appellant-submission-planning-application-number/providePlanningApplicationNumber.js
forms-web-app/src/validators/appellant-submission/application-number.js
forms-web-app/tests/unit/validators/appellant-submission/application-number.test.js

UCD-1295
The ticket extends and refactors feature file and steps fo the planning application number input page. It also adds validation for the 30 character max length for the number in FWA so the tests can pass.

test(e2e-tests): tests for Planning Application Number

---

e2e-tests/cypress/integration/appeal-submission-access-to-appeal-site.feature
e2e-tests/cypress/integration/appeal-submission-access-to-appeal-site/appeal-submission-access-to-appeal-site.js
e2e-tests/cypress/support/appeal-submission-access-to-appeal-site/answerCanSeeTheWholeAppeal.js
e2e-tests/cypress/support/appeal-submission-access-to-appeal-site/answerCannotSeeTheWholeAppeal.js
e2e-tests/cypress/support/appeal-submission-access-to-appeal-site/confirmAccessSiteAnswered.js
e2e-tests/cypress/support/appeal-submission-access-to-appeal-site/confirmAccessSiteNotSubmitted.js
e2e-tests/cypress/support/appeal-submission-access-to-appeal-site/confirmAccessSiteWasAccepted.js
e2e-tests/cypress/support/appeal-submission-access-to-appeal-site/confirmAccessSiteWasRejectedBecause.js
e2e-tests/cypress/support/appeal-submission-access-to-appeal-site/goToAccessSitePage.js
e2e-tests/cypress/support/appeal-submission-access-to-appeal-site/provideMoreDetails.js
e2e-tests/cypress/support/appellant-submission-who-are-you/answerYes.js
e2e-tests/cypress/support/commands.js
forms-web-app/src/views/appellant-submission/site-access.njk
forms-web-app/src/views/appellant-submission/who-are-you.njk

chore(e2e-tests): add step definitions for access site feature

---

e2e-tests/cypress/integration/appeal-submission-appeal-site-address.feature
e2e-tests/cypress/integration/appeal-submission-appeal-site-address/appeal-submission-appeal-site-address.js
e2e-tests/cypress/support/appeal-submission-appeal-site-address/confirmSiteAddressValue.js
e2e-tests/cypress/support/appeal-submission-appeal-site-address/confirmSiteAddressWasAccepted.js
e2e-tests/cypress/support/appeal-submission-appeal-site-address/confirmSiteAddressWasRejectedBecause.js
e2e-tests/cypress/support/appeal-submission-appeal-site-address/goToSiteAddressPage.js
e2e-tests/cypress/support/appeal-submission-appeal-site-address/provideAddressLine1.js
e2e-tests/cypress/support/appeal-submission-appeal-site-address/provideAddressLine2.js
e2e-tests/cypress/support/appeal-submission-appeal-site-address/provideCounty.js
e2e-tests/cypress/support/appeal-submission-appeal-site-address/providePostcode.js
e2e-tests/cypress/support/appeal-submission-appeal-site-address/provideTownOrCity.js
e2e-tests/cypress/support/commands.js
forms-web-app/src/validators/appellant-submission/site-location.js
forms-web-app/src/views/appellant-submission/site-location.njk
forms-web-app/tests/unit/validators/appellant-submission/site-location.test.js

feat(e2e-tests): add of step definitions for appeal site address feature

---

appeals-service-api/src/__tests__/appeals.spec.js
appeals-service-api/src/middleware/validateAppeal.js
forms-web-app/src/services/task.service.js
forms-web-app/tests/unit/controllers/appellant-submission/task-list.test.js

UCD-1156   Only accepted states are name and email both empty or both valued.

feat(ucd-1166): access-appeal-site-validation-appeals-api

---

forms-web-app/src/validators/appellant-submission/your-details.js
forms-web-app/tests/unit/validators/appellant-submission/your-details.test.js

UCD-1307
Updated max length for Your Details name field to match that in the Appeals API spec

feat(forms-web-app): align name max length with Appeals API

---

e2e-tests/cypress/integration/appellant-submission-who-are-you.feature
e2e-tests/cypress/integration/appellant-submission-who-are-you/appellant-submission-who-are-you.js
e2e-tests/cypress/support/appellant-submission-who-are-you/confirmWhoAreYouPageRejectedBecause.js
e2e-tests/cypress/support/commands.js

test(e2e-tests): refactor e2e tests and steps for Who Are You task

---

appeals-service-api/src/__tests__/appeals.spec.js
appeals-service-api/src/middleware/validateAppeal.js

feat(appeals-service-api): extend validation in appeals-service-api

---

e2e-tests/cypress/integration/appellant-submission-applicant-name/appellant-submission-applicant-name.js
e2e-tests/cypress/integration/appellant-submission-your-details.feature
e2e-tests/cypress/integration/appellant-submission-your-details/appellant-submission-your-details.js
e2e-tests/cypress/support/appellant-submission-your-details/confirmDetailsWasAccepted.js
e2e-tests/cypress/support/appellant-submission-your-details/confirmEmailValue.js
e2e-tests/cypress/support/appellant-submission-your-details/confirmEmailValueNotSet.js
e2e-tests/cypress/support/appellant-submission-your-details/confirmNameValue.js
e2e-tests/cypress/support/appellant-submission-your-details/confirmNameValueNotSet.js
e2e-tests/cypress/support/appellant-submission-your-details/confirmOriginalApplicantName.js
e2e-tests/cypress/support/appellant-submission-your-details/confirmOriginalApplicantWasRejected.js
e2e-tests/cypress/support/appellant-submission-your-details/confirmYourDetailsStatus.js
e2e-tests/cypress/support/appellant-submission-your-details/goToApplicantNamePage.js
e2e-tests/cypress/support/appellant-submission-your-details/goToTaskListPage.js
e2e-tests/cypress/support/appellant-submission-your-details/goToWhoAreYouPage.js
e2e-tests/cypress/support/appellant-submission-your-details/goToYourDetailsPage.js
e2e-tests/cypress/support/appellant-submission-your-details/provideAreYouOriginalApplicant.js
e2e-tests/cypress/support/appellant-submission-your-details/provideDetailsEmail.js
e2e-tests/cypress/support/appellant-submission-your-details/provideDetailsName.js
e2e-tests/cypress/support/appellant-submission-your-details/provideNameOfOriginalApplicant.js
e2e-tests/cypress/support/appellant-submission-your-details/saveAndContinue.js
e2e-tests/cypress/support/commands.js
forms-web-app/src/validators/appellant-submission/applicant-name.js

UCD-1298
Updated tests to reflect latest agreed practice and expected behaviour.

feat(e2e-tests): extend e2e tests and steps for Your Details section

---

appeals-service-api/src/__tests__/appeals.spec.js
appeals-service-api/src/middleware/validateAppeal.js

UCD-1270
Appeals api - validation of behalf appellant

feat(ucd-1270): appeals-api-behalf-appellant-validation

---

e2e-tests/cypress/integration/appeal-submission-appeal-site-ownership.feature

UCD-888
https://pins-ds.atlassian.net/browse/UCD-888

test(e2e-tests): add of site owership feature file

---

appeals-service-api/src/__tests__/appeals.spec.js
appeals-service-api/src/middleware/validateAppeal.js

feat(appeals-service-api): add of site address validation in api

---

e2e-tests/cypress/integration/appeal-submission-appeal-site-ownership.feature
e2e-tests/cypress/integration/appeal-submission-appeal-site-ownership/appeal-submission-appeal-site-ownership.js
e2e-tests/cypress/support/appeal-submission-appeal-site-ownership/answerDidNotToldOtherOwnersAppeal.js
e2e-tests/cypress/support/appeal-submission-appeal-site-ownership/answerDidToldOtherOwnersAppeal.js
e2e-tests/cypress/support/appeal-submission-appeal-site-ownership/answerDoesNotOwnTheWholeAppeal.js
e2e-tests/cypress/support/appeal-submission-appeal-site-ownership/answerOwnsTheWholeAppeal.js
e2e-tests/cypress/support/appeal-submission-appeal-site-ownership/confirmOtherOwnersAsked.js
e2e-tests/cypress/support/appeal-submission-appeal-site-ownership/confirmOtherSiteOwnerToldAnswered.js
e2e-tests/cypress/support/appeal-submission-appeal-site-ownership/confirmSiteOwnershipAccepted.js
e2e-tests/cypress/support/appeal-submission-appeal-site-ownership/confirmSiteOwnershipRejectedBecause.js
e2e-tests/cypress/support/appeal-submission-appeal-site-ownership/confirmWholeSiteOwnerAnswered.js
e2e-tests/cypress/support/appeal-submission-appeal-site-ownership/goToOtherSiteOwnerToldPage.js
e2e-tests/cypress/support/appeal-submission-appeal-site-ownership/goToWholeSiteOwnerPage.js
e2e-tests/cypress/support/commands.js
forms-web-app/src/views/appellant-submission/site-ownership-certb.njk

test(e2e-tests): add of site ownership step definitions

---

e2e-tests/cypress/integration/appellant-submission-your-details-v2-your-details-previously-submitted.feature

UCD-1277
Fixed typo so that test exercises where name and email have been previously provided.

test(e2e-tests): fixed typo in one Your Details feature file

---

e2e-tests/cypress/integration/appeal-submission-site-health-and-safety-issues.feature

UCD-944 Health and Safety Issues
New Feature file created with the latest template content
- [ X] New features have tests

Candidate Feature file for UCD-944-Health and Safety Issues

---

appeals-service-api/src/middleware/validateAppeal.js
e2e-tests/cypress/integration/appeal-submission-site-health-and-safety-issues.feature
e2e-tests/cypress/integration/appeal-submission-site-health-and-safety-issues/appeal-submission-site-health-and-safety-issues.js
e2e-tests/cypress/support/appeal-submission-site-health-and-safety-issues/answerSiteHasIssues.js
e2e-tests/cypress/support/appeal-submission-site-health-and-safety-issues/answerSiteHasNoIssues.js
e2e-tests/cypress/support/appeal-submission-site-health-and-safety-issues/confirmHealthAndSafetyPage.js
e2e-tests/cypress/support/appeal-submission-site-health-and-safety-issues/confirmSafetyIssuesConcernsValue.js
e2e-tests/cypress/support/appeal-submission-site-health-and-safety-issues/confirmSiteHasIssuesAnswered.js
e2e-tests/cypress/support/appeal-submission-site-health-and-safety-issues/confirmSiteSafetyRejectedBecause.js
e2e-tests/cypress/support/appeal-submission-site-health-and-safety-issues/goToHealthAndSafetyPage.js
e2e-tests/cypress/support/appeal-submission-site-health-and-safety-issues/isSafetyIssuesInputPresented.js
e2e-tests/cypress/support/appeal-submission-site-health-and-safety-issues/provideSafetyIssuesConcerns.js
e2e-tests/cypress/support/commands.js
forms-web-app/src/controllers/appellant-submission/site-access-safety.js
forms-web-app/src/validators/appellant-submission/site-access-safety.js
forms-web-app/src/views/appellant-submission/site-access-safety.njk
forms-web-app/tests/unit/controllers/appellant-submission/site-access-safety.test.js
forms-web-app/tests/unit/validators/appellant-submission/site-access-safety.test.js

feat(e2e-tests): add of site access safety glue codes

---

e2e-tests/cypress/integration/appeal-submission-site-health-and-safety-issues/appeal-submission-site-health-and-safety-issues.js
forms-web-app/src/validators/appellant-submission/site-access-safety.js
forms-web-app/src/views/appellant-submission/site-access-safety.njk
forms-web-app/tests/unit/validators/appellant-submission/site-access-safety.test.js

UCD-1344
fix error message text on health+safety page
- [ x ] My commit history in this PR is linear

fix: fix error messages for health+safety page

---

forms-web-app/tests/unit/controllers/appellant-submission/site-access-safety.test.js

UCD-944
Bit of a proof of concept - all the controller need this, so I am doing them all. This is the first.

fix(forms-web-app): validate the payload to create or update appeal

---

README.md

N/A
Update docs to help finding issues with release management

docs(readme): add information on debugging releases and writing good commit messages

---

clusters/dev/app.yml
clusters/preprod/app.yml

UCD-1369
Reset app versions to v1.0.0

chore: reset the app versions to 1.0.0

---

.github/workflows/infra-environments.yml
infrastructure/clusters/prod.tfvars

UCD-1368
Create prod environment inside PINS ODT subscription

chore: create prod environment

---

clusters/prod/app.yml

UCD-1368
Create release manifest for prod environemnt

chore: create prod cluster

---

packages/forms-web-app/src/validators/appellant-submission/site-access.js
packages/forms-web-app/tests/unit/validators/appellant-submission/site-access.test.js

feat(forms-web-app): site access details is limited to 255 characters

---

e2e-tests/cypress/integration/common/appeal-header-footer.js
e2e-tests/cypress/integration/google-analytics.feature
e2e-tests/cypress/support/appeal-header-footer-links/confirmGoogleAnalyticsLinkIsPresent.js
e2e-tests/cypress/support/commands.js
packages/forms-web-app/src/app.js
packages/forms-web-app/src/config.js
packages/forms-web-app/src/views/includes/head.njk

feat(forms-web-app): Google Analytics feature

---

clusters/dev/app.yml
clusters/preprod/app.yml
clusters/prod/app.yml

UCD-1427
Configures the HTTP Basic auth on all clusters. Only to be released once #320 is merged

chore: configure http-basic for all clusters

---

packages/forms-web-app/tests/unit/services/task.service.test.js

NA
prefer constants in task.service.test

test(forms-web-app): prefer constants in task.service.test

---

e2e-tests/README.md
e2e-tests/cypress/integration-with-acp/eligibility-check-decision-date.feature
e2e-tests/cypress/integration-with-acp/handle-unavailable-routes.feature
e2e-tests/cypress/integration/common/integration-with-acp.js
e2e-tests/cypress/support/appeal-navigation-confirmation/appellant-submission/confirmNavigationApplicantNamePage.js
e2e-tests/cypress/support/appeal-navigation-confirmation/appellant-submission/confirmNavigationTaskListPage.js
e2e-tests/cypress/support/appeal-navigation-confirmation/appellant-submission/confirmNavigationWhoAreYouPage.js
e2e-tests/cypress/support/appeal-navigation-confirmation/appellant-submission/confirmNavigationYourDetailsPage.js
e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationDecisionDateExpiredPage.js
e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationDecisionDatePage.js
e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationNoDecisionDatePage.js
e2e-tests/cypress/support/commands.js
e2e-tests/cypress/support/integration-with-acp/confirmNavigationAcpPage.js
e2e-tests/cypress/support/integration-with-acp/confirmNavigationPageNotFoundPage.js
e2e-tests/cypress/support/integration-with-acp/goToPageNotFoundPage.js

UCD-1352 and UCD-1353
Feature file and steps for ACP integration

test(e2e-tests): feature file and steps for ACP integration

---

charts/app/templates/formsWebApp.yaml
charts/app/values.yaml
packages/forms-web-app/src/app.js
packages/forms-web-app/src/config.js
packages/forms-web-app/src/controllers/eligibility/decision-date.js
packages/forms-web-app/src/controllers/index.js
packages/forms-web-app/tests/unit/controllers/eligibility/decision-date.test.js
packages/forms-web-app/tests/unit/controllers/index.test.js

UCD-1351
Apply limited routing option to the forms web app. This also applies the Helm configuration - this defaults to `disabled`, so will need to be enabled in the `release` branch manifests

feat(routing): apply special routing config

---

e2e-tests/package.json
package.json

UCD-1371
Added npm scripts for ACP tests

build: added npm scripts for ACP tests

---

.github/workflows/appeals-service-api.yml
.github/workflows/common.yml
.github/workflows/document-service-api.yml
.github/workflows/forms-web-app.yml
.github/workflows/infra-common.yml
.github/workflows/infra-environments.yml

UCD-1447
Release dev cluster infra from the `develop` branch.
This also removes the `main` configuration on all branches - the change to `main` over `master` was an ambition, but I suspect it'll never actually happen so removing this configuration is probably sensible. After all, anyone could create a `main` branch and make whatever changes they like

chore: trigger the dev cluster to be built on the develop branch

---

clusters/dev/app.yml
clusters/preprod/app.yml
clusters/prod/app.yml

UCD-1430
Enables the limited routing. Also, changes the source of the Helm chart for the dev cluster to the `develop` branch. This will save having to pull things in early to get them deployed

Enable limited routing

---

README.md
docker-compose.yml
e2e-tests/cypress/integration-with-acp/eligibility-check-decision-date.feature
e2e-tests/cypress/integration-with-acp/handle-unavailable-routes.feature
e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToAccessSitePage.js
e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToAppealStatementSubmission.js
e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToApplicantNamePage.js
e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToCheckYourAnswersPage.js
e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToDecisionLetterPage.js
e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToHealthAndSafetyPage.js
e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToPlanningApplicationNumberPage.js
e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToPlanningApplicationSubmission.js
e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToSiteAddressPage.js
e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToSubmissionPage.js
e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToTaskListPage.js
e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToWhoAreYouPage.js
e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToWholeSiteOwnerPage.js
e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToYourDetailsPage.js
e2e-tests/cypress/support/appeal-navigation/eligibility/goToAppealStatementInfoPage.js
e2e-tests/cypress/support/appeal-navigation/eligibility/goToListedBuildingOutPage.js
e2e-tests/cypress/support/appeal-navigation/eligibility/goToListedBuildingPage.js
e2e-tests/cypress/support/appeal-navigation/eligibility/goToPlanningDepartmentOutPage.js
e2e-tests/cypress/support/appeal-navigation/eligibility/goToPlanningDepartmentPage.js

UCD-1449
Update tests and docs for ACP integration

test(e2e-tests): update tests and docs for ACP integration

---

clusters/dev/app.yml

N/A
This is breaking the cypress tests. It's likely this will be put back in in future, but a change to cypress needs happening first

chore: disable http basic from dev

---

.github/workflows/e2e-tests-on-PR.yml
.github/workflows/publish-cucumber-on-merge.yml
docker-compose.yml
e2e-tests/cypress/reports/index.html
e2e-tests/package.json
package.json

UCD-1429
Update CI pipeline to run tests for both modes i.e. ACP and PINS(non-ACP)

ci: update CI pipeline to run tests for both modes i.e ACP and non-ACP

---

clusters/dev/app.yml

chore: change keyvault name

---

charts/app/values.yaml

This reverts commit 71a921cfa1f67896e30e41a205b54d03303cec7d.
UCD-
In my investigations of the issue I'd deleted the http-basic secret from the key vault. It was this that was causing the 503 status code

Revert "chore: remove metrics/health endpoints from nginx routing"

---

e2e-tests/cypress/integration/appeal-submission-tasklist.feature
packages/forms-web-app/src/services/task.service.js

UCD-766
update section status icon feature file

test(e2e-tests): update section status icon feature file

---

clusters/preprod/app.yml

chore(preprod): set preprod instances to latest prerelease versions

---

infrastructure/k8s/rbac/user.yaml

N/A
From testing with @frank-dodion 

fix(security): update rbac role to provide readonly to jobs/deployments

---

e2e-tests/cypress/integration/appeal-submission-appeal-site-ownership/appeal-submission-appeal-site-ownership.js

UCD-1360
UCD-1361
confirm that no answer is selected by default in the checkbox

test(e2e-tests): confirm that no answer is selected by default in the checkbox

---

packages/forms-web-app/src/views/appellant-submission/task-list.njk
packages/forms-web-app/src/views/appellant-submission/your-details.njk

…our details
UCD-1288
remove save and return link from task list and your details page

feat(forms-web-app): remove save and return link

---

clusters/dev/app.yml
clusters/preprod/app.yml

UCD-1452
Update the release config to reflect the new branching strategy

chore(branching): use master branch as location of helm charts

---

infrastructure/k8s/rbac/user.yaml

N/A
Enable port forwarding in RBAC settings

fix(security): enable port forward in rbac settings

---

e2e-tests/cypress/integration/appeal-submission-access-to-appeal-site.feature
e2e-tests/cypress/integration/appeal-submission-appeal-site-address.feature
e2e-tests/cypress/integration/appeal-submission-appeal-site-ownership.feature
e2e-tests/cypress/integration/appeal-submission-site-health-and-safety-issues.feature
e2e-tests/cypress/integration/common/appellant-submission-about-the-appeal-site.js
e2e-tests/cypress/integration/common/appellant-submission-your-details.js

UCD-1457
Update e2e tests for appeal site to include section status checks

test(e2e-tests): add section status e2e tests for appeal site

---

e2e-tests/cypress/integration/appeal-submission-tasklist.feature
e2e-tests/cypress/integration/appeal-submission-tasklist/appeal-submission-tasklist.js
e2e-tests/cypress/support/appeal-submission-tasklist/confirmTaskIsAvailableForSelection.js
e2e-tests/cypress/support/appeal-submission-tasklist/confirmTaskIsNotAvailableForSelection.js
e2e-tests/cypress/support/commands.js
packages/forms-web-app/src/controllers/appellant-submission/task-list.js
packages/forms-web-app/src/services/task.service.js
packages/forms-web-app/src/views/components/task-list/template.njk
packages/forms-web-app/tests/unit/controllers/appellant-submission/task-list.test.js

UCD-766
UCD-935
glue codes for task status feature file

test(e2e-tests): glue codes for task status feature

---

e2e-tests/cypress/integration/appeal-submission-save-and-continue-navigation-about-you.feature
e2e-tests/cypress/integration/appeal-submission-save-and-continue-navigation-about-you/appeal-submission-save-and-continue-navigation-about-you.js
e2e-tests/cypress/integration/appeal-submission-save-and-continue-navigation-appeal-site.feature
e2e-tests/cypress/integration/appeal-submission-save-and-continue-navigation-appeal-site/appeal-submission-save-and-continue-navigation-appeal-site.js
e2e-tests/cypress/integration/appeal-submission-save-and-continue-navigation-planning-application.feature
e2e-tests/cypress/integration/appeal-submission-save-and-continue-navigation-planning-application/appeal-submission-save-and-continue-navigation-planning-application.js
e2e-tests/cypress/integration/appeal-submission-save-and-continue-navigation-your-appeal.feature
e2e-tests/cypress/integration/appeal-submission-save-and-continue-navigation-your-appeal/appeal-submission-save-and-continue-navigation-your-appeal.js
e2e-tests/cypress/integration/common/appeal-submission-navigation.js
e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToAppealStatementPage.js
e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToSiteSafetyPage.js
e2e-tests/cypress/support/appeal-navigation/userIsNavigatedToPage.js
e2e-tests/cypress/support/commands.js

test(forms-web-app): adds glue code for save and continue nav tests

---

e2e-tests/cypress/integration/appeal-submission-save-and-continue-navigation-about-you.feature
e2e-tests/cypress/integration/appeal-submission-save-and-continue-navigation-appeal-site.feature
e2e-tests/cypress/integration/appeal-submission-save-and-continue-navigation-appeal-site/appeal-submission-save-and-continue-navigation-appeal-site.js

UCD-1044
merge site ownership cert b setup into one step

test(e2e-tests): merge site ownership cert b setup into one step

---

e2e-tests/cypress/integration/appeal-submission-save-and-continue-navigation-appeal-site.feature

…ertb with NO selected
UCD-1044
shorter given step for Navigation - Site ownership certb with NO selected

test(e2e-tests): shorter given step for Navigation - Site ownership certb with NO selected

---

e2e-tests/cypress/support/appeal-header-footer/confirmGoogleAnalyticsLinkIsPresent.js
packages/forms-web-app/src/config.js

Subtask/ucd 1491 update Id of google analytics

---

clusters/prod/app.yml

UCD-1538
Add GA code to prod cluster

chore(prod): set google analytics code

---

e2e-tests/cypress/integration/appellant-submission-check-your-answers.feature

test(e2e-tests): adds FF for appellant submission check your answers
UCD-1318
adds FF for appellant submission check your answers

test(e2e-tests): adds FF for check your answers

---

clusters/preprod/app.yml

chore(preprod): set google analytics code

---

charts/app/templates/lpa.yaml

UCD-1175
Update configmap to make Bradford LPA the only eligible LPD for deployed environments

chore: update configmap to inc only Bradford LPA

---

.github/workflows/lpa-questionnaire.yml
charts/app/templates/lpaQuestionnaireWebApp.yaml
charts/app/templates/service.yaml
charts/app/values.yaml
infrastructure/environments/applications.tf
infrastructure/environments/output.tf

LPA Questionnaire CI/CD pipeline

---

e2e-tests/cypress/integration/eligibility-decision-date-page-components.feature

UCD-
this test has a hardcoded date in it; it's an old test that should have been deleted ages ago... @wip for now to stop it blocking ci, raising ticket to remove the rest later.

chore: remove legacy test with hardcoded date

---

packages/forms-web-app/src/controllers/eligibility/planning-department.js
packages/forms-web-app/src/services/department.service.js
packages/forms-web-app/tests/unit/controllers/eligibility/planning-department.test.js
packages/forms-web-app/tests/unit/services/department.service.test.js

UCD-1563
Ensure LPD data is always refreshed in LPD controller

feat(forms-web-app): ensure LPD data is always refreshed

---

charts/app/templates/lpa.yaml
packages/forms-web-app/src/views/eligibility/planning-department.njk

UCD-1090
Removed inline style to comply with CSP and included Bradford LPA in configmap for FQC verification

feat(forms-web-app): removed inline style to comply with CSP

---

e2e-tests/cypress/integration/appellant-submission-check-your-answers.feature

UCD-1319
Updated feature file for check your answers

test(e2e-tests): updated feature file for check your answers

---

packages/forms-web-app/src/views/appellant-submission/check-answers.njk

fix(forms-web-app): fix broken links on Check Your Answers

---

e2e-tests/cypress/integration/appellant-submission-check-your-answers.feature
e2e-tests/cypress/integration/common/appellant-submission-check-your-answers.js

UCD-1319 and UCD-1576
Added placeholder step defs

test: added placeholder step defs

---

packages/forms-web-app/src/views/eligibility/planning-department-out.njk

fix(forms-web-app): update content

---

clusters/dev/app.yml
clusters/preprod/app.yml
clusters/prod/app.yml

AS-34
Configure the LPA questionnaire release manifest. To be merged once #405 is merged into `master` (@todo change this reference when the PR is created)

chore: configure lpa-questionnaire release manifest

---

.github/workflows/lpa-questionnaire.yml

ci: set lpa questionnaire to build on master branch

---

packages/forms-web-app/src/views/appellant-submission/check-answers.njk

UCD-1323
Adds missing cy tags for two "change" links

fix(forms-web-app): adds data-cy tags for change links

---

clusters/preprod/app.yml

UCD-1601
disable limited routing in preprod

chore: disable limited routing in preprod

---

clusters/dev/app.yml

chore: set lpaq-dev url for demo

---

e2e-tests/cypress/integration/appellant-submission-check-your-answers.feature
e2e-tests/cypress/integration/common/appellant-submission-check-your-answers.js
e2e-tests/cypress/support/appellant-submission-check-your-answers/confirmCheckYourAnswersDisplayItem.js
e2e-tests/cypress/support/appellant-submission-check-your-answers/provideCompleteAppeal.js
e2e-tests/cypress/support/commands.js

UCD-1576
Step defs for check your answers feature

test: step defs for check your answers feature

---

clusters/dev/app.yml
clusters/preprod/app.yml

This reverts commit 8b1431f2092b7d77d62bb10c6dad0994a5c44d1a.
UCD-

Revert "chore: change FWA URLs whilst waiting for DNS to be corrected"

---

clusters/preprod/app.yml

UCD-1606
Promote versions to preprod for demo

chore: promote versions to preprod for demo

---

packages/lpa-questionnaire-web-app/src/views/placeholder.njk

AS-50
Fixing page title to use the correct value

fix(lpa-task-list): update task-list view to use the correct title

---

packages/lpa-questionnaire-web-app/src/views/task-list.njk

AS-50
Missed task list page in previous fix, updating it here

fix(lpa-tasklist): update title on task list as well as placeholder

---

e2e-tests/cypress/integration/eligibility-decision-date.feature

UCD-1629
Updated FF for Decision Date eligibility check

test(e2e-tests): updated FF for Decision Date eligibility check

---

e2e-tests/cypress/integration-with-acp/handle-unavailable-routes.feature
e2e-tests/cypress/integration/eligibility-decision-date/eligibility-decision-date.js
e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationDecisionDateAbsentPage.js
e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationDecisionDateExpiredPage.js
e2e-tests/cypress/support/commands.js
e2e-tests/cypress/support/eligibility-decision-date/accessConfirmHavingNoDecisionDate.js
e2e-tests/cypress/support/eligibility-decision-date/confirmProvidedDecisionDateWasInvalid.js

UCD-1630
Update step defs for Decision Date feature

test: update step defs for Decision Date feature

---

e2e-tests/cypress/integration-with-acp/handle-unavailable-routes.feature
e2e-tests/cypress/integration/eligibility-decision-date.feature
e2e-tests/cypress/integration/eligibility-decision-date/eligibility-decision-date.js
e2e-tests/cypress/support/appeal-navigation/eligibility/goToDecisionDateExpiredPage.js
e2e-tests/cypress/support/commands.js
e2e-tests/cypress/support/eligibility-decision-date/confirmDecisionDate.js
packages/forms-web-app/src/config.js
packages/forms-web-app/src/controllers/eligibility/decision-date.js
packages/forms-web-app/src/lib/views.js
packages/forms-web-app/src/routes/eligibility/decision-date.js
packages/forms-web-app/src/validators/eligibility/decision-date.js
packages/forms-web-app/src/views/eligibility/decision-date-passed.njk
packages/forms-web-app/src/views/eligibility/decision-date.njk
packages/forms-web-app/tests/unit/controllers/eligibility/decision-date.test.js
packages/forms-web-app/tests/unit/lib/views.test.js
packages/forms-web-app/tests/unit/routes/eligibility/decision-date.test.js
packages/forms-web-app/tests/unit/validators/eligibility/decision-date.test.js

feat(forms-web-app): decision date persistent and date passed url change

---

clusters/preprod/app.yml

Bump preprod version number for sign off

chore: promote version to preprod for sign off

---

e2e-tests/cypress/integration/eligibility-costs.feature
e2e-tests/cypress/integration/eligibility-listed-building-status.feature

UCD-1581
Add Feature File for claiming Costs eligibility check

test(e2e-tests): add Feature File for claiming Costs eligibility check

---

e2e-tests/cypress/integration/common/eligibility-costs.js
e2e-tests/cypress/integration/eligibility-costs.feature
e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationCostsOutPage.js
e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationCostsPage.js
e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationYourAppealStatementPage.js
e2e-tests/cypress/support/appeal-navigation/eligibility/goToCostsPage.js
e2e-tests/cypress/support/commands.js
e2e-tests/cypress/support/eligibility-costs/confirmAcpLinkDisplayed.js
e2e-tests/cypress/support/eligibility-costs/confirmGuidanceLinkDisplayed.js
e2e-tests/cypress/support/eligibility-costs/provideCostsAnswerNo.js
e2e-tests/cypress/support/eligibility-costs/provideCostsAnswerYes.js

UCD-1582
Add step defs for Costs eligibility check feature

test(e2e-tests): add step defs for Costs eligibility check feature

---

infrastructure/k8s/nginx-ingress/configMaps/response-headers.yaml

feat(forms-web-app): update response header

---

clusters/preprod/app.yml

UCD-1585
Deploy latest FWA to preprod for FQC

chore: deploy latest FWA to preprod for FQC

---

infrastructure/k8s/nginx-ingress/configMaps/response-headers.yaml

fix(forms-web-app): allow self url in reponse header

---

infrastructure/k8s/nginx-ingress/configMaps/response-headers.yaml

fix(forms-web-app): allow google analytics website in response header

---

clusters/preprod/app.yml

UCD-998
Update preprod to latest fwa

chore: update preprod to latest fwa

---

e2e-tests/cypress/integration/common/eligibility-householder.js
e2e-tests/cypress/integration/eligibility-appeal-householder-planning-permission.feature
e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationHouseholderQuestionOutPage.js
e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationHouseholderQuestionPage.js
e2e-tests/cypress/support/appeal-navigation/eligibility/goToHouseholderQuestionOutPage.js
e2e-tests/cypress/support/appeal-navigation/eligibility/goToHouseholderQuestionPage.js
e2e-tests/cypress/support/appeal-navigation/eligibility/goToLandingPage.js
e2e-tests/cypress/support/commands.js
e2e-tests/cypress/support/eligibility-householder/accessDetails.js
e2e-tests/cypress/support/eligibility-householder/confirmDetailsDisplayed.js
e2e-tests/cypress/support/eligibility-householder/provideHouseholderAnswerNo.js
e2e-tests/cypress/support/eligibility-householder/provideHouseholderAnswerYes.js

UCD-1633
Added step defs for Householder Question feature

test(e2e-tests): added step defs for Householder Question feature

---

packages/forms-web-app/src/views/eligibility/householder-planning-permission-out.njk

fixed content on planning permission kick out page
UCD-1698
fixed content on planning permission kick out page

fix(ucd-1698): fixed content on planning permission kick out page

---

packages/lpa-questionnaire-web-app/.eslintrc

Outside of ticket scope
Updated eslint config to use es2020 rather than 2018.

chore(eslintrc): update eslint to es2020

---

.github/PULL_REQUEST_TEMPLATE.md

chore: change PR template from UCD to AS

---

.github/workflows/documentation-update.yml
e2e-tests/documentation/index.html
package.json
packages/horizon-add-document/package-lock.json
packages/horizon-add-document/package.json
packages/horizon-create-contact/package-lock.json
packages/horizon-create-contact/package.json
packages/horizon-householder-appeal-publish/package-lock.json
packages/horizon-householder-appeal-publish/package.json

UCD-1702
publish the new unit tests into the report thing

ci: publish test results for serverless fns

---

e2e-tests/cypress/integration/appeal-submission-creation-of-submission-information-file.feature

AS-1035
adds FF for Creation of submission information file

feat(e2e-tests): adds FF for Creation of submission information file

---

docker-compose.yml

k8 configuration of pdf component
AS-1036
k8 configuration of pdf component gotenberg

feat(as-1036): k8 configuration of pdf component

---

clusters/dev/app.yml
clusters/preprod/app.yml
clusters/prod/app.yml

AS-29
Release manifest for appeal reply service api

chore: configure appeal-reply-service-api release

---

e2e-tests/cypress.json
e2e-tests/cypress/integration/appeal-submission-to-horizon.feature
e2e-tests/cypress/integration/appeal-submission-to-horizon/appeal-submission-to-horizon.js
e2e-tests/cypress/integration/appeal-submission-to-horizon/ucd-831-ac1.json
e2e-tests/cypress/plugins/index.js
e2e-tests/cypress/plugins/queue.js
e2e-tests/package-lock.json
e2e-tests/package.json

AS-190?
re-fit the cypress testing against queue content given new encoding + new expected data format

test: basic assertion against queue on submit

---

packages/horizon-add-document/package-lock.json
packages/horizon-add-document/package.json
packages/horizon-create-contact/package-lock.json
packages/horizon-create-contact/package.json

This meant that the release names were incorrect
UCD-831

fix(package): rename openfaas npm packages

---

e2e-tests/cypress/integration/appeal-submission-to-horizon.feature

feature file to create scenarios for as-102-agent-submit-an-appeal
AS-102
Add feature file AC scenario

test: feature file to create scenarios for as-102-agent-submit-an-appeal

---

clusters/dev/app.yml
clusters/dev/functions.yml
clusters/dev/openfaas.yml

UCD-1239
Configures the deployment:
- OpenFaaS (the serverless framework)
- the AMQP connector (to connect OpenFaaS to Azure Service Bus)
- the Horizon Publisher function (to send through the appeal to Horizon)

chore(dev): configure openfaas infrastructure and horizon functions

---

clusters/preprod/app.yml
clusters/preprod/functions.yml
clusters/preprod/openfaas.yml

UCD-831
Deploy Horizon functions to preprod

chore(preprod): configure openfaas infrastructure and horizon functions

---

.github/workflows/infra-environments.yml
infrastructure/k8s/setup.sh
releases/dev/app.yml
releases/dev/functions.yml
releases/dev/openfaas.yml
releases/preprod/app.yml
releases/preprod/functions.yml
releases/preprod/openfaas.yml
releases/prod/app.yml

AS-1183
This decommissions the `release` branch in favour of a `/releases` folder in the `master` branch. This puts it under firmer control within the PINS release management rules

chore(release): move the release manifests back into the master branch

---

e2e-tests/cypress/integration/appeal-submission-to-horizon.feature
e2e-tests/cypress/integration/appeal-submission-to-horizon/appeal-submission-to-horizon.js
e2e-tests/cypress/support/index.js
e2e-tests/package-lock.json
e2e-tests/package.json

AS-102
suggested better way to assert against our payload during 'submission to horizon' tests

test: add cypress jest plugin for better expectations

---

packages/forms-web-app/src/middleware/initial-cookies.js

AS-1193
adds docblock for initial-cookies middleware

docs(forms-web-app): adds docblock for initial-cookies middleware

---

packages/appeals-service-api/README.md
packages/pdf-service-api/api/openapi.yaml
packages/pdf-service-api/mocks/mocks.js
packages/pdf-service-api/src/__tests__/pdf-failure.spec.js
packages/pdf-service-api/src/__tests__/pdf-success.spec.js
packages/pdf-service-api/src/__tests__/pdf.spec.js
packages/pdf-service-api/src/controllers/pdf.js
packages/pdf-service-api/src/lib/pdfUtils.js

AS-1038
New service to generate pdf files

feat(pdf-service-api): New service to generate pdf files

---

e2e-tests/cypress/integration/cookies-consent-bar.feature

AS-1204
adds FF for cookie consent bar

feat(e2e-tests): adds FF for cookie consent bar

---

e2e-tests/cypress/integration/common/cookies.js

AS-1205
**Incremental PR to share progress in feature file.**
Added placeholder step defs for and moved some existing cookie step defs into common folder so they can be shared between feature files.

test(e2e-tests): update cookie step defs

---

releases/preprod/app.yml

chore(lpa-questionnaire): bump version on preprod

---

charts/functions/values.yaml

AS-190
we're having integration problems
this looks like a typo
it currently doesn't work, so this isn't going to make anything worse.

fix: candidate fix for horizon-wrapper integration failures

---

packages/lpa-questionnaire-web-app/src/routes/extra-conditions.js
packages/lpa-questionnaire-web-app/src/validators/extra-conditions.js
packages/lpa-questionnaire-web-app/tests/unit/validators/extra-conditions.test.js

AS-85
extra conditions validator added

feat(lpa-questionnaire): extra conditions validator added

---

e2e-tests/cypress/integration/eligibility-decision-date-page-components/PageObjects/PO_EligibilityDecisionDate.js
packages/forms-web-app/src/views/layouts/main-no-back-button.njk
packages/forms-web-app/src/views/layouts/main.njk

AS-985
Updating Section Heading link to application root

fix(appeal-service-link): update service link to application root

---

infrastructure/k8s/rbac/user.yaml
infrastructure/k8s/setup.sh

AS-1258
Add RBAC configuration to the namespaces:
- openfaas
- openfaas-fn
- flux

chore: add flux and openfaas namespaces to the rbac configuration

---

.github/workflows/documentation-update.yml
.github/workflows/e2e-tests-on-PR.yml

AS-1294
Add CI SKIP to cypress/docs runs

ci: ignore runs if CI SKIP appears in commit message

---

CODEOWNERS

AS-1184
Applies the release management approvals agreed by @Russ-Clarke and the PINS technical leadership.
This means that any commits to `master` and `develop` must have PR approval from one member of the teams:
- @Russ-Clarke 
- @MrSimonEmms
- @AnthonyJWalsh 
- @shilpabasu22 
- @karunak21 
- @danWatkinson 
- Any member of "Prod"
Infrastructure changes must also be approved by me - if this is successful, we may also extend this to other parts of the codebase having specific owners.

chore: configure code ownership rules

---

packages/forms-web-app/src/controllers/cookies/cookie-preferences.js
packages/forms-web-app/src/lib/views.js
packages/forms-web-app/src/routes/cookies.js
packages/forms-web-app/src/routes/home.js
packages/forms-web-app/src/routes/index.js
packages/forms-web-app/src/views/cookies/cookie-preferences.njk
packages/forms-web-app/tests/unit/controllers/cookies/cookie-preferences.test.js
packages/forms-web-app/tests/unit/lib/views.test.js
packages/forms-web-app/tests/unit/routes/cookies/cookie.test.js
packages/forms-web-app/tests/unit/routes/index.test.js

cookie view preferences web page
AS-1224

feat(as-1224): cooke view preferences web page

---

charts/app/templates/formsWebApp.yaml
docker-compose.yml
e2e-tests/cypress/integration/appellant-confirms-declaration/appellant-confirms-declaration.js
e2e-tests/cypress/integration/common/appeal-submission-confirmation.js
packages/forms-web-app/src/config.js
packages/forms-web-app/src/controllers/appellant-submission/submission.js
packages/forms-web-app/src/lib/documents-api-wrapper.js
packages/forms-web-app/src/lib/pdf-api-wrapper.js
packages/forms-web-app/src/services/pdf.service.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/submission.test.js
packages/forms-web-app/tests/unit/lib/documents-api-wrapper.test.js
packages/forms-web-app/tests/unit/lib/pdf-api-wrapper.test.js
packages/forms-web-app/tests/unit/services/pdf.service.test.js

feat(forms-web-app): generate pdf and store it document store

---

e2e-tests/cypress/integration/cookie-consent-view-preferences.feature
e2e-tests/cypress/integration/cookie-consent-view-preferences/cookie-consent-view-preferences.js
e2e-tests/cypress/support/commands.js
e2e-tests/cypress/support/cookies/goToCookiePreferences.js
packages/appeal-reply-service-api/package-lock.json

cookie view preferences glue code
AS-100
glue code for view cookie preferences web page, and feature file as I messed up original branch

feat(as-1222): cookie view preferences glue code

---

e2e-tests/cypress/integration/appeal-submission-to-horizon-other-appellant-submission-scenarios.feature

AS-1190 subtask for AS-105
Feature file scenarios for AS-105
- [ X ] New features have tests

feat: feature file scenarios for as105 appeal submission to horizon

---

e2e-tests/cypress/fixtures/expected-appeal-where-an-inspector-does-not-require-site-access.json
e2e-tests/cypress/fixtures/expected-appeal-where-an-inspector-does-require-site-access.json
e2e-tests/cypress/fixtures/expected-appeal-with-certificate-a.json
e2e-tests/cypress/fixtures/expected-appeal-without-certificate-a-other-owner-informed.json
e2e-tests/cypress/fixtures/expected-appeal-without-certificate-a-other-owner-not-informed.json
e2e-tests/cypress/integration/appeal-submission-to-horizon-other-appellant-submission-scenarios.feature
e2e-tests/cypress/integration/common/appeal-submission-to-horizon.js

test(e2e-tests): add step defs

---

e2e-tests/cypress/integration/cookie-consent-view-preferences.feature
e2e-tests/cypress/integration/cookie-consent-view-preferences/cookie-consent-view-preferences.js
e2e-tests/cypress/support/commands.js
e2e-tests/cypress/support/cookies/goToCookiePreferences.js
packages/forms-web-app/src/controllers/cookies/cookie-preferences.js
packages/forms-web-app/src/lib/views.js
packages/forms-web-app/src/routes/cookies.js
packages/forms-web-app/src/routes/index.js
packages/forms-web-app/src/views/cookies/cookie-preferences.njk
packages/forms-web-app/tests/unit/controllers/cookies/cookie-preferences.test.js
packages/forms-web-app/tests/unit/lib/views.test.js
packages/forms-web-app/tests/unit/routes/cookies/cookie.test.js
packages/forms-web-app/tests/unit/routes/index.test.js

view cookie preferences web page
AS-100
view cookie preferences web page, feature file and glue code

feat(as-100): view cookie preferences web page

---

releases/dev/functions.yml
releases/preprod/functions.yml

AS-
`DOCUMENT_SERVICE_URL` was incorrect - this corrects it

chore(release): update DOCUMENT_SERVICE_URL to point to correct deployment

---

packages/lpa-questionnaire-web-app/src/views/extra-conditions.njk

AS-1323
Fixes issue with extra conditions text area not linking correctly with errors.

fix(lpa-questionnaire): fix id on extra conditions textarea

---

.releaserc

AS-1225
There is a timing issue with the git HEAD which is preventing tags being created caused by this change
Reverses part of #603 

chore(semantic-release): stop the changelog and versions being updated on new releases

---

releases/preprod/app.yml

AS-2, AS-3
Pre Prod version bump for above tickets

chore: version bump lpa-questionnaire appeal-reply-service pre prod

---

README.md

AS-1312
Updated README.md file to include latest k8s namespaces

docs: updated README.md file to include latest k8s namespaces

---

infrastructure/k8s/rbac/namespaces.yaml

chore(cluster-role): configure a cluster role to allow AAD members to list namespaces

---

releases/preprod/app.yml

AS-116, AS-983, AS-985
Version bump to push fixes to pre prod

chore: bump version of preprod for forms-web-app

---

packages/forms-web-app/package.json

AS-1214
Ensure webpack runs on prod build

build(forms-web-app): run webpack on prod build

---

packages/horizon-householder-appeal-publish/handler.js
packages/horizon-householder-appeal-publish/handler.spec.js

fix(horizon-householder-appeal-publish): update mapping

---

e2e-tests/cypress/integration/common/guidance-pages.js
e2e-tests/cypress/integration/guidance-page-before-you-appeal.feature
e2e-tests/cypress/integration/guidance-page-before-you-appeal/guidance-page-before-you-appeal.js
e2e-tests/cypress/support/commands-go-to-page.js
e2e-tests/cypress/support/commands.js
e2e-tests/cypress/support/go-to-page/goToPageBeforeYouAppeal.js
e2e-tests/cypress/support/guidance-pages/guidancePageNavigation.js
e2e-tests/cypress/support/guidance-pages/guidancePageSelectContentList.js

AS-1331
Feature file and step tests for Before Appeal guidance page

test(forms-e2e): feature file and tests for before you appeal page

---

packages/forms-web-app/src/views/cookies.njk

change cookie preferences page title
AS-100

fix(as-100-page-title): change cookie preferences page title

---

releases/preprod/app.yml

update fwa on pre-prod to 1.22.0

feat(as-100-update-fwa): update fwa on pre-prod to 1.22.0

---

infrastructure/clusters/dev.tfvars
infrastructure/environments/README.md
infrastructure/environments/storage.tf
infrastructure/environments/variables.tf

AS-1430
Grant access to document storage in dev so testers can verify uploaded data

chore(rbac): allow access to the document storage data in dev

---

packages/forms-web-app/src/views/guidance-pages/before-appeal.njk

AS-1243
Fix missing link in view

fix(forms-web-app): add missing link to before appeal page

---

e2e-tests/cypress/integration/common/guidance-pages.js
e2e-tests/cypress/integration/guidance-page-when-you-can-appeal.feature
e2e-tests/cypress/integration/guidance-page-when-you-can-appeal/guidance-page-when-you-can-appeal.js
e2e-tests/cypress/support/commands/guidance-page-commands.js
e2e-tests/cypress/support/go-to-page/goToPageWhenYouCanAppeal.js

AS-1334
Feature file and tests for AS-1244

test(forms-web-app): feature file and steps for when you can appeal page

---

packages/forms-web-app/src/controllers/appellant-submission/submission.js
packages/forms-web-app/src/views/appellant-submission/submission-information.njk
packages/forms-web-app/tests/unit/controllers/appellant-submission/submission.test.js

feat(forms-web-app): change pdf generation process

---

docker-compose.yml
packages/forms-web-app/webpack.dev.js
packages/forms-web-app/webpack.prod.js

AS-1439
Allow GA_ID to be set dynamically from env var

fix(forms-web-app): allow GA_ID to be set dynamically from env var

---

packages/horizon-householder-appeal-publish/handler.js
packages/horizon-householder-appeal-publish/handler.spec.js

AS-1462
Update Source Indicator mapping value

fix(horizon-householder-appeal-publish): update mapping value

---

lpa-submissions-e2e-tests/cypress/integration/appealsDevelopmentPlan/appealsDevelopmentPlanSteps.js
packages/lpa-questionnaire-web-app/src/validators/development-plan.js
packages/lpa-questionnaire-web-app/tests/unit/validators/development-plan.test.js

AS-1302
add validation for development plan

feat(lpa-questionnaire-web-app): add validation for development plan

---

releases/preprod/app.yml

AS-97
bump version of preprod fwa to 1.25.2

chore: bump version of preprod fwa to 1.25.2

---

.github/workflows/ping.yml
charts/functions/templates/_helpers.tpl
charts/functions/templates/horizon-ping.yaml
charts/functions/values.yaml
infrastructure/k8s/monitoring/configMap.yaml
infrastructure/k8s/setup.sh
packages/ping/.eslintrc
packages/ping/.prettierrc
packages/ping/Dockerfile
packages/ping/README.md
packages/ping/index.js
packages/ping/package-lock.json
packages/ping/package.json
releases/dev/functions.yml
releases/preprod/functions.yml

AS-1344
- Configures Prometheus monitoring in [Azure Portal via ConfigMap](https://docs.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-prometheus-integration)
- Adds a Ping service to call Horizon as a health check

Monitor pinging horizon from cluster

---

e2e-tests/cypress/integration/guidance-page-after-you-appeal.feature
e2e-tests/cypress/integration/guidance-page-after-you-appeal/guidance-page-after-you-appeal.js
e2e-tests/cypress/support/commands/guidance-page-commands.js
e2e-tests/cypress/support/go-to-page/goToPageAfterYouAppeal.js

AS-1246
Feature file and tests for After Appeal Page

test(forms-web-app): feature-file-and-tests-for-after-appeal-page

---

packages/forms-web-app/src/controllers/guidance-pages.js
packages/forms-web-app/src/lib/views.js
packages/forms-web-app/src/routes/guidance-pages.js
packages/forms-web-app/src/views/guidance-pages/stages-appeal.njk
packages/forms-web-app/tests/unit/controllers/guidance-pages.test.js
packages/forms-web-app/tests/unit/lib/views.test.js
packages/forms-web-app/tests/unit/routes/guidance-pages.test.js

AS-1337
Stages of an appeal page content

feat(forms-web-app): add stages of an appeal guidance page

---

packages/forms-web-app/src/controllers/guidance-pages.js
packages/forms-web-app/src/lib/views.js
packages/forms-web-app/src/routes/guidance-pages.js
packages/forms-web-app/src/views/guidance-pages/after-appeal.njk
packages/forms-web-app/tests/unit/controllers/guidance-pages.test.js
packages/forms-web-app/tests/unit/lib/views.test.js
packages/forms-web-app/tests/unit/routes/guidance-pages.test.js

AS-1339
Add content for after appeal page

feat(forms-web-app): add after appeal guidance page

---

packages/forms-web-app/src/lib/client-side/google-analytics.js
packages/forms-web-app/src/views/includes/head.njk
packages/forms-web-app/tests/unit/lib/client-side/__snapshots__/google-analytics.test.js.snap
packages/forms-web-app/tests/unit/lib/client-side/google-analytics.test.js
packages/forms-web-app/tests/unit/views/includes/__snapshots__/head.njk.test.js.snap
packages/forms-web-app/webpack.dev.js
packages/forms-web-app/webpack.prod.js
releases/dev/app.yml

AS-1439
Add env appropriate GA_ID to each page and use this value to initialise GA.

fix(forms-web-app): add env appropriate GA_ID value to each page

---

e2e-tests/cypress/integration/guidance-page-start-your-appeal.feature
e2e-tests/cypress/integration/guidance-page-start-your-appeal/guidance-page-start-your-appeal.js
e2e-tests/cypress/support/commands/guidance-page-commands.js
e2e-tests/cypress/support/go-to-page/goToPageStartYourAppeal.js

AS-1340
Feature file and e2e step definitions for Start appeal page

test(forms-web-app-e2e): feature file and steps for start appeal page

---

packages/forms-web-app/src/controllers/guidance-pages.js
packages/forms-web-app/src/lib/views.js
packages/forms-web-app/src/routes/guidance-pages.js
packages/forms-web-app/src/views/guidance-pages/start-appeal.njk
packages/forms-web-app/src/views/layouts/guidance-page.njk
packages/forms-web-app/tests/unit/controllers/guidance-pages.test.js
packages/forms-web-app/tests/unit/lib/views.test.js
packages/forms-web-app/tests/unit/routes/guidance-pages.test.js

AS-1247
Adding content for Start Appeal page.
**Please note feature and tests for this have been merged with master already due to my error.** 

feat(forms-web-app): add start appeal page to guidance pages

---

lpa-submissions-e2e-tests/cypress/integration/appealsDevelopmentPlan/appealsDevelopmentPlanSteps.js
lpa-submissions-e2e-tests/cypress/support/PageObjects/appeals-development-plan-pageobjects.js
lpa-submissions-e2e-tests/cypress/support/appeals-development-plan/inputDevelopmentPlanDetails.js
packages/lpa-questionnaire-web-app/src/controllers/development-plan.js
packages/lpa-questionnaire-web-app/src/routes/development-plan.js
packages/lpa-questionnaire-web-app/src/validators/development-plan.js
packages/lpa-questionnaire-web-app/src/views/development-plan.njk
packages/lpa-questionnaire-web-app/tests/unit/controllers/development-plan.test.js
packages/lpa-questionnaire-web-app/tests/unit/validators/development-plan.test.js

AS-1303
create post request with tests

feat(lpa-questionnaire-web-app): create post request

---

packages/forms-web-app/src/views/appellant-submission/site-ownership-certb.njk

AS-1460
To fix issue was easier to refactor the question to use nunjucks. So I did that.

fix(forms-web-app): move site-ownership-certb to nunjucks

---

releases/preprod/app.yml
releases/preprod/functions.yml

AS-190
release all latest versions to preprod
excluding LPA questionaire as I don't believe it's up to me to make that call for team2..

chore: bump everything except LPAquestionaire in preprod to latest

---

packages/forms-web-app/src/views/guidance-pages/start-appeal.njk

AS-1247
Add missing content to start appeal page

fix(forms-web-app): missing content from start-appeal page

---

packages/forms-web-app/src/views/guidance-pages/start-appeal.njk

AS-1496
Content changes for Start Appeal page

fix(forms-web-app): content changes to start appeal page

---

docker-compose.yml
packages/forms-web-app/src/lib/client-side/google-analytics.js
packages/forms-web-app/tests/unit/lib/client-side/google-analytics.test.js

AS-1498
call GA when initialised

fix(forms-web-app): call GA when initialised

---

packages/forms-web-app/src/views/appellant-submission/confirmation.njk

AS-1345
Update content of confirmation page as requested in ticket

fix(forms-web-app): update content of confirmation page

---

packages/forms-web-app/src/views/guidance-pages/when-appeal.njk

AS-1500
Changes to content following review.

fix(forms-web-app): fix content on when you can appeal page

---

packages/forms-web-app/src/controllers/appellant-submission/submission-information.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/submission-information.test.js
packages/forms-web-app/tests/unit/mocks.js

feat(forms-web-app): define default submission date value

---

releases/preprod/app.yml

AS-1350
bumps forms web app to 1.29.1

chore: bumps forms web app to 1.29.1

---

packages/forms-web-app/src/views/appellant-submission/appeal-statement.njk
packages/forms-web-app/src/views/appellant-submission/applicant-name.njk
packages/forms-web-app/src/views/appellant-submission/application-number.njk
packages/forms-web-app/src/views/appellant-submission/check-answers.njk
packages/forms-web-app/src/views/appellant-submission/site-access-safety.njk
packages/forms-web-app/src/views/appellant-submission/site-access.njk
packages/forms-web-app/src/views/appellant-submission/site-location.njk
packages/forms-web-app/src/views/appellant-submission/site-ownership-certb.njk
packages/forms-web-app/src/views/appellant-submission/site-ownership.njk
packages/forms-web-app/src/views/appellant-submission/submission-information.njk
packages/forms-web-app/src/views/appellant-submission/submission.njk
packages/forms-web-app/src/views/appellant-submission/supporting-documents.njk
packages/forms-web-app/src/views/appellant-submission/task-list.njk
packages/forms-web-app/src/views/appellant-submission/upload-application.njk
packages/forms-web-app/src/views/appellant-submission/upload-decision.njk
packages/forms-web-app/src/views/appellant-submission/who-are-you.njk
packages/forms-web-app/src/views/appellant-submission/your-details.njk
packages/forms-web-app/src/views/eligibility/appeal-statement.njk
packages/forms-web-app/src/views/eligibility/decision-date.njk
packages/forms-web-app/src/views/eligibility/listed-building.njk
packages/forms-web-app/src/views/eligibility/listed-out.njk
packages/forms-web-app/src/views/eligibility/planning-department.njk

AS-1514
Update page titles in accordance with AS-141

fix(forms-web-app): update page titles

---

packages/document-service-api/src/services/upload.service.js
packages/document-service-api/src/services/upload.service.spec.js

fix(document-service-api): fix blob storage client

---

charts/app/templates/formsWebApp.yaml
charts/app/values.yaml
docker-compose.yml
packages/forms-web-app/src/app.js
packages/forms-web-app/src/config.js
packages/forms-web-app/src/lib/extract-root-domain-name-from-full-domain-name.js
packages/forms-web-app/src/lib/remove-unwanted-cookies.js
packages/forms-web-app/tests/unit/lib/extract-root-domain-name-from-full-domain-name.test.js
packages/forms-web-app/tests/unit/lib/remove-unwanted-cookies.test.js
packages/forms-web-app/tests/unit/mocks.js

AS-1230
force cookie removal wrt subdomains

fix(forms-web-app): force cookie removal wrt subdomains

---

README.md

AS-1230
adds docs for seeing what tag is deployed in dev

docs: adds docs for seeing what tag is deployed in dev

---

releases/preprod/app.yml
releases/preprod/functions.yml

AS-1192, AS-104, AS-1230
latest release with documents->horizon fixes, + cookie fixes

chore: release latest cookie+horizon doc fixes to preprod

---

releases/preprod/app.yml

AS-1564
changes GA code for preprod

fix(forms-web-app): changes GA code for preprod

---

packages/forms-web-app/src/controllers/appellant-submission/submission.js

fix(forms-web-app): fix existing session id conflict

---

releases/preprod/app.yml

chore(appeals-service-api): bump appeals-service-api to version 1.8

---

e2e-tests/cypress/integration/cookie-consent-save-preferences/cookie-consent-save-preferences.js

…res against other envs
AS-1564
remove reliance on base URL to avoid local test failures against other envs

fix(e2e-tests): remove reliance on base URL to avoid local test failures against other envs

---

README.md
docker-compose.yml
packages/appeals-service-api/package-lock.json
packages/appeals-service-api/package.json
packages/appeals-service-api/src/lib/config.js
packages/appeals-service-api/src/lib/notify.js
packages/appeals-service-api/src/services/appeal.service.js
packages/appeals-service-api/src/services/lpa.service.js
packages/appeals-service-api/tests/unit/lib/notify.test.js
packages/appeals-service-api/tests/unit/services/appeal.service.test.js

AS-1487
Send email via Notify on Appeal submission

feat(appeals-api-service): send email via Notify on appeal submission

---

e2e-tests/cypress/integration/appeal-submisssion-email-notification.feature
e2e-tests/cypress/integration/common/appeal-submission-to-horizon.js
e2e-tests/package-lock.json
e2e-tests/package.json
lpa-submissions-e2e-tests/package-lock.json
package-lock.json
package.json

AS-288
Add FF for email notifications

test(e2e-tests): add FF for email notifications

---

packages/forms-web-app/src/views/appellant-submission/confirmation.njk

fix(forms-web-app): corrected page title on confirmation page

---

e2e-tests/cypress/fixtures/expected-appeal-with-many-documents.json
e2e-tests/cypress/integration/common/appeal-submission-to-horizon.js
e2e-tests/cypress/support/appeal-statement-submission/uploadAppealStatementFile.js
e2e-tests/cypress/support/appellant-submission-decision-letter/uploadDecisionLetterFile.js
e2e-tests/cypress/support/appellant-submission-supporting-documents/uploadSupportingDocuments.js
e2e-tests/cypress/support/appellant-submission-upload-application/uploadPlanningApplicationFile.js

AS-1577
Update cypress fixture file uploads to handle pdf and other files

test: update cypress fixture file uploads to handle pdf and other files

---

packages/forms-web-app/src/controllers/appellant-submission/submission-information.js
packages/forms-web-app/src/views/appellant-submission/submission-information.njk

AS-1593
Fix date rendering on web page for submitted appeal

fix: fix date rendering on web page for submitted appeal

---

infrastructure/environments/message_queue.tf
infrastructure/environments/monitoring.tf

AS-
Add some more monitoring/alerts

chore(monitoring): add alert for abandoned messages in queue

---

e2e-tests/cypress/integration/appeal-submission-tasklist/appeal-submission-tasklist.js

test(e2e-tests): test task list back button absence

---

packages/forms-web-app/src/views/appellant-submission/task-list.njk

feat(forms-web-app): remove back link button from task list

---

packages/forms-web-app/src/views/appellant-submission/application-number.njk

fix(forms-web-app): update application number header

---

packages/forms-web-app/package.json

build(forms-web-app): run fwa unit tests with a higher worker count

---

releases/prod/app.yml
releases/prod/functions.yml
releases/prod/openfaas.yml

N/A
Prepare a release candidate of the MVP for deployment to Prod.
Supersedes #762 #700 and #555

MVP Release Candidate Prod

---

releases/prod/app.yml

N/A
ID provided by @AnthonyJWalsh as "HAS - Appeal submission confirmation"

fix(prod): update template id [CI SKIP]

---

releases/prod/app.yml

chore(prod): re-enable acp version of site

---

CODEOWNERS
README.md
infrastructure/clusters/dev.tfvars
infrastructure/clusters/preprod.tfvars
infrastructure/environments/README.md
infrastructure/environments/mongodb.tf
infrastructure/environments/variables.tf

AS-
Allow devs access to MongoDB and Blob Storage in dev/preprod clusters

Allow devs access to data in dev/preprod

---

releases/prod/app.yml

Reverts Planning-Inspectorate/appeal-planning-decision#786

Disable ACP in Prod

---

charts/functions/values.yaml

fix(ping-horizon): change timeout to 60 seconds rather than 10 seconds

---

e2e-tests/cypress/integration/common/not-found.js
e2e-tests/cypress/integration/not-found.feature
e2e-tests/cypress/support/integration-with-acp/confirmNavigationPageNotFoundPage.js

test(e2e-tests): add page not found feature file and glue codes

---

packages/forms-web-app/src/views/eligibility/planning-department.njk

AS-1620
Added non-js fallback for LPD selection

feat(forms-web-app): added non-js fallback for LPD selection

---

e2e-tests/cypress/integration/common/eligibility-local-planning-department.js
e2e-tests/cypress/integration/eligibility-local-planning-department-no-js.feature
e2e-tests/cypress/support/commands/eligibility-commands.js
e2e-tests/cypress/support/commands/navigation-commands.js
e2e-tests/cypress/support/eligibility-local-planning-department/confirmEligibleLocalPlanningDepartmentWithoutJs.js
e2e-tests/cypress/support/eligibility-local-planning-department/confirmPlanningDepartmentSelectedWithoutJs.js
e2e-tests/cypress/support/eligibility-local-planning-department/selectEligibleLocalPlanningDepartmentWithoutJs.js
e2e-tests/cypress/support/eligibility-local-planning-department/selectIneligibleLocalPlanningDepartmentWithoutJs.js
e2e-tests/cypress/support/eligibility-local-planning-department/selectLocalPlanningDepartmentWithoutJs.js
e2e-tests/cypress/support/go-to-page/goToPlanningDepartmentPageWithoutJs.js
e2e-tests/cypress/support/visit-without-javascript-enabled.js
packages/forms-web-app/src/views/eligibility/planning-department.njk

AS-169 and AS-1620
Add behaviour for selecting LPD without javascript including e2e tests.

feat(forms-web-app): add behaviour for selecting LPD without javascript

---

e2e-tests/cypress/integration/not-found.feature
packages/forms-web-app/src/views/error/not-found.njk

feat(forms-web-app): update implementation of page not found

---

README.md
infrastructure/common/main.tf
infrastructure/environments/main.tf

docs(readme): add information about terraform [CI SKIP]

---

e2e-tests/cypress/integration/common/eligibility-local-planning-department.js
e2e-tests/cypress/integration/eligibility-local-planning-department-no-js.feature
e2e-tests/cypress/support/commands/eligibility-commands.js
e2e-tests/cypress/support/commands/navigation-commands.js
e2e-tests/cypress/support/eligibility-local-planning-department/confirmEligibleLocalPlanningDepartmentWithoutJs.js
e2e-tests/cypress/support/eligibility-local-planning-department/confirmPlanningDepartmentSelectedWithoutJs.js
e2e-tests/cypress/support/eligibility-local-planning-department/selectEligibleLocalPlanningDepartmentWithoutJs.js
e2e-tests/cypress/support/eligibility-local-planning-department/selectIneligibleLocalPlanningDepartmentWithoutJs.js
e2e-tests/cypress/support/eligibility-local-planning-department/selectLocalPlanningDepartmentWithoutJs.js
e2e-tests/cypress/support/go-to-page/goToPlanningDepartmentPageWithoutJs.js
e2e-tests/cypress/support/visit-without-javascript-enabled.js
packages/forms-web-app/src/views/eligibility/planning-department.njk

AS-986
LPD selection without JavaScript

Feature/as 986 - LPD selection without JavaScript

---

releases/preprod/app.yml

AS-112
AS-989
release to preprod

chore: bump preprod, post-mvp fixes

---

packages/lpa-questionnaire-web-app/src/controllers/upload-plans.js
packages/lpa-questionnaire-web-app/src/lib/file-upload-helpers.js
packages/lpa-questionnaire-web-app/tests/unit/controllers/upload-plans.test.js
packages/lpa-questionnaire-web-app/tests/unit/lib/file-upload-helpers.test.js

AS-1537
Refactor of controller to make it more reusable for other questions of the same type

refactor(lpa-questionnaire): improve reusability of common file modules

---

packages/forms-web-app/src/views/guidance-pages/start-appeal.njk

feat(forms-web-app): update start guidance content

---

releases/preprod/app.yml

as-986
as-1556
as-1198
preprod release

chore(as-986 as-1556 as-1198): post mvp bugfixes

---

.github/workflows/infra-environments.yml
infrastructure/environments/README.md
infrastructure/environments/local.tf
infrastructure/environments/message_queue.tf
infrastructure/environments/monitoring.tf
infrastructure/environments/variables.tf

N/A
- Add multiple emails to the monitoring action group
- GitHub Actions secret set to devops and F4 devs distribution groups

Add support for multiple alert emails

---

infrastructure/common/README.md
infrastructure/environments/README.md
infrastructure/environments/local.tf
infrastructure/environments/monitoring.tf
infrastructure/environments/variables.tf

chore(monitoring): change list of emails to a comma-separated list

---

.github/workflows/e2e-tests-on-PR.yml

chanhe machines to 8
AS-1608
Change machines config

feat(as-1608-machines): change machines 

---

e2e-tests/cypress/integration/common/appeal-header-footer.js
e2e-tests/cypress/integration/common/eligibility-local-planning-department.js
e2e-tests/cypress/support/axe/index.js
e2e-tests/cypress/support/commands.js
e2e-tests/cypress/support/go-to-page/goToAccessSitePage.js
e2e-tests/cypress/support/go-to-page/goToAppealStatementInfoPage.js
e2e-tests/cypress/support/go-to-page/goToAppealStatementSubmission.js
e2e-tests/cypress/support/go-to-page/goToDecisionLetterPage.js
e2e-tests/cypress/support/go-to-page/goToHealthAndSafetyPage.js
e2e-tests/cypress/support/go-to-page/goToPlanningApplicationSubmission.js
e2e-tests/package-lock.json
e2e-tests/package.json
packages/forms-web-app/src/controllers/eligibility/planning-department.js
packages/forms-web-app/src/lib/planning-departments-to-nunjucks-list-items.js
packages/forms-web-app/src/views/appellant-submission/appeal-statement.njk
packages/forms-web-app/src/views/appellant-submission/site-access.njk
packages/forms-web-app/src/views/appellant-submission/upload-application.njk
packages/forms-web-app/src/views/appellant-submission/upload-decision.njk
packages/forms-web-app/src/views/eligibility/appeal-statement.njk
packages/forms-web-app/src/views/eligibility/planning-department.njk
packages/forms-web-app/src/views/layouts/main.njk
packages/forms-web-app/tests/unit/controllers/eligibility/planning-department.test.js
packages/forms-web-app/tests/unit/lib/planning-departments-to-nunjucks-list-items.test.js

AS-1618
adds AXE to CI pipeline flow, fix accessibility issues found by AXE

fix(forms-web-app): adds AXE to CI pipeline flow, fix accessibility issues found by AXE

---

releases/preprod/app.yml

update formswebapp to 1.33.0 - rc 2.1.2
AS-1351
update formswebapp to 1.33.0

feat(rc-2.1.2-pre-prod): update formswebapp to 1.33.0 pre-prod

---

e2e-tests/cypress/integration/appeal-statement-submission.feature
packages/forms-web-app/src/validators/appellant-submission/appeal-statement-schema.js
packages/forms-web-app/tests/unit/validators/appellant-submission/appeal-statement-schema.test.js
packages/forms-web-app/tests/unit/validators/appellant-submission/appeal-statement.test.js

feat(forms-web-app): the appeal statement is mandatory

---

e2e-tests/cypress/integration/appellant-submission-upload-application.feature
e2e-tests/cypress/integration/appellant-submission-upload-application/appellant-submission-upload-application.js

test(e2e-tests): update mandatory planning application in feature file

---

releases/preprod/app.yml

updating web forms app in preprod
AS-1559
Release to preprod 

feat(as-1559): updating web forms app in preprod to 1.34.0

---

.github/workflows/e2e-tests-on-PR.yml
e2e-tests/cypress/integration/appeal-statement-submission.feature
e2e-tests/cypress/integration/appeal-statement-submission/appeal-statement-submission.js
e2e-tests/cypress/support/appeal-statement-submission/confirmFileUploadIsRequested.js
e2e-tests/cypress/support/commands/submission-commands.js
packages/forms-web-app/src/validators/appellant-submission/appeal-statement-schema.js
packages/forms-web-app/tests/unit/validators/appellant-submission/appeal-statement-schema.test.js
packages/forms-web-app/tests/unit/validators/appellant-submission/appeal-statement.test.js

test(e2e-tests): update mandatory appeal statement

---

.github/workflows/e2e-tests-on-PR.yml
e2e-tests/cypress/integration/appellant-submission-decision-letter.feature
e2e-tests/cypress/integration/appellant-submission-decision-letter/appellant-submission-decision-letter.js
packages/forms-web-app/src/validators/appellant-submission/upload-decision-schema.js
packages/forms-web-app/tests/unit/validators/appellant-submission/upload-decision-schema.test.js
packages/forms-web-app/tests/unit/validators/appellant-submission/upload-decision.test.js

test: mandatory decision letter file

---

e2e-tests/cypress/integration/appellant-submission-upload-application.feature
e2e-tests/cypress/integration/appellant-submission-upload-application/appellant-submission-upload-application.js
packages/forms-web-app/src/validators/appellant-submission/upload-application-schema.js
packages/forms-web-app/tests/unit/validators/appellant-submission/upload-application-schema.test.js
packages/forms-web-app/tests/unit/validators/appellant-submission/upload-application.test.js

feat: mandatory planning application file

---

packages/document-service-api/src/api/openapi.yaml

AS-1591
Updated openapi docs to include delete.

feat(document-service-api): updated openapi documentation

---

releases/preprod/app.yml

chore: bump fwa preprod to ~1.36.1

---

e2e-tests/cypress/support/integration-with-acp/confirmNavigationPageNotFoundPage.js
packages/forms-web-app/src/views/error/not-found.njk

AS-1705
amend page title on 404 error page

fix(forms-web-app): amend page title on 404 error page

---

e2e-tests/cypress/integration/appellant-submission-decision-letter.feature
e2e-tests/cypress/support/appellant-submission-decision-letter/confirmDecisionLetterRejectedBecause.js
packages/forms-web-app/src/views/appellant-submission/upload-decision.njk

AS-1677
adds 'error' to page title - decision upload

fix(forms-web-app): adds 'error' to page title - decision upload

---

packages/forms-web-app/src/validators/appellant-submission/appeal-statement.js
packages/forms-web-app/tests/unit/validators/appellant-submission/appeal-statement.test.js

fix(forms-web-app): change appeal statement error messages order

---

e2e-tests/cypress/integration/appeal-submission-appeal-site-address.feature
e2e-tests/cypress/support/appeal-submission-appeal-site-address/confirmSiteAddressWasRejectedBecause.js
packages/forms-web-app/src/views/appellant-submission/site-location.njk

AS-1680
adds 'error' to page title - site location

fix(forms-web-app): adds 'error' to page title - site location

---

infrastructure/clusters/prod.tfvars
infrastructure/environments/README.md
infrastructure/environments/mongodb.tf
infrastructure/environments/variables.tf

Allow Pen testers access to the mongodb in prod

---

.github/workflows/e2e-tests-on-PR.yml

cypress machine configuration
AS-1696
Change machine config to 3

fix(as-1696): cypress machine configuration

---

charts/app/templates/queueRetry.yaml
releases/preprod/app.yml
releases/prod/app.yml

N/A
Deploy queue retry service to preprod and prod

Deploy queue retry to preprod and prod

---

e2e-tests/cypress/integration/eligibility-listed-building-status.feature
e2e-tests/cypress/support/eligibility-listed-building-status/confirmListedBuildingStatementIsRequired.js
packages/forms-web-app/src/views/eligibility/listed-building.njk

AS-1670
adds 'error' to page title - listed building

fix(forms-web-app): adds 'error' to page title - listed building

---

e2e-tests/cypress/support/eligibility-enforcement-notice/confirmThatEnforcementNoticeAnswerIsRequired.js
packages/forms-web-app/src/views/eligibility/enforcement-notice.njk

fix(forms-web-app): enforcement notice in title

---

e2e-tests/cypress/integration/eligibility-decision-date.feature
e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationDecisionDateAbsentPage.js
e2e-tests/cypress/support/eligibility-decision-date/confirmProvidedDecisionDateError.js
packages/forms-web-app/src/views/eligibility/decision-date.njk

AS-1666
adds 'error' to page title - decision date

fix(forms-web-app): adds 'error' to page title - decision date

---

e2e-tests/cypress/integration/appellant-submission-your-details-who-are-you.feature
e2e-tests/cypress/support/appellant-submission-your-details/confirmWhoAreYouRejectedBecause.js
packages/forms-web-app/src/views/appellant-submission/who-are-you.njk

AS-1672
adds 'error' to page title - who are you

fix(forms-web-app): adds 'error' to page title - who are you

---

.github/workflows/e2e-tests-on-PR.yml

amend cypress machines to 5
AS-1696
amend cypress machines to 5

feat(as-1696): amend cypress machines to 5

---

e2e-tests/cypress/integration/appellant-submission-your-details-your-details-first-submissison.feature
e2e-tests/cypress/integration/appellant-submission-your-details-your-details-previously-submitted.feature
e2e-tests/cypress/support/appellant-submission-your-details/confirmDetailsWasRejected.js
packages/forms-web-app/src/views/appellant-submission/your-details.njk

AS-1673
adds 'error' to page title - your details

fix(forms-web-app): adds 'error' to page title - your details

---

e2e-tests/cypress/support/appellant-submission-planning-application-number/confirmPlanningApplicationNumberRejectedBecause.js
packages/forms-web-app/src/views/appellant-submission/application-number.njk

fix(forms-web-app): application number error in title

---

e2e-tests/cypress/support/appellant-submission-your-details/confirmOriginalApplicantWasRejected.js
packages/forms-web-app/src/views/appellant-submission/applicant-name.njk

fix(forms-web-app): applicant name error in title

---

e2e-tests/cypress/support/eligibility-local-planning-department/confirmLocalPlanningDepartmentIsRequired.js
packages/forms-web-app/src/views/eligibility/planning-department.njk

fix(forms-web-app): planning department error in title

---

e2e-tests/cypress/support/appellant-submission-upload-application/confirmPlanningApplicationRejectedBecause.js
packages/forms-web-app/src/views/appellant-submission/upload-application.njk

fix(forms-web-app): upload application error in title

---

e2e-tests/cypress/integration/appeal-submission-access-to-appeal-site.feature
e2e-tests/cypress/support/appeal-submission-access-to-appeal-site/confirmAccessSiteWasRejectedBecause.js
packages/forms-web-app/src/views/appellant-submission/site-access.njk

AS-1683
adds 'error' to page title - site access

fix(forms-web-app): adds 'error' to page title - site access

---

e2e-tests/cypress/integration/common/eligibility-costs.js
packages/forms-web-app/src/views/eligibility/costs.njk

fix(forms-web-app): claiming costs error in title

---

e2e-tests/cypress/integration/appeal-statement-submission.feature
e2e-tests/cypress/integration/appeal-statement-submission/appeal-statement-submission.js
packages/forms-web-app/src/views/appellant-submission/appeal-statement.njk

AS-1678
Add Error: to page title for error conditions on the appeal statement page.

feat(forms-web-app): add Error: to page title for error conditions

---

releases/preprod/app.yml

chore: bump FWA to 1.37.2

---

releases/preprod/app.yml

chore(forms-web-app): bump from 1.37.2 to 1.38.0

---

releases/preprod/app.yml
releases/prod/app.yml

Deploy OpenFaaS connector to preprod and prod clusters

---

.github/workflows/terraform-validate.yml
infrastructure/environments/kubernetes.tf
infrastructure/environments/storage.tf
infrastructure/environments/variables.tf

AS-
Applied the [tfsec](https://github.com/tfsec/tfsec) package to Terraform builds, and fixes a couple of issues. A couple are ignored because they don't fit our use-case or are false-positives

chore(terraform): configure terraform security checks

---

releases/prod/app.yml

chore(release): prod release

---

infrastructure/clusters/prod.tfvars

chore(pentest): remove pen test access in prod

---

.github/workflows/documentation-update.yml

documentation run cache
AS-1825
Documentation Run Cache

feat(as-1825): documenatation run cache

---

.github/workflows/documentation-update.yml

build document cache
AS-1825
Build document cache

feat(as-1825): build document cache

---

.github/workflows/documentation-update.yml

amend document run to increase machines
AS-1825
amend document run to increase machines

feat(as-1825): amend document run to increase machines

---

releases/preprod/app.yml

release fwa 1.39 to pre-prod
AS-1627
release fwa 1.39 to pre-prod

feat(as-1627): release fwa 1.39 to pre-prod

---

lpa-submissions-e2e-tests/cypress/support/commands.js

AS-1827
fixed non-passing tests

fix(lpa-submissions-e2e-tests): fixed non-passing tests

---

.github/workflows/documentation-update.yml

cypress documentation
AS-1825
Change to Cypress Documentation

feat(as-1825): cypress documentation

---

.github/workflows/documentation-update.yml

cypress documentation run
AS-1825
Cypress Documentation Run

feat(as-1825): cypress documentation run

---

.github/PULL_REQUEST_TEMPLATE.md

AS-
The idea is to make it one step easier to review ticket when doing a PR 

chore: set the ticket number to be a JIRA link

---

.github/workflows/documentation-update.yml

documentation run
https://pins-ds.atlassian.net/browse/AS-1825
Documentation Run

feat(as-1825): documentation run

---

.github/workflows/documentation-update.yml

correct issue with cypress documentation
https://pins-ds.atlassian.net/browse/AS-1825
Correct issues with Cypress documentation

feat(as-1825): correct issue with cypress documentation

---

releases/prod/app.yml

update production fwa to 1.39.0
https://pins-ds.atlassian.net/browse/AS-1627
update production fwa to 1.39.0

chore(as-1627): update production fwa to 1.39.0

---

packages/lpa-questionnaire-web-app/src/controllers/questionnaire-submitted.js
packages/lpa-questionnaire-web-app/src/lib/views.js
packages/lpa-questionnaire-web-app/src/routes/index.js
packages/lpa-questionnaire-web-app/src/routes/questionnaire-submitted.js
packages/lpa-questionnaire-web-app/src/views/questionnaire-submitted.njk
packages/lpa-questionnaire-web-app/tests/unit/controllers/questionnaire-submitted.test.js
packages/lpa-questionnaire-web-app/tests/unit/lib/views.test.js
packages/lpa-questionnaire-web-app/tests/unit/routes/index.test.js
packages/lpa-questionnaire-web-app/tests/unit/routes/questionnaire-submitted.test.js

https://pins-ds.atlassian.net/browse/AS-1851
created view

feat(lpa-questionnaire-web-app): created view

---

e2e-tests/cypress/fixtures/as-102-ac1.json
e2e-tests/cypress/fixtures/expected-appeal-where-an-inspector-does-not-require-site-access.json
e2e-tests/cypress/fixtures/expected-appeal-where-an-inspector-does-require-site-access.json
e2e-tests/cypress/fixtures/expected-appeal-with-certificate-a.json
e2e-tests/cypress/fixtures/expected-appeal-with-many-documents.json
e2e-tests/cypress/fixtures/expected-appeal-without-certificate-a-other-owner-informed.json
e2e-tests/cypress/fixtures/expected-appeal-without-certificate-a-other-owner-not-informed.json
e2e-tests/cypress/fixtures/ucd-831-ac1.json
e2e-tests/cypress/integration/common/standard-appeal.js
e2e-tests/cypress/support/appellant-submission-check-your-answers/provideCompleteAppeal.js
e2e-tests/cypress/support/eligibility-listed-building-status/confirmUserCanProceedWithNonListedBuilding.js
packages/appeals-service-api/api/openapi.yaml
packages/appeals-service-api/src/models/appeal.js
packages/appeals-service-api/src/validators/appeals/schemas/insert-appeal.js
packages/appeals-service-api/src/validators/appeals/schemas/update-appeal.js
packages/appeals-service-api/tests/unit/validators/appeals-update.validator.test.js
packages/appeals-service-api/tests/unit/value-appeal.js

https://pins-ds.atlassian.net/browse/AS-1855
extend appeals api with isListedBuilding

feat(as-1855): extend appeals api with isListedBuilding

---

releases/preprod/app.yml

https://pins-ds.atlassian.net/browse/AS-1697
prprod release

feat: preprod release of AS-1697

---

e2e-tests/cypress/fixtures/as-102-ac1.json
e2e-tests/cypress/fixtures/expected-appeal-where-an-inspector-does-not-require-site-access.json
e2e-tests/cypress/fixtures/expected-appeal-where-an-inspector-does-require-site-access.json
e2e-tests/cypress/fixtures/expected-appeal-with-certificate-a.json
e2e-tests/cypress/fixtures/expected-appeal-with-many-documents.json
e2e-tests/cypress/fixtures/expected-appeal-without-certificate-a-other-owner-informed.json
e2e-tests/cypress/fixtures/expected-appeal-without-certificate-a-other-owner-not-informed.json
e2e-tests/cypress/fixtures/ucd-831-ac1.json
e2e-tests/cypress/integration/common/appeal-submission-to-horizon.js
e2e-tests/cypress/integration/common/standard-appeal.js
e2e-tests/cypress/support/appellant-submission-check-your-answers/provideCompleteAppeal.js
packages/forms-web-app/src/controllers/eligibility/listed-building.js
packages/forms-web-app/src/routes/eligibility/listed-building.js
packages/forms-web-app/src/validators/eligibility/listed-building.js
packages/forms-web-app/src/views/eligibility/listed-building.njk
packages/forms-web-app/tests/unit/controllers/eligibility/listed-building.test.js
packages/forms-web-app/tests/unit/routes/eligibility/listed-building.test.js
packages/forms-web-app/tests/unit/validators/eligibility/listed-building.test.js

https://pins-ds.atlassian.net/browse/AS-1858
Fixes issue whereby given answer was not being saved or redisplayed on the front end

fix(forms-web-app): controller, validator, route + unit tests for eligibility listed building

---

packages/lpa-questionnaire-web-app/src/services/task-status/check-your-answer.js
packages/lpa-questionnaire-web-app/src/services/task-status/check-your-answers.js
packages/lpa-questionnaire-web-app/src/services/task-status/index.js
packages/lpa-questionnaire-web-app/src/services/task.service.js
packages/lpa-questionnaire-web-app/tests/unit/services/task-status/check-your-answers.test.js

https://pins-ds.atlassian.net/browse/AS-1835
- Adds validation for check your answers on task list
- Removed Check Answers from task completion index to avoid circular reference

feat(questionnaire-web-app): add validation for task list completion

---

e2e-tests/cypress/integration/appeal-submission-more-than-one-appeal.feature

AS-1517
Create Feature file to create more than 1 appeal
- [ X ] New features have tests

feat: new feature file for as-1517 to create more than one appeal

---

packages/lpa-questionnaire-web-app/src/config.js
packages/lpa-questionnaire-web-app/src/lib/pdf-api-wrapper.js
packages/lpa-questionnaire-web-app/src/services/pdf.service.js
packages/lpa-questionnaire-web-app/tests/unit/lib/pdf-api-wrapper.test.js
packages/lpa-questionnaire-web-app/tests/unit/services/pdf.service.test.js

https://pins-ds.atlassian.net/browse/AS-1875
added pdf generation to reply service

feat(lpa-questionnaire-web-app): added pdf generation to reply service

---

lpa-submissions-e2e-tests/cypress/integration/appealsQuestionnaireTaskList/appealsQuestionnaireTaskListSteps.js

https://pins-ds.atlassian.net/browse/AS-22-fix
fixed missing test file

fix(lpa-submissions-e2e-tests): fixed missing file

---

packages/forms-web-app/src/server.js

https://pins-ds.atlassian.net/browse/AS-1909
pointless change to force version bump to debug deploy issues

feat: pointless change to force version bump+deploy as test

---

releases/preprod/app.yml

Pre-prod version bump for LPA Questionnaire to 1.8.0

chore: questionnaire preprod version bump 1.7.0 > 1.8.0

---

lpa-submissions-e2e-tests/cypress/integration/uploadThePlansToReachDecision/uploadPlansToReachDecisionSteps.js
packages/lpa-questionnaire-web-app/src/lib/file-upload-helpers.js
packages/lpa-questionnaire-web-app/src/views/upload-plans.njk
packages/lpa-questionnaire-web-app/tests/unit/lib/file-upload-helpers.test.js

https://pins-ds.atlassian.net/browse/AS-1907
- Added error to title when error present
- Added ID to error for link from error summary

fix(questionnaire-web-app): fix errror handling for file uploads

---

releases/dev/app.yml

update fwa version in dev
https://pins-ds.atlassian.net/browse/AS-116
update fwa in dev

feat(as-116): update fwa version in dev

---

releases/dev/app.yml

reverse fwa release version in dev
https://pins-ds.atlassian.net/browse/AS-116
Reverse fwa release version in development

feat(as-116): reverse fwa release version in dev

---

lpa-submissions-e2e-tests/cypress/integration/planningOfficersReport.feature

https://pins-ds.atlassian.net/browse/AS-1916
Feature file for AS-10

test(questionnaire-e2e): added feature for planning officers report

---

packages/appeals-service-api/tests/unit/lib/notify.test.js

amend bradford lpa to bradford for notify test
https://pins-ds.atlassian.net/browse/AS-116
Amend Bradford LPA to Bradford for notify tests

feat(as-116): amend bradford lpa to bradford for notify test

---

packages/appeals-service-api/api/openapi.yaml
packages/appeals-service-api/package-lock.json
packages/appeals-service-api/src/schemas/lpa.js
packages/appeals-service-api/src/schemas/lpa.spec.js

fix lpa inengland, inwales
https://pins-ds.atlassian.net/browse/AS-1975
fix lpa inwales, inengland

feat(as-1975): fix lpa inengland, inwales

---

lpa-submissions-e2e-tests/cypress/integration/common/taskList.js
lpa-submissions-e2e-tests/cypress/integration/representationInterestedParties.feature
lpa-submissions-e2e-tests/cypress/integration/representationInterestedParties/representationInterestedParties.step.js

https://pins-ds.atlassian.net/browse/AS-1945
- Added feature and step files for Repesentations from interested parties question
- Added new steps for new AC in this ticket

test(questionnaire-e2e): feature and step file for interested parties

---

releases/dev/app.yml

PR to force deployment to dev.

fix(forms web app): version bump to trigger a deploy manually

---

releases/dev/app.yml

Reverting hard coded version for forms web app.

fix(forms web app): revert hard coded version

---

.github/workflows/helm-validation.yml

Ensure `helm lint` is run as part of CI.

build: adds helm chart validation github action

---

lpa-submissions-e2e-tests/cypress/fixtures/completedAppealReply.json
lpa-submissions-e2e-tests/cypress/integration/common/uploadFiles.js
lpa-submissions-e2e-tests/cypress/integration/notifyingInterestedParties.feature
lpa-submissions-e2e-tests/cypress/integration/notifyingInterestedParties/notifyingInterestedParties.step.js
lpa-submissions-e2e-tests/cypress/support/common/subTasks.js

https://pins-ds.atlassian.net/browse/AS-2004
Added feature and tests for notifying interested parties
Formatted uploadFiles common steps

test(questionnaire-e2e): add feature and steps for notifying parties

---

packages/forms-web-app/src/middleware/combine-date-inputs.js

fix(forms-web-app): a small change to trigger a build

---

packages/forms-web-app/tests/unit/controllers/appellant-submission/confirmation.test.js

https://pins-ds.atlassian.net/browse/AS-2050
adds missing unit test for session wipe in confirmation controller

test(forms-web-app): adds missing unit test for session wipe in confirmation controller

---

e2e-tests/cypress/integration/appeal-submission-more-than-one-appeal/appeal-submission-more-than-one-appeal.js

AS-1517
AS-1517 added missing code due to merging issues.

test: updated with the missing code for agent due to merging issues

---

lpa-submissions-e2e-tests/cypress/fixtures/completedAppealReply.json
lpa-submissions-e2e-tests/cypress/integration/planningHistory.feature
lpa-submissions-e2e-tests/cypress/integration/planningHistory/planningHistory.step.js
lpa-submissions-e2e-tests/cypress/support/common/subTasks.js

https://pins-ds.atlassian.net/browse/AS-2006
Feature and steps for planning history question

test(questionnaire-e2e): feature and tests for planning history

---

packages/lpa-questionnaire-web-app/src/lib/views.js
packages/lpa-questionnaire-web-app/src/routes/index.js
packages/lpa-questionnaire-web-app/src/routes/planning-history.js
packages/lpa-questionnaire-web-app/src/services/task-status/index.js
packages/lpa-questionnaire-web-app/src/services/task-status/planning-history.js
packages/lpa-questionnaire-web-app/src/services/task.service.js
packages/lpa-questionnaire-web-app/src/views/planning-history.njk
packages/lpa-questionnaire-web-app/tests/unit/lib/views.test.js
packages/lpa-questionnaire-web-app/tests/unit/routes/index.test.js
packages/lpa-questionnaire-web-app/tests/unit/routes/planning-history.test.js
packages/lpa-questionnaire-web-app/tests/unit/services/task-status/planning-history.test.js

https://pins-ds.atlassian.net/browse/AS-2007
Development work to add planning history question

feat(questionnaire-web-app): added planning history question

---

packages/lpa-questionnaire-web-app/src/services/task.service.js

https://pins-ds.atlassian.net/browse/AS-2089
Update link for plans page in task list and check your answers

fix(questionnaire-web-app): rename task list link for plans

---

.github/workflows/documentation-update.yml

resolve documentation acp issue
https://pins-ds.atlassian.net/browse/AS-1869
resolve documentation acp issue

fix(as-1869): resolve documentation acp issue

---

releases/preprod/app.yml

Releases/pre prod fwa 1.43.1 appeals api 1.15.1

---

packages/lpa-questionnaire-web-app/src/controllers/confirm-answers.js
packages/lpa-questionnaire-web-app/src/controllers/information-submitted.js
packages/lpa-questionnaire-web-app/src/routes/confirm-answers.js
packages/lpa-questionnaire-web-app/src/routes/information-submitted.js
packages/lpa-questionnaire-web-app/src/views/confirm-answers.njk
packages/lpa-questionnaire-web-app/src/views/error/not-found.njk
packages/lpa-questionnaire-web-app/src/views/error/unhandled-exception.njk
packages/lpa-questionnaire-web-app/tests/unit/controllers/confirm-answers.test.js
packages/lpa-questionnaire-web-app/tests/unit/controllers/information-submitted.test.js
packages/lpa-questionnaire-web-app/tests/unit/routes/confirm-answers.test.js

https://pins-ds.atlassian.net/browse/AS-48
Added submission event to call PDF service and for e2e testing

feat(questionnaire-web-app): add endpoint for submission

---

lpa-submissions-e2e-tests/cypress/support/common/completeQuestionnaire.js

https://pins-ds.atlassian.net/browse/AS-15
Add missing step for manual questionnaire completion (used when testing deployed environments)

test(questionnaire-e2e): added planning step for e2e deployed

---

releases/prod/app.yml

chore: prod release fwa 1.43.1, appeals api 1.15.1

---

README.md

adds documentation for logging into the three different k8s envs

docs: adds documentation for logging into the three different k8s envs

---

releases/preprod/app.yml

Version bump questionnaire web app on pre prod to 1.15.X

chore: version bump pre prod questionnaire

---

releases/preprod/app.yml

https://pins-ds.atlassian.net/browse/AS-67
earlier release of features to preprod missed the need to bump document-service-api as part of as-67

chore: bump document-service-api

---

packages/forms-web-app/src/views/appellant-submission/check-answers.njk
packages/forms-web-app/src/views/appellant-submission/submission-information.njk

fix: fix typo in "you're appealing"

---

e2e-tests/cypress/fixtures/as-102-ac1.json
e2e-tests/cypress/fixtures/expected-appeal-where-an-inspector-does-not-require-site-access.json
e2e-tests/cypress/fixtures/expected-appeal-where-an-inspector-does-require-site-access.json
e2e-tests/cypress/fixtures/expected-appeal-with-certificate-a.json
e2e-tests/cypress/fixtures/expected-appeal-with-many-documents.json
e2e-tests/cypress/fixtures/expected-appeal-without-certificate-a-other-owner-informed.json
e2e-tests/cypress/fixtures/expected-appeal-without-certificate-a-other-owner-not-informed.json
e2e-tests/cypress/fixtures/ucd-831-ac1.json
e2e-tests/cypress/integration/common/standard-appeal.js
packages/appeals-service-api/src/validators/appeals/schemas/insert-appeal.js
packages/appeals-service-api/src/validators/appeals/schemas/update-appeal.js
packages/appeals-service-api/tests/unit/controllers/appeals.test.js
packages/appeals-service-api/tests/unit/services/appeal.service.test.js
packages/appeals-service-api/tests/unit/validators/appeals-update.validator.test.js
packages/appeals-service-api/tests/unit/value-appeal.js
packages/forms-web-app/src/controllers/appellant-submission/appeal-statement.js
packages/forms-web-app/src/controllers/appellant-submission/submission.js
packages/forms-web-app/src/controllers/appellant-submission/upload-application.js
packages/forms-web-app/src/controllers/appellant-submission/upload-decision.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/appeal-statement.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/submission.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/upload-application.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/upload-decision.test.js

https://pins-ds.atlassian.net/browse/AS-2131
Capture required additional fields for single file upload

Single file uploads capture the same fields as Multi file uploads 

---

packages/appeal-reply-service-api/package-lock.json
packages/appeal-reply-service-api/package.json
packages/appeal-reply-service-api/src/controllers/reply.js
packages/appeal-reply-service-api/src/lib/config.js
packages/appeal-reply-service-api/src/lib/queue.js
packages/appeal-reply-service-api/src/models/replySchema.js

https://pins-ds.atlassian.net/browse/AS-2114
- Added queue functions
- Added submission date setting
- Added submission actions
Given lack of unit testing in this service, no tests created. Suggest we handle adding this testing an a high priority ticket

feat(appeal-reply-service): added functionality for posting to queue

---

packages/forms-web-app/src/views/your-planning-appeal/index.njk

…real change
a small change to trigger the build process - no real change

fix(forms-web-app): a small change to trigger the build process - no real change

---

.github/workflows/e2e-tests-on-PR.yml

increase cypress machines to 7
https://pins-ds.atlassian.net/browse/AS-2104
increase cypress machines to 7

feat(as-2104): increase cypress machines to 7

---

releases/preprod/app.yml

chore: bumps FWA to 1.44.0 preprod

---

e2e-tests/cypress/integration/your-planning-appeal-landing-page/your-planning-appeal-landing-page.js

fix delay for feature file
https://pins-ds.atlassian.net/browse/AS-1606
fix delay for feature file

fix(as-1606): fix delay for feature file

---

packages/forms-web-app/src/views/your-planning-appeal/index.njk

https://pins-ds.atlassian.net/browse/AS-1606
Updates following FQC

fix: remove back button from your planning appeal page

---

.github/workflows/documentation-update.yml
.github/workflows/e2e-tests-on-PR.yml

increase cypress machines to 10
https://pins-ds.atlassian.net/browse/AS-1607
Increase machines to 10

fix(as-1607): increase cypress machines to 10

---

.github/workflows/documentation-update.yml
.github/workflows/e2e-tests-on-PR.yml

reduce cypress machines to 7
https://pins-ds.atlassian.net/browse/AS-1607
reduce cypress machines to 7

fix(as-1607): reduce cypress machines to 7

---

packages/forms-web-app/src/views/guidance-pages/start-appeal.njk

https://pins-ds.atlassian.net/browse/AS-2209
Adding 2 extra paragraphs of informational text to the page

fix(forms-web-app): updates to copy on start page

---

charts/app/templates/appealReplyServiceApi.yaml

https://pins-ds.atlassian.net/browse/AS-2361
added variable for appealsReplyQueue Config

chore(reply service queue): added variable for appealsReplyQueue Config

---

e2e-tests/cypress/integration/your-planning-appeal-your-appeal-details-agent/your-planning-appeal-your-appeal-details-agent.js
e2e-tests/cypress/integration/your-planning-appeal-your-appeal-details-appellant/your-planning-appeal-your-appeal-details-appellant.js
packages/forms-web-app/src/views/your-planning-appeal/your-appeal-details/your-appeal-details-summary.njk

https://pins-ds.atlassian.net/browse/AS-2347
remove email address from "view my appeal" detail page

fix(forms-web-app): remove email address from "view my appeal" detail page

---

lpa-submissions-e2e-tests/cypress/fixtures/completedAppealReply.json
lpa-submissions-e2e-tests/cypress/integration/otherRelevantPolicies.feature
lpa-submissions-e2e-tests/cypress/integration/otherRelevantPolicies/otherRelevantPolicies.step.js
packages/appeal-reply-service-api/src/models/replySchema.js
packages/lpa-questionnaire-web-app/src/lib/views.js
packages/lpa-questionnaire-web-app/src/routes/index.js
packages/lpa-questionnaire-web-app/src/routes/other-policies.js
packages/lpa-questionnaire-web-app/src/services/task-status/index.js
packages/lpa-questionnaire-web-app/src/services/task-status/other-policies.js
packages/lpa-questionnaire-web-app/src/services/task.service.js
packages/lpa-questionnaire-web-app/src/views/other-policies.njk
packages/lpa-questionnaire-web-app/tests/unit/lib/views.test.js
packages/lpa-questionnaire-web-app/tests/unit/routes/index.test.js
packages/lpa-questionnaire-web-app/tests/unit/routes/other-policies.test.js
packages/lpa-questionnaire-web-app/tests/unit/services/task-status/other-policies.test.js

https://pins-ds.atlassian.net/browse/AS-2343
add other policies page

feat(lpa-questionnaire-web-app): add other policies page

---

lpa-submissions-e2e-tests/cypress/fixtures/completedAppealReply.json
packages/lpa-questionnaire-web-app/src/lib/views.js
packages/lpa-questionnaire-web-app/src/routes/index.js
packages/lpa-questionnaire-web-app/src/routes/statutory-development.js
packages/lpa-questionnaire-web-app/src/services/task-status/index.js
packages/lpa-questionnaire-web-app/src/services/task-status/statutory-development.js
packages/lpa-questionnaire-web-app/src/services/task.service.js
packages/lpa-questionnaire-web-app/src/views/statutory-development.njk
packages/lpa-questionnaire-web-app/tests/unit/lib/views.test.js
packages/lpa-questionnaire-web-app/tests/unit/routes/index.test.js
packages/lpa-questionnaire-web-app/tests/unit/routes/statutory-development.test.js
packages/lpa-questionnaire-web-app/tests/unit/services/task-status/statutory-development.test.js

https://pins-ds.atlassian.net/browse/AS-2225
add-statutory-development-page

feat(lpa-questionnaire-web-app): add statutory development page

---

charts/app/templates/lpaQuestionnaireWebApp.yaml

fix: add pdf service env variable to chart for questionnaire app

---

releases/prod/app.yml

https://pins-ds.atlassian.net/browse/AS-2347
Release to prod

chore: release FWA 1.45.3 to prod

---

lpa-submissions-e2e-tests/cypress/integration/appealsInformationSubmitted.feature
lpa-submissions-e2e-tests/cypress/integration/appealsInformationSubmitted/appealsInformationSubmittedSteps.js
packages/lpa-questionnaire-web-app/src/controllers/information-submitted.js
packages/lpa-questionnaire-web-app/src/views/information-submitted.njk
packages/lpa-questionnaire-web-app/tests/unit/controllers/information-submitted.test.js
packages/lpa-questionnaire-web-app/tests/unit/mockAppealReply.js

https://pins-ds.atlassian.net/browse/AS-2227
added email to view

feat(lpa-questionnaire-web-app): add email to view

---

lpa-submissions-e2e-tests/cypress/fixtures/completedAppealReply.json
lpa-submissions-e2e-tests/cypress/integration/otherRelevantPolicies.feature
lpa-submissions-e2e-tests/cypress/integration/otherRelevantPolicies/otherRelevantPolicies.step.js
lpa-submissions-e2e-tests/cypress/support/common/completeQuestionnaire.js
lpa-submissions-e2e-tests/cypress/support/common/subTasks.js
packages/appeal-reply-service-api/src/models/replySchema.js
packages/lpa-questionnaire-web-app/src/lib/views.js
packages/lpa-questionnaire-web-app/src/routes/index.js
packages/lpa-questionnaire-web-app/src/routes/other-policies.js
packages/lpa-questionnaire-web-app/src/services/task-status/index.js
packages/lpa-questionnaire-web-app/src/services/task-status/other-policies.js
packages/lpa-questionnaire-web-app/src/services/task.service.js
packages/lpa-questionnaire-web-app/src/views/other-policies.njk
packages/lpa-questionnaire-web-app/tests/unit/lib/views.test.js
packages/lpa-questionnaire-web-app/tests/unit/routes/index.test.js
packages/lpa-questionnaire-web-app/tests/unit/routes/other-policies.test.js
packages/lpa-questionnaire-web-app/tests/unit/services/task-status/other-policies.test.js

https://pins-ds.atlassian.net/browse/AS-17
add other policies page

feat(lpa-submissions-e2e-tests): add other policies page

---

releases/preprod/app.yml

https://pins-ds.atlassian.net/browse/AS-2013
deploy fwa 1.46.0 to pre-prod

chore: deploy fwa 1.46.0 to pre-prod

---

packages/appeal-reply-service-api/src/controllers/reply.js
packages/horizon-householder-appeal-publish/handler-reply.js

fix(horizon): add logging for horizon submission

---

LICENSE.md

https://pins-ds.atlassian.net/browse/AS-2262
add MIT license file

docs(as-2262): add MIT license file

---

lpa-submissions-e2e-tests/cypress/fixtures/completedAppealReply.json
lpa-submissions-e2e-tests/cypress/integration/statutoryDevelopmentPlanPolicy.feature
lpa-submissions-e2e-tests/cypress/integration/statutoryDevelopmentPlanPolicy/statutoryDevelopmentPlanPolicy.step.js
lpa-submissions-e2e-tests/cypress/support/common/completeQuestionnaire.js
lpa-submissions-e2e-tests/cypress/support/common/subTasks.js
packages/lpa-questionnaire-web-app/src/lib/views.js
packages/lpa-questionnaire-web-app/src/routes/index.js
packages/lpa-questionnaire-web-app/src/routes/statutory-development.js
packages/lpa-questionnaire-web-app/src/services/task-status/index.js
packages/lpa-questionnaire-web-app/src/services/task-status/statutory-development.js
packages/lpa-questionnaire-web-app/src/services/task.service.js
packages/lpa-questionnaire-web-app/src/views/statutory-development.njk
packages/lpa-questionnaire-web-app/tests/unit/lib/views.test.js
packages/lpa-questionnaire-web-app/tests/unit/routes/index.test.js
packages/lpa-questionnaire-web-app/tests/unit/routes/statutory-development.test.js
packages/lpa-questionnaire-web-app/tests/unit/services/task-status/statutory-development.test.js

https://pins-ds.atlassian.net/browse/AS-16
add statutory development page

test(statutory development plan policy): add statutory development page

---

packages/horizon-add-document/handler.js
packages/horizon-add-document/handler.spec.js

https://pins-ds.atlassian.net/browse/AS-2419
fix issue with ispublish flag for horizon

fix(as-2419): fix issue with ispublish flag for horizon

---

packages/forms-web-app/src/views/appellant-submission/confirmation.njk

https://pins-ds.atlassian.net/browse/AS-2331
Addition of copy to the Appeal confirmation page

fix: update copy on Appeal confirmation page (AS-2331)

---

packages/forms-web-app/Dockerfile

https://pins-ds.atlassian.net/browse/AS-2326
Small dummy change to test the CI pipeline.

fix(forms-web-app): small dummy change to test CI pipeline

---

.github/workflows/forms-web-app.yml
packages/forms-web-app/Dockerfile

https://pins-ds.atlassian.net/browse/AS-2326
As this type of work can only be tested by creating releases and running the pipeline, some tweaks will be needed after test runs of the pipeline.

fix(forms-web-app): as-2326 fix the new release version variable

---

.github/workflows/appeal-reply-service-api.yml
.github/workflows/appeals-service-api.yml
.github/workflows/document-service-api.yml
.github/workflows/horizon-add-document.yml
.github/workflows/horizon-create-case.yml
.github/workflows/horizon-householder-appeal-publish.yml
.github/workflows/lpa-questionnaire.yml
.github/workflows/openfaas-amqp-connector.yml
.github/workflows/pdf-service-api.yml
.github/workflows/ping.yml
.github/workflows/queue-retry.yml

https://pins-ds.atlassian.net/browse/AS-2326
Add the fix to all workflows.

chore: as-2326 add the new changes to all remaining workflows

---

releases/preprod/functions.yml

https://pins-ds.atlassian.net/browse/AS-2419
deploy horizon-add-document 1.2.1 to pre-prod

chore(as-2419): deploy horizon-add-document 1.2.1 to pre-prod

---

packages/appeal-reply-service-api/src/controllers/reply.js
packages/horizon-householder-appeal-publish/handler-reply.js
packages/horizon-householder-appeal-publish/tests/handler-reply.spec.js

… bug
https://pins-ds.atlassian.net/browse/AS-2482
fixed depth id bug

fix(horizon-householder-appeal-publish): fixed depth id bug

---

.github/workflows/terraform-validate.yml

https://pins-ds.atlassian.net/browse/AS-2472
PR to fix the failing workflow: "Terraform Validation". The version of TF security scan needs an upgrade.

chore: as-2472 upgrade tf security scan version

---

packages/lpa-questionnaire-web-app/src/views/other-policies.njk

https://pins-ds.atlassian.net/browse/AS-2548
fix incorrect text on page

fix(lpa-questionnaire-web-app): fix incorrect text on page

---

packages/lpa-questionnaire-web-app/src/views/pdf-generation.njk

https://pins-ds.atlassian.net/browse/AS-2504
Fix heading as was missed in previous PR

fix(lpa-questionnaire-web-app): fix pdf heading

---

packages/lpa-questionnaire-web-app/src/views/interested-parties.njk

https://pins-ds.atlassian.net/browse/AS-2533
fix page description

fix(lpa-questionnaire-web-app): fix page description

---

.github/workflows/e2e-tests-on-PR.yml
e2e-tests/cypress.json
lpa-submissions-e2e-tests/cypress.json

fix(as-2532): stop cypress video artifacts

---

lpa-submissions-e2e-tests/cypress/integration/cookie-consent-save-preferences.feature
lpa-submissions-e2e-tests/cypress/integration/cookie-consent-view-preferences-with-javascript-enabled.feature
lpa-submissions-e2e-tests/cypress/integration/cookie-consent-view-preferences-without-javascript-enabled.feature
lpa-submissions-e2e-tests/cypress/integration/cookies-consent-bar-with-javascript-enabled.feature
lpa-submissions-e2e-tests/cypress/integration/cookies-consent-bar-without-javascript-enabled.feature
lpa-submissions-e2e-tests/cypress/integration/cookies-disabled-by-default.feature

https://pins-ds.atlassian.net/browse/AS-2387
Feature files for Cookies 

test: feature file added for cookies preference

---

e2e-tests/cypress/integration/common/eligibility-local-planning-department.js
e2e-tests/cypress/integration/eligibility-decision-date-page-components/PageObjects/PO_EligibilityNoDecision.js
packages/forms-web-app/src/views/eligibility/no-decision.njk
packages/forms-web-app/src/views/eligibility/planning-department-out.njk

https://pins-ds.atlassian.net/browse/AS-2490
Updating page titles raised in accessibility checks

fix: update page titles for accessibility AS-2490

---

packages/forms-web-app/Dockerfile

https://pins-ds.atlassian.net/browse/AS-2541
Dummy release to test the pipeline now that flux automation has been disabled.

fix: as-2541 dummy release to test pipeline

---

.github/workflows/commit.yml
releases/dev/app.yml

https://pins-ds.atlassian.net/browse/AS-2541
Test a manual deployment now that flux automation has been disabled.

chore: [ci skip] as-2541 deploy forms-web-app-v1.46.6 to dev

---

.github/workflows/appeal-reply-service-api.yml
.github/workflows/appeals-service-api.yml
.github/workflows/common.yml
.github/workflows/document-service-api.yml
.github/workflows/forms-web-app.yml
.github/workflows/horizon-add-document.yml
.github/workflows/horizon-create-case.yml
.github/workflows/horizon-householder-appeal-publish.yml
.github/workflows/lpa-questionnaire.yml
.github/workflows/openfaas-amqp-connector.yml
.github/workflows/pdf-service-api.yml
.github/workflows/ping.yml
.github/workflows/queue-retry.yml

https://pins-ds.atlassian.net/browse/AS-2590
As DevOps, I want to delete the local flux-sync tags before every run of semantic-release, so that the risk of git fetch "clobber tags" errors are minimised.
See the ticket for more information.

chore: as-2590 delete local flux sync tags

---

packages/horizon-add-document/handler.js

fix(horizon-add-document): horizon logging

---

releases/dev/app.yml

chore: deploy v1.16.0 of ARS API

---

.github/workflows/e2e-tests-on-PR.yml

https://pins-ds.atlassian.net/browse/AS-2575
Identify Cypress Parallel Jobs

fix(as-2575): identify Cypress Groups

---

e2e-tests/cypress/integration/your-planning-appeal-landing-page/your-planning-appeal-landing-page.js
e2e-tests/package-lock.json
e2e-tests/package.json
package-lock.json
package.json

https://pins-ds.atlassian.net/browse/AS-2574
Update Cypress version

fix(as-2574): update cypress version

---

releases/dev/app.yml

chore: deploy Appeal Reply Service API v1.6.0

---

e2e-tests/cypress/integration/eligibility-decision-date-page-components.feature
e2e-tests/cypress/integration/eligibility-decision-date-page-components/PageObjects/PO_EligibilityDecisionDate.js
e2e-tests/cypress/integration/eligibility-decision-date-page-components/eligibility-decision-date-page-components.js

test(test): fix failed tests in decision date

---

lpa-submissions-e2e-tests/cypress/fixtures/completedAppealReply.json
lpa-submissions-e2e-tests/cypress/integration/common/booleanQuestion.js
lpa-submissions-e2e-tests/cypress/integration/enterAppealSite.feature
lpa-submissions-e2e-tests/cypress/integration/enterAppealSite/enterAppealSite.step.js
lpa-submissions-e2e-tests/cypress/integration/siteSeenPublicLand.feature

test(questionnaire-e2e): feature and tests for boolean with text

---

packages/appeal-reply-service-api/src/lib/config.js
packages/appeals-service-api/src/lib/config.js

fix: minor change to force a new build

---

packages/horizon-add-document/handler.js
packages/horizon-add-document/handler.spec.js

added horizonId and edited logging

fix(horizon-add-document): added horizonId and edited logging

---

README.md
charts/app/values.yaml
docker-compose.yml
documentation/debugger.md
e2e-tests/README.md
e2e-tests/cypress.json

https://pins-ds.atlassian.net/browse/AS-2608
Amend fwa to port 9003

fix(as-2608): amend fwa port to 9003

---

releases/dev/functions.yml

chore(horizon-add-document): version bump

---

releases/dev/functions.yml

chore: version bump

---

packages/appeals-service-api/src/main.js

fix: small change to ASAPI to trigger new build

---

releases/dev/functions.yml

horizon-householder-appeal-publish-version-bump

chore(horizon-householder-appeal-publish): version bump

---

releases/dev/app.yml

Release PR for 1.24.0 of LPA Questionnaire

chore: deploy lpa-questionnaire-web-app-v1.24.0 to dev [ci skip]

---

releases/dev/functions.yml

chore(horizon): version bumps [ci skip]

---

releases/dev/app.yml

https://pins-ds.atlassian.net/browse/AS-1660
adds missing config for notify secret to ARS API

fix: adds missing config for notify secret to ARS API

---

packages/appeal-reply-service-api/README.md

fix: force a new fix tag for ARS API

---

releases/dev/app.yml

chore: [ci skip] deploy v1.6.2 ARS API dev

---

packages/horizon-add-document/handler.js

fix(horizon-add-document): logging change

---

releases/dev/functions.yml

chore(horizon add document): version bump [ci-skip]

---

.github/workflows/e2e-tests-on-PR.yml

https://pins-ds.atlassian.net/browse/AS-2632
resolve cypress issues

fix(as-2632): fix cypress intermittent failures

---

releases/prod/app.yml

https://pins-ds.atlassian.net/browse/AS-2490
Deploy fwa 1.46.5 to production

chore(as-2490): deploy fwa 1.46.5 to prod

---

releases/dev/app.yml

Version bump for lpa-questionnaire-web-app dev environment

chore: deploy lpa-questionnaire-web-app-v1.25.0 to dev [ci skip]

---

lpa-submissions-e2e-tests/cypress/integration/pageFooter.feature

https://pins-ds.atlassian.net/browse/AS-2602

test: feature file for footer

---

releases/dev/app.yml

https://pins-ds.atlassian.net/browse/AS-1660
deploy appeal-reply-service-api-v1.7.1 to dev

chore: [ci skip] deploy appeal-reply-service-api-v1.7.1 to dev

---

releases/dev/functions.yml

chore(horizon-householder-appeal-publish): version bump [ci skip]

---

releases/dev/functions.yml

chore(horizon-ass-document): version bump 1.2.11->1.2.12

---

packages/horizon-householder-appeal-publish/handler-reply.js
packages/horizon-householder-appeal-publish/tests/handler-reply.spec.js

fix(horizon-add-document): edit hard-coded horizonId

---

releases/dev/functions.yml

chore(horizon-add-document): version bump [ci skip]

---

packages/lpa-questionnaire-web-app/src/views/accuracy-submission.njk
packages/lpa-questionnaire-web-app/src/views/development-plan.njk
packages/lpa-questionnaire-web-app/src/views/extra-conditions.njk
packages/lpa-questionnaire-web-app/src/views/other-appeals.njk

https://pins-ds.atlassian.net/browse/AS-2638
add ‘Error: ’ to the beginning of the page <title>

fix(lpa-questionnaire-web-app): add ‘Error: ’ to the beginning of the page <title>

---

lpa-submissions-e2e-tests/cypress/integration/pageFooter.feature
lpa-submissions-e2e-tests/cypress/integration/pageFooter/pageFooter.step.js

test: added Cypress tests for Footer

---

packages/forms-web-app/Dockerfile

Dummy release to test pipeline

fix: as-2663 dummy release to test pipeline

---

.github/actions/semantic-release/action.yml
.github/workflows/appeal-reply-service-api.yml
.github/workflows/appeals-service-api.yml
.github/workflows/document-service-api.yml
.github/workflows/forms-web-app.yml
.github/workflows/horizon-add-document.yml
.github/workflows/horizon-create-case.yml
.github/workflows/horizon-householder-appeal-publish.yml
.github/workflows/lpa-questionnaire.yml
.github/workflows/openfaas-amqp-connector.yml
.github/workflows/pdf-service-api.yml
.github/workflows/ping.yml
.github/workflows/queue-retry.yml

Rollback changes due to unforeseen effects with the CI pipeline.

chore: as-2663 rollback due to pipeline errors

---

packages/forms-web-app/src/views/includes/head.njk
packages/forms-web-app/tests/unit/views/includes/__snapshots__/head.njk.test.js.snap

https://pins-ds.atlassian.net/browse/AS-2493
resolve html validation error wrt to head > p tag

fix(forms-web-app): resolve html validation error wrt to head > p tag

---

releases/dev/app.yml

chore: [ci-skip] deploy fwa 1.46.10 to dev

---

releases/preprod/app.yml

deploy 1.46.10 of FWA to preprod

chore(forms-web-app): deploy 1.46.10 of FWA to preprod

---

e2e-tests/cypress/integration/appeal-submission-confirmation.feature
e2e-tests/cypress/integration/appellant-submission-header.feature
e2e-tests/cypress/support/appeal-header-footer/confirmFeedbackLinkIsDisplayed.js
e2e-tests/cypress/support/appeal-submission/confirmFeedbackLinkIsDisplayedInPageBody.js
packages/forms-web-app/src/views/appellant-submission/confirmation.njk
packages/forms-web-app/src/views/layouts/guidance-page.njk
packages/forms-web-app/src/views/layouts/main.njk

https://pins-ds.atlassian.net/browse/AS-2264
replace Smart Survey with MS Form

fix(forms-web-app): replace Smart Survey with MS Form

---

releases/preprod/app.yml

deploy appeal-reply-service-api-v1.7.1, appeals-service-api-v1.16.2 to preprod
https://pins-ds.atlassian.net/browse/AS-1660
deploy appeal-reply-service-api-v1.7.1, appeals-service-api-v1.16.2 to preprod

chore: [ci skip] deploy appeal-reply-service-api-v1.7.1, appeals-service-api-v1.16.2 to preprod

---

releases/dev/app.yml

chore: deploy forms-web-app-v1.46.11 to dev

---

releases/dev/app.yml

deploy lpa-questionnaire-web-app-v1.27.0, forms-web-app-v1.47.0 to dev

chore: deploy lpa-questionnaire-web-app-v1.27.0, forms-web-app-v1.47.0 to dev

---

packages/forms-web-app/src/views/appellant-submission/upload-application.njk

https://pins-ds.atlassian.net/browse/AS-2494
add aria-labelledby to input for upload-application form

fix(forms-web-app): add aria-labelledby to input for upload-application form

---

releases/prod/app.yml

chore(forms-web-app): deploy 1.46.10 FWA to prod

---

releases/preprod/app.yml

chore: [ci skip] deploy 1.46.11 fwa to preprod

---

charts/app/templates/appealsServiceApi.yaml
charts/app/values.yaml
docker-compose.yml
e2e-tests/cypress.json
e2e-tests/cypress/integration/appeal-submisssion-email-notification.feature
e2e-tests/cypress/integration/common/appeal-submission-to-horizon.js
packages/appeals-service-api/src/lib/config.js
packages/appeals-service-api/src/lib/notify.js
packages/appeals-service-api/src/services/appeal.service.js
packages/appeals-service-api/tests/unit/lib/notify.test.js
packages/appeals-service-api/tests/unit/services/appeal.service.test.js
releases/dev/app.yml
releases/preprod/app.yml
releases/prod/app.yml

https://pins-ds.atlassian.net/browse/AS-1703
Adds link to `your-planning-appeal` to submission confirmation email instead of pdf

feat: add your-planning-appeal link to post appeal submission email

---

releases/dev/app.yml

chore: [ci skip] release 1.47.1 to dev

---

releases/preprod/functions.yml

chore(horizon): version bump pre-prod [ci skip]

---

releases/preprod/app.yml

chore(forms-web-app): [ci skip] Deploy fwa 1.47.1 to preprod

---

releases/dev/app.yml

https://pins-ds.atlassian.net/browse/AS-1703
Release feature to dev environment

chore: [ci skip] deploy 1.19.0 appeals-service-api to dev

---

releases/prod/app.yml

Deployment of 1.47.1 of FWA to prod
forms-web-app-v1.47.1 (2021-06-14)
Bug Fixes
forms-web-app: add aria-labelledby to input for upload-application form (90ea6f5)
forms-web-app-v1.47.0 (2021-06-11)
Features
extract footer from FWA, move to common, import for FWA & LPAQ (88247f4)
forms-web-app-v1.46.11 (2021-06-11)
Bug Fixes
forms-web-app: replace Smart Survey with MS Form (53e0241)

chore(forms-web-app): deploy 1.47.1 of FWA to prod

---

releases/dev/app.yml

chore(forms-web-app): [ci skip] deploy 1.47.2 fwa to dev

---

releases/dev/app.yml

chore/version bump [ci skip]

---

releases/preprod/app.yml

chore(forms-web-app): [ci skip] deploy 1.47.2 to preprod

---

e2e-tests/cypress/integration/appeal-submission-appeal-site-address/appeal-submission-appeal-site-address.js
packages/forms-web-app/src/validators/appellant-submission/site-location.js
packages/forms-web-app/src/views/appellant-submission/site-location.njk
packages/forms-web-app/tests/unit/validators/appellant-submission/site-location.test.js

https://pins-ds.atlassian.net/browse/AS-2483
make City have uppercase c for site-location label

fix(forms-web-app): make City have uppercase c for site-location label

---

releases/dev/app.yml

chore(forms-web-app): [ci skip] deploy 1.47.3 fwa to dev

---

charts/app/templates/appealsServiceApi.yaml

https://pins-ds.atlassian.net/browse/AS-1703
Fix typo in config value

fix: config value typo

---

releases/preprod/app.yml

deploy fwa 1.47.3 to pre-prod
https://pins-ds.atlassian.net/browse/AS-2483
deploy fwa 1.47.3 to pre-prod

chore(as-2483): deploy fwa 1.47.3 to pre-prod

---

packages/pdf-service-api/src/lib/pdfUtils.js

fix(pdf-service-api): fix pdf cut-off issue

---

releases/prod/app.yml

https://pins-ds.atlassian.net/browse/AS-2483
deploy fwa 1.47.3 and appeals api 1.19.0 to production

chore(as-2483): deploy fwa 1.47.3 and appeals api 1.19.0

---

releases/dev/app.yml

chore(lpa-questionnaire-web-app): rollback version bump [ci skip]

---

lpa-submissions-e2e-tests/cypress/integration/nearConservationArea/nearConservationArea.step.js
packages/lpa-questionnaire-web-app/src/lib/questionTypes.js

fix(lpa-questionnaire-web-app): fixed typo

---

e2e-tests/cypress/support/appeal-statement-submission/confirmAppealStatementFileIsUploaded.js
e2e-tests/cypress/support/appellant-submission-decision-letter/confirmDecisionLetterAccepted.js
e2e-tests/cypress/support/appellant-submission-decision-letter/confirmDecisionLetterFileIsUploaded.js
e2e-tests/cypress/support/appellant-submission-upload-application/confirmPlanningApplicationAccepted.js
e2e-tests/cypress/support/appellant-submission-upload-application/confirmPlanningApplicationFileIsUploaded.js
packages/document-service-api/src/controllers/documents.js
packages/forms-web-app/src/controllers/document-service-proxy.js
packages/forms-web-app/src/lib/appeals-api-wrapper.js
packages/forms-web-app/src/lib/documents-api-wrapper.js
packages/forms-web-app/src/middleware/ensure-appeal-matches-session.js
packages/forms-web-app/src/middleware/navigation-history.js
packages/forms-web-app/src/routes/document-service-proxy.js
packages/forms-web-app/src/routes/index.js
packages/forms-web-app/src/views/appellant-submission/appeal-statement.njk
packages/forms-web-app/src/views/appellant-submission/check-answers.njk
packages/forms-web-app/src/views/appellant-submission/supporting-documents.njk
packages/forms-web-app/src/views/appellant-submission/upload-application.njk
packages/forms-web-app/src/views/appellant-submission/upload-decision.njk
packages/forms-web-app/src/views/components/multi-file-upload/template.njk
packages/forms-web-app/src/views/macros/document-download-field.njk
packages/forms-web-app/src/views/macros/multifile-upload-to-anchor-list.njk
packages/forms-web-app/tests/unit/controllers/document-service-proxy.test.js
packages/forms-web-app/tests/unit/lib/documents-api-wrapper.test.js
packages/forms-web-app/tests/unit/middleware/ensure-appeal-matches-session.test.js
packages/forms-web-app/tests/unit/middleware/navigation-history.test.js
packages/forms-web-app/tests/unit/mocks.js
packages/forms-web-app/tests/unit/routes/document-service-proxy.test.js
packages/forms-web-app/tests/unit/routes/index.test.js

https://pins-ds.atlassian.net/browse/AS-2802

feat(forms-web-app): proxy to documents service api to allow in session downloads

---

lpa-submissions-e2e-tests/cypress/integration/originalPlanningApplicationPublicised.feature
lpa-submissions-e2e-tests/cypress/integration/originalPlanningApplicationPublicised/originalPlanningApplicationPublicised.step.js
packages/lpa-questionnaire-web-app/src/lib/questionTypes.js

fix(lpa-questionnaire-web-app): added error message for nothing selected

---

releases/dev/app.yml

deploy fwa 1.47.4 to dev environment
https://pins-ds.atlassian.net/browse/AS-2495
Deploy as-2495/fwa 1.47.4 to dev environment

chore(as-2495): deploy fwa 1.47.4 to dev environment

---

releases/dev/app.yml

chore(dev-version-bump): version bump [ci skip]

---

e2e-tests/cypress/integration/appellant-submission-decision-letter/appellant-submission-decision-letter.js
e2e-tests/cypress/integration/appellant-submission-supporting-documents/appellant-submission-supporting-documents.js
e2e-tests/cypress/integration/appellant-submission-upload-application/appellant-submission-upload-application.js
e2e-tests/cypress/support/appeal-statement-submission/confirmFileInvalidBecauseWrongFileType.js
packages/forms-web-app/src/validators/appellant-submission/appeal-statement-schema.js
packages/forms-web-app/src/validators/appellant-submission/supporting-documents-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-application-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-decision-schema.js
packages/forms-web-app/tests/unit/validators/appellant-submission/appeal-statement-schema.test.js
packages/forms-web-app/tests/unit/validators/appellant-submission/supporting-documents-schema.test.js
packages/forms-web-app/tests/unit/validators/appellant-submission/upload-application-schema.test.js
packages/forms-web-app/tests/unit/validators/appellant-submission/upload-decision-schema.test.js
packages/forms-web-app/tests/unit/validators/custom/mime-binary-type.test.js

https://pins-ds.atlassian.net/browse/AS-2833
Update error messages for uploaded files

feat(as-2833): update error messages for uploaded files

---

releases/preprod/app.yml

deplot fwa 1.47.4 to pre prod
https://pins-ds.atlassian.net/browse/AS-2495
deploy fwa 1.47.4 to pre prod

chore(as-2495): deploy fwa 1.47.4 to pre prod

---

packages/appeal-reply-service-api/src/controllers/reply.js

fix(appeal-reply-service-api): kick off automatic run

---

releases/dev/app.yml

chore(appeal-reply-service-api): version bump [ci skip]

---

releases/dev/app.yml

chore(lpa-questionnaire-web-app): version bump [ci skip]

---

e2e-tests/cypress/integration/common/appellant-submission-your-details.js
e2e-tests/cypress/support/appellant-submission-your-details/confirmWhoAreYouRejectedBecause.js
e2e-tests/cypress/support/appellant-submission-your-details/provideAnswerNo.js
e2e-tests/cypress/support/appellant-submission-your-details/provideAnswerYes.js
packages/forms-web-app/src/controllers/appellant-submission/who-are-you.js
packages/forms-web-app/src/validators/appellant-submission/who-are-you.js
packages/forms-web-app/src/views/appellant-submission/who-are-you.njk
packages/forms-web-app/tests/unit/controllers/appellant-submission/who-are-you.test.js

https://pins-ds.atlassian.net/browse/AS-2754
amend wording on the original applicant question

feat(as-2754): amend content on original applicant question

---

docker-compose.yml

feat: Add mongo GUI app

---

releases/dev/app.yml

deploy fwa 1.51.0 to dev
https://pins-ds.atlassian.net/browse/AS-2802
Deploy fwa 1.51.0 to dev

chore(as-2802): deploy fwa 1.51.0 to dev

---

releases/dev/app.yml

deploy fwa 1.51.1 to dev
https://pins-ds.atlassian.net/browse/AS-2889
deploy as-2889 to dev environment

chore(as-2889): deploy fwa 1.51.1 to dev

---

charts/app/templates/clamav.yaml
charts/app/values.yaml
docker-compose.yml
packages/forms-web-app/package-lock.json
packages/forms-web-app/package.json
packages/forms-web-app/src/validators/appellant-submission/appeal-statement-schema.js
packages/forms-web-app/src/validators/appellant-submission/supporting-documents-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-application-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-decision-schema.js
packages/forms-web-app/src/validators/custom/clamav.js

implement clamav
Implement clamav for forms web app

feat(as-2831): implement clamav

---

releases/dev/app.yml

deploy clamav to dev
deploy clamav to dev

chore(as-2831): deploy clamav to dev

---

charts/app/templates/clamav.yaml
charts/app/values.yaml

fix issue with k8s deployment
fix issue with k8s deployment

fix(as-2831): fix issue with k8s deployment

---

charts/app/values.yaml

fix(as-2831): fix k8s

---

charts/app/templates/clamav.yaml
charts/app/values.yaml

fix(as-2831): k8s fix

---

packages/forms-web-app/src/validators/custom/clamav.js

fix clamav server name
fix clamav server name

fix(as-2831): fix clamav server name

---

releases/dev/app.yml

deploy fwa 1.52.1 to dev
Deploy fwa 1.52.1 to dev

chore(as-2831): deploy fwa 1.52.1 to dev

---

docker-compose.yml
packages/forms-web-app/src/validators/appellant-submission/appeal-statement-schema.js
packages/forms-web-app/src/validators/appellant-submission/supporting-documents-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-application-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-decision-schema.js

disable clam av
Disable clamav

fix(as-2831): disable clamav

---

docker-compose.yml

correct clamav server
correct clamav server name

fix(as-2831): correct clamav server

---

packages/forms-web-app/src/validators/appellant-submission/appeal-statement-schema.js
packages/forms-web-app/src/validators/appellant-submission/supporting-documents-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-application-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-decision-schema.js

configure clamav
configure clamav

fix(as-2831): configure clamav

---

releases/dev/app.yml

chore(as-2831): deploy fwa 1.52.3 to dev

---

releases/dev/app.yml

chore(as-2831): deploy fwa to dev

---

releases/dev/app.yml

chore(lpa-questionnaire-web-app): vb rollback [ci skip]

---

releases/dev/app.yml

chore(lpa-questionnaire): web-app roll forward [ci skip]

---

packages/lpa-questionnaire-web-app/src/controllers/upload-question.js

fix(lpa-q): filter files on delete

---

packages/lpa-questionnaire-web-app/src/lib/appeal-reply-api-wrapper.js

fix(lp-web-app): change to kick off kubernetes

---

releases/dev/app.yml

chore(lpa-questionnaire-web-app): update env vars

---

packages/forms-web-app/src/validators/appellant-submission/appeal-statement-schema.js

fix(as-2831): clamAV issue

---

releases/dev/app.yml

deploy 1.52.5 to dev
deploy 1.52.5 to dev

chore(as-2831): deploy 1.52.5 to dev

---

packages/forms-web-app/src/validators/appellant-submission/appeal-statement-schema.js

fix(as-2831): fix clam

---

releases/preprod/app.yml

deploy fwa 1.50.0 to pre-prod
https://pins-ds.atlassian.net/browse/AS-2833
deploy fwa 1.50.0 to pre-prod

chore(as-2833): deploy fwa 1.50.0 to pre-prod

---

charts/app/templates/service.yaml
packages/forms-web-app/src/validators/appellant-submission/upload-application-schema.js

fix(as-2831): fix clamav k8s

---

releases/dev/app.yml

chore(as-2831): deploy fwa 1.52.7 to dev

---

charts/app/templates/service.yaml

amend clamav config
amend clamav config

fix(as-2831): amend clamav config

---

charts/app/templates/clamav.yaml

fix(as-2831): k8s clamav

---

charts/app/templates/clamav.yaml

fix clamav deployment
fix clamav deployment

fix(as-2831): fix clamav deployment

---

e2e-tests/cypress/integration/appeal-submission-appeal-site-address/appeal-submission-appeal-site-address.js
e2e-tests/cypress/integration/common/appellant-submission-your-details.js
packages/forms-web-app/src/validators/appellant-submission/site-location.js
packages/forms-web-app/src/validators/appellant-submission/your-details.js
packages/forms-web-app/tests/unit/validators/appellant-submission/site-location.test.js
packages/forms-web-app/tests/unit/validators/appellant-submission/your-details.test.js

fix aa error messages
fix aa error messages

fix(as-2498): fix aa error messages

---

releases/dev/app.yml

chore(as-2498): deploy fwa 1.52.8 to dev

---

releases/dev/app.yml

chore(as-2831): deploy dev fwa 1.52.9

---

releases/preprod/app.yml

https://pins-ds.atlassian.net/browse/AS-2819
deploy fwa 1.51.1 to preprod

chore(as-2819): deploy fwa 1.51.1 to preprod

---

e2e-tests/cypress/integration/common/appellant-submission-your-details.js
packages/forms-web-app/src/validators/appellant-submission/your-details.js
packages/forms-web-app/tests/unit/validators/appellant-submission/your-details.test.js

correct aa error message
correct aa error message

fix(as-2498): correct aa error message

---

releases/dev/app.yml

chore(as-2498): deploy fwa 1.52.10 to dev

---

e2e-tests/cypress/integration/appeal-submission-appeal-site-address/appeal-submission-appeal-site-address.js
packages/forms-web-app/src/validators/appellant-submission/site-location.js
packages/forms-web-app/tests/unit/validators/appellant-submission/site-location.test.js

fix(as-2498): correct error message

---

releases/dev/app.yml

chore(as-2498): deploy fwa 1.52.11 to dev

---

releases/preprod/app.yml

deploy fwa 1.52.11 to pre-prod

chore(as-2498): deploy fwa 1.52.11 to pre-prod

---

releases/prod/app.yml

chore(as-2498): deploy fwa 1.52.11 to prod

---

lpa-submissions-e2e-tests/cypress/integration/common/uploadFiles.js
lpa-submissions-e2e-tests/cypress/support/PageObjects/common-page-objects.js
lpa-submissions-e2e-tests/cypress/support/commands.js
lpa-submissions-e2e-tests/cypress/support/common/validateFileUploadErrorMessage.js

https://pins-ds.atlassian.net/browse/AS-2726
Updated tests for invalid file delete

test: updated tests for invalid file delete

---

packages/forms-web-app/src/validators/appellant-submission/upload-application-schema.js
packages/forms-web-app/src/validators/custom/clamav.js

fix(as-2831): clamav

---

releases/dev/app.yml

chore(as-2831): deploy dev fwa 1.52.12

---

packages/forms-web-app/src/validators/custom/clamav.js

fix(as-2831): clamav server

---

releases/dev/app.yml

fix(as-2831): deploy dev fwa 1.52.13

---

packages/forms-web-app/src/validators/appellant-submission/appeal-statement-schema.js
packages/forms-web-app/src/validators/appellant-submission/supporting-documents-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-decision-schema.js

fix(as-2831): implement clamav

---

releases/dev/app.yml

fix(as-2831): deploy fwa 1.52.14 to dev

---

charts/app/templates/formsWebApp.yaml
charts/app/values.yaml
docker-compose.yml
releases/dev/app.yml

fix(as-2831): clamav docker k8s config

---

charts/app/templates/formsWebApp.yaml

fix(as-2831): fix yaml file

---

charts/app/templates/formsWebApp.yaml
charts/app/values.yaml
docker-compose.yml
releases/dev/app.yml

fix(as-2831): fix deployments

---

charts/app/templates/formsWebApp.yaml
charts/app/values.yaml
packages/forms-web-app/src/validators/appellant-submission/appeal-statement-schema.js
packages/forms-web-app/src/validators/appellant-submission/supporting-documents-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-application-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-decision-schema.js
packages/forms-web-app/src/validators/custom/clamav.js

fix(as-2831): fix dev

---

packages/authentication-service-api/.eslintignore
packages/authentication-service-api/.eslintrc
packages/authentication-service-api/.npmrc
packages/authentication-service-api/.prettierrc
packages/authentication-service-api/Dockerfile
packages/authentication-service-api/README.md
packages/authentication-service-api/jest-mongodb-config.js
packages/authentication-service-api/jest.config.js
packages/authentication-service-api/package-lock.json
packages/authentication-service-api/package.json

fix: add min files to get auth service working

---

releases/preprod/app.yml

Deploy fwa 1.52.14 to pre-prod

chore(as-2831): deploy fwa 1.52.14 to pre-prod

---

packages/forms-web-app/src/validators/appellant-submission/upload-application-schema.js

fix(as-2831): clamav implementation

---

releases/dev/app.yml

chore(as-2831): deploy fwa 1.52.16 to dev

---

packages/forms-web-app/src/validators/appellant-submission/appeal-statement-schema.js
packages/forms-web-app/src/validators/appellant-submission/supporting-documents-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-decision-schema.js

fix(as-2831): update clamav

---

releases/dev/app.yml

chore(as-2831): deploy fwa 1.52.17 to dev

---

releases/dev/app.yml

https://pins-ds.atlassian.net/browse/AS-2836
Deploy fwa 1.53.0 to dev

chore(as-2836): deploy fwa 1.53.0 to dev

---

charts/app/templates/authenticationServiceApi.yaml

https://pins-ds.atlassian.net/browse/AS-3029
Should fix the following K8s event warning:
synchronization of release 'app' in namespace 'app-dev' failed: dry-run upgrade failed: dry-run upgrade for comparison failed: parse error at (app/templates/authenticationServiceApi.yaml:60): unexpected {{end}}

chore(helm): adds missing line to Helm chart

---

releases/preprod/app.yml

chore(lpa-questionnaire-web-app): rollback version [ci skip]

---

packages/forms-web-app/src/validators/appellant-submission/appeal-statement-schema.js
packages/forms-web-app/src/validators/appellant-submission/supporting-documents-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-application-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-decision-schema.js
packages/forms-web-app/src/validators/custom/clamav.js

fix(as-2831): correct clamav error message

---

releases/dev/app.yml

chore(as-2831): deploy fwa 1.53.1 to dev

---

packages/appeals-service-api/Dockerfile

https://pins-ds.atlassian.net/browse/AS-k8s
fix appeal-service-api after k8s upgrade

fix(as-k8s): fix volume mounts

---

releases/preprod/app.yml

https://pins-ds.atlassian.net/browse/AS-k8s
deploy appeal-service-api 1.22.1 to pre-prod

fix(as-k8s): deploy appeal-service-api 1.22.1 to pre-prod

---

packages/appeals-service-api/Dockerfile

https://pins-ds.atlassian.net/browse/AS-k8s-2
fix k8s

fix(as-k8s-2): fix k8s

---

releases/preprod/app.yml

https://pins-ds.atlassian.net/browse/AS-k8s-2
fix k8s

chore(as-k8s-2): fix k8s-2

---

packages/appeals-service-api/Dockerfile

fix(as-2831): fix k8s-3

---

releases/preprod/app.yml

chore(as-2831): fix k8s

---

releases/dev/app.yml

chore(as-2831): deploy k8s-dev

---

packages/appeals-service-api/Dockerfile

fix(as-2831): fix k8s appeal api

---

releases/preprod/app.yml

chore(as-2831): fix k8s appeal api

---

packages/authentication-service-api/Dockerfile

fix k8s - authentication service

fix(as-2831): fix k8s - authentication service

---

packages/authentication-service-api/Dockerfile

fix(as-2831): fix k8s auth

---

releases/dev/app.yml

chore(as-2831): fix k8s-dev

---

infrastructure/environments/variables.tf

fix(as-2831): amend k8s version

---

infrastructure/environments/variables.tf

fix(as-2831): fix k8s version

---

packages/appeals-service-api/Dockerfile

fix(as-2831): fix j8s

---

.github/workflows/infra-environments.yml

fix(as-2831): k8s deployments

---

infrastructure/environments/variables.tf

fix(as-2831): k8s version 1.19

---

charts/app/templates/formsWebApp.yaml

fix(as-2381): fwa-probe-delay

---

charts/app/templates/appealsServiceApi.yaml
charts/app/templates/authenticationServiceApi.yaml
charts/app/templates/lpaQuestionnaireWebApp.yaml
charts/app/templates/pdfServiceApi.yaml
charts/app/templates/queueRetry.yaml

fix(as-2381): fix probe delay

---

charts/app/templates/appealReplyServiceApi.yaml

fix(as-2831): fix reply api probe delay

---

charts/app/templates/documentServiceApi.yaml

fix issue with doc service api probe

fix(as-2371): fix doc service api probe

---

charts/app/templates/gotenberg.yaml

fix(as-2381): fix goternbery pdf probe

---

charts/functions/templates/horizon-ping.yaml
charts/openfaas-amqp1.0-connector/templates/deployment.yaml

fix(as-2381): fix k8s

---

charts/app/templates/appealReplyServiceApi.yaml
charts/app/templates/appealsServiceApi.yaml
charts/app/templates/authenticationServiceApi.yaml
charts/app/templates/documentServiceApi.yaml
charts/app/templates/formsWebApp.yaml
charts/app/templates/gotenberg.yaml
charts/app/templates/lpaQuestionnaireWebApp.yaml
charts/app/templates/pdfServiceApi.yaml
charts/app/templates/queueRetry.yaml
charts/functions/templates/horizon-ping.yaml
charts/openfaas-amqp1.0-connector/templates/deployment.yaml

fix(as-2831): undo probe fix

---

releases/dev/app.yml

deploy appealServiceAPI 1.22.6 to dev

chore(as-2831): deploy appeal api 1.22.6 to dev

---

infrastructure/environments/variables.tf

fix(as-2831): k8s version

---

releases/dev/app.yml

chore(as-2831): k8s dev release

---

charts/app/templates/appealReplyServiceApi.yaml
charts/app/templates/appealsServiceApi.yaml
charts/app/templates/documentServiceApi.yaml
charts/app/templates/formsWebApp.yaml
charts/app/templates/gotenberg.yaml
charts/app/templates/lpaQuestionnaireWebApp.yaml
charts/app/templates/pdfServiceApi.yaml
charts/app/templates/queueRetry.yaml

fix(as-2831): k8x probe

---

charts/app/templates/appealReplyServiceApi.yaml
charts/app/templates/appealsServiceApi.yaml
charts/app/templates/documentServiceApi.yaml
charts/app/templates/formsWebApp.yaml
charts/app/templates/gotenberg.yaml
charts/app/templates/lpaQuestionnaireWebApp.yaml
charts/app/templates/pdfServiceApi.yaml
charts/app/templates/queueRetry.yaml

fix(as-2831): k8s probe config

---

charts/app/templates/appealReplyServiceApi.yaml
charts/app/templates/appealsServiceApi.yaml
charts/app/templates/documentServiceApi.yaml
charts/app/templates/formsWebApp.yaml
charts/app/templates/gotenberg.yaml
charts/app/templates/lpaQuestionnaireWebApp.yaml
charts/app/templates/pdfServiceApi.yaml
charts/app/templates/queueRetry.yaml

fix(as-2831): extend k8s probe

---

.github/workflows/infra-environments.yml

fix(as-2831): remove prod env

---

docker-compose.yml

fix(as-3095): fix issue with rabbitmq

---

.github/actions/kubectl-helm/Dockerfile

fix(as-3095): fix k8s

---

infrastructure/k8s/cert-manager/letsencrypt-clusterissuer.yaml
infrastructure/k8s/cert-manager/test-resource.yaml

fix(as-3095): fix certs

---

releases/preprod/app.yml

chore(as-3095): test deployment

---

releases/preprod/app.yml

chore(as-3095): test release

---

.github/workflows/terraform-validate.yml
releases/preprod/app.yml

fix(as-3095): validate k8s

---

releases/preprod/app.yml

https://pins-ds.atlassian.net/browse/AS-2095
test deployment

chore(as-2095): test deployment

---

releases/preprod/app.yml

fix(as-2831): k8s release

---

infrastructure/k8s/setup.sh

Add if condition before k8s namespace creation.
https://pins-ds.atlassian.net/browse/AS-3085

fix(infrastructure): add if condition before k8s namespace creation

---

infrastructure/k8s/cert-manager/letsencrypt-clusterissuer.yaml
infrastructure/k8s/cert-manager/test-resource.yaml

update kubernetes version for cert manager

fix(infrastructure): update kubernetes version for cert manager

---

releases/dev/app.yml

chore(as-3095): dev deployment

---

.github/workflows/infra-environments.yml

https://pins-ds.atlassian.net/browse/AS-3905
fix k8s

fix(as-3905): k8s fix

---

releases/dev/app.yml

chore(as-3095): fix k8s

---

releases/dev/app.yml

chore(as-3095): latest dev

---

packages/forms-web-app/src/validators/custom/clamav.js

fix(as-2831): clamav deployment

---

packages/forms-web-app/src/validators/custom/clamav.js

fix(as-2831): clamav fix

---

releases/dev/app.yml

fix(as-2831): deploy clamav to dev

---

releases/dev/app.yml

chore(as-2831): dev deployment

---

releases/preprod/app.yml

chore(as-2831): deploy to pre-prod

---

packages/forms-web-app/src/validators/custom/clamav.js

feat(as-2831): clamav

---

releases/dev/app.yml

chore(as-2831): deploy dev

---

releases/dev/app.yml

https://pins-ds.atlassian.net/browse/AS-3098
Deploy test

feat(as-3098): deploy test

---

infrastructure/k8s/setup.sh

fix(as-3101): fix k8s

---

.github/workflows/infra-environments.yml

fix(as-3101): deploy k8s pre-prod

---

infrastructure/k8s/setup.sh

fix(as-3101): fix helm

---

releases/dev/app.yml

fix(as-3101): helm charts

---

releases/preprod/app.yml

fix(as-3101): test deployment

---

releases/preprod/app.yml

chore(as-3101): k8s deployment

---

infrastructure/k8s/setup.sh

fix(as-3101): fix timeouts

---

infrastructure/k8s/setup.sh
releases/dev/app.yml

fix(as-3101): timeout

---

packages/appeal-reply-service-api/Dockerfile
packages/appeals-service-api/Dockerfile
packages/document-service-api/Dockerfile
packages/pdf-service-api/Dockerfile

fix(as-3101): fix volumes

---

packages/forms-web-app/src/lib/client-side/google-tag-manager.js
packages/forms-web-app/src/lib/client-side/javascript-requiring-consent.js
packages/forms-web-app/tests/unit/lib/client-side/google-tag-manager.test.js
packages/forms-web-app/tests/unit/lib/client-side/javascript-requiring-consent.test.js
packages/forms-web-app/webpack.common.js

fix(as-3101): fix cypress and gtm

---

packages/forms-web-app/src/views/appellant-submission/site-access-safety.njk
packages/forms-web-app/src/views/appellant-submission/site-ownership.njk

https://pins-ds.atlassian.net/browse/AS-3242
Add wording (help text) to explain what the appeal site is

feat(as-3242): add wording to explain what the appeal site is

---

packages/lpa-questionnaire-web-app/src/app.js
packages/lpa-questionnaire-web-app/src/lib/views.js
packages/lpa-questionnaire-web-app/src/views/error/unhandled-exception.njk
packages/lpa-questionnaire-web-app/tests/unit/lib/views.test.js

https://pins-ds.atlassian.net/browse/AS-1630
LPA Questionnaire - 500 Error page

feat(lpa questionnaire - unhappy path 500 error page): LPA Questionnaire - 500 Error page

---

lpa-submissions-e2e-tests/cypress/integration/supplementaryUploadedDocument/supplementaryUploadedDocument.steps.js
packages/lpa-questionnaire-web-app/src/controllers/confirm-answers.js
packages/lpa-questionnaire-web-app/src/controllers/supplementary-documents/uploaded-documents.js
packages/lpa-questionnaire-web-app/src/controllers/task-list.js
packages/lpa-questionnaire-web-app/src/middleware/check-if-supplementary-documents.js
packages/lpa-questionnaire-web-app/src/routes/supplementary-documents.js
packages/lpa-questionnaire-web-app/src/views/supplementary-documents/uploaded-documents.njk
packages/lpa-questionnaire-web-app/tests/unit/middleware/check-if-supplementary-documents.test.js
packages/lpa-questionnaire-web-app/tests/unit/routes/supplementaryPlanningRouter.test.js

https://pins-ds.atlassian.net/browse/AS-3174
fix incorrect routing

fix(lpa-questionnaire-web-app): fix incorrect routing

---

packages/pdf-service-api/Dockerfile
packages/pdf-service-api/__tests__/pdf-failure.spec.js
packages/pdf-service-api/__tests__/pdf-success.spec.js
packages/pdf-service-api/azure-pdf-service-api-build.yml
packages/pdf-service-api/jest.config.js
packages/pdf-service-api/package-lock.json
packages/pdf-service-api/package.json

azure pipelines pdf service api

fix(as-3074): azure pipelines pdf service api

---

packages/forms-web-app/src/config.js

https://pins-ds.atlassian.net/browse/AS-1001
test

fix(as-1001): test

---

packages/forms-web-app/src/config.js

https://pins-ds.atlassian.net/browse/AS-1001
test

fix(as-1001): amendment test

---

packages/appeal-reply-service-api/Dockerfile
packages/appeal-reply-service-api/__tests__/notify.spec.js
packages/appeal-reply-service-api/__tests__/reply.spec.js
packages/appeal-reply-service-api/azure-appeal-reply-service-api-build.yml
packages/appeal-reply-service-api/jest.config.js
packages/appeal-reply-service-api/package-lock.json
packages/appeal-reply-service-api/package.json

azure pipeline appeal reply service api

fix(as-3074): azure pipelines reply service api

---

packages/forms-web-app/src/validators/appellant-submission/appeal-statement-schema.js

azure pipelines - disable clamav

fix(as-3074): azure pipelines disable clamav

---

packages/forms-web-app/__tests__/unit/controllers/appellant-submission/site-ownership.test.js
packages/forms-web-app/__tests__/unit/lib/client-side/cookie/cookie-consent.test.js
packages/forms-web-app/__tests__/unit/services/department.service.test.js
packages/forms-web-app/src/middleware/navigation-history.js
packages/forms-web-app/src/routes/index.js
packages/forms-web-app/src/server.js
packages/forms-web-app/src/services/task-status/status-your-details.js
packages/forms-web-app/src/validators/appellant-submission/appeal-statement-schema.js
packages/forms-web-app/src/validators/appellant-submission/site-location.js
packages/forms-web-app/src/validators/appellant-submission/supporting-documents-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-application-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-decision-schema.js

fix(as-3074): correct fwa file and lint issues

---

packages/document-service-api/Dockerfile

fix(as-3074): doc api

---

packages/document-service-api/Dockerfile

https://pins-ds.atlassian.net/browse/AS-3071
doc-storage-api

fix(as-3074): document service api

---

data/data/appeals-service-api/001-appeals.json
e2e-tests/cypress/fixtures/as-102-ac1.json
e2e-tests/cypress/fixtures/expected-appeal-where-an-inspector-does-not-require-site-access.json
e2e-tests/cypress/fixtures/expected-appeal-where-an-inspector-does-require-site-access.json
e2e-tests/cypress/fixtures/expected-appeal-with-certificate-a.json
e2e-tests/cypress/fixtures/expected-appeal-with-many-documents.json
e2e-tests/cypress/fixtures/expected-appeal-without-certificate-a-other-owner-informed.json
e2e-tests/cypress/fixtures/expected-appeal-without-certificate-a-other-owner-not-informed.json
e2e-tests/cypress/fixtures/ucd-831-ac1.json
e2e-tests/cypress/integration/common/standard-appeal.js
lpa-submissions-e2e-tests/cypress/fixtures/as-102-ac1.json
lpa-submissions-e2e-tests/cypress/fixtures/completedAppeal.json
lpa-submissions-e2e-tests/cypress/fixtures/ucd-831-ac1.json

https://pins-ds.atlassian.net/browse/AS-3345
fix cypress tests

fix(as-3345): fix cypress tests

---

packages/lpa-questionnaire-web-app/package-lock.json

https://pins-ds.atlassian.net/browse/AS-3345
fix cypress for lpa

fix(as-3345): fix cypress lpa

---

data/data/appeals-service-api/001-appeals.json

https://pins-ds.atlassian.net/browse/AS-3045
fix cypress issue

fix(as-3045): fix cypress issue

---

packages/lpa-questionnaire-web-app/Dockerfile
packages/lpa-questionnaire-web-app/__tests__/unit/controllers/supplementary-documents/uploaded-documents.test.js
packages/lpa-questionnaire-web-app/__tests__/unit/routes/supplementaryPlanningRouter.test.js
packages/lpa-questionnaire-web-app/azure-lpa-questionnaire-web-app-build.yml

https://pins-ds.atlassian.net/browse/AS-3356
- Fix unit tests which were currently broken in master
- Update `Dockerfile` to add `src` directory and run the unit tests
- Update the pipeline branch triggers
- Re-enable unit tests in the pipeline

fix(as-3356): fix unit tests and re-enable in the pipeline for lpa questionnaire

---

packages/lpa-questionnaire-web-app/Dockerfile
packages/lpa-questionnaire-web-app/azure-lpa-questionnaire-web-app-build.yml

AS-3414
https://pins-ds.atlassian.net/browse/AS-3414
Adding additional folders to docker file so it can actually run when deployed. 

fix(as-3414): fixed docker issue with running container

---

lpa-submissions-e2e-tests/cypress/integration/common/uploadFiles.js
packages/lpa-questionnaire-web-app/__tests__/unit/controllers/supplementary-documents/uploaded-documents.test.js
packages/lpa-questionnaire-web-app/src/controllers/confirm-answers.js
packages/lpa-questionnaire-web-app/src/controllers/supplementary-documents/delete-supplementary-document.js
packages/lpa-questionnaire-web-app/src/controllers/supplementary-documents/uploaded-documents.js
packages/lpa-questionnaire-web-app/src/middleware/check-if-supplementary-documents.js

AS-3380
https://pins-ds.atlassian.net/browse/AS-3380
Fixed minor issues with routing

fix(as-3380): fix supplementary document upload + other stuff

---

packages/lpa-questionnaire-web-app/src/validators/schemas/files.js

https://pins-ds.atlassian.net/browse/AS-3429
Disable clamav temporarily

refactor(as-3429): disable clamav temporarily

---

packages/horizon-functions/horizon-add-document/function.json
packages/horizon-functions/horizon-create-contact/function.json
packages/horizon-functions/horizon-householder-appeal-publish/src/config.js
packages/horizon-functions/horizon-householder-appeal-publish/src/createContacts.js
packages/horizon-functions/horizon-householder-appeal-publish/src/publishDocuments.js

AS-3301
https://pins-ds.atlassian.net/browse/AS-3301
Refactor Azure Functions to use HTTP instead of the AMQP protocol. 

refactor(as-3301): refactor azure functions to use http

---

packages/lpa-questionnaire-web-app/__tests__/unit/services/pdf.service.test.js
packages/lpa-questionnaire-web-app/src/controllers/supplementary-documents/uploaded-documents.js
packages/lpa-questionnaire-web-app/src/middleware/check-if-supplementary-documents.js
packages/lpa-questionnaire-web-app/src/services/pdf.service.js

feat(lpa-questionnaire-web-app): disabled pdf service

---

lpa-submissions-e2e-tests/cypress/integration/accessNeighboursLand.feature
lpa-submissions-e2e-tests/cypress/integration/enterAppealSite.feature
lpa-submissions-e2e-tests/cypress/integration/generateSubmissionPdf.feature
lpa-submissions-e2e-tests/cypress/integration/greenBelt.feature
lpa-submissions-e2e-tests/cypress/integration/nearConservationArea.feature
lpa-submissions-e2e-tests/cypress/integration/originalPlanningApplicationPublicised.feature
lpa-submissions-e2e-tests/cypress/integration/sendEmailConfirmationToNotify.feature
lpa-submissions-e2e-tests/cypress/integration/settingListedBuilding.feature
lpa-submissions-e2e-tests/cypress/integration/siteSeenPublicLand.feature

https://pins-ds.atlassian.net/browse/AS-3435

test: commented PDF Validation and notify tests for lpa questionnaire

---

packages/appeals-service-api/src/services/appeal.service.js
packages/forms-web-app/src/services/pdf.service.js

fix(as-3430): remove pdf submission validation

---

packages/forms-web-app/src/services/pdf.service.js

fix(as-3430): pdf validation

---

packages/appeals-service-api/__tests__/unit/services/appeal.service.test.js

fix(as-3430): pdf statement jest tests

---

packages/appeals-service-api/src/services/appeal.service.js

https://pins-ds.atlassian.net/browse/AS-3454
fix appeals json

fix(as-3453): fix appeals json

---

packages/appeals-service-api/azure-appeals-service-api-build.yml

https://pins-ds.atlassian.net/browse/AS-3453
appeals service

fix(as-3453): appeals service

---

packages/appeals-service-api/azure-appeals-service-api-build.yml
packages/appeals-service-api/src/services/appeal.service.js

https://pins-ds.atlassian.net/browse/AS-3453
Appeals service notify

fix(as-3453): fix notify

---

packages/appeals-service-api/azure-appeals-service-api-build.yml
packages/appeals-service-api/src/services/appeal.service.js

fix(as-3430): appeals service

---

packages/appeals-service-api/src/services/appeal.service.js

fix(as-3430): appeals fix notify

---

packages/appeals-service-api/src/services/appeal.service.js

https://pins-ds.atlassian.net/browse/AS-3458
enable horizon for appeals

fix(as-3458): enable horizon for appeals

---

packages/appeals-service-api/src/services/appeal.service.js

https://pins-ds.atlassian.net/browse/AS-3458
notify appeals api

fix(as-3458): notify appeals

---

packages/appeals-service-api/data/lpa-trialists.json

https://pins-ds.atlassian.net/browse/AS-3301
fix lpa list

fix(as-3301): fix lpa list

---

lpa-submissions-e2e-tests/cypress/plugins/index.js
lpa-submissions-e2e-tests/cypress/support/common/goToPage.js
lpa-submissions-e2e-tests/cypress/support/index.js
lpa-submissions-e2e-tests/package-lock.json
lpa-submissions-e2e-tests/package.json
packages/lpa-questionnaire-web-app/src/views/accuracy-submission.njk
packages/lpa-questionnaire-web-app/src/views/components/task-list/template.njk
packages/lpa-questionnaire-web-app/src/views/confirm-answers.njk
packages/lpa-questionnaire-web-app/src/views/development-plan.njk
packages/lpa-questionnaire-web-app/src/views/extra-conditions.njk
packages/lpa-questionnaire-web-app/src/views/health-safety.njk
packages/lpa-questionnaire-web-app/src/views/includes/head.njk
packages/lpa-questionnaire-web-app/src/views/layouts/main.njk
packages/lpa-questionnaire-web-app/src/views/layouts/multi-file-upload.njk
packages/lpa-questionnaire-web-app/src/views/layouts/question.njk
packages/lpa-questionnaire-web-app/src/views/other-appeals.njk
packages/lpa-questionnaire-web-app/src/views/supplementary-documents/delete-document.njk
packages/lpa-questionnaire-web-app/src/views/supplementary-documents/uploaded-documents.njk

https://pins-ds.atlassian.net/browse/AS-2979
Fixed all the HTML validation errors

feat(as-2979): update files to address HTML validation issue

---

packages/lpa-questionnaire-web-app/__tests__/unit/controllers/contact-us.test.js
packages/lpa-questionnaire-web-app/__tests__/unit/controllers/supplementary-documents/uploaded-documents.test.js
packages/lpa-questionnaire-web-app/__tests__/unit/lib/views.test.js
packages/lpa-questionnaire-web-app/__tests__/unit/routes/contact-us.test.js
packages/lpa-questionnaire-web-app/__tests__/unit/routes/index.test.js
packages/lpa-questionnaire-web-app/__tests__/unit/routes/supplementaryPlanningRouter.test.js
packages/lpa-questionnaire-web-app/src/controllers/contact-us.js
packages/lpa-questionnaire-web-app/src/lib/views.js
packages/lpa-questionnaire-web-app/src/routes/contact-us.js
packages/lpa-questionnaire-web-app/src/routes/index.js
packages/lpa-questionnaire-web-app/src/views/contact-us.njk
packages/lpa-questionnaire-web-app/src/views/error/not-found.njk

AS-3123
https://pins-ds.atlassian.net/browse/AS-3123
This ticket is primarily intended to provide a contact us page whenever a user encounters a 404

feat(as-3123): create contact us page

---

packages/lpa-questionnaire-web-app/src/controllers/health-safety.js

AS-3410
https://pins-ds.atlassian.net/browse/AS-3410
Fix routing for the health safety question

fix(as-3410): fix health safety routing

---

packages/lpa-questionnaire-web-app/src/controllers/health-safety.js
packages/lpa-questionnaire-web-app/src/controllers/other-appeals.js
packages/lpa-questionnaire-web-app/src/controllers/upload-question.js

https://pins-ds.atlassian.net/browse/AS-3410
AS-3410

Additional Fixes for Routing

---

packages/lpa-questionnaire-web-app/__tests__/unit/controllers/authentication.test.js
packages/lpa-questionnaire-web-app/__tests__/unit/middleware/authenticate.test.js
packages/lpa-questionnaire-web-app/__tests__/unit/routes/auth/authentication.test.js
packages/lpa-questionnaire-web-app/src/controllers/authentication.js
packages/lpa-questionnaire-web-app/src/middleware/authenticate.js
packages/lpa-questionnaire-web-app/src/routes/auth/authentication.js
packages/lpa-questionnaire-web-app/src/validators/email.js
packages/lpa-questionnaire-web-app/src/views/authentication/your-email.njk
packages/magiclink-auth-service-api/lib/getYamlAsJson.js
packages/magiclink-auth-service-api/src/config.js
packages/magiclink-auth-service-api/src/controllers/magiclink.js
packages/magiclink-auth-service-api/src/middleware/authenticate.js
packages/magiclink-auth-service-api/src/routes/api-docs.js
packages/magiclink-auth-service-api/tests/resources/magicLinkData.json
packages/magiclink-auth-service-api/tests/unit/lib/getYamlAsJson.test.js
packages/magiclink-auth-service-api/tests/unit/middleware/authenticate.test.js
packages/magiclink-auth-service-api/tests/unit/routes/api-docs.test.js

https://pins-ds.atlassian.net/browse/AS-3487
Validate 'Your Email page' for user input, refactor the code to make the code unit testable, add unit
tests. These changes are on top of yet to be reviewed Magic link code. New PR that will be raised as part of AS-58 - feature level branch requires greater scrutiny.
E2E tests may fail as the code has breaking changes. These will be addressed as part of AS-3488

feat(as-3487): changes to make Magic Link code PR ready

---

packages/horizon-functions/horizon-householder-appeal-publish/handler-reply.js

Removing additional change for horizon function whilst trying to find root cause of error. 

fix(horizon): remove extra document type

---

packages/appeal-reply-service-api/src/controllers/reply.js
packages/appeal-reply-service-api/src/lib/config.js
packages/appeal-reply-service-api/src/lib/sql-lpa-queue.js
packages/appeals-service-api/src/lib/config.js
packages/appeals-service-api/src/lib/sql-appeals-queue.js
packages/appeals-service-api/src/services/appeal.service.js

https://pins-ds.atlassian.net/browse/AS-3018
sql message queue

feat(as-3018): sql message queue

---

packages/appeals-service-api/src/lib/sql-appeals-queue.js
packages/appeals-service-api/src/services/appeal.service.js

https://pins-ds.atlassian.net/browse/AS-3018
sql queue 

fix(as-3018): sql-queue

---

packages/horizon-functions/sql-householder-appeal-publish/index.js

https://pins-ds.atlassian.net/browse/AS-3573
appeals azure fn

fix(as-3573): appeals azure fn

---

packages/appeal-reply-service-api/src/controllers/reply.js
packages/appeals-service-api/src/services/appeal.service.js

https://pins-ds.atlassian.net/browse/AS-3573
fix order of azure functions

fix(as-3573): fix order of azure fns

---

packages/document-service-api/src/lib/migrateMetadata.js
packages/document-service-api/src/lib/migrateMetadata.test.js

https://pins-ds.atlassian.net/browse/AS-3317
cosmodb to blobstorage migration response covers failed item info

feat(cosmodb to blobstorage): migration response covers failed item info

---

azure-pipelines-publish-cypress.yml

https://pins-ds.atlassian.net/browse/AS-3573
cypress pipelines

fix(as-3573): cypress e2e tests azure pipelines

---

Makefile
docker-compose.yml
e2e-tests/cypress/integration/your-planning-appeal-landing-page/your-planning-appeal-landing-page.js
e2e-tests/package-lock.json
e2e-tests/package.json

https://pins-ds.atlassian.net/browse/AS-3835
fix cypress issues

fix(as-3835): fix cypress issues

---

packages/lpa-questionnaire-web-app/package-lock.json

https://pins-ds.atlassian.net/browse/AS-3835
fix lpa cypress

fix(as-3835): fix lpa cypress

---

lpa-submissions-e2e-tests/cypress/integration/common/uploadFiles.js
lpa-submissions-e2e-tests/cypress/integration/conservationAreaMap.feature
lpa-submissions-e2e-tests/cypress/integration/interestedPartiesApplication.feature
lpa-submissions-e2e-tests/cypress/integration/notifyingInterestedParties.feature
lpa-submissions-e2e-tests/cypress/integration/otherRelevantPolicies.feature
lpa-submissions-e2e-tests/cypress/integration/planningHistory.feature
lpa-submissions-e2e-tests/cypress/integration/planningOfficersReport.feature
lpa-submissions-e2e-tests/cypress/integration/representationsInterestedParties.feature
lpa-submissions-e2e-tests/cypress/integration/sendEmailConfirmationToNotify.feature
lpa-submissions-e2e-tests/cypress/integration/siteNotices.feature
lpa-submissions-e2e-tests/cypress/integration/statutoryDevelopmentPlanPolicy.feature
lpa-submissions-e2e-tests/cypress/integration/uploadThePlansToReachDecision.feature

https://pins-ds.atlassian.net/browse/AS-3778

test: updated the tests for upload document

---

packages/forms-web-app/src/validators/appellant-submission/appeal-statement-schema.js
packages/forms-web-app/src/validators/appellant-submission/supporting-documents-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-application-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-decision-schema.js
packages/lpa-questionnaire-web-app/src/validators/schemas/files.js

https://pins-ds.atlassian.net/browse/AS-3650

refactor(clamav): reenable support for clamav

---

packages/forms-web-app/__tests__/unit/controllers/before-you-start/local-planning-department.test.js
packages/forms-web-app/__tests__/unit/lib/views.test.js
packages/forms-web-app/__tests__/unit/routes/before-you-start/index.test.js
packages/forms-web-app/__tests__/unit/routes/before-you-start/local-planning-department.test.js
packages/forms-web-app/__tests__/unit/routes/index.test.js
packages/forms-web-app/__tests__/unit/validators/before-you-start/local-planning-department.test.js
packages/forms-web-app/src/controllers/before-you-start/local-planning-department.js
packages/forms-web-app/src/lib/views.js
packages/forms-web-app/src/routes/before-you-start/index.js
packages/forms-web-app/src/routes/before-you-start/local-planning-department.js
packages/forms-web-app/src/routes/index.js
packages/forms-web-app/src/validators/before-you-start/local-planning-department.js
packages/forms-web-app/src/views/before-you-start/local-planning-department.njk
packages/forms-web-app/src/views/layouts/main-no-back-link.njk

https://pins-ds.atlassian.net/browse/AS-3782
added full-planning local-planning-department page

feat(forms-web-app): added full-planning local-planning-department page

---

packages/forms-web-app/src/validators/appellant-submission/appeal-statement-schema.js
packages/forms-web-app/src/validators/appellant-submission/supporting-documents-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-application-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-decision-schema.js
packages/lpa-questionnaire-web-app/src/validators/schemas/files.js

Hotfix to remove integration with ClamAV

revert(clamav): revert clamav commit

---

packages/magiclink-auth-service-api/Dockerfile

https://pins-ds.atlassian.net/browse/AS-3867

Update Dockerfile for Magic Link

---

lpa-submissions-e2e-tests/cypress/support/magic-link/getMagicLink.js
packages/lpa-questionnaire-web-app/__tests__/unit/middleware/authenticate.test.js
packages/lpa-questionnaire-web-app/src/controllers/authentication.js
packages/lpa-questionnaire-web-app/src/middleware/authenticate.js
packages/magiclink-auth-service-api/__tests__/unit/interactors/sendMagicLinkEmail.test.js
packages/magiclink-auth-service-api/__tests__/unit/middleware/authenticate.test.js
packages/magiclink-auth-service-api/src/controllers/magiclink.js
packages/magiclink-auth-service-api/src/interactors/sendMagicLinkEmail.js
packages/magiclink-auth-service-api/src/middleware/authenticate.js

https://pins-ds.atlassian.net/browse/AS-4012
Following information needed to be passed to Notify services to send email to LPA with the Magic Link

fix(as-4012): send required info for Magic link email to Notify services

---

packages/magiclink-auth-service-api/Dockerfile
packages/magiclink-auth-service-api/azure-magic-link-web-app-build.yml
packages/magiclink-auth-service-api/package-lock.json
packages/magiclink-auth-service-api/package.json

Fixed build pipeline for magiclink pipeline

feat(magiclink): fix magiclink pipeline

---

e2e-tests/cypress/integration/before-you-start-appellant-selects-the-site.feature
e2e-tests/cypress/integration/before-you-start-appellant-selects-the-site/before-you-start-appellant-selects-the-site-steps.js
e2e-tests/cypress/integration/before-you-start-local-planning-department/before-you-start-local-planning-department-steps.js
e2e-tests/cypress/support/before-you-start-appellant-selects-the-site/deselect-site-option.js
e2e-tests/cypress/support/before-you-start-appellant-selects-the-site/select-site-option.js
e2e-tests/cypress/support/before-you-start-appellant-selects-the-site/verify-deselect-site-option.js
e2e-tests/cypress/support/page-objects/appellant-selects-the-site-po.js
e2e-tests/cypress/support/page-objects/common-po.js

https://pins-ds.atlassian.net/browse/AS-3878

test: added tests for appellant selects the site

---

packages/common/src/document-types.js

https://pins-ds.atlassian.net/browse/AS-3685
Update the document types in the common package with display names as these are used in the Back Office when adding documents to an appeal

feat(as-3685): update document types in common package

---

packages/forms-web-app/__tests__/unit/controllers/before-you-start/use-a-different-service.test.js
packages/forms-web-app/__tests__/unit/lib/views.test.js
packages/forms-web-app/__tests__/unit/routes/before-you-start/index.test.js
packages/forms-web-app/__tests__/unit/routes/before-you-start/use-a-different-service.test.js
packages/forms-web-app/src/controllers/before-you-start/use-a-different-service.js
packages/forms-web-app/src/lib/views.js
packages/forms-web-app/src/routes/before-you-start/index.js
packages/forms-web-app/src/routes/before-you-start/use-a-different-service.js
packages/forms-web-app/src/views/before-you-start/use-a-different-service.njk

https://pins-ds.atlassian.net/browse/AS-4058
create use a different service page

feat(before-you-start): create use a different service page

---

.github/workflows/e2e-tests-on-PR.yml

upgrade of build agent versions

ci(github-actions): github actions - build agent workflow

---

e2e-tests/cypress/integration/before-you-start-shutter-page.feature
e2e-tests/cypress/integration/before-you-start-shutter-page/before-you-start-shutter-page-steps.js
e2e-tests/cypress/support/page-objects/shutter-page-po.js

https://pins-ds.atlassian.net/browse/AS-4059

test: added tests for shutter page

---

packages/forms-web-app/__tests__/unit/controllers/before-you-start/any-of-following.spec.js
packages/forms-web-app/__tests__/unit/lib/views.test.js
packages/forms-web-app/__tests__/unit/routes/before-you-start/index.test.js
packages/forms-web-app/__tests__/unit/routes/index.test.js
packages/forms-web-app/__tests__/unit/validators/before-you-start/any-of-following.test.js
packages/forms-web-app/src/controllers/before-you-start/any-of-following.js
packages/forms-web-app/src/lib/views.js
packages/forms-web-app/src/routes/before-you-start/any-of-following.js
packages/forms-web-app/src/routes/before-you-start/index.js
packages/forms-web-app/src/validators/before-you-start/any-of-following.js
packages/forms-web-app/src/views/before-you-start/any-of-following.njk

https://pins-ds.atlassian.net/browse/AS-3842
Adding any of following page 
Previous PR: https://github.com/Planning-Inspectorate/appeal-planning-decision/pull/1900

feat(as-3842): add any of following page

---

README.md

https://pins-ds.atlassian.net/browse/AS-4047
Documentation

fix(as-4047): documentation

---

packages/appeals-service-api/src/models/appeal.js
packages/forms-web-app/.npmrc
packages/forms-web-app/__tests__/unit/controllers/full-planning/full-appeal/task-list.test.js
packages/forms-web-app/__tests__/unit/lib/full-planning/views.test.js
packages/forms-web-app/__tests__/unit/routes/full-planning/full-appeal/index.test.js
packages/forms-web-app/__tests__/unit/routes/full-planning/full-appeal/task-list.test.js
packages/forms-web-app/__tests__/unit/routes/index.test.js
packages/forms-web-app/__tests__/unit/services/task.service.test.js
packages/forms-web-app/src/controllers/full-planning/full-appeal/task-list.js
packages/forms-web-app/src/lib/full-planning/views.js
packages/forms-web-app/src/routes/full-planning/full-appeal/index.js
packages/forms-web-app/src/routes/full-planning/full-appeal/task-list.js
packages/forms-web-app/src/routes/index.js
packages/forms-web-app/src/services/task.service.js
packages/forms-web-app/src/views/full-planning/full-appeal/task-list.njk

https://pins-ds.atlassian.net/browse/AS-4027
/full-appeal/task-list page implementation for full-planning app

feat(full appeal): task list page implemented for full-planning app

---

packages/forms-web-app/__tests__/unit/controllers/full-planning/full-appeal/check-answers.test.js
packages/forms-web-app/__tests__/unit/controllers/full-planning/full-appeal/task-list.test.js
packages/forms-web-app/__tests__/unit/lib/full-planning/views.test.js
packages/forms-web-app/__tests__/unit/routes/full-planning/check-answers.test.js
packages/forms-web-app/src/controllers/full-planning/full-appeal/check-answers.js
packages/forms-web-app/src/lib/full-planning/views.js
packages/forms-web-app/src/routes/full-planning/full-appeal/check-answers.js
packages/forms-web-app/src/routes/full-planning/full-appeal/index.js
packages/forms-web-app/src/services/task.service.js
packages/forms-web-app/src/views/full-planning/full-appeal/check-answers.njk
packages/forms-web-app/src/views/macros/contact-details.njk

https://pins-ds.atlassian.net/browse/AS-3614
/full-appeal/check-answers page implemented for Full Planning

feat(full appeal): check your answers page implementation

---

packages/forms-web-app/__tests__/unit/controllers/full-planning/granted-or-refused.test.js
packages/forms-web-app/__tests__/unit/lib/views.test.js
packages/forms-web-app/__tests__/unit/routes/full-planning/granted-or-refused.test.js
packages/forms-web-app/__tests__/unit/routes/full-planning/index.test.js
packages/forms-web-app/__tests__/unit/validators/full-planning/granted-or-refused.test.js
packages/forms-web-app/src/constants.js
packages/forms-web-app/src/controllers/full-planning/granted-or-refused.js
packages/forms-web-app/src/lib/views.js
packages/forms-web-app/src/routes/full-planning/granted-or-refused.js
packages/forms-web-app/src/routes/full-planning/index.js
packages/forms-web-app/src/validators/full-planning/granted-or-refused.js
packages/forms-web-app/src/views/full-planning/granted-or-refused.njk

https://pins-ds.atlassian.net/browse/AS-4161
full Planning Dev & Unit test for Granted or Refused screen

feat(as-4161): full Planning Dev & Unit test for Granted or Refused screen

---

packages/forms-web-app/src/views/full-planning/full-appeal/task-list.njk

https://pins-ds.atlassian.net/browse/AS-4194
fixed sections to tasks

fix(full appeal): changed sections to tasks

---

packages/forms-web-app/src/services/task.service.js

https://pins-ds.atlassian.net/browse/AS-4037
fix check your answers

fix(as-4037): fix check your answers

---

packages/e2e-tests/cypress/integration/full-planning/before-you-start/appellant-selects-the-site.feature
packages/e2e-tests/cypress/integration/full-planning/before-you-start/appellant-selects-the-site/appellant-selects-the-site-steps.js
packages/e2e-tests/cypress/integration/full-planning/before-you-start/granted-or-refused-application/granted-or-refused-application-steps.js
packages/forms-web-app/__tests__/unit/controllers/full-planning/any-of-following.spec.js
packages/forms-web-app/__tests__/unit/controllers/full-planning/granted-or-refused.test.js
packages/forms-web-app/src/controllers/full-planning/any-of-following.js
packages/forms-web-app/src/controllers/full-planning/granted-or-refused.js

https://pins-ds.atlassian.net/browse/AS-4236
link full-planning eligibility journey up to granted-or-refused

feat(as-4236): link full-planning eligibility journey upto graded-or-refused

---

docker-compose.yml
packages/forms-web-app/package-lock.json
packages/forms-web-app/package.json
packages/forms-web-app/src/validators/appellant-submission/appeal-statement-schema.js
packages/forms-web-app/src/validators/appellant-submission/supporting-documents-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-application-schema.js
packages/forms-web-app/src/validators/appellant-submission/upload-decision-schema.js

https://pins-ds.atlassian.net/browse/AS-4120
reenable support for clamav in forms web app

feat(as-4120): reenable support for clamav

---

packages/e2e-tests/cypress/cucumber-json/shutter-page-deadline-passed.cucumber.json
packages/e2e-tests/cypress/integration/full-planning/before-you-start/shutter-page-deadline-passed.feature
packages/e2e-tests/cypress/integration/full-planning/before-you-start/shutter-page-deadline-passed/shutter-page-deadline-passed-steps.js
packages/forms-web-app/__tests__/unit/controllers/full-planning/any-of-following.spec.js
packages/forms-web-app/__tests__/unit/controllers/full-planning/out-of-time-shutter-page.spec.js
packages/forms-web-app/__tests__/unit/lib/views.test.js
packages/forms-web-app/__tests__/unit/routes/full-planning/index.test.js
packages/forms-web-app/__tests__/unit/routes/full-planning/out-of-time-shutter-page.spec.js
packages/forms-web-app/src/controllers/full-planning/out-of-time-shutter-page.js
packages/forms-web-app/src/lib/views.js
packages/forms-web-app/src/routes/full-planning/index.js
packages/forms-web-app/src/routes/full-planning/out-of-time.js
packages/forms-web-app/src/views/full-planning/out-of-time-shutter-page.njk

https://pins-ds.atlassian.net/browse/AS-3736

feat(as-4190): add out of time shutter page

---

packages/appeals-service-api/.npmrc
packages/appeals-service-api/src/models/appeal.js
packages/business-rules/src/schemas/full-planning/insert.js
packages/business-rules/src/schemas/full-planning/insert.test.js
packages/business-rules/src/schemas/full-planning/update.js
packages/business-rules/src/schemas/full-planning/update.test.js
packages/business-rules/test/data/full-planning.js
packages/forms-web-app/__tests__/unit/controllers/full-planning/full-appeal/contact-details.test.js
packages/forms-web-app/__tests__/unit/controllers/full-planning/full-appeal/task-list.test.js
packages/forms-web-app/__tests__/unit/lib/full-planning/views.test.js
packages/forms-web-app/__tests__/unit/routes/full-planning/contact-details.test.js
packages/forms-web-app/__tests__/unit/validators/full-planning/contact-details.test.js
packages/forms-web-app/src/controllers/full-planning/full-appeal/contact-details.js
packages/forms-web-app/src/lib/empty-appeal.js
packages/forms-web-app/src/lib/full-planning/views.js
packages/forms-web-app/src/routes/full-planning/full-appeal/contact-details.js
packages/forms-web-app/src/routes/full-planning/full-appeal/index.js
packages/forms-web-app/src/services/task.service.js
packages/forms-web-app/src/validators/full-planning/contact-details.js
packages/forms-web-app/src/views/full-planning/full-appeal/contact-details.njk

https://pins-ds.atlassian.net/browse/AS-3888
contact details page for Full Planning app

feat(full planning): contact details page implementation

---

docker-compose.yml
e2e-tests/cypress/support/common/verify-error-message.js
e2e-tests/cypress/support/go-to-page/goToPage.js
packages/e2e-tests/cypress/integration/full-planning/eligibility/enforcement-notice.feature
packages/e2e-tests/cypress/integration/full-planning/eligibility/enforcement-notice/enforcement-notice-steps.js
packages/e2e-tests/cypress/support/common/go-to-page/goToPage.js
packages/e2e-tests/cypress/support/full-planning/eligibility/page-objects/enforcement-notice-po.js
packages/forms-web-app/__tests__/unit/controllers/full-planning/enforcement-notice.test.js
packages/forms-web-app/__tests__/unit/lib/views.test.js
packages/forms-web-app/__tests__/unit/routes/full-planning/enforcement-notice.test.js
packages/forms-web-app/__tests__/unit/routes/full-planning/index.test.js
packages/forms-web-app/__tests__/unit/validators/full-planning/enforcement-notice.test.js
packages/forms-web-app/src/controllers/full-planning/enforcement-notice.js
packages/forms-web-app/src/lib/empty-appeal.js
packages/forms-web-app/src/lib/views.js
packages/forms-web-app/src/routes/full-planning/enforcement-notice.js
packages/forms-web-app/src/routes/full-planning/index.js
packages/forms-web-app/src/validators/full-planning/enforcement-notice.js
packages/forms-web-app/src/views/full-planning/enforcement-notice.njk

https://pins-ds.atlassian.net/browse/AS-3732
Development of Enforcement Notice page and its E2E tests

feat(as-3732): enforcement notice dev and e2e

---

packages/forms-web-app/__tests__/unit/controllers/householder-planning/decision-date-householder.test.js
packages/forms-web-app/__tests__/unit/lib/views.test.js
packages/forms-web-app/__tests__/unit/routes/householder-planning/decision-date-householder.test.js
packages/forms-web-app/__tests__/unit/routes/householder-planning/index.test.js
packages/forms-web-app/__tests__/unit/routes/index.test.js
packages/forms-web-app/__tests__/unit/validators/householder-planning/decision-date-householder.test.js
packages/forms-web-app/src/controllers/householder-planning/decision-date-householder.js
packages/forms-web-app/src/lib/views.js
packages/forms-web-app/src/routes/householder-planning/decision-date-householder.js
packages/forms-web-app/src/routes/householder-planning/index.js
packages/forms-web-app/src/routes/index.js
packages/forms-web-app/src/validators/householder-planning/decision-date-householder.js
packages/forms-web-app/src/views/householder-planning/decision-date-householder.njk

https://pins-ds.atlassian.net/browse/AS-4276
add enter letter date lpd page

feat(householder-planning): add enter letter date lpd page

---

azure-pipelines-publish-cypress.yml
package.json

https://pins-ds.atlassian.net/browse/AS-4061
fix cypress pipeline

fix(as-4061): fix cypress pipeline

---

packages/e2e-tests/cypress/integration/full-appeal/eligibility/appellant-selects-the-site/appellant-selects-the-site-steps.js
packages/forms-web-app/src/views/full-appeal/any-of-following.njk

https://pins-ds.atlassian.net/browse/AS-4144
Simple content change to reflect changes from v9 to v11

feat(as-4144): implement content change

---

packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/application-number.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/application-number.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js
packages/forms-web-app/__tests__/unit/validators/full-appeal/application-number.test.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/application-number.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/task-list.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/application-number.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js
packages/forms-web-app/src/services/task.service.js
packages/forms-web-app/src/validators/full-appeal/application-number.js
packages/forms-web-app/src/views/full-appeal/submit-appeal/application-number.njk

https://pins-ds.atlassian.net/browse/AS-4179
/submit-appeal/application-number page implemented

feat(full appeal): /submit-appeal/application-number page implemented

---

packages/forms-web-app/__tests__/unit/controllers/householder-planning/date-decision-due-householder.test.js
packages/forms-web-app/__tests__/unit/lib/views.test.js
packages/forms-web-app/__tests__/unit/routes/householder-planning/date-decision-due-householder.test.js
packages/forms-web-app/__tests__/unit/routes/index.test.js
packages/forms-web-app/__tests__/unit/validators/householder-planning/date-decision-due-householder.test.js
packages/forms-web-app/src/controllers/householder-planning/date-decision-due-householder.js
packages/forms-web-app/src/lib/views.js
packages/forms-web-app/src/routes/householder-planning/date-decision-due-householder.js
packages/forms-web-app/src/routes/householder-planning/index.js
packages/forms-web-app/src/routes/index.js
packages/forms-web-app/src/validators/householder-planning/date-decision-due-householder.js
packages/forms-web-app/src/views/householder-planning/date-decision-due-householder.njk

https://pins-ds.atlassian.net/browse/AS-4303
add date-decision-due-householder screen

feat(householder-planning): add date-decision-due-householder screen

---

packages/business-rules/src/schemas/full-appeal/insert.js
packages/business-rules/src/schemas/full-appeal/insert.test.js
packages/business-rules/src/schemas/full-appeal/update.js
packages/business-rules/src/schemas/full-appeal/update.test.js
packages/business-rules/test/data/full-appeal.js
packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/appeal-site-address.test.js
packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/task-list.test.js
packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/appeal-site-address.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js
packages/forms-web-app/__tests__/unit/validators/full-appeal/appeal-site-address.test.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/appeal-site-address.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/task-list.js
packages/forms-web-app/src/lib/full-appeal/views.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/appeal-site-address.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js
packages/forms-web-app/src/services/task.service.js
packages/forms-web-app/src/validators/full-appeal/appeal-site-address.js
packages/forms-web-app/src/views/full-appeal/submit-appeal/appeal-site-address.njk

https://pins-ds.atlassian.net/browse/AS-3856
/full-appeal/submit-appeal/appeal-site-address implementation

feat(full appeal): /full-appeal/submit-appeal/appeal-site-address implementation

---

packages/e2e-tests/cypress/integration/eligibility/full-appeal/date-decision-due/date-decision-due-steps.js
packages/e2e-tests/cypress/integration/eligibility/full-appeal/lpd-letter-decision-date.feature
packages/e2e-tests/cypress/integration/eligibility/full-appeal/lpd-letter-decision-date/lpd-letter-decision-date-steps.js
packages/e2e-tests/cypress/support/common/clickContinueButton.js
packages/e2e-tests/cypress/support/eligibility/date-decision-due/enter-date-decision-due.js
packages/e2e-tests/cypress/support/eligibility/date-decision-received/enter-date-decision-received.js
packages/e2e-tests/cypress/support/eligibility/page-objects/date-decision-received-po.js
packages/forms-web-app/src/views/eligibility/decision-date.njk
packages/forms-web-app/src/views/full-appeal/decision-date.njk

https://pins-ds.atlassian.net/browse/AS-4178

test: added E2E tests for decision date

---

packages/e2e-tests/cypress/integration/eligibility/householder-planning/claiming-costs.feature
packages/e2e-tests/cypress/integration/eligibility/householder-planning/claiming-costs/claiming-costs-steps.js
packages/e2e-tests/cypress/support/eligibility/page-objects/claiming-costs-po.js

https://pins-ds.atlassian.net/browse/AS-4295

test: added E2E tests for claiming costs

---

packages/appeals-service-api/__tests__/unit/value-appeal.js
packages/appeals-service-api/src/models/appeal.js
packages/business-rules/src/schemas/full-appeal/insert.js
packages/business-rules/src/schemas/full-appeal/insert.test.js
packages/business-rules/src/schemas/full-appeal/update.js
packages/business-rules/src/schemas/full-appeal/update.test.js
packages/business-rules/test/data/full-appeal.js
packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/applicant-name.test.js
packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/applicant-name.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js
packages/forms-web-app/__tests__/unit/validators/full-appeal/applicant-name.test.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/applicant-name.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/task-list.js
packages/forms-web-app/src/lib/full-appeal/views.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/applicant-name.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js
packages/forms-web-app/src/services/task.service.js
packages/forms-web-app/src/validators/full-appeal/applicant-name.js
packages/forms-web-app/src/views/full-appeal/submit-appeal/applicant-name.njk

https://pins-ds.atlassian.net/browse/AS-4050
/full-appeal/submit-appeal/applicant-name implementation

feat(full appeal): /full-appeal/submit-appeal/applicant-name implementation

---

packages/e2e-tests/cypress/integration/eligibility/full-appeal/appellant-selects-the-site/appellant-selects-the-site-steps.js
packages/forms-web-app/src/views/full-appeal/any-of-following.njk

https://pins-ds.atlassian.net/browse/AS-4310
Content change for page title

feature: content change for page title

---

packages/e2e-tests/cypress/integration/eligibility/full-appeal/enforcement-notice.feature
packages/e2e-tests/cypress/integration/eligibility/householder-planning/enforcement-notice.feature
packages/e2e-tests/cypress/integration/eligibility/householder-planning/enforcement-notice/enforcement-notice-steps.js
packages/e2e-tests/cypress/integration/eligibility/householder-planning/listed-building.feature
packages/e2e-tests/cypress/integration/eligibility/householder-planning/listed-building/listed-building-steps.js
packages/e2e-tests/cypress/support/common/go-to-page/goToAppealsPage.js
packages/forms-web-app/__tests__/unit/controllers/householder-planning/eligibility/enforcement-notice-householder.test.js
packages/forms-web-app/__tests__/unit/controllers/householder-planning/eligibility/listed-building-householder.test.js
packages/forms-web-app/__tests__/unit/lib/householder-planning/views.test.js
packages/forms-web-app/__tests__/unit/routes/householder-planning/eligibility/enforcement-notice-householder.test.js
packages/forms-web-app/__tests__/unit/routes/householder-planning/eligibility/index.test.js
packages/forms-web-app/__tests__/unit/routes/householder-planning/index.test.js
packages/forms-web-app/__tests__/unit/routes/index.test.js
packages/forms-web-app/__tests__/unit/validators/householder-planning/eligibility/enforcement-notice-householder.test.js
packages/forms-web-app/src/controllers/householder-planning/eligibility/enforcement-notice-householder.js
packages/forms-web-app/src/controllers/householder-planning/eligibility/listed-building-householder.js
packages/forms-web-app/src/lib/householder-planning/views.js
packages/forms-web-app/src/routes/householder-planning/eligibility/enforcement-notice-householder.js
packages/forms-web-app/src/routes/householder-planning/eligibility/index.js
packages/forms-web-app/src/routes/householder-planning/index.js
packages/forms-web-app/src/routes/index.js
packages/forms-web-app/src/validators/householder-planning/eligibility/enforcement-notice-householder.js
packages/forms-web-app/src/views/householder-planning/eligibility/enforcement-notice-householder.njk

https://pins-ds.atlassian.net/browse/AS-3638
Dev, unit tests and E2E test changes for householder enforcement page. 

feat(as-3638): Householder Enforcement Notice page

---

packages/e2e-tests/cypress/integration/full-appeal/appeals-service/planning-application-number/planning-application-number.js
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/upload-planning-application-form.feature
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/upload-planning-application-form/upload-planning-application-form.js
packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/file-upload-po.js
packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/task-list-page-po.js

https://pins-ds.atlassian.net/browse/AS-4336
Add cypress tests

feat: add cypress tests for upload planning application form

---

packages/e2e-tests/cypress/integration/eligibility/full-appeal/planning-application-type/planning-application-type-steps.js
packages/forms-web-app/__tests__/unit/controllers/full-appeal/type-of-planning-application.test.js
packages/forms-web-app/src/controllers/full-appeal/type-of-planning-application.js

https://pins-ds.atlassian.net/browse/AS-3652
Navigate to limited-building-householder page when householder application type is chosen

feat(as-3652): Navigate to limited-building-householder page when householder application type is chosen

---

packages/business-rules/src/schemas/full-appeal/insert.js
packages/business-rules/src/schemas/full-appeal/insert.test.js
packages/business-rules/src/schemas/full-appeal/update.js
packages/business-rules/src/schemas/full-appeal/update.test.js
packages/business-rules/test/data/full-appeal.js
packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/original-applicant.test.js
packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/task-list.test.js
packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/original-applicant.test.js
packages/forms-web-app/__tests__/unit/validators/full-appeal/original-applicant.test.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/applicant-name.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/original-applicant.js
packages/forms-web-app/src/lib/full-appeal/views.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/original-applicant.js
packages/forms-web-app/src/services/task.service.js
packages/forms-web-app/src/validators/full-appeal/original-applicant.js
packages/forms-web-app/src/views/full-appeal/submit-appeal/original-applicant.njk

https://pins-ds.atlassian.net/browse/AS-3887
/full-appeal/submit-appeal/original-applicant implementation

feat(full appeal): /full-appeal/submit-appeal/original-applicant implementation

---

packages/forms-web-app/src/views/full-appeal/date-decision-due.njk

https://pins-ds.atlassian.net/browse/AS-3637
Remove page hint that shows below page header

feat(as-3637): remove page hint

---

packages/forms-web-app/src/views/full-appeal/enforcement-notice.njk
packages/forms-web-app/src/views/householder-planning/eligibility/enforcement-notice-householder.njk

https://pins-ds.atlassian.net/browse/AS-3638
Remove the page hint from Enforcement page for both Full-Appeal and Householder

feat(as-3638): remove page hint

---

packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/task-list.test.js
packages/forms-web-app/__tests__/unit/validators/common/appeal-statement.test.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/task-list.js
packages/forms-web-app/src/services/task.service.js
packages/forms-web-app/src/validators/common/appeal-statement.js

https://pins-ds.atlassian.net/browse/AS-4353
Update Full Appeals Task List link and Appeal Statement error message

fix(as-4353): update full appeals task list link and appeal statement

---

packages/forms-web-app/__tests__/unit/controllers/full-appeal/type-of-planning-application.test.js
packages/forms-web-app/__tests__/unit/lib/full-appeal/map-planning-application.test.js
packages/forms-web-app/src/controllers/full-appeal/type-of-planning-application.js
packages/forms-web-app/src/lib/full-appeal/map-planning-application.js

https://pins-ds.atlassian.net/browse/AS-4343
Updating appeal type according to the type of planning application

feat(as-4343): update appeal type

---

packages/e2e-tests/cypress/integration/eligibility/full-appeal/date-decision-due/date-decision-due-steps.js
packages/forms-web-app/src/views/full-appeal/date-decision-due.njk

https://pins-ds.atlassian.net/browse/AS-3637
Updated page title and header text

feat(as-3637): updated page title and header text

---

packages/e2e-tests/cypress/integration/full-appeal/appeals-service/original-applicant-or-not.feature
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/original-applicant-or-not/original-applicant-or-not.js
packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/original-applicant-or-not-po.js
packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/task-list-page-po.js

https://pins-ds.atlassian.net/browse/AS-3887
Add cypress tests for Original Applicant or not

feat: add cypress tests for original applicant or not

---

packages/e2e-tests/cypress/integration/full-appeal/appeals-service/design-access-statement.feature
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/design-access-statement/design-access-statement.js
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/your-appeal-statement.feature

https://pins-ds.atlassian.net/browse/AS-4197
Add cypress e2e tests

feat: AS-4197 Add cypress tests for design and access statement

---

packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-address.feature
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-address/appeal-site-address.js

https://pins-ds.atlassian.net/browse/AS-3856
- [ X ] My commit history in this PR is linear

refactor: update e2e tests for site address - AS-3856

---

packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/applicant-name.test.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/applicant-name.js

https://pins-ds.atlassian.net/browse/AS-4352
applicant-name next page fix

fix(full appeal): applicant-name next page fix

---

packages/appeals-service-api/__tests__/integration/appeals.test.js
packages/appeals-service-api/__tests__/unit/controllers/appeals.test.js
packages/appeals-service-api/__tests__/unit/value-appeal.js
packages/appeals-service-api/src/models/appeal.js
packages/appeals-service-api/src/validators/appeals/appeals.validator.js
packages/business-rules/src/constants.js
packages/business-rules/src/schemas/full-appeal/insert.js
packages/business-rules/src/schemas/full-appeal/insert.test.js
packages/business-rules/src/schemas/full-appeal/update.js
packages/business-rules/src/schemas/full-appeal/update.test.js
packages/business-rules/src/schemas/householder-appeal/insert.js
packages/business-rules/src/schemas/householder-appeal/insert.test.js
packages/business-rules/src/schemas/householder-appeal/update.js
packages/business-rules/src/schemas/householder-appeal/update.test.js
packages/business-rules/test/data/full-appeal.js
packages/business-rules/test/data/householder-appeal.js
packages/e2e-tests/cypress/integration/eligibility/householder-planning/granted-or-refused-application.feature
packages/forms-web-app/src/controllers/householder-planning/eligibility/granted-or-refused-householder.js
packages/horizon-functions/horizon-householder-appeal-publish/index.js

https://pins-ds.atlassian.net/browse/AS-4351
Schema changes for eligibility journey for Full-appeal and Householder

feat(as-4351): Schema changes for eligibility journey

---

packages/e2e-tests/cypress/fixtures/Download/upload-file-valid.jpeg
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/applicant-name/applicant-name.js
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/design-access-statement-submitted.feature
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/design-access-statement-submitted/design-access-statement-submitted.js
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/design-access-statement.feature
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/design-access-statement/design-access-statement.js
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/upload-planning-application-form/upload-planning-application-form.js
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/your-appeal-statement/your-appeal-statement.js
packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/design-access-statement-submitted-po.js
packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/task-list-page-po.js
packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/your-appeal-statement-po.js
q

https://pins-ds.atlassian.net/browse/AS-4373
Add cypress tests

feat: add cypress tests for design access statement submitted

---

packages/appeals-service-api/__tests__/integration/appeals.test.js
packages/appeals-service-api/__tests__/unit/controllers/appeals.test.js
packages/appeals-service-api/src/models/appeal.js
packages/business-rules/src/schemas/full-appeal/insert.js
packages/business-rules/src/schemas/full-appeal/insert.test.js
packages/business-rules/src/schemas/full-appeal/update.js
packages/business-rules/src/schemas/full-appeal/update.test.js
packages/business-rules/test/data/full-appeal.js
packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/own-all-the-land.test.js
packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/own-all-the-land.test.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/own-all-the-land.js
packages/forms-web-app/src/lib/full-appeal/views.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/own-all-the-land.js
packages/forms-web-app/src/services/task.service.js
packages/forms-web-app/src/views/full-appeal/submit-appeal/own-all-the-land.njk

https://pins-ds.atlassian.net/browse/AS-4208
Adds the Full Appeal 'Do you own some of the land involved in the appeal? ' page

feat(as-4208): add full appeal own all the land page

---

packages/e2e-tests/cypress/fixtures/Download/upload-file-valid.jpeg
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/applicant-name.feature
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/applicant-name/applicant-name.js
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/contact-details.feature
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/design-access-statement-submitted.feature
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/design-access-statement.feature
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/upload-decision-letter.feature
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/upload-decision-letter/upload-decision-letter.js
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/upload-planning-application-form.feature
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/upload-planning-application-form/upload-planning-application-form.js

https://pins-ds.atlassian.net/browse/AS-4375
fix cypress file upload and back link issues and e2e tests

refactor: fix e2e tests on file upload and back link
