packages/e2e-tests/cypress/integration/full-appeal/appeals-service/own-all-the-land.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/own-all-the-land/own-all-the-land.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/own-some-of-the-land.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/own-some-of-the-land/own-some-of-the-land.js, packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/own-the-land-po.js
https://pins-ds.atlassian.net/browse/AS-4230
add cypress tests
=> feat: add cypress tests for 4230 own some of the land

packages/appeals-service-api/__tests__/integration/appeals.test.js, packages/appeals-service-api/__tests__/unit/controllers/appeals.test.js, packages/appeals-service-api/src/models/appeal.js, packages/business-rules/src/schemas/full-appeal/insert.js, packages/business-rules/src/schemas/full-appeal/insert.test.js, packages/business-rules/src/schemas/full-appeal/update.js, packages/business-rules/src/schemas/full-appeal/update.test.js, packages/business-rules/test/data/full-appeal.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/are-you-a-tenant.test.js, packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/are-you-a-tenant.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/are-you-a-tenant.js, packages/forms-web-app/src/lib/full-appeal/views.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/are-you-a-tenant.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js, packages/forms-web-app/src/services/task.service.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/are-you-a-tenant.njk
https://pins-ds.atlassian.net/browse/AS-4281
Add Full Appeal 'Are you a tenant of the agricultural holding?' page
=> feat(as-4281): add full appeal agricultural holding tenant page

packages/e2e-tests/cypress/fixtures/Download/upload-file-valid.jpeg, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-form-task-list/appeal-form-task-list.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-address/appeal-site-address.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/applicant-name/applicant-name.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/check-your-answers/check-your-answers.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/contact-details/contact-details.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/design-access-statement-submitted/design-access-statement-submitted.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/design-access-statement.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/design-access-statement/design-access-statement.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/know-the-owners.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/know-the-owners/know-the-owners.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/original-applicant-or-not/original-applicant-or-not.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/own-all-the-land.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/own-all-the-land/own-all-the-land.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/own-some-of-the-land.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/own-some-of-the-land/own-some-of-the-land.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/planning-application-number/planning-application-number.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/upload-decision-letter/upload-decision-letter.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/upload-planning-application-form/upload-planning-application-form.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/your-appeal-statement/your-appeal-statement.js, packages/e2e-tests/cypress/support/common-page-objects/common-po.js, packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/own-all-the-land-po.js, packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/own-the-land-po.js
https://pins-ds.atlassian.net/browse/AS-4233
https://pins-ds.atlassian.net/browse/AS-4235
This includes both the above user stories as they have been combined into one
=> feat: cypress tests to cover scenarios for own some of and rest of land

packages/e2e-tests/cypress/integration/full-appeal/appeals-service/part-of-agricultural-holding.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/part-of-agricultural-holding/part-of-agricultural-holding.js, packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/own-the-land-po.js
https://pins-ds.atlassian.net/browse/AS-4231
Add cypress e2e tests
=> feat: add cypress tests for agricultural holding

packages/e2e-tests/cypress/integration/eligibility/householder-planning/date-decision-due/date-decision-due-steps.js, packages/e2e-tests/cypress/support/eligibility/page-objects/shutter-page-po.js, packages/forms-web-app/src/controllers/householder-planning/eligibility/date-decision-due-householder.js
https://pins-ds.atlassian.net/browse/AS-4464
=> fix: fixed tests and updated the issue with decision date

packages/e2e-tests/cypress/integration/full-appeal/appeals-service/part-of-agricultural-holding/part-of-agricultural-holding.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/tenant-of-agricultural-holding.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/tenant-of-agricultural-holding/tenant-of-agricultural-holding.js, packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/own-the-land-po.js
https://pins-ds.atlassian.net/browse/AS-4281
add cypress e2e tests
=> feat: add cypress tests for tenant of agricultural holding page

.github/workflows/e2e-tests-on-PR.yml, package.json
=> fix(as-1234): cypress machines 11

packages/common/package-lock.json, packages/common/package.json
=> fix(as-1234): common service

packages/queue-retry/package-lock.json, packages/queue-retry/package.json
=> fix(as-1234): queue

docker-compose.yml, packages/business-rules/package-lock.json, packages/business-rules/package.json, packages/horizon-functions/package-lock.json, packages/horizon-functions/package.json
=> fix(as-1234): services

packages/forms-web-app/package-lock.json, packages/forms-web-app/package.json, packages/lpa-questionnaire-web-app/package-lock.json, packages/lpa-questionnaire-web-app/package.json
=> fix(as-1234): ui changes

packages/appeals-service-api/package-lock.json, packages/appeals-service-api/package.json
security updates appeal service api
=> fix(as-1234): security updates appeal service api

packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/task-list.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/task-list.js
https://pins-ds.atlassian.net/browse/AS-4472
Update Full Appeal Task List text from 'Application incomplete' to 'Appeal incomplete'
=> feat(as-4472): update full appeal task list text

packages/horizon-functions/horizon-householder-appeal-publish/index.js, packages/horizon-functions/horizon-householder-appeal-publish/src/createContacts.js
https://pins-ds.atlassian.net/browse/AS-4307
horizon functions
=> feat(as-4307): horizon functions - full planning

packages/e2e-tests/cypress/integration/eligibility/householder-planning/claiming-costs.feature, packages/e2e-tests/cypress/integration/eligibility/householder-planning/claiming-costs/claiming-costs-steps.js, packages/forms-web-app/__tests__/unit/controllers/householder-planning/eligibility/claiming-costs-householder.test.js, packages/forms-web-app/src/controllers/householder-planning/eligibility/claiming-costs-householder.js
https://pins-ds.atlassian.net/browse/AS-4403
Change URL to appellant-submission task list
=> feat(as-4403): View householder appeal task list

packages/appeals-service-api/__tests__/unit/lib/full-appeal/notify.test.js, packages/appeals-service-api/src/lib/full-appeal/notify.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/declaration.js
https://pins-ds.atlassian.net/browse/AS-4474
confirmation email is using data from contact details
=> fix(full appeal): confirmation email is using data from contact details

packages/e2e-tests/cypress/integration/eligibility/full-appeal/enforcement-notice.feature, packages/e2e-tests/cypress/integration/eligibility/full-appeal/enforcement-notice/enforcement-notice-steps.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/enforcement-notice.test.js, packages/forms-web-app/__tests__/unit/controllers/householder-planning/eligibility/date-decision-due-householder.test.js, packages/forms-web-app/src/controllers/full-appeal/enforcement-notice.js
https://pins-ds.atlassian.net/browse/AS-4402
Redirect to task list from enforcement page
=> feat(as-4402): redirect to task list from enforcement page

packages/appeals-service-api/src/routes/appealsHorizon.js, packages/appeals-service-api/src/routes/index.js, packages/horizon-functions/horizon-householder-appeal-publish/index.js
https://pins-ds.atlassian.net/browse/AS-4089
horizon issue
=> fix(as-4089): fix horizon issue

packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/visible-from-road.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/visible-from-road/visible-from-road.js, packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/visible-from-road-po.js
https://pins-ds.atlassian.net/browse/AS-4306
Add E2E tests for the Full Appeal Visible From Road page
=> feat(as-4306): add e2e tests for the full appeal visible from road page

packages/e2e-tests/cypress/integration/full-appeal/appeals-service/declaration.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/declaration/declaration.js, packages/e2e-tests/cypress/support/common-page-objects/common-po.js, packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/task-list-page-po.js
https://pins-ds.atlassian.net/browse/AS-4062
Includes cypress tests for Declaration and Submission pages (AS-4055)
=> feat: cypress tests for Declaration and Submission pages

packages/business-rules/src/rules/appeal/deadline-period.js, packages/business-rules/src/rules/appeal/deadline-period.test.js, packages/business-rules/src/rules/appeal/index.js, packages/business-rules/src/rules/appeal/index.test.js, packages/e2e-tests/cypress/integration/eligibility/full-appeal/date-decision-due/date-decision-due-steps.js, packages/e2e-tests/cypress/integration/eligibility/full-appeal/lpd-letter-decision-date/lpd-letter-decision-date-steps.js, packages/e2e-tests/cypress/integration/eligibility/full-appeal/shutter-page-deadline-passed/shutter-page-deadline-passed-steps.js, packages/e2e-tests/cypress/integration/eligibility/householder-planning/date-decision-due/date-decision-due-steps.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/decision-date.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/out-of-time-shutter-page.spec.js, packages/forms-web-app/__tests__/unit/controllers/householder-planning/eligibility/decision-date-householder.test.js, packages/forms-web-app/package-lock.json, packages/forms-web-app/package.json, packages/forms-web-app/src/controllers/eligibility/decision-date.js, packages/forms-web-app/src/controllers/full-appeal/date-decision-due.js, packages/forms-web-app/src/controllers/full-appeal/decision-date.js, packages/forms-web-app/src/controllers/full-appeal/out-of-time-shutter-page.js, packages/forms-web-app/src/controllers/householder-planning/eligibility/date-decision-due-householder.js, packages/forms-web-app/src/controllers/householder-planning/eligibility/decision-date-householder.js, packages/forms-web-app/src/views/full-appeal/out-of-time-shutter-page.njk
https://pins-ds.atlassian.net/browse/AS-4325
adding formatting for appeal deadline
=> feat(as-4325): add formatting for appeal deadline 

packages/business-rules/src/schemas/full-appeal/insert.js, packages/business-rules/src/schemas/full-appeal/insert.test.js, packages/business-rules/src/schemas/full-appeal/update.js, packages/business-rules/src/schemas/full-appeal/update.test.js, packages/business-rules/test/data/full-appeal.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/declaration.js
https://pins-ds.atlassian.net/browse/AS-4106
pdf url in appellant email was fixed
=> fix(full appeal): pdf url in appellant email was fixed

packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/identifying-the-landowners.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/identifying-the-landowners/identifying-the-landowners.js, packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/own-the-land-po.js
https://pins-ds.atlassian.net/browse/AS-4278
cypress tests for identifying land owners
=> feat: add cypress tests for identifying the owners

package.json, packages/appeals-service-api/package-lock.json, packages/forms-web-app/package-lock.json, packages/horizon-functions/horizon-householder-appeal-publish/index.js, packages/lpa-questionnaire-web-app/package-lock.json
https://pins-ds.atlassian.net/browse/AS-4465
cypress issues
=> fix(as-4465): cypress issues

packages/e2e-tests/cypress/integration/eligibility/full-appeal/complete-eligibility-journey.feature, packages/e2e-tests/cypress/integration/eligibility/full-appeal/complete-eligibility-journey/complete-eligibility-journey.js, packages/e2e-tests/cypress/integration/eligibility/householder-planning/complete-eligibility-journey.feature, packages/e2e-tests/cypress/integration/eligibility/householder-planning/complete-eligibility-journey/complete-eligibility-journey.js, packages/e2e-tests/cypress/support/eligibility/appellant-selects-the-site/get-site-option.js, packages/e2e-tests/cypress/support/eligibility/date-decision-due-householder/get-date-decision-due-householder.js, packages/e2e-tests/cypress/support/eligibility/date-decision-due/get-date-decision-due.js, packages/e2e-tests/cypress/support/eligibility/date-decision-received/get-date-decision-received.js, packages/e2e-tests/cypress/support/eligibility/date-decision-received/get-date-householder-decision-received.js, packages/e2e-tests/cypress/support/eligibility/granted-or-refused-application/get-planning-application-decision.js, packages/e2e-tests/cypress/support/eligibility/listed-building/get-listed-building-decision.js, packages/e2e-tests/cypress/support/eligibility/page-objects/local-planning-depart.js, packages/e2e-tests/cypress/support/eligibility/planning-application-type/get-planning-application-type.js
https://pins-ds.atlassian.net/browse/AS-4506
Added tests to verify that the data is persisted on UI for eligibility journey
=> test: added tests for ui data persist for eligibility journey

packages/appeals-service-api/__tests__/integration/appeals.test.js, packages/appeals-service-api/src/lib/config.js, packages/business-rules/src/config.js, packages/forms-web-app/src/config.js
https://pins-ds.atlassian.net/browse/AS-4390
Default the new journey feature flag to `true`
=> feat(as-4390): default new journey feature flag to true

.github/workflows/e2e-tests-on-PR.yml
https://pins-ds.atlassian.net/browse/AS-2424
7 cypress machines
=> fix(as-2424): cypress machines 7

.github/workflows/e2e-tests-on-PR.yml
https://pins-ds.atlassian.net/browse/AS-4242
Cypress 12
=> fix(as-2424): cypress 12

packages/business-rules/src/constants.js, packages/business-rules/src/lib/pins-yup.js, packages/business-rules/src/lib/pins-yup.test.js, packages/business-rules/src/schemas/full-appeal/insert.js, packages/business-rules/src/schemas/full-appeal/insert.test.js, packages/business-rules/src/schemas/full-appeal/update.js, packages/business-rules/src/schemas/full-appeal/update.test.js, packages/business-rules/src/validators/common/array.js, packages/business-rules/src/validators/index.js, packages/business-rules/src/validators/index.test.js, packages/business-rules/test/data/full-appeal.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/telling-the-landowners.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/telling-the-tenants.test.js, packages/forms-web-app/__tests__/unit/lib/to-array.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/telling-the-landowners.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/telling-the-tenants.test.js, packages/forms-web-app/__tests__/unit/validators/common/checkboxes.test.js, packages/forms-web-app/__tests__/unit/validators/utils/validate-checkbox-against-options.js.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/telling-the-landowners.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/telling-the-tenants.js, packages/forms-web-app/src/lib/to-array.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/telling-the-landowners.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/telling-the-tenants.js, packages/forms-web-app/src/validators/common/checkboxes.js, packages/forms-web-app/src/validators/utils/validate-checkbox-against-options.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/identifying-the-owners.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/telling-the-landowners.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/telling-the-tenants.njk
https://pins-ds.atlassian.net/browse/AS-4345
telling the landowners and tenants pages
=> feat(full appeal): telling the landowners and tenants pages

docker-compose.yml
https://pins-ds.atlassian.net/browse/AS-4465
remove services
=> feat(as-4465): remove extra services

packages/lpa-questionnaire-web-app/Dockerfile
https://pins-ds.atlassian.net/browse/AS-4465
docker typo
=> fix(as-4465): docker typo

packages/business-rules/src/schemas/full-appeal/insert.js, packages/business-rules/src/schemas/full-appeal/insert.test.js, packages/business-rules/src/schemas/full-appeal/update.js, packages/business-rules/src/schemas/full-appeal/update.test.js, packages/business-rules/test/data/full-appeal.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/why-hearing.test.js, packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/health-safety-issues.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/visible-from-road.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/why-hearing.test.js, packages/forms-web-app/__tests__/unit/validators/common/textfield.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/declaration.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/why-hearing.js, packages/forms-web-app/src/lib/full-appeal/views.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/health-safety-issues.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/visible-from-road.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/why-hearing.js, packages/forms-web-app/src/validators/common/textfield.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/why-hearing.njk
https://pins-ds.atlassian.net/browse/AS-4330
Add Full Appeal Why Hearing page
=> feat(as-4330): add full appeal why hearing page

packages/appeals-service-api/src/controllers/appeals.js, packages/appeals-service-api/src/services/appeal.service.js
https://pins-ds.atlassian.net/browse/AS-4465
drop back office from appeals service
=> fix(as-4465): drop back office from appeals service

packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/know-the-owners.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/know-the-owners/know-the-owners.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/telling-the-landowners.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/telling-the-landowners/telling-the-landowners.js, packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/own-the-land-po.js, packages/e2e-tests/cypress/support/full-appeal/appeals-service/selectTheOwners.js
https://pins-ds.atlassian.net/browse/AS-4279
Added E2E tests for Telling the landowners
=> test: added cypress tests for telling the landowners

packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/telling-the-landowners.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/telling-the-landowners/telling-the-landowners.js, packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/own-the-land-po.js
https://pins-ds.atlassian.net/browse/AS-4345
Added tests for telling other landowners
=> test: added tests for telling the other landowners

packages/forms-web-app/src/views/appellant-submission/task-list.njk
https://pins-ds.atlassian.net/browse/AS-4525
Amend HAS title on task list page
=> fix(as-4525): has appeal title on task list

packages/business-rules/src/schemas/full-appeal/insert.js, packages/business-rules/src/schemas/full-appeal/insert.test.js, packages/business-rules/src/schemas/full-appeal/update.js, packages/business-rules/src/schemas/full-appeal/update.test.js, packages/business-rules/test/data/full-appeal.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/expect-inquiry-last.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/expect-inquiry-last.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js, packages/forms-web-app/__tests__/unit/validators/common/numberfield.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/expect-inquiry-last.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/expect-inquiry-last.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js, packages/forms-web-app/src/validators/common/numberfield.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/expect-inquiry-last.njk
https://pins-ds.atlassian.net/browse/AS-4470
Add Full Appeal 'How many days would you expect the inquiry to last?' page
=> feat(as-4470): add full appeal expect-inquiry-last page

packages/business-rules/src/schemas/full-appeal/insert.js, packages/business-rules/src/schemas/full-appeal/insert.test.js, packages/business-rules/src/schemas/full-appeal/update.js, packages/business-rules/src/schemas/full-appeal/update.test.js, packages/business-rules/test/data/full-appeal.js, packages/common/src/document-types.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/draft-statement-common-ground.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/draft-statement-common-ground.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/draft-statement-common-ground.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/draft-statement-common-ground.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/draft-statement-common-ground.njk
https://pins-ds.atlassian.net/browse/AS-4469
Add Full Appeal Draft Statement of Common Ground page
=> feat(as-4469): add full appeal draft statement of common ground page

packages/pdf-service-api/package-lock.json
https://pins-ds.atlassian.net/browse/AS-4645
pdf service updates
=> fix(as-4645): updates pdf service

packages/document-service-api/package-lock.json, packages/document-service-api/package.json, q
https://pins-ds.atlassian.net/browse/AS-4645
document service
=> fix(as-4645): updates document service

packages/document-service-api/package-lock.json, packages/document-service-api/package.json
https://pins-ds.atlassian.net/browse/AS-4645
document services
=> fix(as-4645): document services

packages/business-rules/src/schemas/full-appeal/insert.js, packages/business-rules/src/schemas/full-appeal/insert.test.js, packages/business-rules/src/schemas/full-appeal/update.js, packages/business-rules/src/schemas/full-appeal/update.test.js, packages/business-rules/test/data/full-appeal.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/advertising-your-appeal.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/telling-the-landowners.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/telling-the-tenants.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/advertising-your-appeal.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/advertising-your-appeal.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/telling-the-landowners.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/telling-the-tenants.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/advertising-your-appeal.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/telling-the-landowners.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/advertising-your-appeal.njk
https://pins-ds.atlassian.net/browse/AS-4324
advertising-your-appeal page implemented
=> feat(full appeal): advertising-your-appeal page implemented

packages/e2e-tests/cypress/integration/full-appeal/appeals-service/task-list/appeal-form-task-list.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/task-list/appeal-form-task-list/appeal-form-task-list.js, packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/appeal-form-task-list-po.js
https://pins-ds.atlassian.net/browse/AS-4473
add cypress tests for additional section in task list
=> feat: add new section decide your appeal to task list

packages/e2e-tests/cypress/integration/full-appeal/appeals-service/prefer-to-decide-your-appeal/decide-your-appeal.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/prefer-to-decide-your-appeal/decide-your-appeal/decide-your-appeal.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/task-list/appeal-form-task-list/appeal-form-task-list.js, packages/e2e-tests/cypress/support/common-page-objects/common-po.js, packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/appeal-form-task-list-po.js, packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/decide-your-appeal-po.js
https://pins-ds.atlassian.net/browse/AS-4467
Add cypress tests for decide your appeal
=> feat: cypress tests for decide your appeal page

packages/business-rules/src/schemas/full-appeal/insert.js, packages/business-rules/src/schemas/full-appeal/insert.test.js, packages/business-rules/src/schemas/full-appeal/update.js, packages/business-rules/src/schemas/full-appeal/update.test.js, packages/business-rules/test/data/full-appeal.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/identfying-the-owners.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/identifying-the-owners.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/identifying-the-owners.njk
https://pins-ds.atlassian.net/browse/AS-4280
identifying the other landowners page implementation
=> feat(full appeal): identifying the other landowners page implementation

packages/e2e-tests/cypress/integration/full-appeal/appeals-service/prefer-to-decide-your-appeal/days-inquiry-last.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/prefer-to-decide-your-appeal/days-inquiry-last/days-inquiry-last.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/prefer-to-decide-your-appeal/prefer-an-inquiry.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/prefer-to-decide-your-appeal/prefer-an-inquiry/prefer-an-inquiry.js, packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/appeal-form-task-list-po.js, packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/decide-your-appeal-po.js
https://pins-ds.atlassian.net/browse/AS-4468
https://pins-ds.atlassian.net/browse/AS-4470
cypress tests covers both stories prefer an inquiry and days for inquiry
=> feat: cypress tests to cover prefer for an inquiry and days for inquiry

packages/forms-web-app/src/views/full-appeal/submit-appeal/are-you-a-tenant.njk
https://pins-ds.atlassian.net/browse/AS-4575
Fix the Full Appeal Are you a Tenant page so it displays the selected value when the user returns to the page
=> fix(as-4575): update the full appeal are you a tenant page to display the selected value

packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/agricultural-holding.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/agricultural-holding.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/agricultural-holding.njk
https://pins-ds.atlassian.net/browse/AS-4543
Fix the back link on the Full Appeal Agricultural Holding page to work in all scenarios
=> fix(as-4543): fix full appeal agricultural holding page back link

packages/business-rules/src/schemas/full-appeal/update.js, packages/business-rules/src/schemas/full-appeal/update.test.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/declaration.feature, packages/e2e-tests/cypress/support/full-appeal/appeals-service/declarationPageMethodsAppellant.js, packages/e2e-tests/cypress/support/full-appeal/appeals-service/declariationPageMethodsAgent.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/declaration.js
https://pins-ds.atlassian.net/browse/AS-4576
dummy data removed from declaration
=> fix(full appeal): dummy data removed from declaration

packages/e2e-tests/cypress/integration/full-appeal/appeals-service/prefer-to-decide-your-appeal/statement-of-common-ground.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/prefer-to-decide-your-appeal/statement-of-common-ground/statement-of-common-ground.js
https://pins-ds.atlassian.net/browse/AS-4469
cypress tests for draft statement
=> feat: add cypress tests for draft statement

packages/forms-web-app/src/views/full-appeal/submit-appeal/check-your-answers.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/declaration.njk
- Text change on Check Your Answers page
- Update the Declaration back link to redirect back to the Check Your Answers page
=> fix(as-4504): update to text on full appeal check your answers page and declaration back link

.github/workflows/e2e-tests-on-PR.yml, packages/e2e-tests/cypress/integration/eligibility/full-appeal/complete-eligibility-journey/complete-eligibility-journey.js, packages/e2e-tests/cypress/integration/eligibility/full-appeal/date-decision-due/date-decision-due-steps.js, packages/e2e-tests/cypress/integration/eligibility/full-appeal/lpd-letter-decision-date/lpd-letter-decision-date-steps.js, packages/e2e-tests/cypress/integration/eligibility/householder-planning/claiming-costs/claiming-costs-steps.js, packages/e2e-tests/cypress/integration/eligibility/householder-planning/complete-eligibility-journey/complete-eligibility-journey.js, packages/e2e-tests/cypress/integration/eligibility/householder-planning/date-decision-due/date-decision-due-steps.js, packages/e2e-tests/cypress/integration/eligibility/householder-planning/enforcement-notice.feature, packages/e2e-tests/cypress/integration/eligibility/householder-planning/enforcement-notice/enforcement-notice-steps.js, packages/e2e-tests/cypress/integration/eligibility/householder-planning/lpd-letter-decision-date/lpd-letter-decision-date-steps.js, packages/e2e-tests/cypress/support/eligibility/date-decision-due-householder/enter-date-decision-due-householder.js, packages/e2e-tests/reporter.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/check-your-answers.njk
Update a couple of `data-cy` attributes on the Full Appeal Check Your Answers page
=> fix(as-4504): update data-cy attributes on full appeal check your answers page

.github/workflows/e2e-tests-on-PR.yml
https://pins-ds.atlassian.net/browse/AS-2424
fix cypress failures
=> fix(as-2424): cypress issues

.github/workflows/e2e-tests-on-PR.yml, packages/e2e-tests/cypress/integration/eligibility/householder-planning/claiming-costs.feature, packages/e2e-tests/cypress/integration/eligibility/householder-planning/enforcement-notice.feature
https://pins-ds.atlassian.net/browse/AS-2424
fix cypress fail fast
=> fix(as-2424): fix cypress fail fast

packages/e2e-tests/cypress/downloads/upload-file-valid.jpeg, packages/e2e-tests/cypress/integration/eligibility/full-appeal/enforcement-notice/enforcement-notice-steps.js, packages/e2e-tests/cypress/integration/eligibility/full-appeal/lpd-letter-decision-date/lpd-letter-decision-date-steps.js, packages/e2e-tests/cypress/integration/eligibility/householder-planning/claiming-costs.feature, packages/e2e-tests/cypress/integration/eligibility/householder-planning/claiming-costs/claiming-costs-steps.js, packages/e2e-tests/cypress/integration/eligibility/householder-planning/enforcement-notice.feature, packages/e2e-tests/cypress/integration/eligibility/householder-planning/enforcement-notice/enforcement-notice-steps.js
https://pins-ds.atlassian.net/browse/AS-4618
Fixed failing eligibility tests
=> fix: fixed eligibility date tests

packages/forms-web-app/src/views/full-appeal/submit-appeal/check-your-answers.njk
Updated the logic on the Full Appeal Check Your Answers page
=> fix(as-4504): update full appeal check your answers logic

packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/telling-the-landowners.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/visible-from-road.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/telling-the-landowners.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/visible-from-road.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/telling-the-landowners.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/visible-from-road.njk
https://pins-ds.atlassian.net/browse/AS-4605
Update Full Appeal back links
=> fix(as-4605): update full appeal back links

packages/business-rules/src/schemas/full-appeal/insert.js, packages/business-rules/src/schemas/full-appeal/insert.test.js, packages/business-rules/src/schemas/full-appeal/update.js, packages/business-rules/src/schemas/full-appeal/update.test.js, packages/business-rules/test/data/full-appeal.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/draft-statement-common-ground.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/expect-inquiry-last.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/how-decide-appeal.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/why-hearing.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/why-inquiry.test.js, packages/forms-web-app/__tests__/unit/services/task-status/full-appeal/status-appeal-decision-section.test.js, packages/forms-web-app/__tests__/unit/services/task-status/full-appeal/status-appeal-site-section.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/draft-statement-common-ground.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/expect-inquiry-last.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/how-decide-appeal.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/why-hearing.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/why-inquiry.js, packages/forms-web-app/src/services/task-status/full-appeal/status-appeal-decision-section.js, packages/forms-web-app/src/services/task.service.js
https://pins-ds.atlassian.net/browse/AS-4389
appeal decision section status
=> feat(full appeal): appeal decision section status

packages/forms-web-app/__tests__/unit/services/task-status/full-appeal/status-appeal-site-section.test.js, packages/forms-web-app/__tests__/unit/services/task.service.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/task-list.js, packages/forms-web-app/src/services/task-status/full-appeal/status-appeal-site-section.js, packages/forms-web-app/src/services/task.service.js
https://pins-ds.atlassian.net/browse/AS-4389
task list status of "Submit Your Appeal"
=> feat(full appeal): task list status of "Submit Your Appeal"

packages/horizon-functions/horizon-householder-appeal-publish/index.js, packages/horizon-functions/horizon-householder-appeal-publish/src/createContacts.js, packages/horizon-functions/horizon-householder-appeal-publish/src/logic/createContact.js, packages/horizon-functions/horizon-householder-appeal-publish/src/logic/createOrganisation.js
https://pins-ds.atlassian.net/browse/AS-4628
Full Planning Integration
=> feat(as-4628): horizon full planning

packages/horizon-functions/horizon-householder-appeal-publish/index.js
https://pins-ds.atlassian.net/browse/AS-4628
fix issue with quotes
=> fix(as-4628): fix issue

packages/appeals-service-api/__tests__/integration/appeals.test.js, packages/appeals-service-api/__tests__/unit/controllers/appeals.test.js, packages/appeals-service-api/package-lock.json, packages/appeals-service-api/package.json
https://pins-ds.atlassian.net/browse/AS-4588
Update appeals-service-api packages
=> fix(as-4586): update appeals-service-api packages

packages/appeals-service-api/package-lock.json, packages/business-rules/package-lock.json, packages/business-rules/package.json, packages/business-rules/src/schemas/full-appeal/update.test.js
https://pins-ds.atlassian.net/browse/AS-4589
Update Business Rules packages to try to address dependabot vulnerabilities
=> fix(as-4588): update business-rules packages

packages/horizon-functions/horizon-householder-appeal-publish/index.js
https://pins-ds.atlassian.net/browse/AS-4628
fixed issues around horizon file uploads
=> fix(as-4628): fixed issues around horizon file uploads

packages/forms-web-app/__tests__/unit/controllers/appellant-submission/task-list.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/declaration-information.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/task-list.test.js, packages/forms-web-app/__tests__/unit/services/task.service.test.js, packages/forms-web-app/__tests__/unit/validators/common/checkboxes.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/task-list.js
https://pins-ds.atlassian.net/browse/AS-4634
increasing test coverage
=> test(full appeal): increasing test coverage

packages/e2e-tests/cypress.json, packages/e2e-tests/cypress/integration/common/full-appeal/check-your-answers/check-your-answers.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/advertising-your-appeal/advertising-your-appeal.js, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/check-your-answers-section/change-your-answers.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/check-your-answers-section/check-your-answers.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/task-list/appeal-form-task-list.feature, packages/e2e-tests/cypress/integration/full-appeal/appeals-service/task-list/appeal-form-task-list/appeal-form-task-list.js, packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/appeal-form-task-list-po.js
https://pins-ds.atlassian.net/browse/AS-4389
cypress tests for task list
=> feat: add cypress tests for task list progress check

packages/document-service-api/package-lock.json, packages/document-service-api/package.json
https://pins-ds.atlassian.net/browse/AS-4592
Package updates in document-service-api
=> fix(as-4592): update document-service-api packages

packages/horizon-functions/package-lock.json, packages/horizon-functions/package.json
https://pins-ds.atlassian.net/browse/AS-4595
horizon fixes
=> fix(as-4595): horizon updates

mocked-services/horizon/package-lock.json
https://pins-ds.atlassian.net/browse/AS-4595
mock horizon updates
=> fix(as-4595): updates mock horizon

mocked-services/notify/package-lock.json
https://pins-ds.atlassian.net/browse/AS-4595
update mock services
=> fix(as-4595): mock services updates

packages/pdf-service-api/package-lock.json, packages/pdf-service-api/package.json
https://pins-ds.atlassian.net/browse/AS-4596
Update pdf-service-api packages for dependabot vulnerabilities
=> fix(as-4596): update pdf-service-api packages

pipelines/appeals-service-api/Dockerfile, pipelines/appeals-service-api/appeals-service-api-cd.yml, pipelines/appeals-service-api/appeals-service-api-ci.yml, pipelines/appeals-service-api/variables.yml, pipelines/business-rules/business-rules-ci.yml, pipelines/business-rules/variables.yml, pipelines/common/common-ci.yml, pipelines/common/variables.yml, pipelines/variables.yml
- Added pipelines to deploy the Appeals service API to the new environments.
=> Appeals Service API release pipelines

packages/business-rules/src/config.js, packages/business-rules/src/config.spec.js
https://pins-ds.atlassian.net/browse/AS-4649
pdf link changed in appellant email for householder
=> feat(householder): pdf link changed in appellant email

packages/ping/package-lock.json, packages/ping/package.json
https://pins-ds.atlassian.net/browse/AS-4597
update packages for ping service
=> fix(as-4597): update packages ping service

packages/appeals-service-api/__tests__/unit/lib/notify.test.js, packages/appeals-service-api/jest.config.js, packages/appeals-service-api/package-lock.json, packages/appeals-service-api/package.json
https://pins-ds.atlassian.net/browse/AS-4591
appeal service api issues
=> fix(as-4591): appeal service api issues

packages/forms-web-app/src/views/full-appeal/use-existing-service-application-type.njk
https://pins-ds.atlassian.net/browse/AS-4742
Amend to insert missing text to page title on http://localhost:9003/before-you-start/use-existing-service-application-type shutter page
=> fix(amend page title): amend page title to add missing text

packages/forms-web-app/src/controllers/full-appeal/submit-appeal/declaration.js
=> fix(declaration.js): trying to fix validation issue

packages/forms-web-app/__tests__/unit/controllers/before-you-start/before-you-start-first-page.test.js, packages/forms-web-app/__tests__/unit/lib/views.test.js, packages/forms-web-app/__tests__/unit/routes/before-you-start.test.js, packages/forms-web-app/__tests__/unit/routes/index.test.js, packages/forms-web-app/src/controllers/before-you-start.js, packages/forms-web-app/src/lib/views.js, packages/forms-web-app/src/routes/before-you-start.js, packages/forms-web-app/src/routes/index.js, packages/forms-web-app/src/views/before-you-start/first-page.njk
https://pins-ds.atlassian.net/browse/AS-4606
Add new page with routing (`/before-you-start`) to provide information. Page links to next page `/before-you-start/local-planning-depart`
=> feat(bys first page): add first page for before-you-start route

packages/forms-web-app/src/views/householder-planning/eligibility/use-existing-service-costs.njk
https://pins-ds.atlassian.net/browse/AS-4757
Add missing text to shutter page title.
=> fix(amend page title): amend shutter page title to add missing text

packages/e2e-tests/cypress/integration/eligibility/full-appeal/appellant-selects-the-site/appellant-selects-the-site-steps.js, packages/forms-web-app/__tests__/unit/controllers/before-you-start/use-existing-service-development-type.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/any-of-following.spec.js, packages/forms-web-app/__tests__/unit/lib/views.test.js, packages/forms-web-app/__tests__/unit/routes/before-you-start/index.test.js, packages/forms-web-app/__tests__/unit/routes/before-you-start/use-existing-service-development-type.test.js, packages/forms-web-app/__tests__/unit/routes/index.test.js, packages/forms-web-app/src/controllers/before-you-start/use-existing-service-development-type.js, packages/forms-web-app/src/controllers/full-appeal/any-of-following.js, packages/forms-web-app/src/lib/views.js, packages/forms-web-app/src/routes/before-you-start/index.js, packages/forms-web-app/src/routes/before-you-start/use-existing-service-development-type.js, packages/forms-web-app/src/routes/index.js, packages/forms-web-app/src/views/before-you-start/use-existing-service-development-type.njk
=> feat(added new shutter page): added new shutter page

packages/forms-web-app/__tests__/unit/controllers/appellant-submission/supporting-documents.test.js, packages/forms-web-app/src/controllers/appellant-submission/supporting-documents.js, packages/forms-web-app/src/views/components/multi-file-upload/template.njk
=> fix(any-documents upload): fixed files not getting uploaded

packages/e2e-tests/cypress/integration/eligibility/householder-planning/listed-building.feature, packages/e2e-tests/cypress/integration/eligibility/householder-planning/listed-building/listed-building-steps.js, packages/forms-web-app/__tests__/unit/controllers/before-you-start/use-existing-service-listed-building.test.js, packages/forms-web-app/__tests__/unit/controllers/eligibility/listed-building.test.js, packages/forms-web-app/__tests__/unit/controllers/householder-planning/eligibility/listed-building-householder.test.js, packages/forms-web-app/__tests__/unit/lib/views.test.js, packages/forms-web-app/__tests__/unit/routes/before-you-start/index.test.js, packages/forms-web-app/__tests__/unit/routes/before-you-start/use-existing-service-listed-building.test.js, packages/forms-web-app/__tests__/unit/routes/index.test.js, packages/forms-web-app/src/controllers/before-you-start/use-existing-service-listed-building.js, packages/forms-web-app/src/controllers/eligibility/listed-building.js, packages/forms-web-app/src/controllers/householder-planning/eligibility/listed-building-householder.js, packages/forms-web-app/src/lib/views.js, packages/forms-web-app/src/routes/before-you-start/index.js, packages/forms-web-app/src/routes/before-you-start/use-existing-service-listed-building.js, packages/forms-web-app/src/views/before-you-start/use-existing-service-listed-building.njk
AS-4625 created shutter page for listed buildings - Householder Planning
https://pins-ds.atlassian.net/browse/AS-4625
Created shutter page for listed buildings - Householder Planning
=> feat(as-4625 created shutter page for listed buildings): created shutter page for listed buildings - Householder Planning

packages/appeals-service-api/__tests__/unit/services/appeal.service.test.js, packages/appeals-service-api/src/services/appeal.service.js
=> fix(queue): commented out queue to avoid looping error

docker-compose.yml, packages/appeals-service-api/__tests__/unit/controllers/appeals.test.js, packages/appeals-service-api/src/controllers/appeals.js, packages/appeals-service-api/src/lib/config.js, packages/business-rules/src/config.js, packages/business-rules/src/schemas/validate.js, packages/business-rules/src/schemas/validate.test.js, packages/forms-web-app/__tests__/unit/middleware/check-appeal-type-exists.test.js, packages/forms-web-app/src/config.js, packages/forms-web-app/src/middleware/check-appeal-type-exists.js
=> fix(featureflag): feature flag removed as it not useful

packages/forms-web-app/src/views/appellant-submission/confirmation.njk
Amendment to wording on Householder Appeal Submission page.
=> feat(as-4690): amend wording on HAS confirmation page

packages/appeals-service-api/src/controllers/appeals.js, packages/appeals-service-api/src/models/appeal.js, packages/business-rules/src/schemas/full-appeal/insert.js, packages/business-rules/src/schemas/full-appeal/update.js, packages/business-rules/test/data/full-appeal.js, packages/common/src/document-types.js, packages/forms-web-app/__tests__/mockData/full-appeal.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/original-decision-notice.test.js, packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/original-decision-notice.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/original-decision-notice.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/task-list.js, packages/forms-web-app/src/lib/full-appeal/views.js, packages/forms-web-app/src/lib/get-route-for-special-cases.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/original-decision-notice.js, packages/forms-web-app/src/services/task-status/full-appeal/status-planning-application-documents-section.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/original-decision-notice.njk
https://pins-ds.atlassian.net/browse/AS-4806
decision notice from your original planning application
=> Feature(as-4806): decision notice from your original planning application

packages/forms-web-app/src/views/full-appeal/submit-appeal/proposed-development-changed.njk
=> fix(proposed development changed): fixed default selector to false

docker-compose.yml, packages/forms-web-app/src/validators/common/schemas/file-upload.js
=> fix(clamav): enabled clamav for full planning

packages/forms-web-app/src/views/full-appeal/submit-appeal/application-certificates-included.njk
https://pins-ds.atlassian.net/browse/AS-4804
Amending page title in case of error.
=> feat(as-4804): amend error page title

packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/new-documents.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/new-documents.js
https://pins-ds.atlassian.net/browse/AS-4898
change link from invalid to valid route
=> feat(as-4898): fix broken route

packages/forms-web-app/src/views/full-appeal/submit-appeal/certificates.njk
https://pins-ds.atlassian.net/browse/AS-4914
Include 'Error: ' in title of error page for `full-appeal/submit-appeal/certificates` page. 
=> fix(as-4914): update error page title

packages/forms-web-app/src/views/full-appeal/submit-appeal/planning-obligation-planned.njk
https://pins-ds.atlassian.net/browse/AS-4887
Remove a line from relevant njk file.
=> feat(as-4887): remove unnecessary text

packages/forms-web-app/src/views/full-appeal/submit-appeal/new-plans-drawings.njk
https://pins-ds.atlassian.net/browse/AS-4855
amend to page title and heading
=> feat(as-4855): amend title of plans or drawings upload page

packages/forms-web-app/src/controllers/full-appeal/submit-appeal/proposed-development-changed.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/proposed-development-changed.njk
=> fix(description of development correct): fixed state of the view

packages/business-rules/src/schemas/full-appeal/insert.js, packages/business-rules/src/schemas/full-appeal/update.js, packages/business-rules/test/data/full-appeal.js, packages/common/src/document-types.js, packages/forms-web-app/__tests__/mockData/full-appeal.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/design-access-statement.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/letter-confirming-application.test.js, packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/letter-confirming-application.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/letter-confirming-application.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/proposed-development-changed.js, packages/forms-web-app/src/lib/full-appeal/views.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/letter-confirming-application.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/letter-confirming-application.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/proposed-development-changed.njk
=> feat: letter confirming application

packages/business-rules/src/schemas/full-appeal/update.js
=> fix(letter confirming): fixed optional letter confirming

packages/business-rules/src/schemas/full-appeal/update.js
=> fix(fixed letter validation): fixed letter validation

packages/appeals-service-api/src/lib/config.js, packages/appeals-service-api/src/lib/queue.js, packages/appeals-service-api/src/services/appeal.service.js, packages/horizon-functions/horizon-householder-appeal-publish/src/logic/createContact.js
=> fix(horizon fix): horizon fixes

packages/appeals-service-api/src/lib/config.js
=> fix(reverted horizon hostname): reverted horizon hostname

packages/forms-web-app/src/views/full-appeal/can-use-service.njk, packages/forms-web-app/src/views/full-appeal/prior-approval/can-use-service.njk, packages/forms-web-app/src/views/full-appeal/removal-or-variation-of-conditions/can-use-service.njk, packages/forms-web-app/src/views/householder-planning/eligibility/can-use-service.njk, packages/forms-web-app/src/views/householder-planning/eligibility/prior-approval/can-use-service.njk, packages/forms-web-app/src/views/householder-planning/eligibility/removal-or-variation-of-conditions/can-use-service.njk
https://pins-ds.atlassian.net/browse/AS-4762
content change on the CYA pages
=> feat(as-4762 content change on cya): content change on the CYA pages

azure-pipelines-commit-lint.yml, packages/appeal-reply-service-api/pipelines/azure-pipelines-build.yml, packages/appeal-reply-service-api/pipelines/azure-pipelines-release.yml, packages/appeals-service-api/pipelines/azure-pipelines-build.yml, packages/appeals-service-api/pipelines/azure-pipelines-release.yml, packages/business-rules/pipelines/azure-pipelines-build.yml, packages/clamav-rest-server/pipelines/azure-pipelines-build.yml, packages/clamav-rest-server/pipelines/azure-pipelines-release.yml, packages/common/pipelines/azure-pipelines-build.yml, packages/document-service-api/pipelines/azure-pipelines-build.yml, packages/document-service-api/pipelines/azure-pipelines-release.yml, packages/e2e-tests/pipelines/azure-pipelines-cypress-e2e.yml, packages/forms-web-app/pipelines/azure-pipelines-build.yml, packages/forms-web-app/pipelines/azure-pipelines-release.yml, packages/horizon-functions/pipelines/azure-pipelines-build.yml, packages/horizon-functions/pipelines/azure-pipelines-release.yml, packages/pdf-service-api/pipelines/azure-pipelines-build.yml, packages/pdf-service-api/pipelines/azure-pipelines-release.yml, packages/ping/pipelines/azure-pipelines-build.yml, packages/queue-retry/pipelines/azure-pipelines-build.yml
Update pipelines to version 2.5.1
=> chore(pipelines): update pipelines to version 2.5.1

packages/forms-web-app/__tests__/unit/controllers/submit-appeal/application-saved.test.js, packages/forms-web-app/__tests__/unit/lib/submit-appeal/views.test.js, packages/forms-web-app/__tests__/unit/routes/index.test.js, packages/forms-web-app/__tests__/unit/routes/submit-appeal/application-saved.test.js, packages/forms-web-app/__tests__/unit/routes/submit-appeal/index.test.js, packages/forms-web-app/src/controllers/submit-appeal/application-saved.js, packages/forms-web-app/src/lib/submit-appeal/views.js, packages/forms-web-app/src/routes/index.js, packages/forms-web-app/src/routes/submit-appeal/application-saved.js, packages/forms-web-app/src/routes/submit-appeal/index.js, packages/forms-web-app/src/views/submit-appeal/application-saved.njk
https://pins-ds.atlassian.net/browse/AS-4688
=> feat(as-4688): add page to inform user application has been saved

packages/forms-web-app/src/views/components/save-and-return/macro.njk, packages/forms-web-app/src/views/components/save-and-return/template.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/original-applicant.njk
=> feat: save and return template

azure-pipelines-commit-lint.yml, packages/appeal-reply-service-api/pipelines/azure-pipelines-build.yml, packages/appeal-reply-service-api/pipelines/azure-pipelines-release.yml, packages/appeals-service-api/pipelines/azure-pipelines-build.yml, packages/appeals-service-api/pipelines/azure-pipelines-release.yml, packages/appeals-service-api/src/lib/config.js, packages/appeals-service-api/src/services/appeal.service.js, packages/business-rules/pipelines/azure-pipelines-build.yml, packages/clamav-rest-server/pipelines/azure-pipelines-build.yml, packages/clamav-rest-server/pipelines/azure-pipelines-release.yml, packages/common/pipelines/azure-pipelines-build.yml, packages/document-service-api/pipelines/azure-pipelines-build.yml, packages/document-service-api/pipelines/azure-pipelines-release.yml, packages/e2e-tests/pipelines/azure-pipelines-cypress-e2e.yml, packages/forms-web-app/pipelines/azure-pipelines-build.yml, packages/forms-web-app/pipelines/azure-pipelines-release.yml, packages/horizon-functions/pipelines/azure-pipelines-build.yml, packages/horizon-functions/pipelines/azure-pipelines-release.yml, packages/pdf-service-api/pipelines/azure-pipelines-build.yml, packages/pdf-service-api/pipelines/azure-pipelines-release.yml, packages/ping/pipelines/azure-pipelines-build.yml, packages/queue-retry/pipelines/azure-pipelines-build.yml
- Updates pipelines to deploy app service correctly.
#
=> Update pipeline with staging slots

packages/forms-web-app/src/views/full-appeal/submit-appeal/draft-statement-common-ground.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/expect-inquiry-last.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/how-decide-appeal.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/why-hearing.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/why-inquiry.njk
https://pins-ds.atlassian.net/browse/AS-4758
=> feat(as-4758): add save and come back later buttons

packages/forms-web-app/__tests__/mockData/full-appeal.js, packages/forms-web-app/src/lib/choose-appropriate-task-list.js
N/A
Changed ../../../business-rules to @pins/business-rules as that is what is consistently used and fixes a bug that stopped us building the solution on WIndows.
=> chore: fixed business rules import

packages/forms-web-app/src/views/full-appeal/submit-appeal/appeal-statement.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/new-documents.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/new-plans-drawings.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/other-supporting-documents.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/plans-drawings.njk
https://pins-ds.atlassian.net/browse/AS-4765
=> feat(as-4765): add save and come back later buttons

packages/appeals-service-api/__tests__/unit/controllers/save-and-return.test.js, packages/appeals-service-api/src/controllers/save.js, packages/business-rules/src/config.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/applicant-name.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/contact-details.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/original-applicant.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/original-applicant.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/applicant-name.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/contact-details.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/original-applicant.njk
Implemented save and return contact details
feat#AS-4756
=> feat(save and return contact details): save and return contact details

packages/forms-web-app/src/views/full-appeal/submit-appeal/task-list.njk
=> fix(button alignment): button alignment

packages/forms-web-app/src/controllers/full-appeal/submit-appeal/draft-statement-common-ground.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/expect-inquiry-last.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/how-decide-appeal.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/why-hearing.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/why-inquiry.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/draft-statement-common-ground.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/expect-inquiry-last.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/how-decide-appeal.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/why-hearing.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/why-inquiry.njk
=> feat(as-4758): update controllers for updated s+r component

packages/forms-web-app/src/views/full-appeal/submit-appeal/task-list.njk
=> fix(task list save and return): fixed button action

packages/forms-web-app/src/controllers/full-appeal/submit-appeal/health-safety-issues.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/health-safety-issues.njk
=> fix(health safety button): health safety button

packages/business-rules/src/schemas/full-appeal/insert.js, packages/business-rules/src/schemas/full-appeal/update.js, packages/business-rules/test/data/full-appeal.js, packages/forms-web-app/__tests__/unit/controllers/before-you-start/can-use-service.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/planning-application-number.test.js, packages/forms-web-app/__tests__/unit/controllers/submit-appeal/application-saved.test.js, packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/planning-application-number.test.js, packages/forms-web-app/src/controllers/before-you-start/can-use-service.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/planning-application-number.js, packages/forms-web-app/src/controllers/submit-appeal/application-saved.js, packages/forms-web-app/src/lib/choose-appropriate-application-number-page.js, packages/forms-web-app/src/lib/choose-appropriate-task-list.js, packages/forms-web-app/src/lib/extract-appeal-props.js, packages/forms-web-app/src/lib/full-appeal/views.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/planning-application-number.js, packages/forms-web-app/src/views/full-appeal/can-use-service.njk, packages/forms-web-app/src/views/full-appeal/check-your-answers.njk, packages/forms-web-app/src/views/full-appeal/prior-approval/can-use-service.njk, packages/forms-web-app/src/views/full-appeal/removal-or-variation-of-conditions/can-use-service.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/declaration-information.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/planning-application-number.njk, packages/forms-web-app/src/views/householder-planning/eligibility/can-use-service.njk, packages/forms-web-app/src/views/householder-planning/eligibility/prior-approval/can-use-service.njk, packages/forms-web-app/src/views/householder-planning/eligibility/removal-or-variation-of-conditions/can-use-service.njk
https://pins-ds.atlassian.net/browse/AS-4679
=> feat(as-4679): add what is your planning application number page

packages/business-rules/src/schemas/full-appeal/insert.test.js
=> fix(removed extra curly brackets): removed extra curly brackets

packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/email-confirmed.test.js, packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/email-confirmed.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/email-confirmed.js, packages/forms-web-app/src/lib/full-appeal/views.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/email-confirmed.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/email-confirmed.njk
https://pins-ds.atlassian.net/browse/AS-4682
Adds your email is confirmed page and routes it to "You’ll need to submit some documents with your appeal" page. The tests associated with the routes, controller, view and index have been created also.
=> feat(as-4682): adds email confirmed page and associated tests

packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/list-of-documents.js, packages/forms-web-app/src/lib/full-appeal/views.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/list-of-documents.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/list-of-documents.njk
https://pins-ds.atlassian.net/browse/AS-4687
Addition of the list of documents page
=> feat(as-4687): adding the list of documents page for full appeals

packages/appeals-service-api/__tests__/unit/controllers/save-and-return.test.js, packages/appeals-service-api/__tests__/unit/routes/save.test.js, packages/appeals-service-api/src/controllers/save.js, packages/appeals-service-api/src/lib/notify.js, packages/appeals-service-api/src/routes/save.js, packages/appeals-service-api/src/services/save-and-return.service.js, packages/business-rules/src/config.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/enter-code.test.js, packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js, packages/forms-web-app/__tests__/unit/lib/submit-appeal/views.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/enter-code.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/enter-code.js, packages/forms-web-app/src/lib/appeals-api-wrapper.js, packages/forms-web-app/src/lib/full-appeal/views.js, packages/forms-web-app/src/lib/submit-appeal/views.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/enter-code.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js, packages/forms-web-app/src/services/task-status/full-appeal/status-planning-application-documents-section.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/enter-code.njk
=> feat(enter code page): enter code page

packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/sent-another-link.test.js, packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js, packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/sent-another-link.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/sent-another-link.js, packages/forms-web-app/src/lib/full-appeal/views.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/sent-another-link.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/sent-another-link.njk
https://pins-ds.atlassian.net/browse/AS-4686
Addition of the sent another link page
=> feat(as-4686): adding sent another link page

packages/appeals-service-api/src/controllers/save.js, packages/appeals-service-api/src/lib/notify.js, packages/appeals-service-api/src/routes/save.js, packages/appeals-service-api/src/services/save-and-return.service.js, packages/forms-web-app/src/lib/appeals-api-wrapper.js
=> fix(enter code): enter code fixes

package.json, packages/appeals-service-api/__tests__/unit/controllers/save-and-return.test.js, packages/appeals-service-api/__tests__/unit/routes/save.test.js, packages/business-rules/jest.config.js, packages/business-rules/src/config.js, packages/business-rules/src/config.spec.js, packages/clamav-rest-server/__tests__/unit/lib/clamd.test.js, packages/clamav-rest-server/jest.config.js, packages/clamav-rest-server/src/lib/clamd.js, packages/horizon-functions/horizon-householder-appeal-publish/index.js, packages/horizon-functions/horizon-householder-appeal-publish/src/createContacts.js, packages/horizon-functions/horizon-householder-appeal-publish/tests/handler.spec.js
=> fix(fixed unit tests): fixed unit tests

packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/cannot-appeal.test.js, packages/forms-web-app/__tests__/unit/controllers/save-and-return.test.js, packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/cannot-appeal.js, packages/forms-web-app/src/controllers/save.js, packages/forms-web-app/src/lib/calculate-deadline.js, packages/forms-web-app/src/lib/full-appeal/views.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/cannot-appeal.js, packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/cannot-appeal.njk
https://pins-ds.atlassian.net/browse/AS-4808
=> feat(as-4808 deadline period): deadline period added

packages/appeals-service-api/__tests__/unit/lib/notify.test.js, packages/appeals-service-api/src/lib/notify.js
=> fix(email confirmation link): fixed email confirmation link

packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/sent-another-link.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/sent-another-link.js, packages/forms-web-app/src/views/full-appeal/submit-appeal/sent-another-link.njk
https://pins-ds.atlassian.net/browse/AS-5044
Small fix for typo which snuck in and missing appeal data within the controller
=> fix(as-5044): typo correction and adding missing data

packages/appeals-service-api/__tests__/unit/controllers/confirm-email.test.js, packages/appeals-service-api/__tests__/unit/services/confirm-email.service.test.js, packages/appeals-service-api/src/controllers/confirm-email.js, packages/appeals-service-api/src/services/confirm-email.service.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/email-address-confirmed.test.js, packages/forms-web-app/__tests__/unit/controllers/submit-appeal/link-expired.test.js, packages/forms-web-app/__tests__/unit/lib/is-token-expired.test.js, packages/forms-web-app/__tests__/unit/lib/submit-appeal/views.test.js, packages/forms-web-app/__tests__/unit/routes/submit-appeal/index.test.js, packages/forms-web-app/__tests__/unit/routes/submit-appeal/link-expired.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/email-address-confirmed.js, packages/forms-web-app/src/controllers/submit-appeal/link-expired.js, packages/forms-web-app/src/lib/appeals-api-wrapper.js, packages/forms-web-app/src/lib/is-token-expired.js, packages/forms-web-app/src/lib/submit-appeal/views.js, packages/forms-web-app/src/routes/submit-appeal/index.js, packages/forms-web-app/src/routes/submit-appeal/link-expired.js, packages/forms-web-app/src/views/submit-appeal/link-expired.njk
https://pins-ds.atlassian.net/browse/AS-4685
=> feat(as-4685): add link expired page and routing

packages/forms-web-app/src/views/appellant-submission/your-details.njk
https://pins-ds.atlassian.net/browse/AS-5144
=> fix(as-5144): remove unnecessary 'z'

packages/forms-web-app/src/views/appellant-submission/your-details.njk
https://pins-ds.atlassian.net/browse/AS-4993
Adds used email to hint text
=> feature(as-4993): changed the hint text

packages/forms-web-app/src/controllers/appellant-submission/site-access-safety.js, packages/forms-web-app/src/controllers/appellant-submission/site-ownership.js
https://pins-ds.atlassian.net/browse/AS-5128
=> fix(as-5128): fix save and return functionality

packages/appeals-service-api/src/services/appeal.service.js
https://pins-ds.atlassian.net/browse/AS-5154
=> fix(as-5154): remove check for non-existent field

packages/forms-web-app/src/views/appellant-submission/check-answers.njk, packages/forms-web-app/src/views/appellant-submission/submission-information.njk
https://pins-ds.atlassian.net/browse/AS-5152
addition of the planning number to the pdf, and removal from the cya partial
=> feat(as-5152): adding planning number to pdf, removing from cya

packages/forms-web-app/__tests__/unit/controllers/appeal-householder-decision/cannot-appeal.test.js, packages/forms-web-app/__tests__/unit/lib/views.test.js, packages/forms-web-app/__tests__/unit/routes/appeal-householder-decision/cannot-appeal.test.js, packages/forms-web-app/src/controllers/appeal-householder-decision/cannot-appeal.js, packages/forms-web-app/src/lib/views.js, packages/forms-web-app/src/routes/appeal-householder-decision/cannot-appeal.js, packages/forms-web-app/src/routes/appeal-householder-decision/index.js, packages/forms-web-app/src/views/appeal-householder-decision/cannot-appeal.njk
https://pins-ds.atlassian.net/browse/AS-5146
=> feat(as-5146): cannot appeal page feature

packages/forms-web-app/__tests__/unit/controllers/appeal-householder-decision/code-expired.test.js, packages/forms-web-app/__tests__/unit/routes/appeal-householder-decision/code-expired.test.js, packages/forms-web-app/__tests__/unit/routes/appeal-householder-decision/index.test.js, packages/forms-web-app/src/controllers/appeal-householder-decision/code-expired.js, packages/forms-web-app/src/routes/appeal-householder-decision/code-expired.js, packages/forms-web-app/src/routes/appeal-householder-decision/index.js, packages/forms-web-app/src/views/appeal-householder-decision/code-expired.njk
https://pins-ds.atlassian.net/browse/AS-5145
Adds code expired page for HAS
=> feature(as-5145): adds code expired page and associated tests for householder appeals

packages/forms-web-app/src/views/appeal-householder-decision/enter-code.njk
https://pins-ds.atlassian.net/browse/AS-5212
=> fix(as-5212 removed back link): as-5212 removed back link

packages/appeals-service-api/data/lpa-trialists.json
https://pins-ds.atlassian.net/browse/AS-5029
=> feat(as-5029): remove harrogate e60000059 from beta

packages/business-rules/src/config.js, packages/business-rules/src/validation/appeal/decision-date/is-within-decision-date-expiry-period.test.js, packages/forms-web-app/__tests__/unit/controllers/before-you-start/can-use-service.test.js, packages/forms-web-app/__tests__/unit/controllers/eligibility/decision-date.test.js, packages/forms-web-app/src/controllers/appeal-householder-decision/cannot-appeal.js, packages/forms-web-app/src/controllers/full-appeal/out-of-time-shutter-page.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/cannot-appeal.js
https://pins-ds.atlassian.net/browse/AS-5049
Updated the decision deadline calculation logic for Householder Planning, so that it matches the business guidelines.
=> feat(as-5049): as-5049 implemented deadline calculation for HAS

packages/forms-web-app/src/views/appeal-householder-decision/link-expired.njk
https://pins-ds.atlassian.net/browse/AS-5239
=> fix(as-5239 removed back link): as-5239 removed back link

packages/forms-web-app/__tests__/unit/controllers/appeal-householder-decision/confirm-email-address.test.js, packages/forms-web-app/src/controllers/appeal-householder-decision/confirm-email-address.js, packages/forms-web-app/src/views/appeal-householder-decision/confirm-email-address.njk
https://pins-ds.atlassian.net/browse/AS-5131
=> fix(as-5131): fix resend email link to correct url

packages/forms-web-app/src/views/appeal-householder-decision/email-address-confirmed.njk
https://pins-ds.atlassian.net/browse/AS-5130
Changed title from 'Your email address is confirmed - Appeal a householder planning decisions -
GOV.UK' to 'Your email address is confirmed - Appeal a planning decision - GOV.UK'
=> fix: updates page title

packages/forms-web-app/src/views/appellant-submission/check-answers.njk
https://pins-ds.atlassian.net/browse/AS-5204
=> fix(as-5204): remove planning application number from cya page (has)

packages/forms-web-app/src/views/appellant-submission/submission-information.njk
https://pins-ds.atlassian.net/browse/AS-5226
=> fix(as-5226): update email field on HAS PDF

packages/forms-web-app/src/views/appellant-submission/submission-information.njk
https://pins-ds.atlassian.net/browse/AS-5240
=> fix(as-5240): amend title of generated pdf for householder appeal

packages/forms-web-app/src/views/appeal-householder-decision/application-saved.njk, packages/forms-web-app/src/views/appeal-householder-decision/cannot-appeal.njk, packages/forms-web-app/src/views/appeal-householder-decision/confirm-email-address.njk, packages/forms-web-app/src/views/appeal-householder-decision/email-address.njk, packages/forms-web-app/src/views/appeal-householder-decision/enter-code.njk, packages/forms-web-app/src/views/appeal-householder-decision/link-expired.njk, packages/forms-web-app/src/views/appeal-householder-decision/list-of-documents.njk, packages/forms-web-app/src/views/appeal-householder-decision/planning-application-number.njk
https://pins-ds.atlassian.net/browse/AS-5198
Changed feedback form link for householder pages
=> feat(as-5198): changes feedback form to householder

packages/forms-web-app/src/views/accessibility-statement/accessibility-statement.njk
https://pins-ds.atlassian.net/browse/AS-5350
https://pins-ds.atlassian.net/browse/AS-5351
=> fix(fixed two bugs 5351, 5350): fixed two bugs 5351, 5350

packages/appeals-service-api/__tests__/unit/services/lpa.service.test.js, packages/appeals-service-api/data/lpa-list.csv, packages/appeals-service-api/src/services/lpa.service.js, packages/forms-web-app/src/services/department.service.js
=> feat(additional fields lpa csv): added additional fields to Lpa csv

packages/appeals-service-api/data/lpa-list.csv, packages/appeals-service-api/src/services/lpa.service.js
=> fix(lpa email fix): lpa email fix

packages/appeals-service-api/src/controllers/local-planning-authorities.js, packages/appeals-service-api/src/services/lpa.service.js
=> fix(fixed get lpa param): fixed get lpa param

packages/document-service-api/src/configuration/featureFlag.js
=> feat(as-5031): amend logger to display bool for feature flag

packages/document-service-api/src/configuration/featureFlag.js
=> feat(as-5031): get feature flag cache to work

packages/forms-web-app/src/mappers/document-mapper.js, packages/horizon-functions/horizon-add-document/index.js, packages/horizon-functions/horizon-householder-appeal-publish/src/logic/addDocument.js
=> fix(as-5031): fix mapper and horizon azure functions, and add logs

packages/business-rules/src/schemas/full-appeal/appeal-schema/sections/appeal-decision/appeal-decision-validation.js, packages/business-rules/src/schemas/full-appeal/appeal-schema/sections/appeal-documents/appeal-documents-validation.js, packages/business-rules/src/schemas/full-appeal/appeal-schema/sections/appeal-submission/appeal-submission-validation.js, packages/business-rules/src/schemas/full-appeal/appeal-schema/sections/planning-application-documents/planning-application-documents-validation.js
=> feat(as-5031): amend validation rules

packages/appeals-service-api/src/validators/appeals/appeals.validator.js
=> feat(as-5031): restore validation

packages/horizon-functions/horizon-householder-appeal-publish/index.js
=> fix(as-5031): type correction in planning obligations casing

packages/platform-feature-tests/cypress/e2e/submit-full-appeal.cy.js, packages/platform-feature-tests/cypress/support/flows/sections/initialiseFullAppeal.js
=> fix(as-5459): add Horizon-specifics, and correct day on date section

packages/forms-web-app/src/views/full-appeal/submit-appeal/enter-code.njk
=> fix(as-5385): remove backlink from page

packages/appeals-service-api/__tests__/developer/developer.test.js, packages/appeals-service-api/__tests__/unit/controllers/save-and-return.test.js, packages/appeals-service-api/__tests__/unit/services/confirm-email.service.test.js, packages/appeals-service-api/__tests__/unit/services/save-and-return.service.test.js, packages/appeals-service-api/jest.config.js, packages/appeals-service-api/src/routes/appeals.js, packages/appeals-service-api/src/services/appeal.service.js
=> fix(as-5031): fix enter code page error

packages/appeals-service-api/src/controllers/save.js, packages/appeals-service-api/src/lib/notify.js, packages/appeals-service-api/src/services/appeal.service.js, packages/appeals-service-api/src/services/save-and-return.service.js
=> fix(as-5031): add logging

packages/appeals-service-api/src/lib/notify.js, packages/appeals-service-api/src/services/appeal.service.js, packages/appeals-service-api/src/services/save-and-return.service.js
=> fix(as-5031): remove bug fix logs

packages/forms-web-app/src/controllers/appeal-householder-decision/application-saved.js
=> fix(as-5031): fix require causing save and return error

packages/appeals-service-api/src/services/appeal.service.js, packages/horizon-functions/horizon-householder-appeal-publish/index.js
=> fix(as-5031): fix appeal ID being undefined in Horizon function

README.md, packages/appeals-service-api/package.json
=> fix(as-5031): move pino-pretty into dependencies, update readme

packages/forms-web-app/src/views/appeal-householder-decision/email-address.njk, packages/forms-web-app/src/views/appellant-submission/your-details.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/contact-details.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/email-address.njk, packages/forms-web-app/src/views/submit-appeal/enter-appeal-details.njk, packages/lpa-questionnaire-web-app/src/views/authentication/your-email.njk
=> fix(as-4920): adds autocomplete attribute to autofill components

packages/forms-web-app/src/views/full-appeal/submit-appeal/application-certificates-included.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/new-documents.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/planning-obligation-planned.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/proposed-development-changed.njk, packages/forms-web-app/src/views/full-appeal/type-of-planning-application.njk, packages/forms-web-app/src/views/householder-planning/eligibility/claiming-costs-householder.njk, packages/forms-web-app/src/views/householder-planning/eligibility/listed-building-householder.njk
=> fix(as-4917): fixed semantic markup for screen-reader

README.md, packages/appeals-service-api/__tests__/developer/developer.test.js, packages/appeals-service-api/__tests__/developer/external-dependencies/rest-apis/expectations/horizon/create-contact-request-body.ts, packages/appeals-service-api/__tests__/developer/external-dependencies/rest-apis/expectations/request-body-expectation.ts, packages/appeals-service-api/__tests__/developer/external-dependencies/rest-apis/interactions/horizon-interaction.ts, packages/appeals-service-api/__tests__/developer/external-dependencies/rest-apis/interactions/interaction.ts, packages/appeals-service-api/__tests__/developer/external-dependencies/rest-apis/json-path-expression.ts, packages/appeals-service-api/__tests__/developer/external-dependencies/rest-apis/mocked-external-apis.ts, packages/appeals-service-api/__tests__/developer/fixtures/appeals.ts, packages/appeals-service-api/__tests__/developer/utils/horizon-integration-input-condition.js, packages/appeals-service-api/src/gateway/horizon-gateway.js, packages/appeals-service-api/src/mappers/horizon-mapper.js, packages/appeals-service-api/src/services/appeal.service.js, packages/appeals-service-api/src/services/horizon.service.js, packages/appeals-service-api/src/value-objects/appeal/organisation-names.value.js, packages/forms-web-app/src/lib/appeals-api-wrapper.js
=> As 5031 fix org creation

packages/forms-web-app/src/views/full-appeal/submit-appeal/proposed-development-changed.njk
missing comma on proposed-development-changed.njk caused the page to fail to build
https://pins-ds.atlassian.net/browse/AS-5694
=> fix(as-5694): typo broke page rendering

packages/appeals-service-api/__tests__/developer/developer.test.js, packages/appeals-service-api/src/gateway/horizon-gateway.js, packages/appeals-service-api/src/mappers/horizon-mapper.js, packages/appeals-service-api/src/services/appeal.service.js, packages/appeals-service-api/src/services/horizon.service.js, packages/appeals-service-api/src/value-objects/appeal/contact-details.value.js
=> refactor(as-5031): tidy-up `create contact in Horizon` logic in back-end

packages/forms-web-app/src/lib/appeals-api-wrapper.js
=> fix(as-5031): fix logging for back office document submission

packages/forms-web-app/src/views/full-appeal/submit-appeal/agricultural-holding.njk
https://pins-ds.atlassian.net/browse/AS-5625
=> fix(as-5625): add nunjucks code to render pageTitle to page view

azure-pipelines-build.yml, azure-pipelines-deploy.yml
=> refactor(removed unused lpa build step): removed unused lpa build

azure-pipelines-build.yml
=> chore(skipping less frequent builds): skipping less frequent builds

packages/appeals-service-api/data/lpa-list.csv
https://pins-ds.atlassian.net/browse/AS-5718
=> fix(as-5718): add system test borough council horizon lpa code

packages/forms-web-app/src/controllers/full-appeal/submit-appeal/declaration.js
=> fix(appeal submission timeout): appeal submission

packages/forms-web-app/src/controllers/full-appeal/submit-appeal/declaration.js
https://pins-ds.atlassian.net/browse/AS-5746
=> fix(as-5746): remove req.session.appeal update

packages/appeals-service-api/src/routes/back-office.js
https://pins-ds.atlassian.net/browse/AS-5746
=> fix(as-5746): return empty json

packages/appeals-service-api/src/gateway/horizon-gateway.js, packages/appeals-service-api/src/mappers/horizon-mapper.js
=> refactor: adds more logging for debug

packages/appeals-service-api/src/mappers/horizon-mapper.js
=> fix(as-5721): attempt to fix debug logging

packages/forms-web-app/__tests__/unit/validators/appellant-submission/site-location.test.js, packages/forms-web-app/__tests__/unit/validators/full-appeal/appeal-site-address.test.js, packages/forms-web-app/src/validators/appellant-submission/site-location.js, packages/forms-web-app/src/validators/appellant-submission/who-are-you.js, packages/forms-web-app/src/validators/full-appeal/appeal-site-address.js
https://pins-ds.atlassian.net/browse/AS-5702
=> fix(as-5702): remove escape() validation as unnecessary

packages/forms-web-app/src/views/appellant-submission/check-answers.njk, packages/forms-web-app/src/views/appellant-submission/submission-information.njk
=> fix: prepend some answers with yes or no

packages/appeals-service-api/src/controllers/appeals-for-submission-to-horizon-scheduler.js
=> fix(config.js): fixed misnamed config variable call in scheduler

docker-compose.yml, packages/appeals-service-api/src/controllers/appeals-for-submission-to-horizon-scheduler.js
=> fix: fix trigger for cron job

packages/appeals-service-api/src/configuration/featureFlag.js
https://pins-ds.atlassian.net/browse/AS-5777
=> fix: featureflag to allow empty array

packages/forms-web-app/src/views/accessibility-statement/accessibility-statement.njk
=> feat: update accessibility statement

packages/forms-web-app/src/lib/client-side/index.js, packages/forms-web-app/src/views/components/multi-file-upload/template.njk
https://pins-ds.atlassian.net/browse/AS-5335
=> refactor(as-5335): comment out new multi file upload js to revert component to previous state

packages/forms-web-app/src/controllers/appellant-submission/supporting-documents.js, packages/forms-web-app/src/lib/client-side/components/multi-file-upload.js, packages/forms-web-app/src/lib/client-side/index.js, packages/forms-web-app/src/views/components/multi-file-upload/template.njk
https://pins-ds.atlassian.net/browse/AS-5335
=> fix(as-5335): update multi file upload to allow user to remove uploaded files

packages/document-service-api/src/configuration/featureFlag.js
https://pins-ds.atlassian.net/browse/AS-5807
=> fix(as-5807): updating featureflag behaviour to align cross service

packages/forms-web-app/__tests__/unit/routes/final-comment/final-comment.test.js, packages/forms-web-app/src/config.js, packages/forms-web-app/src/controllers/final-comment/final-comment.js, packages/forms-web-app/src/lib/views.js, packages/forms-web-app/src/routes/final-comment/final-comment.js, packages/forms-web-app/src/routes/full-appeal/submit-final-comment/index.js, packages/forms-web-app/src/routes/index.js, packages/forms-web-app/src/validators/common/appeal-statement.js, packages/forms-web-app/src/validators/common/does-not-include-sensitive-information.js, packages/forms-web-app/src/validators/final-comment/final-comment.js, packages/forms-web-app/src/views/final-comment/final-comment.njk, packages/forms-web-app/src/views/includes/sensitive-information.njk
https://pins-ds.atlassian.net/browse/AS-5748
=> feat(as-5748): add final comments page

packages/forms-web-app/src/views/error/unhandled-exception.njk
https://pins-ds.atlassian.net/browse/AS-5379
=> AS-5379: content for service unavailable

packages/forms-web-app/__tests__/unit/controllers/final-comment/comments-question.test.js, packages/forms-web-app/__tests__/unit/routes/final-comment/comments-question.test.js, packages/forms-web-app/src/controllers/final-comment/comments-question.js, packages/forms-web-app/src/lib/views.js, packages/forms-web-app/src/routes/final-comment/comments-question.js, packages/forms-web-app/src/routes/full-appeal/submit-final-comment/index.js, packages/forms-web-app/src/routes/index.js, packages/forms-web-app/src/views/final-comment/comments-question.njk
https://pins-ds.atlassian.net/browse/AS-5769
=> feat(as-5769): add route, controller, view for comments-question page

packages/document-service-api/README.md
=> feat(readme): updated document service API readme

packages/forms-web-app/src/controllers/final-comment/final-comment-submitted.js, packages/forms-web-app/src/lib/views.js, packages/forms-web-app/src/routes/final-comment/final-comment-submitted.js, packages/forms-web-app/src/routes/full-appeal/submit-final-comment/index.js, packages/forms-web-app/src/views/full-appeal/submit-final-comment/final-comment-submitted.njk
https://pins-ds.atlassian.net/browse/AS-5752
=> feat: add route and njk template for a final comment submitted page

packages/common/package-lock.json, packages/common/package.json
https://pins-ds.atlassian.net/browse/AS-5815
=> fix(as-5815): updating common to ensure depandancies are up to date

packages/appeals-service-api/src/configuration/featureFlag.js, packages/document-service-api/src/configuration/featureFlag.js
https://pins-ds.atlassian.net/browse/AS-5815
=> fix(as-5815): updating erroneous logger imports

packages/forms-web-app/__tests__/unit/controllers/final-comment/appeal-closed-for-comment.test.js, packages/forms-web-app/__tests__/unit/routes/final-comment/appeal-closed-for-comment.test.js, packages/forms-web-app/src/controllers/final-comment/appeal-closed-for-comment.js, packages/forms-web-app/src/lib/views.js, packages/forms-web-app/src/routes/final-comment/appeal-closed-for-comment.js, packages/forms-web-app/src/routes/full-appeal/submit-final-comment/index.js, packages/forms-web-app/src/views/full-appeal/submit-final-comment/appeal-closed-for-comment.njk
as-5753
https://pins-ds.atlassian.net/browse/AS-5753
=> feat: appeal closed for comment page

packages/appeals-service-api/src/mappers/horizon-mapper.js
https://pins-ds.atlassian.net/browse/AS-5811
Sanitise org and contact name
=> fix: sanitise org and contact names

packages/forms-web-app/src/views/full-appeal/submit-final-comment/documents-check.njk
https://pins-ds.atlassian.net/browse/AS-5855
=> fix(as-5855): fix incorrect title content on final comment document check page

packages/appeals-service-api/__tests__/unit/controllers/token.test.js, packages/appeals-service-api/__tests__/unit/services/token.service.test.js, packages/appeals-service-api/src/controllers/token.js, packages/appeals-service-api/src/services/token.service.js
https://pins-ds.atlassian.net/browse/AS-5872
=> fix(as-5872): fix bug that sent secure code email twice

packages/forms-web-app/src/views/before-you-start/first-page.njk
https://pins-ds.atlassian.net/browse/AS-5878
=> feat(as-5878): remove feedback link from before-you-start page

packages/appeals-service-api/data/lpa-list.csv
=> feat(as-5893): update lpa data

packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/application-certificates-included.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/design-access-statement-submitted.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/new-documents.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/new-plans-drawings.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/planning-obligation-planned.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/planning-obligation-status.test.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/application-certificates-included.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/design-access-statement-submitted.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/new-documents.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/new-plans-drawings.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/planning-obligation-planned.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/planning-obligation-status.js
=> fix(as-5910): remove uploaded files depending on changes to user choices

packages/forms-web-app/__tests__/unit/controllers/final-comment/upload-documents.test.js, packages/forms-web-app/src/controllers/final-comment/upload-documents.js, packages/forms-web-app/src/views/full-appeal/submit-final-comment/upload-documents.njk
https://pins-ds.atlassian.net/browse/AS-5930
=> refactor(as-5930): refactor upload-documents for consistency

packages/forms-web-app/__tests__/unit/controllers/final-comment/input-code.test.js, packages/forms-web-app/src/controllers/final-comment/input-code.js, packages/forms-web-app/src/lib/views.js, packages/forms-web-app/src/routes/final-comment/code-expired.js, packages/forms-web-app/src/routes/final-comment/input-code.js, packages/forms-web-app/src/routes/full-appeal/submit-final-comment/index.js
=> feat(as-5929): adding expired code screen and functionality

packages/appeals-service-api/src/gateway/horizon-gateway.js, packages/appeals-service-api/src/services/final-comments.service.js
=> feat(as-5892): add debug logs

packages/appeals-service-api/__tests__/developer/lpas.test.js, packages/appeals-service-api/__tests__/developer/users.test.js, packages/appeals-service-api/src/controllers/local-planning-authorities.js, packages/appeals-service-api/src/routes/local-planning-authorities.js, packages/appeals-service-api/src/services/lpa.service.js, packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/service-invite.test.js, packages/forms-web-app/__tests__/unit/lib/appeals-api-wrapper.test.js, packages/forms-web-app/src/controllers/lpa-dashboard/service-invite.js, packages/forms-web-app/src/lib/appeals-api-wrapper.js, packages/forms-web-app/src/lib/views.js, packages/forms-web-app/src/routes/lpa-dashboard/lpa-dashboard.js
https://pins-ds.atlassian.net/browse/AS-5837
=> feat(as-5837): add invite page for lpa admin users

packages/forms-web-app/src/routes/lpa-dashboard/code-expired.js, packages/forms-web-app/src/routes/lpa-dashboard/index.js
https://pins-ds.atlassian.net/browse/AS-5896
_**This should be merged after 5882**_
=> feat(as-5896): added expired code route, routing to align with 5822

packages/appeals-service-api/data/lpa-list.csv
https://pins-ds.atlassian.net/browse/AS-5980
=> feat(as-5980): updated july lpa list

packages/forms-web-app/__tests__/unit/controllers/common/request-new-code.test.js, packages/forms-web-app/__tests__/unit/views/lpa/request-new-code.njk.test.js, packages/forms-web-app/src/controllers/common/request-new-code.js, packages/forms-web-app/src/routes/lpa-dashboard/lpa-dashboard.js, packages/forms-web-app/src/views/manage-appeals/request-new-code.njk
AS-5883
https://pins-ds.atlassian.net/browse/AS-5883
Added route, view and controller (and associated unit tests) for the LPA Request New Code story.
=> feat(lpa request new code): added new feature to allow LPAs to Request a New Code

packages/forms-web-app/__tests__/unit/controllers/common/enter-code.test.js, packages/forms-web-app/__tests__/unit/controllers/common/need-new-code.test.js, packages/forms-web-app/src/controllers/common/enter-code.js, packages/forms-web-app/src/controllers/common/need-new-code.js
https://pins-ds.atlassian.net/browse/AS-5914
=> feat(as-5914): lPA need-new-code sends new token to user

packages/forms-web-app/src/controllers/common/request-new-code.js, packages/forms-web-app/src/routes/lpa-dashboard/request-new-code.js
https://pins-ds.atlassian.net/browse/AS-5883
=> fix(as-5883): use correct controllers for LPA request code routes

packages/appeals-service-api/__tests__/unit/controllers/token.test.js, packages/appeals-service-api/src/controllers/token.js, packages/forms-web-app/__tests__/unit/lib/is-token-valid.test.js, packages/forms-web-app/src/lib/appeals-api-wrapper.js, packages/forms-web-app/src/lib/is-token-valid.js
=> fix(as-5973): remove createOrUpdateTokenDocument call in token API

packages/forms-web-app/__tests__/unit/controllers/common/enter-code.test.js, packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/your-appeals.test.js, packages/forms-web-app/__tests__/unit/routes/lpa/index.test.js, packages/forms-web-app/__tests__/unit/routes/lpa/your-appeals.test.js, packages/forms-web-app/__tests__/unit/views/lpa/your-appeals.test.js, packages/forms-web-app/src/controllers/lpa-dashboard/your-appeals.js, packages/forms-web-app/src/lib/views.js, packages/forms-web-app/src/routes/lpa-dashboard/index.js, packages/forms-web-app/src/routes/lpa-dashboard/your-appeals.js, packages/forms-web-app/src/views/manage-appeals/your-appeals.njk
https://pins-ds.atlassian.net/browse/AAPD-4
Base your-appeals page
=> feat(aapd-4): add base your-appeals page

packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/add-remove-users.test.js, packages/forms-web-app/__tests__/unit/routes/lpa/add-remove-users.test.js, packages/forms-web-app/__tests__/unit/views/lpa/add-remove-users.njk.test.js, packages/forms-web-app/src/controllers/lpa-dashboard/add-remove-users.js, packages/forms-web-app/src/lib/views.js, packages/forms-web-app/src/routes/lpa-dashboard/add-remove-users.js, packages/forms-web-app/src/routes/lpa-dashboard/index.js, packages/forms-web-app/src/views/manage-appeals/add-remove-users.njk
=> feat(aapd-6): add add-remove-users page

packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/email-address.test.js, packages/forms-web-app/src/controllers/lpa-dashboard/email-address.js
https://pins-ds.atlassian.net/browse/AAPD-8
=> feat(aapd-8): display domain of lpa based on logged in user

packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/email-address.test.js, packages/forms-web-app/__tests__/unit/routes/lpa/email-address.test.js, packages/forms-web-app/__tests__/unit/validators/common/lpa-user-email.test.js, packages/forms-web-app/src/controllers/lpa-dashboard/email-address.js, packages/forms-web-app/src/routes/lpa-dashboard/email-address.js, packages/forms-web-app/src/validators/common/lpa-user-email.js
https://pins-ds.atlassian.net/browse/AAPD-9
=> feat(aapd-9): add empty email validation to add lpa user

packages/appeals-service-api/__tests__/routerMock.js, packages/appeals-service-api/__tests__/unit/controllers/user.test.js, packages/appeals-service-api/__tests__/unit/routes/users.test.js, packages/appeals-service-api/__tests__/unit/services/user.service.test.js, packages/appeals-service-api/src/controllers/user.js, packages/appeals-service-api/src/routes/users.js, packages/appeals-service-api/src/services/user.service.js, packages/forms-web-app/__tests__/unit/controllers/common/enter-code.test.js, packages/forms-web-app/__tests__/unit/services/lpa-user.service.test.js, packages/forms-web-app/src/controllers/common/enter-code.js, packages/forms-web-app/src/lib/appeals-api-wrapper.js, packages/forms-web-app/src/services/lpa-user.service.js
https://pins-ds.atlassian.net/browse/AAPD-36
Change status of LPA User from added to confirmed on enter-code
=> Feature/aapd 36 dbstatus=confirmed

packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/confirm-remove-user.test.js, packages/forms-web-app/__tests__/unit/routes/lpa/confirm-remove-user.test.js, packages/forms-web-app/__tests__/unit/views/lpa/confirm-remove-user.njk.test.js, packages/forms-web-app/src/controllers/lpa-dashboard/confirm-remove-user.js, packages/forms-web-app/src/lib/views.js, packages/forms-web-app/src/routes/lpa-dashboard/confirm-remove-user.js, packages/forms-web-app/src/routes/lpa-dashboard/index.js, packages/forms-web-app/src/views/manage-appeals/confirm-remove-user.njk
https://pins-ds.atlassian.net/browse/aapd-14
=> feat(aapd-14): add confirm-remove-users page

packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/add-remove-users.test.js, packages/forms-web-app/src/controllers/lpa-dashboard/add-remove-users.js, packages/forms-web-app/src/controllers/lpa-dashboard/confirm-add-user.js, packages/forms-web-app/src/views/manage-appeals/add-remove-users.njk
=> feat(aapd-12): user added success banner

packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/add-remove-users.test.js, packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/confirm-remove-user.test.js, packages/forms-web-app/src/controllers/lpa-dashboard/add-remove-users.js, packages/forms-web-app/src/controllers/lpa-dashboard/confirm-remove-user.js, packages/forms-web-app/src/views/manage-appeals/add-remove-users.njk
https://pins-ds.atlassian.net/browse/aapd-15
=> feat(aadd-15): add success message for removing user

packages/appeals-service-api/__tests__/developer/users.test.js, packages/appeals-service-api/src/controllers/user.js, packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/add-remove-users.test.js, packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/confirm-remove-user.test.js, packages/forms-web-app/__tests__/unit/lib/appeals-api-wrapper.test.js, packages/forms-web-app/__tests__/unit/middleware/lpa-dashboard/require-user.test.js, packages/forms-web-app/src/controllers/lpa-dashboard/add-remove-users.js, packages/forms-web-app/src/controllers/lpa-dashboard/confirm-remove-user.js, packages/forms-web-app/src/lib/appeals-api-wrapper.js, packages/forms-web-app/src/views/manage-appeals/add-remove-users.njk, packages/forms-web-app/src/views/manage-appeals/confirm-remove-user.njk
https://pins-ds.atlassian.net/browse/aapd-16
=> feat(aapd-16): confirm remove user

packages/appeals-service-api/__tests__/unit/services/user.service.test.js, packages/appeals-service-api/src/services/user.service.js
=> fix(user-service): user.enabled replaced with status field

packages/appeals-service-api/__tests__/developer/lpa-dashboard-appeals.test.js, packages/appeals-service-api/__tests__/unit/controllers/lpa-dashboard-appeals.test.js, packages/appeals-service-api/__tests__/unit/services/lpa-dashboard-appeals.service.test.js, packages/appeals-service-api/__tests__/unit/services/user.service.test.js, packages/appeals-service-api/src/controllers/lpa-dashboard-appeals.js, packages/appeals-service-api/src/errors/apiError.js, packages/appeals-service-api/src/routes/index.js, packages/appeals-service-api/src/routes/lpa-dashboard-appeals.js, packages/appeals-service-api/src/services/lpa-dashboard-appeals.service.js, packages/appeals-service-api/src/services/user.service.js, packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/your-appeals.test.js, packages/forms-web-app/src/controllers/lpa-dashboard/your-appeals.js, packages/forms-web-app/src/lib/appeals-api-wrapper.js
=> feat(aapd-70): retrieve appeals case data from db based on lpa code

packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/appeal-details.test.js, packages/forms-web-app/__tests__/unit/routes/lpa/appeal-details.test.js, packages/forms-web-app/src/controllers/lpa-dashboard/appeal-details.js, packages/forms-web-app/src/lib/views.js, packages/forms-web-app/src/routes/lpa-dashboard/appeal-details.js, packages/forms-web-app/src/routes/lpa-dashboard/index.js, packages/forms-web-app/src/views/manage-appeals/appeal-details.njk
https://pins-ds.atlassian.net/browse/AAPD-47-appeal-details-page
Added route, controller and view for appeal-details
=> feat(frontend): added route, controller and view for appeal-details

packages/appeals-service-api/__tests__/developer/developer.test.js, packages/appeals-service-api/__tests__/developer/external-dependencies/rest-apis/mocked-external-apis.js, packages/appeals-service-api/__tests__/developer/globalSetup.js
Reducing the amount of logging in developer/integration tests to make failed tests easier to find
Logging can be added back in as needed if debugging is required
=> refactor(developer-tests): reduce logging noise

packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/appeal-details.test.js, packages/forms-web-app/src/controllers/lpa-dashboard/appeal-details.js, packages/forms-web-app/src/lib/appeals-api-wrapper.js, packages/forms-web-app/src/views/manage-appeals/appeal-details.njk
Appeal details top of page banner
https://pins-ds.atlassian.net/browse/AAPD-48
Appeal details top banner
=> feat(front end): /appeal-details: banner FE

packages/forms-web-app/src/controllers/common/enter-code.js
=> fix(enter-code): add missing await to test login createUser call

packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/appeal-details.test.js, packages/forms-web-app/__tests__/unit/views/lpa/appeal-details.njk.test.js, packages/forms-web-app/src/controllers/lpa-dashboard/appeal-details.js, packages/forms-web-app/src/lib/appeals-api-wrapper.js, packages/forms-web-app/src/views/manage-appeals/appeal-details.njk
https://pins-ds.atlassian.net/browse/AAPD-50
appeal-details-appeal-headlines
=> feat(front end): /appeal-details: appeal headlines

packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/your-appeals.test.js, packages/forms-web-app/src/controllers/lpa-dashboard/your-appeals.js, packages/forms-web-app/src/lib/views.js, packages/forms-web-app/src/views/manage-appeals/your-appeals.njk
=> feat(aapd-42): add questionnaire hyperlink in rows on to do column

packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/your-appeals.test.js, packages/forms-web-app/__tests__/unit/lib/calculate-due-in-days.test.js, packages/forms-web-app/src/controllers/lpa-dashboard/your-appeals.js, packages/forms-web-app/src/lib/calculate-due-in-days.js, packages/forms-web-app/src/views/manage-appeals/your-appeals.njk
=> feat(aapd-41): calculate and display 'due in' days

packages/appeals-service-api/src/repositories/document-metadata-repository.js, packages/appeals-service-api/src/repositories/mongo-repository.js, packages/appeals-service-api/src/routes/documentMetadata.js, packages/appeals-service-api/src/routes/index.js, packages/appeals-service-api/src/services/document-metadata.service.js
https://pins-ds.atlassian.net/browse/AAPD-130
Document metadata repository
=> feat(appeals-service-api): documentMetadata repository

commitlint.config.js, package-lock.json, package.json
Support for custom commit prompt messages
AAPD-147
https://pins-ds.atlassian.net/browse/AAPD-147
Allows support for custom commitizen prompts and messages
=> chore(na): custom commit prompts

packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/appeal-details.test.js, packages/forms-web-app/src/views/manage-appeals/appeal-details.njk
This should be merged after https://github.com/Planning-Inspectorate/appeal-planning-decision/pull/2966 AAPD-50 as this adds builds on this ticket. 
=> feat(AAPD-51): addition of appeal submission table

packages/appeals-service-api/data/lpa-list.csv
https://pins-ds.atlassian.net/browse/AAPD-149
=> feat(AAPD-149): updating email for somerset west

packages/forms-web-app/__tests__/unit/views/lpa/appeal-details.njk.test.js, packages/forms-web-app/src/views/manage-appeals/appeal-details.njk
https://pins-ds.atlassian.net/browse/AAPD-159
=> feat(AAPD-159): appeal details view refactor

packages/common/src/utils.js, packages/common/src/utils.test.js, packages/forms-web-app/__tests__/unit/controllers/appellant-submission/appeal-statement.test.js, packages/forms-web-app/__tests__/unit/controllers/appellant-submission/upload-application.test.js, packages/forms-web-app/__tests__/unit/controllers/appellant-submission/upload-decision.test.js, packages/forms-web-app/__tests__/unit/controllers/common/appeal-multi-file-upload.test.js, packages/forms-web-app/__tests__/unit/controllers/final-comment/upload-documents.test.js, packages/forms-web-app/src/controllers/appellant-submission/appeal-statement.js, packages/forms-web-app/src/controllers/appellant-submission/supporting-documents.js, packages/forms-web-app/src/controllers/appellant-submission/upload-application.js, packages/forms-web-app/src/controllers/appellant-submission/upload-decision.js, packages/forms-web-app/src/controllers/common/appeal-multi-file-upload.js, packages/forms-web-app/src/controllers/final-comment/upload-documents.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/appeal-statement.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/application-form.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/certificates.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/decision-letter.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/design-access-statement.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/draft-statement-common-ground.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/letter-confirming-application.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/original-decision-notice.js, packages/forms-web-app/src/lib/documents-api-wrapper.js, packages/forms-web-app/src/mappers/document-mapper.js
https://pins-ds.atlassian.net/browse/AAPD-144
=> fix(aapd-144): sanitize filenames on upload

packages/forms-web-app/__tests__/unit/routes/appellant-submission/appeal-statement.test.js, packages/forms-web-app/src/routes/appellant-submission/appeal-statement.js
=> fix(aapd-165): add taskName and sectionName to router

packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/appeal-details.test.js, packages/forms-web-app/src/controllers/lpa-dashboard/appeal-details.js, packages/forms-web-app/src/views/manage-appeals/appeal-details.njk
https://pins-ds.atlassian.net/browse/AAPD-54
=> feat(AAPD-54): addition of appeal statement row in submission table

packages/forms-web-app/__tests__/unit/views/lpa/your-appeals.test.js, packages/forms-web-app/src/views/manage-appeals/appeal-details.njk, packages/forms-web-app/src/views/manage-appeals/your-appeals.njk
=> fix(aapd-173): content fixes

packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/appeal-details.test.js, packages/forms-web-app/src/controllers/lpa-dashboard/appeal-details.js, packages/forms-web-app/src/views/manage-appeals/appeal-details.njk
https://pins-ds.atlassian.net/browse/aapd-60
=> feat(aapd-60): show appeal due on appeal detail page

packages/forms-web-app/src/dynamic-forms/dynamic-components/task-list/index.njk, packages/forms-web-app/src/views/macros/appeal-details.njk, packages/forms-web-app/src/views/manage-appeals/appeal-details.njk
=> feat(aapd-106): add appeal details header to questionnaire page

packages/forms-web-app/src/dynamic-forms/controller.js, packages/forms-web-app/src/dynamic-forms/controller.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/task-list/index.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/task-list/questionnaire.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/views.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js, packages/forms-web-app/src/dynamic-forms/question.js, packages/forms-web-app/src/dynamic-forms/section.js
=> feat(aapd-107): add questionnaire table structure

packages/appeals-service-api/__tests__/developer/mongo-db-repository.test.js, packages/appeals-service-api/src/repositories/appeals-case-data-repository.js, packages/appeals-service-api/src/repositories/mongo-repository.js, packages/forms-web-app/src/views/manage-appeals/appeal-details.njk
=> fix(aapd-69): re-adding supporting docs and resolving query issue

packages/forms-web-app/src/dynamic-forms/section.test.js
https://pins-ds.atlassian.net/browse/AAPD-184
Journey section class
=> feat(AAPD-184): journey section class

packages/appeals-service-api/__tests__/developer/mongo-repository.test.js, packages/appeals-service-api/__tests__/developer/responses.test.js, packages/appeals-service-api/__tests__/unit/controllers/responses.test.js, packages/appeals-service-api/__tests__/unit/services/responses.service.test.js, packages/appeals-service-api/src/controllers/responses.js, packages/appeals-service-api/src/errors/apiError.js, packages/appeals-service-api/src/repositories/mongo-repository.js, packages/appeals-service-api/src/repositories/responses-repository.js, packages/appeals-service-api/src/routes/index.js, packages/appeals-service-api/src/routes/responses.js, packages/appeals-service-api/src/services/responses.service.js
=> feat(aapd-119): persist data on questionnaire (API patch endpoint)

packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/appeal-details.test.js, packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/your-appeals.test.js, packages/forms-web-app/src/controllers/lpa-dashboard/appeal-details.js, packages/forms-web-app/src/controllers/lpa-dashboard/your-appeals.js, packages/forms-web-app/src/dynamic-forms/controller.js, packages/forms-web-app/src/dynamic-forms/controller.test.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.test.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/route.js, packages/forms-web-app/src/dynamic-forms/journey-response.js, packages/forms-web-app/src/dynamic-forms/journey-response.test.js, packages/forms-web-app/src/dynamic-forms/journey-types.js, packages/forms-web-app/src/dynamic-forms/journey-types.test.js, packages/forms-web-app/src/dynamic-forms/journey.js, packages/forms-web-app/src/dynamic-forms/journey.test.js, packages/forms-web-app/src/dynamic-forms/question.js, packages/forms-web-app/src/dynamic-forms/section.js, packages/forms-web-app/src/lib/views.js
https://pins-ds.atlassian.net/browse/aadd-185
Journey class
- Tested and added jsdocs
- Removed url hardcoding
- Questionnaire url in const in journey implementation
- Refactored to avoid nesting
=> feat(aapd-185): base journey class

packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js
https://pins-ds.atlassian.net/browse/aapd-214
=> feat(aapd-214): update has-questionnaire q1 url

packages/forms-web-app/src/dynamic-forms/dynamic-components/boolean/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/boolean/question.test.js
https://pins-ds.atlassian.net/browse/AAPD-200
Boolean question
=> feat(AAPD-200): boolean question class

packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js
https://pins-ds.atlassian.net/browse/aapd-219
=> feat(aapd-219): set url for has q2

packages/forms-web-app/src/dynamic-forms/controller.js, packages/forms-web-app/src/dynamic-forms/controller.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/boolean-text/index.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/boolean-text/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/boolean/index.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/boolean/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/boolean/question.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/checkbox/index.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/checkbox/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/listed-building/listed-building-list.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/listed-building/listed-building-lookup.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-file-upload/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/radio/index.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/radio/question.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/template.njk, packages/forms-web-app/src/dynamic-forms/options-question.js, packages/forms-web-app/src/dynamic-forms/options-question.test.js, packages/forms-web-app/src/dynamic-forms/question.js, packages/forms-web-app/src/dynamic-forms/question.test.js, packages/forms-web-app/src/views/layouts/lpa-dashboard/main.njk
https://pins-ds.atlassian.net/browse/aapd-216
- added to questionnaire link
- used viewFolder property instead of fieldName for clarity
=> feat(aapd-216): add return to list link to question page

packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-file-upload/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-file-upload/question.test.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js
https://pins-ds.atlassian.net/browse/aapd-254
=> feat(aapd-254): test multi-file question class

packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.test.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js, packages/forms-web-app/src/dynamic-forms/section.js
https://pins-ds.atlassian.net/browse/AAPD-93
Boolean - Q2:/affects-listed-building-check
=> feat(AAPD-93): affects listed building check

packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js
https://pins-ds.atlassian.net/browse/AAPD-98
Green belt question
=> feat(AAPD-98): green belt question

packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js
https://pins-ds.atlassian.net/browse/AAPD-96
Conservation check
=> feat(AAPD-96): conservation-check

packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js
https://pins-ds.atlassian.net/browse/AAPD-272
Display notice question
=> feat(AAPD-272): display site notice question

packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js
https://pins-ds.atlassian.net/browse/AAPD-274
Letters to neighbours
=> feat(AAPD-274): letters to neighbouts

packages/forms-web-app/src/dynamic-forms/journey.js, packages/forms-web-app/src/dynamic-forms/journey.test.js, packages/forms-web-app/src/dynamic-forms/question.js
https://pins-ds.atlassian.net/browse/AAPD-278
Alternative question url slug
=> feat(AAPD-278): add alternative url slug to base question class

packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js
https://pins-ds.atlassian.net/browse/AAPD-275
Press advert
=> feat(AAPD-275): press advert

packages/appeals-service-api/__tests__/developer/responses.test.js, packages/appeals-service-api/__tests__/unit/controllers/responses.test.js, packages/appeals-service-api/__tests__/unit/services/responses.service.test.js, packages/appeals-service-api/src/controllers/responses.js, packages/appeals-service-api/src/errors/apiError.js, packages/appeals-service-api/src/repositories/responses-repository.js, packages/appeals-service-api/src/routes/responses.js, packages/appeals-service-api/src/services/responses.service.js, packages/forms-web-app/src/dynamic-forms/controller.js, packages/forms-web-app/src/dynamic-forms/controller.test.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/route.js, packages/forms-web-app/src/dynamic-forms/journey-factory.js, packages/forms-web-app/src/dynamic-forms/journey-factory.test.js, packages/forms-web-app/src/dynamic-forms/middleware/getJourneyResponse.js, packages/forms-web-app/src/dynamic-forms/validator/validator.js, packages/forms-web-app/src/dynamic-forms/validator/validator.test.js, packages/forms-web-app/src/lib/appeals-api-wrapper.js
=> feat(AAPD-213): adding get response route

packages/forms-web-app/src/dynamic-forms/has-questionnaire/route.js, packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response.js, packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response.test.js, packages/forms-web-app/src/dynamic-forms/validator/validator.js, packages/forms-web-app/src/dynamic-forms/validator/validator.test.js
=> fix(journey-middleware): use res.locals in validate method

packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js
https://pins-ds.atlassian.net/browse/AAPD-178
Notified who
=> feat(AAPD-178): notified-who

packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js
https://pins-ds.atlassian.net/browse/AAPD-204
Access to site
=> test(AAPD-204): test fixes

packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-202
representation other parties
=> feat(AAPD-204): representations from others

packages/appeals-service-api/__tests__/developer/external-dependencies/rest-apis/interactions/notify-interaction.js, packages/appeals-service-api/__tests__/developer/utils/horizon-integration-input-condition.js
=> fix(integration-tests): fix date regex in tests

packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js
https://pins-ds.atlassian.net/browse/AAPDD-205
=> feat(aapd-205): updating content with up to date prototype

packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js
https://pins-ds.atlassian.net/browse/AAPD-195
Press advert upload
=> feat(AAPD-195): press advert upload

packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js
https://pins-ds.atlassian.net/browse/aapd-262
=> feat(aapd-262): aligning report upload text with prototype

packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js
=> fix(question titles): updating question titles to align with prototype

packages/appeals-service-api/__tests__/unit/lib/flattenObjectToDotNotation.test.js, packages/appeals-service-api/src/lib/flattenObjectToDotNotation.js, packages/common/src/document-types.js, packages/document-service-api/src/controllers/documents.js, packages/forms-web-app/__tests__/unit/lib/documents-api-wrapper.test.js, packages/forms-web-app/__tests__/unit/lib/multi-file-upload.test.js, packages/forms-web-app/src/dynamic-forms/controller.js, packages/forms-web-app/src/dynamic-forms/controller.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-file-upload/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-file-upload/question.test.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.test.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js, packages/forms-web-app/src/dynamic-forms/journey.js, packages/forms-web-app/src/dynamic-forms/journey.test.js, packages/forms-web-app/src/dynamic-forms/question.js, packages/forms-web-app/src/dynamic-forms/question.test.js, packages/forms-web-app/src/lib/documents-api-wrapper.js, packages/forms-web-app/src/lib/multi-file-upload-helpers.js
https://pins-ds.atlassian.net/browse/aapd-253
https://pins-ds.atlassian.net/browse/aapd-255
=> feat(aapd-253): dynamic form file upload

packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js
=> fix(aapd-195): change url properties for uploading press advert

packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js
https://pins-ds.atlassian.net/browse/AAPD-193
Upload site notice
=> feat(AAPD-193): upload site notice

packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-file-upload/index.njk, packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js
https://pins-ds.atlassian.net/browse/AAPD-261
=> feat(aapd-261): updating to use updated validator

packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js, packages/forms-web-app/src/public/resources/upload-letters-emails/content.html
https://pins-ds.atlassian.net/browse/AAPD-194
Upload letters to neighbours
=> feat(AAPD-194): upload letters to neighbours

packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js
=> fix(aapd-261): update fieldname

packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js
=> fix(aapd-205): add validator

packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js
=> fix(aapd-97): change url

packages/forms-web-app/src/views/layouts/multi-file-upload.njk
=> fix(aapd-342): add text to multifile upload pages

packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js
=> fix(aapd-302): fix section title

packages/common/src/lib/address.js, packages/common/src/lib/address.test.js
=> feat(aapd-323): add Address class

packages/appeals-service-api/__tests__/unit/services/appeals-case-data.service.test.js, packages/appeals-service-api/src/repositories/appeals-case-data-repository.js, packages/appeals-service-api/src/services/appeals-case-data.service.js, packages/integration-functions/appeals-case-data-fo-integration/index.js
Fix mongo query syntax
Fix LPACode property
=> feat(AAPD-45): fix mongo db query syntax and LPACode property name

packages/common/src/lib/address.js, packages/common/src/lib/address.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/address-entry/index.njk
=> feat(aapd-321): add njk view for address entry

packages/forms-web-app/src/dynamic-forms/dynamic-components/identifier/index.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/identifier/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/identifier/question.test.js, packages/forms-web-app/src/dynamic-forms/question.js, packages/forms-web-app/src/dynamic-forms/question.test.js
https://pins-ds.atlassian.net/browse/aapd-317
=> feat(aapd-317): add identifier question type

packages/forms-web-app/src/dynamic-forms/controller.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/add-more/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/add-more/question.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/list-add-more/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/list-add-more/question.test.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js, packages/forms-web-app/src/dynamic-forms/middleware/utils.js, packages/forms-web-app/src/dynamic-forms/middleware/utils.test.js, packages/forms-web-app/src/dynamic-forms/validator/validator.js, packages/forms-web-app/src/dynamic-forms/validator/validator.test.js
https://pins-ds.atlassian.net/browse/aapd-316
=> feat(aapd-316): add AddMoreQuestion class

packages/forms-web-app/src/dynamic-forms/validator/string-validator.js, packages/forms-web-app/src/dynamic-forms/validator/string-validator.test.js
https://pins-ds.atlassian.net/browse/AAPD-319
String validation
=> feat(AAPD-319): string validator

packages/forms-web-app/__tests__/unit/lib/valid-postcode.test.js, packages/forms-web-app/src/config.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/address-entry/index.njk, packages/forms-web-app/src/dynamic-forms/validator/address-validator.js, packages/forms-web-app/src/dynamic-forms/validator/address-validator.test.js, packages/forms-web-app/src/dynamic-forms/validator/validator.js, packages/forms-web-app/src/dynamic-forms/validator/validator.test.js, packages/forms-web-app/src/lib/valid-postcode.js, packages/forms-web-app/src/validators/full-appeal/appeal-site-address.js
=> feat(aapd-322): add address validator

packages/forms-web-app/src/dynamic-forms/controller.js, packages/forms-web-app/src/dynamic-forms/controller.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/list-add-more/question.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-file-upload/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-file-upload/question.test.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js, packages/forms-web-app/src/dynamic-forms/question.js, packages/forms-web-app/src/dynamic-forms/question.test.js
=> feat(aapd-308): aligning task list values with up to date prototype

packages/forms-web-app/src/dynamic-forms/dynamic-components/identifier/index.njk
=> fix(identifier-question): add missing error summary macro import

packages/forms-web-app/src/views/manage-appeals/your-appeals.njk
https://pins-ds.atlassian.net/browse/aapd-314
=> feat(aapd-314): add visually hidden text to your-appeals links

packages/forms-web-app/src/dynamic-forms/controller.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-file-upload/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-file-upload/question.test.js
=> feat(aapd-354): add ability to download uploaded files from task list

.github/PULL_REQUEST_TEMPLATE.md, packages/forms-web-app/src/dynamic-forms/dynamic-components/address-add-more/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/address-add-more/question.test.js
https://pins-ds.atlassian.net/browse/AAPD-324
=> feat(aapd-324): add AddressAddMoreQuestion class

packages/appeals-service-api/__tests__/developer/appeals-case-data.test.js
=> fix(aapd-324): fix integration test

packages/forms-web-app/src/config.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/identifier/index.njk, packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/validator/string-validator.js, packages/forms-web-app/src/public/resources/listed-building-number/content.html
https://pins-ds.atlassian.net/browse/AAPD-94
=> feat(aapd-94): add listed building number question

packages/integration-functions/common/src/azure-service-bus/service-bus.js, packages/integration-functions/common/src/azure-service-bus/service-bus.test.js
https://pins-ds.atlassian.net/browse/AAPD-370
=> fix(aapd-370): format service bus message

packages/common/src/lib/listed-building.js, packages/common/src/lib/listed-building.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/listed-building-add-more/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/listed-building-add-more/question.test.js, packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js, packages/forms-web-app/src/lib/appeals-api-wrapper.js
=> feat(aapd-265): add call to listed building api

README.md, package.json, packages/appeals-service-api/data/populate-db.sh, packages/forms-web-app/src/dynamic-forms/dynamic-components/checkbox/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/checkbox/question.test.js, packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/validator/valid-option-validator.js, packages/forms-web-app/src/dynamic-forms/validator/valid-option-validator.test.js
https://pins-ds.atlassian.net/browse/AAPD-391
New component for using checkboxes completed
=> feat(aapd-391): checkbox question added for page how did you notify

packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-430
New boolean question added for ongoing other appeals
=> feat(aapd-430): new boolean question added for ongoing other appeals

packages/forms-web-app/src/dynamic-forms/questions.js
=> fix(aapd-401): fix url for community levy

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/public/resources/safety-risks/content.html
https://pins-ds.atlassian.net/browse/AAPD-279
Added list of potential safety risks
=> feat(aapd-279): addition of list of potential safety risks

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
=> refactor(aapd-402): update previous question name and title

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-419
New boolean for site entry
=> feat(aapd-419): boolean for site entry

packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/AAPD-491
Fixing URL
=> fix(aapd-491): fix url appear near site

packages/forms-web-app/src/dynamic-forms/questions.js
=> fix(aapd-500): add custom error message

packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-408
New boolean for conservation check
=> feat(aapd-408): boolean for conservation check

packages/appeals-service-api/src/event-client/event-client.js, packages/appeals-service-api/src/event-client/service-bus-event-client.js, packages/appeals-service-api/src/infrastructure/event-client.js
=> fix(AAPD-313): fix issue with event client signatures

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-417
New boolean for question: representation by other parties
=> feat(aapd-417): boolean for representation by other parties

packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/AAPD-520
Fixed error message for ongoing appeals page
=> fix(aapd-520): fix error message ongoing appeals page

packages/forms-web-app/src/dynamic-forms/dynamic-components/checkbox/index.njk, packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/AAPD-391
Rectifications in page content
=> feat(aapd-391): rectify page content

packages/appeals-service-api/src/event-client/service-bus-event-client.js
Fix require statement for default azure statement
=> fix(AAPD-313): fix require statement for default azure credential

packages/appeals-service-api/src/services/responses.service.js
Fix the topic name for lpa questionnaire submissions
=> fix(AAPD-313): fix service bus topic name for lpa submissions

packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/AAPD-543
Fixed error message for inspector access page
=> fix(aapd-543): fix error inspector access

packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/AAPD-543
Error message fix
=> fix(aapd-543): fix error message content for inspector access

packages/appeals-service-api/src/mappers/questionnaire-submission/has-mapper.js
=> fix(AAPD-313): pass case reference to submission in mapper

packages/forms-web-app/__tests__/unit/validators/common/schemas/multifile-upload-schema.test.js, packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js, packages/forms-web-app/src/validators/common/schemas/multifile-upload-schema.js
https://pins-ds.atlassian.net/browse/AAPD-424
Upload page for the consultation responses
=> feat(aapd-424): upload consultation responses

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-400
Upload page for community infrastructure levy
=> feat(aapd-400): upload page for community infrastructure levy

packages/forms-web-app/src/dynamic-forms/section.js, packages/forms-web-app/src/dynamic-forms/section.test.js, packages/integration-functions/appeals-case-data-fo-integration/function.json
Update name of appeals case data topic and fix issue with section complete status
Update appeal topic name and fix bug with section completeness status
=> fix(AAPD-313): upodate appeal topic name

packages/appeals-service-api/src/mappers/questionnaire-submission/has-mapper.js
=> fix(AAPD-313): wrong feild name for neighbour visit

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js, packages/forms-web-app/src/public/resources/emerging-plan-upload/content.html
https://pins-ds.atlassian.net/browse/AAPD-396
=> feat(aapd-396): upload emerging plan question

packages/business-rules/src/validation/appeal/decision-date/is-within-decision-date-expiry-period.js
https://pins-ds.atlassian.net/browse/AAPD-aapd-376
=> fix(aapd-376): ensure decision date uses end of day yesterday in uk time

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-415
=> feat(aapd-415): upload letters to interesting parties question

packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
=> feat(aapd-416): add press advert question to s78 journey

packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/AAPD-421
=> feat(aapd-421): updating url to align with copy deck

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-552
Add is the correct appeal type question to s78 journey
- [x ] My commit history in this PR is linear
=> feat(aapd-552): add correct appeal type boolean question to s78 journey

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js, packages/forms-web-app/src/public/resources/notified-who/content.html
https://pins-ds.atlassian.net/browse/AAPD-555
=> feat(aapd-556): add notify question to s78 journey

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js, packages/forms-web-app/src/public/resources/community-infrastructure-levy/content.html
https://pins-ds.atlassian.net/browse/AAPD-399
=> feat(aapd-399): community infrastructure levy boolean question

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-564
=> feat(aapd-564): add representations from others upload to s78 journey

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-523
=> feat(aapd-523): add scheduled monument question to s78 journey

packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-568
list view for add more neightbours on s78
=> feat(AAPD-568): list view for add more neightbours on s78

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/validator/date-validator.js, packages/forms-web-app/src/dynamic-forms/validator/date-validator.test.js
https://pins-ds.atlassian.net/browse/AAPD-403
=> feat(aapd-403): add levy to be adpoted date question to s78 journey

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-521
=> feat(aapd-521): addition of gypsy or traveller question

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js, packages/forms-web-app/src/public/resources/safety-risks/content.html
=> feat(aapd-597): add safety risks question to s78 and update content

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-435
List add more building or site
=> feat(aapd-435): list add more building or site

packages/appeals-service-api/src/mappers/appeal-submission/has-mapper.js
=> fix(AAPD-582): fix has mapper for appeal submission

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
=> feat(aapd-575): changes a listed building question implementation

packages/forms-web-app/src/config.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/identifier/index.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/identifier/question.js, packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/validator/string-validator.js
https://pins-ds.atlassian.net/browse/AAPD-530
Added input field to specify the changed listed building number
=> feat(aapd-530): added text field for changed listed building number

packages/forms-web-app/src/config.js, packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-570
Added component to add several nearby appeals
=> feat(aapd-570): added list add more for nearby appeals

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-534
boolean to ask about consultation responses to upload
=> feat(aapd-534): boolean to ask about consultation responses to upload

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-623
Boolean for public right of way question
=> feat(aapd-623): boolean for public right of way question

packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/AAPD-661
=> fix(aapd-661): fixes for aapd 661 title and aapd 656 url

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-625
Boolean: Is in area of outstanding natural beauty
=> feat(aapd-625): boolean area of oustanding natural beauty

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js, packages/forms-web-app/src/public/resources/upload-planning-officer-report/content.html
https://pins-ds.atlassian.net/browse/AAPD-610
Upload page for uploading the planning officer's report
=> feat(aapd-610): upload page for planning officer report

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-517
add protected species question to s78 journey
=> feat(aapd-517): add protected species question to s78 journey

packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/AAPD-584
Checkboxes added for the question How did you notify people?
=> feat(aapd-584): cheboxes how did you notify people HAS

packages/appeals-service-api/src/data-producers/appeal-producer.js
Fixes the topic name for appellant submissions of the HAS questionnaire
=> fix(AAPD-582): fix topic name for appellant submissions

packages/appeals-service-api/src/services/back-office-v2.service.js
Fix lpa code property name for has appeal submissions
=> fix(AAPD-582): fix lpa code property name on appeal for submissions

packages/forms-web-app/src/dynamic-forms/questions.js
=> feat(aapd-647): change url to match copy deck

packages/forms-web-app/src/dynamic-forms/controller.js, packages/forms-web-app/src/dynamic-forms/controller.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/conditional/text.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/radio/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/radio/question.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/utils/question-utils.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/utils/question-utils.test.js, packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/validator/validator.js
https://pins-ds.atlassian.net/browse/AAPD-630
Added a boolean with a conditional text for procedure type
=> feat(aapd-630): boolean with conditional. Procedure type

packages/appeals-service-api/src/services/back-office-v2.service.js
=> fix(AAPD-582): using incorrect producer type for appeals

packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/AAPD-790
Title fixed
=> fix(aapd-790): title fixed for changed listed building

packages/appeals-service-api/src/mappers/appeal-submission/has-mapper.js
Fix the health and safety issues field on the appeal has mapper
- [ x] My commit history in this PR is linear
=> fix(AAPD-582): fix property name for h and s issues field

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
=> feat(674): add schedule question

packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/AAPD-816
Added max nimber validation. Maximum number is 999.
=> fix(aapd-816): add max number validation

packages/forms-web-app/src/controllers/document.js
=> feat(aapd-658): updating document downloads to have additional security

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/validator/conditional-required-validator.js
=> feat(aapd-649): add designated sites check question

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
aapd-694
Adds a boolean for screening opinion environmental statement
=> feat(aapd-694): add screening opinion environmental statement question

packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/AAPD-790
Modified tab title to match copy deck
=> fix(aapd-790): fix of the tab title

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-690
=> feat(aapd-690): adding sensitive area question

.gitignore, README.md, docker-compose.yml, init/mssql/mssql.conf
https://pins-ds.atlassian.net/browse/AAPD-616
Added instructions to set up the SQL database locally.
=> feat(aapd-616): instructions to set up database locally

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
=> feat(aapd-663): add why hearing question

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
=> feat(664): update required policy question

README.md, docker-compose.yml, package-lock.json, package.json, packages/appeals-service-api/.env.example, packages/appeals-service-api/package.json, packages/appeals-service-api/src/db/schema.prisma, packages/appeals-service-api/src/db/seed/seed.js
https://pins-ds.atlassian.net/browse/AAPD-617
Added Prisma set up with placeholder database schema.
Prisma is responsible for:
- Creating the database
- Creating the database tables
- Populating the tables with some initial data (see example below)
=> feat(aapd-617): prisma set up added

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-686
=> feat(aapd-686): adding development description question

azure-pipelines-deploy.yml, azure-pipelines-release.yml
- fix env var name in pipeline
- auto deploy to test
=> fix(pipeline): deploy to test automatically and fix pipeline

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-676
add environmental upload question to s78 journey
- [ x] My commit history in this PR is linear
=> feat(aapd-676): add environmental upload question to s78 journey

azure-pipelines-db-seed.yml, azure-pipelines-deploy.yml
- Fix seeding pipeline env var + node version
- Added SQL to some params to clarify not for mongo/cosmos
=> feat(pipelines): resolve issues wth seeding pipeline and add clarity to display names

azure-pipelines-db-seed.yml
Final fixes for seeding pipeline
=> fix(pipeline): use prisma generate on non prod deployments

azure-pipelines-deploy.yml
https://pins-ds.atlassian.net/browse/AAPD-835
Deployment pipeline for the interested parties service
=> ci(AAPD-835): deployment pipeline for interested parties service

azure-pipelines-deploy.yml
=> fix: typo in deploy for web-comment

dev/release-util/.env.example, dev/release-util/.gitignore, dev/release-util/README.md, dev/release-util/package.json, dev/release-util/src/commit-summary.js, dev/release-util/src/commit.js, dev/release-util/src/jira-api.js, package-lock.json, package.json
N/A
A script to aid with selecting a release candidate.
=> feat(dev): add release-util script

packages/forms-web-app/src/dynamic-forms/questions.js
add in missing radio button for description of development page
AAPD-879
=> fix(aapd-879): fix bug in relation to aapd 686

docs/api-spec.md
https://pins-ds.atlassian.net/browse/AAPD-171
I left the docs out of date when we changed approach.
=> docs(aapd-171): update docs with new approach

dev/release-util/package.json, dev/release-util/src/command.js, dev/release-util/src/commit-summary.js, dev/release-util/src/jira-api.js, dev/release-util/src/package-changes.js
N/A
Few additions to release utils:
- add parent ticket to commit summary
- little tool to output packages with changes
=> feat: release utils

packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/AAPD-783
=> fix(aapd-783): move uploadOtherRelevantPolicies question in journey

packages/web-comment/src/routes/appeal-search-no-results/index.njk, packages/web-comment/src/routes/enter-appeal-reference/index.js, packages/web-comment/src/routes/enter-appeal-reference/index.njk, packages/web-comment/src/routes/find-planning-appeal/index.js, packages/web-comment/src/routes/find-planning-appeal/index.njk
=> fix(AAPD-825): correct urls

packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
=> feat(aapd-791): fix navigation of environmental section

packages/appeals-service-api/src/mappers/appeal-submission/has-mapper.js
https://pins-ds.atlassian.net/browse/AAPD-492
=> fix(aapd-492): use correct lpa code format

packages/forms-web-app/src/dynamic-forms/dynamic-components/list-add-more/question.js, packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
=> fix(917): add page checking whether more listed buildings to add

packages/forms-web-app/src/views/manage-appeals/your-appeals.njk
=> feat(907): add waiting for review columns and status

packages/forms-web-app/src/dynamic-forms/questions.js
=> feat(AAPD-900): additions to inspector access question

packages/appeals-service-api/src/db/seed/data-dev.js, packages/appeals-service-api/src/lib/filter.js, packages/appeals-service-api/src/routes/index.js, packages/appeals-service-api/src/routes/v2/index.js, packages/appeals-service-api/src/routes/v2/users/:id/appeals/controller.js, packages/appeals-service-api/src/routes/v2/users/:id/appeals/index.js, packages/appeals-service-api/src/routes/v2/users/:id/appeals/repo.js, packages/appeals-service-api/src/routes/v2/users/:id/appeals/service.js, packages/appeals-service-api/src/routes/v2/users/:id/appeals/spec.yaml, packages/appeals-service-api/src/spec/appeal-submission.yaml
https://pins-ds.atlassian.net/browse/AAPD-997
api to retrieve appeals by AppealUser 
(currently no filter options, but only includes draft submissions and appeal cases)
=> feat(aapd-997): add /api/v2/users/:id/appeals endpoint

packages/appeals-service-api/src/db/db-client.js, packages/appeals-service-api/src/db/seed/data-static.js, packages/forms-web-app/src/controllers/index.js
https://pins-ds.atlassian.net/browse/AAPD-861
=> docs(aapd-861): update jsdoc and use flag from const

packages/forms-web-app/__tests__/unit/controllers/full-appeal/type-of-planning-application.test.js, packages/forms-web-app/__tests__/unit/lib/full-appeal/map-planning-application.test.js, packages/forms-web-app/__tests__/unit/routes/appeals/index.test.js, packages/forms-web-app/__tests__/unit/routes/appeals/your-appeals.test.js, packages/forms-web-app/src/controllers/appeals/your-appeals.js, packages/forms-web-app/src/controllers/full-appeal/type-of-planning-application.js, packages/forms-web-app/src/lib/appeals-api-wrapper.js, packages/forms-web-app/src/lib/dashboard-functions.js, packages/forms-web-app/src/lib/full-appeal/map-planning-application.js, packages/forms-web-app/src/lib/views.js, packages/forms-web-app/src/routes/appeals/index.js, packages/forms-web-app/src/routes/appeals/your-appeals.js, packages/forms-web-app/src/routes/index.js, packages/forms-web-app/src/views/appeals/your-appeals.njk
https://pins-ds.atlassian.net/browse/AAPD-961
https://pins-ds.atlassian.net/browse/AAPD-968
https://pins-ds.atlassian.net/browse/AAPD-962
https://pins-ds.atlassian.net/browse/AAPD-969
https://pins-ds.atlassian.net/browse/AAPD-973
View your appeals page structure. Using test data for now.
=> feat(aapd-961): view your appeals page structure

packages/appeals-service-api/__tests__/developer/appeals.test.js, packages/appeals-service-api/__tests__/developer/back-office.test.js, packages/appeals-service-api/__tests__/developer/external-dependencies/rest-apis/mocked-external-apis.js, packages/appeals-service-api/__tests__/developer/final-comments.test.js, packages/appeals-service-api/__tests__/developer/tokens-v2.test.js
https://pins-ds.atlassian.net/browse/AAPD-861
Split developer tests into 3 separate files so it's easier to understand what is being tested in each
renamed token test to indicate it is for v2 endpoint
=> refactor(aapd-861): split and tidy integration tests

packages/appeals-service-api/src/controllers/appeals-for-submission-to-horizon-scheduler.js, packages/appeals-service-api/src/routes/api-docs.js
https://pins-ds.atlassian.net/browse/AAPD-896
Log horizon error correctly
Did a quick search for other instances and found the one in api-docs
=> fix(aapd-896): log errors correctly

packages/appeals-service-api/data/lpa-list.csv
https://pins-ds.atlassian.net/browse/AAPD-1038
=> chore(aapd-1038): update email for Tower Hamlets

docs/api-spec.md, package-lock.json, packages/appeals-service-api/README.md, packages/appeals-service-api/__tests__/setup-jest.js, packages/appeals-service-api/index.d.ts, packages/appeals-service-api/package.json, packages/appeals-service-api/src/configuration/config.js, packages/appeals-service-api/src/routes/index.js, packages/appeals-service-api/src/spec/api-types.d.ts, packages/appeals-service-api/src/spec/gen-api-spec.js, packages/appeals-service-api/src/spec/gen-api-types.js
https://pins-ds.atlassian.net/browse/AAPD-1039
Generate (and export) TypeScript definitions from the OpenAPI spec.
=> feat(appd-1039): generate types from the api spec

packages/forms-web-app/src/controllers/appeals/your-appeals.js, packages/forms-web-app/src/controllers/appeals/your-appeals/decided-appeals.js
https://pins-ds.atlassian.net/browse/AAPD-987
get email from appeal in session for testing purposes
=> feat(aapd-987): get email from appeal in session for testing purposes

dev/data/Dockerfile
N/A
Fix `dev/data` Docker build for local dev.
=> fix(dev/data): correct path for data package in dockerfile

packages/common/src/client/appeals-api-client.js
https://pins-ds.atlassian.net/browse/AAPD-861
Will add some tests to cover the api client in a separate PR
=> fix(aapd-861): add missing require

packages/appeals-service-api/__tests__/developer/appeals.test.js, packages/appeals-service-api/__tests__/developer/back-office.test.js, packages/appeals-service-api/__tests__/developer/final-comments.test.js, packages/appeals-service-api/__tests__/developer/tokens-v2.test.js, packages/appeals-service-api/__tests__/unit/controllers/save-and-return.test.js, packages/appeals-service-api/__tests__/unit/controllers/token.test.js, packages/appeals-service-api/__tests__/unit/services/appeal.service.test.js, packages/appeals-service-api/src/repositories/sql/appeals-repository.js, packages/appeals-service-api/src/routes/v2/users/users.spec.js, packages/appeals-service-api/src/services/appeal.service.js
https://pins-ds.atlassian.net/browse/AAPD-861
Updates the role a user has on an appeal when isOriginalAppellant changes
Integration tests take into account a shared DB and parallel running
=> feat(aapd-861): update appeal and user link if role changes

packages/appeals-service-api/src/db/seed/data-dev.js, packages/appeals-service-api/src/db/seed/lpa-appeal-case-data-dev.js, packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/your-appeals.test.js, packages/forms-web-app/__tests__/unit/lib/dashboard-functions.spec.js, packages/forms-web-app/src/controllers/lpa-dashboard/decided-appeals.js, packages/forms-web-app/src/controllers/lpa-dashboard/your-appeals.js, packages/forms-web-app/src/lib/appeals-api-wrapper.js, packages/forms-web-app/src/lib/dashboard-functions.js, packages/forms-web-app/src/views/manage-appeals/decided-appeals.njk, packages/forms-web-app/src/views/manage-appeals/your-appeals.njk
https://pins-ds.atlassian.net/browse/AAPD-937
https://pins-ds.atlassian.net/browse/AAPD-938
https://pins-ds.atlassian.net/browse/AAPD-939
Add the decided appeals page for LPA USER
=> feat(937): decided appeals lpaUser page, update seed data

packages/forms-web-app/src/controllers/appeals/your-appeals/decided-appeals.js, packages/forms-web-app/src/lib/dashboard-functions.js, packages/forms-web-app/src/views/appeals/your-appeals/decided-appeals.njk
https://pins-ds.atlassian.net/browse/AAPD-995
display correct tag for decision outcome
=> feat(aapd-995): display correct tag for decision outcome

packages/appeals-service-api/src/routes/v2/appeal-cases/appeal-cases.spec.js, packages/appeals-service-api/src/routes/v2/appeal-cases/controller.js, packages/common/src/client/appeals-api-client.js, packages/common/src/client/utils.js, packages/common/src/client/utils.test.js
https://pins-ds.atlassian.net/browse/AAPD-954
Unit tests and bug fixes for appeal case endpoint(s).
=> feat(aapd-954): add tests and fix bugs found

packages/forms-web-app/src/views/appeals/your-appeals/decided-appeals.njk
https://pins-ds.atlassian.net/browse/AAPD-1055
Remove some extra text
=> fix(aapd-1055): remove extra to do text

packages/forms-web-app/src/dynamic-forms/questions.js
=> fix(AAPD-900): fix page title

Makefile, README.md, package.json
=> fix(local-dev): serve correct services with npm

packages/web-comment/src/main.njk, packages/web-comment/src/routes/appeal-open-comment/index.njk, packages/web-comment/src/routes/appeal-search-no-results/index.njk, packages/web-comment/src/routes/appeals/index.njk, packages/web-comment/src/routes/decided-appeals/index.njk, packages/web-comment/src/routes/enter-appeal-reference/index.njk, packages/web-comment/src/routes/enter-postcode/index.njk, packages/web-comment/src/routes/index.js, packages/web-comment/src/views/includes/head.njk
=> fix(AAPD-825): fix page titles

packages/appeals-service-api/src/lib/notify.js, packages/appeals-service-api/src/routes/v2/token/controller.js
https://pins-ds.atlassian.net/browse/AAPD-868
Update variables to be in line with modified template
=> feat(aapd-868): update register email variables

packages/forms-web-app/src/views/appeals/your-appeals/decided-appeals.njk, packages/forms-web-app/src/views/manage-appeals/decided-appeals.njk
relates to
https://pins-ds.atlassian.net/browse/AAPD-994
Reflects renamed field in display data object
=> fix(994): fix display of decision on decided pages

packages/web-comment/src/main.njk, packages/web-comment/src/routes/enter-postcode/index.njk
=> fix(AAPD-836): fix copy

packages/appeals-service-api/src/services/appeal.service.js
=> fix(live-issue): add feature flag check to appeal update

dev/release-util/README.md, dev/release-util/package.json, dev/release-util/src/jira-api.js, dev/release-util/src/update-released-issues.js
N/A
Script to help updating ticket statuses after release
=> feat(dev): add script to update ticket statuses

packages/forms-web-app/__tests__/unit/controllers/common/enter-code.test.js, packages/forms-web-app/src/controllers/common/enter-code.js, packages/forms-web-app/src/views/appeal-householder-decision/email-address.njk, packages/forms-web-app/src/views/appeal-householder-decision/enter-code.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/email-address.njk, packages/forms-web-app/src/views/includes/enter-security-code.njk, packages/forms-web-app/src/views/manage-appeals/enter-code.njk, packages/forms-web-app/src/views/manage-appeals/your-email-address.njk, packages/web-comment/src/views/includes/enter-security-code.njk
https://pins-ds.atlassian.net/browse/aapd-1202
- Ensure error messages appear with email code fields
- Ensure labels referenced various fields correctly
- updated in web comment, assume this isn't actually used currently
=> fix(aapd-1202): error messages and label fixes

packages/forms-web-app/src/controllers/common/enter-code.js, packages/forms-web-app/src/routes/appeal-householder-decision/login/enter-code.js, packages/forms-web-app/src/routes/full-appeal/login/enter-code.js, packages/forms-web-app/src/validators/common/check-id-is-uuid.js
https://pins-ds.atlassian.net/browse/AAPD-863
=> fix(aapd-863): use new param name in validation middleware

packages/appeals-service-api/src/db/seed/data-dev.js, packages/appeals-service-api/src/db/seed/lpa-appeal-case-data-dev.js, packages/web-comment/src/routes/decided-appeals/controller.js
https://pins-ds.atlassian.net/browse/AAPD-922
Fix colours for decision tag
=> fix(aapd-922): split decision colours

packages/forms-web-app/src/views/appeals/your-appeals/decided-appeals.njk, packages/forms-web-app/src/views/manage-appeals/decided-appeals.njk
https://pins-ds.atlassian.net/browse/AAPD-939
I rushed some changes and the syntax was not correct...
=> fix(aapd-939): create tag class correctly

packages/web-comment/src/routes/decided-appeals/index.njk
https://pins-ds.atlassian.net/browse/AAPD-922
I rushed some changes and the syntax was not correct... missed a fix in web-comment
=> fix: create tag class correctly 

packages/web-comment/src/routes/decided-appeals/index.njk
https://pins-ds.atlassian.net/browse/AAPD-922
=> fix(aapd-922): web-comment its appeal not item in the loop

packages/forms-web-app/src/views/appeals/your-appeals/decided-appeals.njk
https://pins-ds.atlassian.net/browse/AAPD-991
Noticed a little bug when we changed the display data formats.
=> fix(aapd-991): update appeal number field

packages/forms-web-app/__tests__/unit/lib/dashboard-functions.spec.js, packages/forms-web-app/src/lib/dashboard-functions.js
https://pins-ds.atlassian.net/browse/AAPD-995
Just show the appeal outcome, don't transform it.
=> fix(aapd-995): show appeal outcome as-is

package-lock.json, packages/appeals-service-api/package.json, packages/appeals-service-api/src/routes/api-docs.js, packages/appeals-service-api/src/routes/v2/users/_id/appeal-submissions/_appealSubmissionId/controller.js, packages/appeals-service-api/src/routes/v2/users/_id/appeal-submissions/_appealSubmissionId/index.js, packages/appeals-service-api/src/routes/v2/users/_id/appeal-submissions/_appealSubmissionId/repo.js, packages/appeals-service-api/src/routes/v2/users/_id/appeal-submissions/_appealSubmissionId/service.js, packages/appeals-service-api/src/routes/v2/users/_id/appeal-submissions/_appealSubmissionId/spec.yaml, packages/appeals-service-api/src/spec/api-types.d.ts, packages/appeals-service-api/src/spec/appeal-submission.yaml, packages/appeals-service-api/src/spec/format-write.js, packages/appeals-service-api/src/spec/gen-api-spec-types.js, packages/appeals-service-api/src/spec/gen-api-spec.js, packages/appeals-service-api/src/spec/write-api-spec.js, packages/appeals-service-api/src/spec/write-api-types.js, packages/appeals-service-api/src/validators/validate-open-api.js, packages/common/src/client/appeals-api-client.js, packages/common/src/router.js, packages/forms-web-app/src/controllers/appeals/continue.js, packages/forms-web-app/src/controllers/appeals/your-appeals.js, packages/forms-web-app/src/lib/dashboard-functions.js, packages/forms-web-app/src/routes/appeals/your-appeals/index.js, packages/forms-web-app/src/views/appeals/your-appeals.njk
- Makes continue links on /appeals/your-appeals#to-do work. 
- Adds a script for validating the openapi spec because I broke the spec
=> feat(aapd-808): make your appeals continue links work

packages/forms-web-app/src/controllers/appeals/continue.js
=> fix(aapd-798): fix isAppealSubmission import

packages/appeals-service-api/src/db/migrations/20240214094844_case_published/migration.sql, packages/appeals-service-api/src/db/schema.prisma, packages/appeals-service-api/src/db/seed/data-static.js, packages/appeals-service-api/src/errors/apiError.js, packages/appeals-service-api/src/repositories/sql/appeal-user-repository.js, packages/appeals-service-api/src/routes/v2/users/_id/appeal-cases/_caseReference/controller.js, packages/appeals-service-api/src/routes/v2/users/_id/appeal-cases/_caseReference/index.js, packages/appeals-service-api/src/routes/v2/users/_id/appeal-cases/_caseReference/repo.js, packages/appeals-service-api/src/routes/v2/users/_id/appeal-cases/_caseReference/service.js, packages/appeals-service-api/src/routes/v2/users/_id/appeal-cases/_caseReference/spec.yaml, packages/appeals-service-api/src/routes/v2/users/index.js, packages/appeals-service-api/src/spec/api-types.d.ts, packages/appeals-service-api/src/spec/appeal-case.yaml, packages/common/src/client/appeals-api-client.js, packages/common/src/constants.js
=> Get appeal case for specific user with specific role API endpoint 

packages/appeals-service-api/src/routes/v2/appeal-cases/appeal-cases.spec.js, packages/appeals-service-api/src/routes/v2/appeal-cases/controller.js, packages/appeals-service-api/src/routes/v2/appeal-cases/repo.js, packages/appeals-service-api/src/routes/v2/appeal-cases/service.js, packages/appeals-service-api/src/routes/v2/appeal-cases/spec.yaml, packages/common/src/client/appeals-api-client.js, packages/common/src/view-model-maps/appeal-headline.js, packages/forms-web-app/src/controllers/selected-appeal/selected-appeal.js, packages/web-comment/src/routes/appeals/_appealNumber/controller.js
https://pins-ds.atlassian.net/browse/AAPD-926
Only return published cases to IPs.
=> only show published cases to IPs

docker-compose.yml
This appears to speed up shutting down of sql docker container, not really sure what else it does but feels like a nice QOL improvement
=> chore(local-dev): speed up sql docker with init

package-lock.json, package.json, packages/appeals-service-api/package.json, packages/common/package.json, packages/document-service-api/package.json, packages/forms-web-app/package.json, packages/pdf-service-api/package.json, packages/web-comment/package.json
=> chore(logging): consolidate pino

packages/appeals-service-api/src/db/migrations/20240216151149_view_appeal/migration.sql, packages/appeals-service-api/src/db/schema.prisma, packages/appeals-service-api/src/spec/api-types.d.ts, packages/appeals-service-api/src/spec/appeal-case.yaml, packages/common/src/frontend/pins/components/appeal-sections-block.njk, packages/forms-web-app/src/app.js, packages/forms-web-app/src/controllers/selected-appeal/appellant-sections.js, packages/forms-web-app/src/controllers/selected-appeal/lpa-user-sections.js, packages/forms-web-app/src/controllers/selected-appeal/section.d.ts, packages/forms-web-app/src/controllers/selected-appeal/selected-appeal.js, packages/forms-web-app/src/lib/array-has-items.js, packages/forms-web-app/src/lib/determine-user.js
=> feat(aapd-945): Appelant and LPA appeal pages

packages/forms-web-app/src/controllers/selected-appeal/selected-appeal.js, packages/forms-web-app/src/views/selected-appeal/appeal.njk
=> fix(aapd-1074): fix page title

packages/appeals-service-api/src/services/token.service.js
=> fix(token-hotfix): use correct id on token lookup to hit index

packages/business-rules/src/utils/decision-outcome.js, packages/forms-web-app/src/controllers/selected-appeal/selected-appeal.js, packages/forms-web-app/src/views/selected-appeal/appeal.njk
=> feat(aapd-950): add appeal decision section and tag

packages/appeals-service-api/src/db/seed/lpa-appeal-case-data-dev.js
N/A
add procedure and appellant names to seed data - these fields are used for the 'headlines' section of the Appeal Details page
=> chore - View Appeal Headline Data: 

packages/forms-web-app/__tests__/unit/controllers/appellant-submission/submission.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/declaration.test.js, packages/forms-web-app/__tests__/unit/services/pdf.service.test.js, packages/forms-web-app/src/controllers/appellant-submission/submission.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/declaration.js, packages/forms-web-app/src/services/pdf.service.js
Fix issue from https://github.com/Planning-Inspectorate/appeal-planning-decision/pull/3444
=> fix: householder appeal pdf fix

packages/forms-web-app/src/controllers/selected-appeal/rule-6-sections.js
Correct typo in rule 6 statement section
=> refactor: correct rule 6 statement section typo

packages/common/src/view-model-maps/sections/index.js
Minor change to fix typo in sections 'isSection' check
=> chore(fix typo): fix typo

packages/database/src/seed/lpa-appeal-case-data-dev.js
Add a HAS appeal requiring a questionnaire
=> chore: seed HAS case w/questionnaire

packages/database/src/seed/lpa-appeal-case-data-dev.js
=> fix: seed HAS case w/questionnaire

README.md, packages/common/src/lib/array-has-items.js, packages/forms-web-app/src/app.js, packages/web-comment/src/app.js
=> fix: move array has items to common

packages/forms-web-app/src/controllers/selected-appeal/lpa-user-sections.js
=> fix(aapd-1122): amend copy

README.md, packages/database/src/README.md
=> chore: update readme files for local database setup

docker-compose.yml, packages/forms-web-app/__tests__/unit/routes/index.test.js, packages/forms-web-app/src/config.js, packages/forms-web-app/src/routes/index.js
https://pins-ds.atlassian.net/browse/AAPD-1375
add a dashboards enabled check to the lpa appellant and rule 6 party dashboards
This makes use of the env variables added to the infra repo here:
https://github.com/Planning-Inspectorate/infrastructure-environments/pull/690
=> Aapd 1375/feature flag for dashboards

packages/business-rules/src/utils/decision-outcome.js
=> fix(aapd-950): update outcome colors

azure-pipelines-build.yml, azure-pipelines-deploy.yml
https://pins-ds.atlassian.net/browse/AAPD-1195
Pipeline to deploy auth server
=> feat(aapd-1195): add auth server to pipelines

package-lock.json, packages/auth-server/package.json
https://pins-ds.atlassian.net/browse/AAPD-1195
Add express
=> fix(aapd-1195): add missing dependency

packages/auth-server/src/configuration/schema.js
https://pins-ds.atlassian.net/browse/AAPD-1195
endpoint is prefixed with Endpoint=
=> fix(aapd-1195): feature flag endpoint validation revert to just string

azure-pipelines-db-seed.yml, packages/database/.env.example, packages/database/src/configuration/config.js, packages/database/src/seed/data-dev.js
Allow seeding of doc uri via an env var
Added a variable to pipeline in devops that only points to test
=> chore: allow seeding of doc uris via env var

packages/web-comment/src/routes/appeals/_appealNumber/controller.js
https://pins-ds.atlassian.net/browse/AAPD-1226
Content fix
=> fix(aapd-1226): appeal detail content fix

packages/database/src/seed/data-dev.js
=> fix: seed documents uri

packages/forms-web-app/src/lib/dashboard-functions.js
https://pins-ds.atlassian.net/browse/AAPD-1431
Use label mapper for decided appeals pages
=> fix(aapd-1431): use correct label for decision

packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/submit/index.test.js, packages/appeals-service-api/src/services/back-office-v2/formatters/confluence-tools.js, packages/appeals-service-api/src/services/back-office-v2/formatters/documents.d.ts, packages/appeals-service-api/src/services/back-office-v2/formatters/has/has.d.ts, packages/appeals-service-api/src/services/back-office-v2/formatters/has/questionnaire.js, packages/appeals-service-api/src/services/back-office-v2/formatters/index.js, packages/appeals-service-api/src/services/back-office-v2/formatters/s78/questionnaire.js, packages/appeals-service-api/src/services/back-office-v2/formatters/s78/s78.d.ts, packages/appeals-service-api/src/services/back-office-v2/formatters/utils.js
=> feat(aadp-1034): add s78 formatter, rework has formatter

packages/forms-web-app/src/views/layouts/lpa-dashboard/main-no-back-link.njk, packages/forms-web-app/src/views/layouts/lpa-dashboard/main.njk, packages/forms-web-app/src/views/manage-appeals/your-email-address.njk
https://pins-ds.atlassian.net/browse/AAPD-1347
Update page title across all lpa pages
=> feat(aapd-1347): update page title to your appeals

dev/release-util/src/jira-api.js
=> fix(dev): handle ticket IDs that aren't found

packages/forms-web-app/src/controllers/appeals/no-appeals.js, packages/forms-web-app/src/controllers/appeals/your-appeals.js, packages/forms-web-app/src/lib/views.js, packages/forms-web-app/src/routes/appeals/index.js, packages/forms-web-app/src/views/appeals/no-appeals.njk
https://pins-ds.atlassian.net/browse/AAPD-728
Use no appeals page when user has no appeals
=> feat(aapd-728): add no appeals page

packages/common/src/view-model-maps/appeal-headline.js, packages/database/src/seed/lpa-appeal-case-data-dev.js, packages/web-comment/src/routes/appeals/_appealNumber/index.njk, packages/web-comment/src/utils/format-deadline-text.js
https://pins-ds.atlassian.net/browse/AAPD-1227
Corrects some formatting errors for interested parties appeal summary view.
=> fix(1227): fix formatting errors

packages/database/src/seed/data-dev.js
=> fix(aapd-1501): fix appellantSubmission seeding

packages/forms-web-app/src/controllers/appeal/new-saved-appeal.js, packages/forms-web-app/src/controllers/before-you-start/before-you-start.js, packages/forms-web-app/src/routes/before-you-start/before-you-start.js, packages/forms-web-app/src/views/before-you-start/first-page.njk
https://pins-ds.atlassian.net/browse/AAPD-1343
=> fix(aapd-1343): reset appeal in session on hitting start new

packages/appeals-service-api/src/services/appeal.service.js, packages/common/src/client/appeals-api-client.js, packages/common/src/feature-flags.js, packages/forms-web-app/__tests__/unit/controllers/common/enter-code.test.js, packages/forms-web-app/src/controllers/common/enter-code.js, packages/forms-web-app/src/controllers/document.js, packages/forms-web-app/src/lib/is-token-valid.js, packages/forms-web-app/src/middleware/check-logged-in.js
https://pins-ds.atlassian.net/browse/AAPD-1449
Splits enrol-users (dashboard) from using sql for login
=> feat(aapd-1449): separate use of sql from dashboard

packages/forms-web-app/src/views/before-you-start/first-page.njk
https://pins-ds.atlassian.net/browse/AAPD-1343
Adds CSRF token to before you start
=> fix(aapd-1343): add csrf token input to before you start input

packages/appeals-service-api/src/spec/api-types.d.ts, packages/appeals-service-api/src/spec/appellant-submission.yaml, packages/common/src/client/appeals-api-client.js, packages/forms-web-app/src/dynamic-forms/journey-response.js, packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response-for-appellant.js, packages/forms-web-app/src/dynamic-forms/middleware/utils.js
=> feat(aapd-1505): add middleware for submission lookup

packages/forms-web-app/src/views/selected-appeal/appeal.njk
=> fix(aapd-1158): correct notification banner title

packages/forms-web-app/src/dynamic-forms/controller.js, packages/forms-web-app/src/dynamic-forms/has-appeal-form/journey.js, packages/forms-web-app/src/dynamic-forms/journey-factory.js, packages/forms-web-app/src/dynamic-forms/journey.js, packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response-for-appellant.js, packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response-for-lpa.js, packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response-for-lpa.test.js, packages/forms-web-app/src/routes/appeals/index.js, packages/forms-web-app/src/routes/appellant-submission/submission-form.js, packages/forms-web-app/src/routes/index.js
=> feat: fix routing for has appeal form v2

packages/appeals-service-api/src/routes/back-office.js
https://pins-ds.atlassian.net/browse/AAPD-1535
=> fix(aapd-1535): comment out v1 appeal submission to new back office

packages/forms-web-app/src/dynamic-forms/dynamic-components/submission-screen/index.njk, packages/forms-web-app/src/views/layouts/full-appeal-banner/main-no-back-link.njk
=> fix(aapd-516): update service name

packages/appeals-service-api/src/spec/api-types.d.ts, packages/appeals-service-api/src/spec/appellant-submission.yaml, packages/database/src/migrations/20240409172924_add_v2_submission_fields/migration.sql, packages/database/src/schema.prisma
=> feat: add some v2 appeal question fields to sql

packages/forms-web-app/src/views/layouts/no-banner-link/main.njk
=> fix: add required blocks to main template

packages/appeals-service-api/src/spec/appellant-submission.yaml, packages/forms-web-app/src/dynamic-forms/controller.js, packages/forms-web-app/src/dynamic-forms/controller.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/add-more/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/address-add-more/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/boolean/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/date/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/list-add-more/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/listed-building-add-more/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-file-upload/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-file-upload/question.test.js, packages/forms-web-app/src/dynamic-forms/middleware/utils.js, packages/forms-web-app/src/dynamic-forms/question.js, packages/forms-web-app/src/dynamic-forms/question.test.js
=> fix: use authorized api client in dynamic forms

packages/forms-web-app/src/dynamic-forms/has-appeal-form/journey.js
=> feat(aapd-1463): add greenbelt q to has appeal journey

packages/common/src/document-types.js, packages/forms-web-app/src/dynamic-forms/has-appeal-form/journey.js, packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/views/layouts/multi-file-upload.njk
=> feat(aapd-1474): add application section

packages/appeals-service-api/src/routes/v2/appellant-submissions/_id/document-upload/controller.js, packages/appeals-service-api/src/routes/v2/appellant-submissions/_id/document-upload/index.js, packages/appeals-service-api/src/routes/v2/appellant-submissions/_id/document-upload/repo.js, packages/appeals-service-api/src/routes/v2/appellant-submissions/_id/document-upload/service.js, packages/appeals-service-api/src/routes/v2/appellant-submissions/repo.js, packages/common/src/client/appeals-api-client.js, packages/common/src/document-types.js, packages/database/src/migrations/20240412105724_/migration.sql, packages/database/src/schema.prisma, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/planning-obligation-deadline.test.js, packages/forms-web-app/__tests__/unit/mocks.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-file-upload/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-file-upload/question.test.js, packages/forms-web-app/src/dynamic-forms/has-appeal-form/journey.js, packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/lib/multi-file-upload-helpers.js
=> fix: fixes multifile uploads for appellant forms

packages/forms-web-app/src/views/full-appeal/can-use-service.njk, packages/forms-web-app/src/views/full-appeal/granted-or-refused.njk, packages/forms-web-app/src/views/full-appeal/prior-approval/can-use-service.njk, packages/forms-web-app/src/views/full-appeal/removal-or-variation-of-conditions/can-use-service.njk, packages/forms-web-app/src/views/householder-planning/eligibility/can-use-service.njk, packages/forms-web-app/src/views/householder-planning/eligibility/granted-or-refused-householder.njk, packages/forms-web-app/src/views/householder-planning/eligibility/prior-approval/can-use-service.njk, packages/forms-web-app/src/views/householder-planning/eligibility/removal-or-variation-of-conditions/can-use-service.njk
=> fix: remove double questionmarks

packages/common/src/document-types.js, packages/database/src/migrations/20240417092022_/migration.sql, packages/database/src/migrations/20240417094940_/migration.sql, packages/database/src/schema.prisma, packages/forms-web-app/src/dynamic-forms/has-appeal-form/journey.js, packages/forms-web-app/src/dynamic-forms/questions.js
=> feat: add appeal documents section

packages/appeals-service-api/src/routes/v2/appellant-submissions/controller.js, packages/appeals-service-api/src/routes/v2/appellant-submissions/index.js, packages/appeals-service-api/src/routes/v2/appellant-submissions/repo.js, packages/appeals-service-api/src/routes/v2/appellant-submissions/service.js, packages/forms-web-app/src/controllers/debug.js, packages/forms-web-app/src/routes/debug.js
Temporary debug route to allow testers to create appeals and find their ids
=> chore: add debug route to create an appeal

packages/forms-web-app/src/dynamic-forms/dynamic-components/single-line-input/index.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/single-line-input/question.js, packages/forms-web-app/src/dynamic-forms/has-appeal-form/journey.js, packages/forms-web-app/src/dynamic-forms/questions.js
=> feat(aapd-1453): add phone question

packages/appeals-service-api/src/spec/api-types.d.ts, packages/appeals-service-api/src/spec/appellant-submission.yaml, packages/forms-web-app/src/dynamic-forms/dynamic-components/boolean/index.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/boolean/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/single-line-input/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/text-entry/index.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/text-entry/question.js, packages/forms-web-app/src/dynamic-forms/has-appeal-form/journey.js, packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/validator/date-validator.js, packages/forms-web-app/src/dynamic-forms/validator/date-validator.test.js, packages/forms-web-app/src/public/resources/development-description/content.html
https://pins-ds.atlassian.net/browse/AAPD-1466
Bugfixes following QA - largely relating to error messages but including:
- add getDate function to questions and convert instances of DateQuestions to functions in order to dynamically generate hint dates rather than setting on server starting
- allow passing of options to BooleanQuestion
=> fix(1466): fix error messages, add dynamic date function to DateQuestions

packages/appeals-service-api/src/errors/apiError.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/address/repo.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/linked-case/repo.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/listed-building/controller.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/listed-building/index.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/listed-building/repo.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/listed-building/service.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/questionnaire-submission.d.ts, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/repo.js, packages/common/src/client/appeals-api-client.js, packages/database/src/migrations/20240418160920_add_listed_building_submission/migration.sql, packages/database/src/schema.prisma, packages/forms-web-app/src/dynamic-forms/dynamic-components/list-add-more/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/listed-building-add-more/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/listed-building-add-more/question.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/utils/question-utils.js, packages/forms-web-app/src/dynamic-forms/section.js
https://pins-ds.atlassian.net/browse/AAPD-1032
=> fix(aapd-1032): fix listed building for lpaq sql

.gitignore, .vscode/extensions.json, .vscode/settings.json
=> feat(tooling): add jest-runner extension and settings

packages/appeals-service-api/src/routes/v2/appellant-submissions/index.js, packages/appeals-service-api/src/services/lpa.service.js, packages/common/src/client/appeals-api-client.js, packages/common/src/constants.js, packages/database/src/migrations/20240425172612_add_bfs_fields_to_appellant_submission/migration.sql, packages/database/src/schema.prisma, packages/forms-web-app/src/controllers/appeal-householder-decision/list-of-documents.js, packages/forms-web-app/src/controllers/debug.js, packages/forms-web-app/src/dynamic-forms/has-appeal-form/journey.js, packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response-for-appellant.js, packages/forms-web-app/src/lib/appeals-api-wrapper.js, packages/forms-web-app/src/routes/appeals/index.js
https://pins-ds.atlassian.net/browse/AAPD-1534
=> feat(aapd-1534): route users from BYS to v2 HAS appeal form

packages/forms-web-app/src/dynamic-forms/dynamic-components/single-line-input/index.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/single-line-input/question.js, packages/forms-web-app/src/dynamic-forms/questions.js
=> fix(aapd-1483): fix missing text

packages/forms-web-app/src/dynamic-forms/questions.js
=> chore(aapd-1558): update question copy

packages/forms-web-app/src/controllers/appeal-householder-decision/list-of-documents.js
=> fix: appeal v2 feature flag to use correct lpaCode

azure-pipelines-deploy.yml
=> chore: auth server deploy by default

packages/forms-web-app/src/dynamic-forms/questions.js
=> fix(aapd-1474): correct error message

packages/forms-web-app/src/views/appeal-householder-decision/email-address.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/email-address.njk
=> feat(aapd-1545): amend email page copy

packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/repo.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/service.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/submit/index.test.js, packages/appeals-service-api/src/routes/v2/appellant-submissions/_id/service.js, packages/appeals-service-api/src/routes/v2/appellant-submissions/repo.js, packages/appeals-service-api/src/services/back-office-v2/index.js, packages/appeals-service-api/src/spec/api-types.d.ts, packages/appeals-service-api/src/spec/appellant-submission.yaml, packages/appeals-service-api/src/spec/lpa-questionnaire-submission.yaml, packages/database/src/migrations/20240429103800_add_journey_submitted_fields/migration.sql, packages/database/src/schema.prisma, packages/forms-web-app/src/dynamic-forms/middleware/check-not-submitted.js, packages/forms-web-app/src/dynamic-forms/middleware/check-not-submitted.test.js, packages/forms-web-app/src/routes/appellant-submission/submission-form.js, packages/forms-web-app/src/routes/lpa-dashboard/questionnaire.js
https://pins-ds.atlassian.net/browse/AAPD-1507
https://pins-ds.atlassian.net/browse/AAPD-1567
=> feat(aapd-1567): add journey submitted check

packages/forms-web-app/src/dynamic-forms/questions.js
=> fix(qqpd-1479): fix cost application validation

packages/forms-web-app/src/dynamic-forms/has-appeal-form/journey.js, packages/forms-web-app/src/dynamic-forms/journey.js, packages/forms-web-app/src/dynamic-forms/journey.test.js
=> feat(aapd-1593): return to listing page on HAS v2 section completion

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/public/resources/upload-appeal-statement/content.html, packages/forms-web-app/src/views/layouts/multi-file-upload.njk
=> fix(aapd-1478): add missing content

packages/forms-web-app/__tests__/mockData/prior-approval/prior-approval-has-route.js, packages/forms-web-app/__tests__/mockData/removal-or-variation-of-conditions/removal-or-variation-of-conditions-has-route.js, packages/forms-web-app/__tests__/unit/controllers/householder-planning/eligibility/claiming-costs-householder.test.js, packages/forms-web-app/src/controllers/before-you-start/can-use-service.js, packages/forms-web-app/src/controllers/householder-planning/eligibility/claiming-costs-householder.js, packages/forms-web-app/src/views/householder-planning/eligibility/can-use-service.njk, packages/forms-web-app/src/views/householder-planning/eligibility/prior-approval/can-use-service.njk, packages/forms-web-app/src/views/householder-planning/eligibility/removal-or-variation-of-conditions/can-use-service.njk
https://pins-ds.atlassian.net/browse/AAPD-160
=> feat(aapd-160): skip costs question for has v2

packages/appeals-service-api/src/spec/api-types.d.ts, packages/appeals-service-api/src/spec/appellant-submission.yaml
=> fix(aapd-1623): make optional strings nullable

packages/forms-web-app/src/dynamic-forms/has-appeal-form/journey.js, packages/forms-web-app/src/dynamic-forms/questions.js
=> feat(aapd-1591): change of description navigation

packages/forms-web-app/src/dynamic-forms/has-appeal-form/journey.js, packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/AAPD-1568
Adds (a lot of) conditional navigation logic for the site-details section.
=> feat(1568): land ownership navigation

packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/AAPD-1469
Removes rogue full stop and updates hint
=> fix(1469): correct typo

packages/forms-web-app/src/dynamic-forms/has-appeal-form/journey.js
=> fix: correct condition typo in has journey

packages/forms-web-app/src/dynamic-forms/dynamic-components/list-add-more/index.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/macros/answer-list.njk
=> fix(aapd-1654): fix list add more bug

packages/forms-web-app/src/dynamic-forms/questions.js
=> fix(aapd-1558): amend more planning copy

packages/forms-web-app/__tests__/unit/validators/common/enter-code.test.js, packages/forms-web-app/src/controllers/common/enter-code.js, packages/forms-web-app/src/validators/common/enter-code.js
https://pins-ds.atlassian.net/browse/AAPD-1615
Updating error messages to more generic text
=> feat(aapd-1615): update to error messages to comply with security report

packages/appeals-service-api/src/services/back-office-v2/formatters/has/appeal.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/submission-screen/appellant.njk
https://pins-ds.atlassian.net/browse/AAPD-1495
Correct tiny typo in njks 
=> feat(1495): fix typo in njks

packages/auth-server/src/configuration/config.js, packages/forms-web-app/__tests__/unit/lib/check-session-idle.test.js, packages/forms-web-app/__tests__/unit/middleware/lpa-dashboard/require-user.test.js, packages/forms-web-app/src/config.js, packages/forms-web-app/src/lib/check-session-idle.js, packages/forms-web-app/src/middleware/check-logged-in.js, packages/forms-web-app/src/middleware/check-logged-in.test.js, packages/forms-web-app/src/middleware/lpa-dashboard/require-user.js
https://pins-ds.atlassian.net/browse/AAPD-1649
=> feat(aapd-1649): set idle + absolute expiry for user sessions

package-lock.json, packages/forms-web-app/package.json, packages/forms-web-app/src/app.js, packages/forms-web-app/src/csp.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/task-list/index.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/task-list/questionnaire.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/task-list/submission.njk, packages/forms-web-app/src/views/appellant-submission/site-access-safety.njk, packages/forms-web-app/src/views/appellant-submission/submission-information.njk, packages/forms-web-app/src/views/eligibility/planning-department.njk, packages/forms-web-app/src/views/full-appeal/local-planning-department.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/declaration-information.njk, packages/forms-web-app/src/views/includes/head.njk, packages/forms-web-app/src/views/includes/scripts.njk, packages/forms-web-app/src/views/manage-appeals/appeal-details.njk
https://pins-ds.atlassian.net/browse/AAPD-1496
Switched to using helmet as it seems like it is kept more up to date than lusca and aligns us with other projects
=> feat(aapd-1496): sort out security headers

packages/forms-web-app/src/dynamic-forms/controller.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/submission-screen/appellant.njk
=> fix(aapd-1495): amend submission copy

packages/appeals-service-api/src/services/back-office-v2/index.js
=> fix: fix declaration page error

azure-pipelines-build.yml
=> fix: include all root node_modules in functions

packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/AAPD-1555
=> fix(aapd-1555): correct ownsAllLand question url

packages/appeals-service-api/src/lib/notify.js, packages/appeals-service-api/src/services/back-office-v2/index.js
https://pins-ds.atlassian.net/browse/AAPD-1518
Fixes issues with the submit has form functions:
- adds another check for retrieving lpaCode
- pulls email from the user object rather than appellantSubmission
=> fix(1518): correct lpa look up and email

packages/appeals-service-api/src/lib/notify.js
https://pins-ds.atlassian.net/browse/AAPD-1518
dummy pdf link
=> fix(1518): add dummy pdf download link

packages/common/src/client/appeals-api-client.js, packages/common/src/constants.js, packages/common/src/view-model-maps/events.js, packages/common/src/view-model-maps/index.js, packages/database/src/seed/data-dev.js, packages/forms-web-app/src/controllers/selected-appeal/index.js, packages/forms-web-app/src/views/selected-appeal/appeal.njk
https://pins-ds.atlassian.net/browse/AAPD-1684
=> feat(aapd-1684): show access required site visits to appellants

packages/forms-web-app/src/dynamic-forms/controller.js, packages/forms-web-app/src/dynamic-forms/controller.test.js, packages/forms-web-app/src/routes/appellant-submission/submission-form.js
- Move appeal specific task list code into appeal router
- Would be nice to think a sensible means of testing this
=> fix: move appeal specific code out of controller shared with lpaq

packages/forms-web-app/src/dynamic-forms/dynamic-components/submission-screen/appellant.njk
https://pins-ds.atlassian.net/browse/AAPD-1734
Use correct link for feedback survey following submission of appeal
=> feat(1734): correct link for post submission survey

packages/forms-web-app/src/controllers/appeals/continue.js
https://pins-ds.atlassian.net/browse/AAPD-1730
Refactors dynamic generation of continue link in appellant dashboard in order to accoutn for s78 journey
=> feat(1730): refactor continue link from dashboard

packages/database/src/seed/data-dev.js
=> fix: fix test data for site visit accessRequired

packages/forms-web-app/src/services/pdf.service.js
https://pins-ds.atlassian.net/browse/AAPD-1755
=> fix(1755): sort fetch import

packages/forms-web-app/src/dynamic-forms/dynamic-components/list-add-more/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-file-upload/question.js, packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/AAPD-1733
Correct text used on task list display
- [X My commit history in this PR is linear
=> fix(1773): fixes task list display inconsistencies

packages/appeals-service-api/src/repositories/sql/service-user-repository.js, packages/appeals-service-api/src/routes/v2/service-users/controller.js, packages/appeals-service-api/src/routes/v2/service-users/index.js, packages/appeals-service-api/src/routes/v2/service-users/index.spec.js, packages/appeals-service-api/src/routes/v2/service-users/service.js, packages/appeals-service-api/src/routes/v2/service-users/spec.yaml, packages/appeals-service-api/src/spec/api-types.d.ts, packages/appeals-service-api/src/spec/service-user.yaml, packages/common/src/middleware/async-handler.js, packages/database/src/migrations/20231120091203_users/migration.sql, packages/database/src/migrations/20240614133557_augment_service_user/migration.sql, packages/database/src/migrations/20240618111850_update_service_user_id_type/migration.sql, packages/database/src/schema.prisma
=> feat(ASI-58): add service-user API

packages/database/src/migrations/20231120091203_users/migration.sql, packages/database/src/migrations/20240618111850_update_service_user_id_type/migration.sql
=> fix(ASI-58): drop index in migration

packages/appeals-service-api/src/services/back-office-v2/formatters/utils.js, packages/common/src/document-types.js, packages/forms-web-app/src/dynamic-forms/questions.js
=> fix: add document types to mapper

.eslintrc.js, packages/appeals-service-api/src/routes/v2/documents/controller.js, packages/appeals-service-api/src/routes/v2/documents/index.js, packages/appeals-service-api/src/routes/v2/documents/index.spec.js, packages/appeals-service-api/src/routes/v2/documents/repo.js, packages/appeals-service-api/src/routes/v2/documents/service.js, packages/appeals-service-api/src/routes/v2/documents/spec.yaml, packages/database/src/migrations/20240620104234_add_data_model_document_fields/migration.sql, packages/database/src/schema.prisma
=> feat(ASI-55): add documents api

packages/common/src/document-types.js, packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-appeal-form/journey.js, packages/forms-web-app/src/public/resources/upload-statement-common-ground/content.html
https://pins-ds.atlassian.net/browse/AAPD-1790
Adds statement of common ground upload question, with condition relating to procedure preference
=> feat(1790): add statement common ground question

package-lock.json, packages/common/package.json, packages/common/src/client/appeals-api-client.js, packages/integration-functions/__tests__/functions/appeal-service-user.test.js, packages/integration-functions/src/functions/appeal-service-user.js
=> feat(ASI-67): service user consumer

packages/common/src/client/appeals-api-client.js, packages/integration-functions/__tests__/functions/appeal-document.test.js, packages/integration-functions/src/functions/appeal-document.js
=> feat(ASI-65): document meta comsumer

packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/AAPD-1779
correct error message text
=> fix(aapd-1779): correct error msgs for inquiry how many days question

packages/common/src/client/appeals-api-client.js, packages/integration-functions/__tests__/functions/appeal-event.test.js, packages/integration-functions/src/functions/appeal-event.js
=> feat(asi-57): add appeal-event int func logic

packages/appeals-service-api/src/repositories/sql/service-user-repository.js, packages/appeals-service-api/src/routes/v2/documents/controller.js, packages/appeals-service-api/src/routes/v2/documents/repo.js, packages/appeals-service-api/src/routes/v2/documents/service.js, packages/appeals-service-api/src/routes/v2/documents/spec.yaml, packages/appeals-service-api/src/routes/v2/service-users/controller.js, packages/appeals-service-api/src/spec/api-types.d.ts, packages/appeals-service-api/src/spec/data-model-document.yaml
=> fix(asi-115): add data model doc schema

packages/integration-functions/src/common/config.js
=> fix(asi-115): update config

packages/database/src/seed/lpa-appeal-case-data-dev.js
https://pins-ds.atlassian.net/browse/AAPD-1676
updates data to withdraw an appeal for testing
=> refactor(aapd-1676): update data to withdraw appeal for testing

azure-pipelines-pr.yml
=> ci: update pipeline templates for merge queues

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/public/resources/upload-statement-common-ground/content.html
https://pins-ds.atlassian.net/browse/AAPD-1790
Hint text has been removed form copy deck so is removed here
=> fix(1790): remove hint on upload common ground statement question

packages/common/src/view-model-maps/appeal-headline.js, packages/forms-web-app/src/controllers/selected-appeal/appellant-sections.js, packages/forms-web-app/src/controllers/selected-appeal/ip-comment-details/index.js, packages/forms-web-app/src/controllers/selected-appeal/lpa-user-sections.js, packages/forms-web-app/src/lib/views.js, packages/forms-web-app/src/routes/appeals/selected-appeal/selected-appeal.js, packages/forms-web-app/src/routes/lpa-dashboard/selected-appeal.js, packages/forms-web-app/src/views/selected-appeal/ip-comment-details.njk
https://pins-ds.atlassian.net/browse/AAPD-1065
https://pins-ds.atlassian.net/browse/AAPD-1090
https://pins-ds.atlassian.net/browse/AAPD-1093
https://pins-ds.atlassian.net/browse/AAPD-1134
adds routes to interested party comment details pages for both appellant and lpa views
=> feat(aapd-1065): ip comment details page

packages/appeals-service-api/src/routes/v2/documents/controller.js, packages/appeals-service-api/src/routes/v2/documents/index.js, packages/appeals-service-api/src/routes/v2/documents/index.spec.js, packages/appeals-service-api/src/routes/v2/documents/repo.js, packages/appeals-service-api/src/routes/v2/documents/service.js, packages/common/src/client/appeals-api-client.js, packages/integration-functions/__tests__/functions/appeal-document.test.js, packages/integration-functions/src/functions/appeal-document.js
=> feat(asi-121): add document delete function

azure-pipelines-deploy.yml
Deploys integration functions by default, previously wasn't due to being rarely touched + very slow to deploy
Neither of those reasons are true anymore
=> chore: deploy integration functions by default (time has been reduced)

packages/appeals-service-api/src/services/back-office-v2/formatters/utils.js
https://pins-ds.atlassian.net/browse/asi-109
Adds some missing doc types from LPAQ
=> feat(asi-109): add additional doc types to bo mapping

package-lock.json, packages/appeals-service-api/package.json, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/submit/index.test.js, packages/appeals-service-api/src/routes/v2/appellant-submissions/_id/submit/index.test.js, packages/appeals-service-api/src/services/back-office-v2/formatters/has/appeal.js, packages/appeals-service-api/src/services/back-office-v2/formatters/utils.js, packages/appeals-service-api/src/spec/api-types.d.ts, packages/appeals-service-api/src/spec/appellant-submission.yaml, packages/database/src/migrations/20240708095000_update_phone_number_field_name/migration.sql, packages/database/src/schema.prisma, packages/forms-web-app/src/dynamic-forms/questions.js
=> feat(asi-117): add missing appellant submission command fields

packages/forms-web-app/src/lib/views.js, packages/forms-web-app/src/views/error/firewall-error.njk, packages/forms-web-app/src/views/error/service-unavailable.njk
https://pins-ds.atlassian.net/browse/AAPD-926
Adds generic content to help users who run into firewall blocks
=> feat(aapd-926): generic content for firewall error page

packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/A2-462
correct how upload separate ownership certificate question is displayed on task list
=> refactor(a2-462): amend question title to correct row on task list page

packages/appeals-service-api/src/routes/v2/appellant-submissions/_id/controller.js, packages/appeals-service-api/src/routes/v2/appellant-submissions/_id/index.js, packages/appeals-service-api/src/routes/v2/appellant-submissions/_id/service.js, packages/common/src/client/appeals-api-client.js, packages/forms-web-app/src/controllers/document.js
https://pins-ds.atlassian.net/browse/A2-489
Amend route for confirming user and appeallant submission linked when downloading appeal
=> fix(489): amend confirm user route for download

packages/appeals-service-api/src/routes/v2/appellant-submissions/spec.yaml, packages/forms-web-app/src/controllers/document.js
=> feat(459): submission

packages/forms-web-app/__tests__/unit/controllers/appeals/your-appeals.test.js, packages/forms-web-app/__tests__/unit/controllers/appeals/your-appeals/decided-appeals.test.js, packages/forms-web-app/__tests__/unit/controllers/common/enter-code.test.js, packages/forms-web-app/__tests__/unit/controllers/common/request-new-code.test.js, packages/forms-web-app/__tests__/unit/controllers/common/your-email-address.test.js, packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/add-remove-users.test.js, packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/confirm-add-user.test.js, packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/confirm-remove-user.test.js, packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/service-invite.test.js, packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/your-appeals.test.js, packages/forms-web-app/__tests__/unit/services/user.service.test.js, packages/forms-web-app/src/controllers/common/email-address.js, packages/forms-web-app/src/controllers/common/enter-code.js, packages/forms-web-app/src/controllers/common/request-new-code.js, packages/forms-web-app/src/controllers/common/your-email-address.js, packages/forms-web-app/src/controllers/lpa-dashboard/add-remove-users.js, packages/forms-web-app/src/controllers/lpa-dashboard/confirm-add-user.js, packages/forms-web-app/src/controllers/lpa-dashboard/confirm-remove-user.js, packages/forms-web-app/src/controllers/lpa-dashboard/service-invite.js, packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response-for-lpa.test.js, packages/forms-web-app/src/lib/appeals-api-client.js, packages/forms-web-app/src/services/user.service.js
Replaces all uses of unauthorized api client with the authorized client attached to req
=> chore: remove all instances of api client without auth

packages/database/src/migrations/20240718160257_add_submission_dates/migration.sql, packages/database/src/schema.prisma
- Adds created/updated dates to main submission tables to help with debugging/auditing
=> feat: add submission dates

packages/forms-web-app/src/lib/documents-api-wrapper.js
https://pins-ds.atlassian.net/browse/A2-603
These unfortunately aren't all uuids, have reverted to a path traversal in the handler
=> fix(a2-603): use simpler check for doc ref as not all are uuids

packages/appeals-service-api/src/routes/v2/interested-party-submissions/controller.js, packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/check-answers/controller.js, packages/forms-web-app/src/services/interested-party.service.js
https://pins-ds.atlassian.net/browse/A2-270
Fix to remove submitted field from ip data sent to api
=> fix(a2-270): update ipsubmission data

packages/forms-web-app/src/views/appeal-householder-decision/list-of-documents.njk
https://pins-ds.atlassian.net/browse/A2-569
Update list of docs copy for HAS V2
=> feat(a2-569): update list of docs copy for has v2

packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/check-answers/controller.js
https://pins-ds.atlassian.net/browse/A2-177
correct field name
=> fix(177): typo

packages/forms-web-app/src/dynamic-forms/controller.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/submission-information/index.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/utils/submission-information-utils.js, packages/forms-web-app/src/dynamic-forms/has-appeal-form/journey.js, packages/forms-web-app/src/dynamic-forms/s78-appeal-form/journey.js, packages/forms-web-app/src/routes/appellant-submission/submission-form.js
=> fix(489): add css to page

packages/common/src/client/documents-api-client.js, packages/document-service-api/src/db/repos/repository.js, packages/document-service-api/src/routes/v2/back-office/controller.js, packages/document-service-api/src/routes/v2/submission-document/_id/controller.js, packages/document-service-api/src/routes/v2/submission-document/_id/index.js, packages/document-service-api/src/routes/v2/submission-document/_id/spec.yaml, packages/document-service-api/test/developer/developer.test.js
Adds an endpoint for deleting submission docs by id
=> feat: add remove submission doc endpoint

packages/forms-web-app/src/controllers/selected-appeal/index.js, packages/forms-web-app/src/views/selected-appeal/appeal.njk
https://pins-ds.atlassian.net/browse/A2-470
Action banners for final comments and statements due
=> feat(a2-470): action banners for final comments and statements due

packages/appeals-service-api/src/spec/data-model-document.yaml
https://pins-ds.atlassian.net/browse/ASI-141
These fields are not required and are causing docs to 400
=> fix(asi-141): remove nullable fields from required list for bo documents

packages/database/src/seed/lpa-appeal-case-data-dev.js, packages/forms-web-app/src/controllers/selected-appeal/index.js, packages/forms-web-app/src/views/selected-appeal/appeal.njk
https://pins-ds.atlassian.net/browse/AAPD-470
https://pins-ds.atlassian.net/browse/AAPD-471
https://pins-ds.atlassian.net/browse/AAPD-472
correct action banner display and add data to display the banners
=> fix(A2-471): correct action banner display and add data

packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/site-access-details-rows.js
=> fix(asi-113): fix has-neighbours check

packages/common/src/client/blob-storage-client.js
https://pins-ds.atlassian.net/browse/asi-149
This removes the host from a BO blob if the container name is not included in the url
=> fix(asi-149): remove host from blob url if container is not provided

packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-documents-rows.js, packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/appeals/_appealNumber/ip-application-rows.js
https://pins-ds.atlassian.net/browse/asi-150
=> fix(asi-150): use data model doc type for displaying decision letter

packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-statement-submission/controller.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-statement-submission/index.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-statement-submission/repo.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-statement-submission/service.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-statement-submission/spec.yaml, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-statement-submission/statement.spec.js, packages/appeals-service-api/src/spec/api-types.d.ts, packages/appeals-service-api/src/spec/lpa-statement-submission.yaml, packages/common/src/client/appeals-api-client.js, packages/common/src/dynamic-forms/journey-types.js, packages/database/src/migrations/20240812150501_lpa_statment_submission/migration.sql, packages/database/src/schema.prisma, packages/forms-web-app/__tests__/unit/lib/dashboard-functions.spec.js, packages/forms-web-app/src/config.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/task-list/statement.njk, packages/forms-web-app/src/dynamic-forms/journey-factory.js, packages/forms-web-app/src/dynamic-forms/journey.js, packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response-for-lpa-statement.js, packages/forms-web-app/src/dynamic-forms/middleware/redirect-to-unanswered-question.js, packages/forms-web-app/src/dynamic-forms/middleware/set-default-section.js, packages/forms-web-app/src/dynamic-forms/question.js, packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-lpa-statement/journey.js, packages/forms-web-app/src/dynamic-forms/s78-lpa-statement/journey.test.js, packages/forms-web-app/src/dynamic-forms/statement-template.njk, packages/forms-web-app/src/lib/dashboard-functions.js, packages/forms-web-app/src/public/resources/lpa-statement/content.html, packages/forms-web-app/src/routes/lpa-dashboard/index.js, packages/forms-web-app/src/routes/lpa-dashboard/statement.js, packages/forms-web-app/src/views/manage-appeals/your-appeals.njk
https://pins-ds.atlassian.net/browse/AAPD-234
sets up new journey for lpa statement submission and adds appeal statement question
=> feat(A2-234): lpa statement journey set up and statement question

packages/appeals-service-api/src/routes/v2/appeal-cases/repo.js, packages/database/src/migrations/20240813152427_add_sanitized_postcode_fields/migration.sql, packages/database/src/schema.prisma
Adds a sanitized postcode for easier searching on DB
=> feat: add sanitized postcode field for easier searches in future

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/public/resources/lpa-statement/content.html
https://pins-ds.atlassian.net/browse/A2-234
update question to match updated copy deck
=> fix(A2-234): correct question as per copy deck

packages/appeals-service-api/src/spec/api-types.d.ts, packages/appeals-service-api/src/spec/lpa-questionnaire-submission.yaml, packages/database/src/migrations/20240904163253_has_upload_plans_drawings/migration.sql, packages/database/src/schema.prisma, packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/A2-889
Add question for LPA to upload plans on HAS Questionnaire journey.  Updates QuestionnaireSubmission table.
=> feat(a2-889): add question for lpa to upload plans in has quesitonnaire

azure-pipelines-deploy.yml, packages/forms-web-app/src/routes/index.js
Integration function couldn't be deployed
v1 document downloads caught by v2 route
=> fix: download function artifact

packages/forms-web-app/src/routes/lpa-dashboard/questionnaire.js
https://pins-ds.atlassian.net/browse/A2-880
changes back link on questionnaire task list page to navigate back to your appeals page
=> refactor(A2-880): amend back link on questionnaire task list

packages/forms-web-app/src/dynamic-forms/statement-template.njk
https://pins-ds.atlassian.net/browse/A2-234
Removes the return to task list link from lpa statement question pages as per copy deck
=> refactor(A2-234): remove return to journey task list link

packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-field-input/index.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/radio/index.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/unit-option-entry/index.njk, packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/a2-635
FIeldsets had no legends
This change uses the h1 as the legend
=> fix(a2-635): use fieldsets correctly for radio/checkbox questions

packages/forms-web-app/src/controllers/selected-appeal/index.js
Times in UTC
Needs converting to UK time before displaying to user
=> fix: format date notifications in UK timezone

packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response-for-appellant-final-comments.js, packages/forms-web-app/src/routes/appeals/final-comments/index.js
https://pins-ds.atlassian.net/browse/A2-246
Fix following updating of redirectToUnansweredQuestion function
=> fix(a2-246): fix redirect to unanswered question for appellantFC

packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/appellant-final-comment-submission/document-upload/controller.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/appellant-final-comment-submission/document-upload/index.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/appellant-final-comment-submission/document-upload/repo.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/appellant-final-comment-submission/document-upload/service.js, packages/common/src/client/appeals-api-client.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-file-upload/question.js, packages/forms-web-app/src/dynamic-forms/question.js
=> fix(a2-253): fix persistance of final comment answers and doc upload

packages/common/src/client/appeals-api-client.js, packages/forms-web-app/__tests__/unit/lib/dashboard-functions.spec.js, packages/forms-web-app/src/dynamic-forms/final-comments-template.njk, packages/forms-web-app/src/dynamic-forms/journey-factory.js, packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response-for-lpa-final-comments.js, packages/forms-web-app/src/dynamic-forms/s78-lpa-final-comments/journey.js, packages/forms-web-app/src/lib/dashboard-functions.js, packages/forms-web-app/src/routes/lpa-dashboard/final-comments.js, packages/forms-web-app/src/routes/lpa-dashboard/index.js
https://pins-ds.atlassian.net/browse/A2-248 - set up steps
Final setup steps for lpa final comments - middleware, journey.
=> feat(a2-248): lpa final comments setup

packages/appeals-service-api/src/controllers/token.js, packages/auth-server/__tests__/tests.spec.js, packages/auth-server/src/grants/ropc-grant-handler.js
https://pins-ds.atlassian.net/browse/a2-1014
v1/v2 codes ignore case in codes
=> fix(a2-1014): case insensitive token check

packages/forms-web-app/src/app.js, packages/forms-web-app/src/robots.txt
Adds robots.txt to ask crawlers to crawl site slowly
=> chore: add robots.txt

packages/common/src/frontend/pins/components/footer.njk, packages/forms-web-app/src/views/accessibility-statement/accessibility-statement.njk, packages/forms-web-app/src/views/components/footer/footer.njk, packages/forms-web-app/src/views/error/400.njk, packages/forms-web-app/src/views/error/401.njk, packages/forms-web-app/src/views/error/unhandled-exception.njk, packages/forms-web-app/src/views/layouts/comment-planning-appeal/main-no-back-link.njk, packages/forms-web-app/src/views/layouts/comment-planning-appeal/main.njk, packages/forms-web-app/src/views/layouts/full-appeal-banner/main-no-back-link.njk, packages/forms-web-app/src/views/layouts/full-appeal-banner/main.njk, packages/forms-web-app/src/views/layouts/guidance-page.njk, packages/forms-web-app/src/views/layouts/householder-banner/main-no-back-link.njk, packages/forms-web-app/src/views/layouts/householder-banner/main.njk, packages/forms-web-app/src/views/layouts/lpa-dashboard/main-no-back-link.njk, packages/forms-web-app/src/views/layouts/lpa-dashboard/main.njk, packages/forms-web-app/src/views/layouts/main-no-back-link.njk, packages/forms-web-app/src/views/layouts/main.njk, packages/forms-web-app/src/views/layouts/multi-file-upload.njk, packages/forms-web-app/src/views/layouts/no-banner-link/main-no-back-link.njk, packages/forms-web-app/src/views/layouts/no-banner-link/main.njk, packages/forms-web-app/src/views/manage-appeals/lpa-dashboard.njk
https://pins-ds.atlassian.net/browse/a2-632
Skip link goes to main content, skipping repeated sections banner + back link
=> fix(a2-632): skip link goes to main content

packages/forms-web-app/src/views/layouts/no-banner-link/main-no-back-link.njk
https://pins-ds.atlassian.net/browse/a2-632
=> fix(a2-632): fix missing quote on layout page

packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-field-input/index.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-field-input/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/single-line-input/index.njk, packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/a2-876
=> fix(a2-876): add input attributes

packages/appeals-service-api/src/controllers/token.js, packages/auth-server/src/account/account.js, packages/auth-server/src/account/repository.js, packages/auth-server/src/grants/ropc-grant-handler.js, packages/common/src/client/appeals-api-client.js, packages/common/src/client/appeals-api-client.test.js, packages/common/src/lib/address.js, packages/forms-web-app/src/controllers/common/email-address.js, packages/forms-web-app/src/controllers/common/enter-code.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/boolean/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/case-add-more/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/date/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/listed-building-add-more/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-field-input/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/unit-option-entry/question.js, packages/forms-web-app/src/dynamic-forms/options-question.js
=> chore: trim input fields

packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/A2-889
Copy update
=> fix(a2-889): fix typos in copy for uploadPlansDrawingsHAS question

packages/forms-web-app/src/dynamic-forms/dynamic-components/date/question.js
https://pins-ds.atlassian.net/browse/A2-1155
=> fix(a2-1155): don't trim date inputs

azure-pipelines-deploy.yml, azure-pipelines-release.yml
Ticket number: DEV-285
Ticket link: https://pins-ds.atlassian.net/browse/DEV-285
Parent ticket link: https://pins-ds.atlassian.net/browse/DEV-273  
Updating common pipeline tag in deploy and release pipelines as these pipelines refers to azure_web_app_deploy.yml 
Change:  Docker credentials are removed from 'azure_web_app_deploy.yml'
=> fix: Updating common pipeline tag 3.18.1 

packages/forms-web-app/__tests__/unit/controllers/common/enter-code.test.js, packages/forms-web-app/src/controllers/appeal-householder-decision/email-address.js, packages/forms-web-app/src/controllers/common/email-address.js, packages/forms-web-app/src/controllers/common/enter-code.js, packages/forms-web-app/src/controllers/common/your-email-address.js, packages/forms-web-app/src/services/user.service.js
https://pins-ds.atlassian.net/browse/A2-852
Returning users occasionally experience a log in loop
This clears the user from session at the start of log in journeys to avoid any issues
=> fix(a2-852): clear existing user from session after entering email

packages/appeals-service-api/src/services/back-office-v2/formatters/has/appeal.js, packages/appeals-service-api/src/services/back-office-v2/formatters/s78/appeal.js
=> fix: use data model for caseType/procedure in mapping

packages/common/src/document-types.js, packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-documents-rows.js, packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-documents-rows.test.js, packages/forms-web-app/src/controllers/selected-appeal/planning-obligation-details/planning-obligation-details-rows.js, packages/forms-web-app/src/controllers/selected-appeal/planning-obligation-details/planning-obligation-details-rows.test.js, packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/constraints-details-rows.js, packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/constraints-details-rows.test.js, packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/consultation-details-rows.js, packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/consultation-details-rows.test.js, packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/environmental-details-rows.js, packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/environmental-details-rows.test.js, packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/planning-officer-details-rows.js, packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/planning-officer-details-rows.test.js, packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/appeals/_appealNumber/ip-appeal-submission-rows.js, packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/appeals/_appealNumber/ip-appeal-submission-rows.test.js, packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/appeals/_appealNumber/ip-application-rows.js, packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/appeals/_appealNumber/ip-application-rows.test.js
=> fix: use data model doc types on dashboards

packages/forms-web-app/src/dynamic-forms/dynamic-components/radio/index.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/radio/question.js, packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/public/resources/health-and-safety/content.html
https://pins-ds.atlassian.net/browse/a2-638
=> fix(a2-638): remove duplicate legend

packages/appeals-service-api/src/services/back-office-v2/index.js
=> fix(a2-273): amend check on serviceuser for appellant FC submission

packages/forms-web-app/src/dynamic-forms/controller.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/boolean/index.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/boolean/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/list-add-more/question.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/list-add-more/question.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/listed-building-add-more/question.js, packages/forms-web-app/src/dynamic-forms/middleware/redirect-to-unanswered-question.js, packages/forms-web-app/src/dynamic-forms/middleware/utils.test.js, packages/forms-web-app/src/dynamic-forms/question-props.d.ts, packages/forms-web-app/src/dynamic-forms/question.js, packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/validator/validator.test.js
=> refactor(a2-1099): create question prop type d

README.md
Update tldr set up with required steps - based on recent onboarding experience.
=> docs: update readme tldr

packages/forms-web-app/src/views/appeal-householder-decision/list-of-documents.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/list-of-documents.njk
https://pins-ds.atlassian.net/browse/A2-779
Update title for list of documents page to reflect revised journey and urls
=> fix(a2-779): amend page title

packages/forms-web-app/src/dynamic-forms/dynamic-components/submission-screen/appellant.njk
[A2-1249 Appeal a planning decision feedback form - October 2024 version](https://pins-ds.atlassian.net.mcas.ms/browse/A2-1249)
Feedback form on appellant 'Appeal submitted' page replaced
=> fix(A2-1249): appellant feedback form updated

packages/appeals-service-api/__tests__/developer/repositories/appeal-user-repository.test.js, packages/appeals-service-api/src/repositories/sql/appeal-user-repository.js, packages/appeals-service-api/src/routes/v2/users/controller.js, packages/appeals-service-api/src/routes/v2/users/service.js, packages/appeals-service-api/src/routes/v2/users/users.spec.js, packages/appeals-service-api/src/spec/api-types.d.ts, packages/appeals-service-api/src/spec/appeal-user.yaml, packages/common/src/client/appeals-api-client.js, packages/forms-web-app/__tests__/unit/controllers/rule-6/enter-code.test.js, packages/forms-web-app/src/controllers/rule-6/enter-code.js, packages/forms-web-app/src/controllers/rule-6/your-appeals.js, packages/forms-web-app/src/middleware/rule-6/require-user.js, packages/forms-web-app/src/routes/rule-6/your-appeals.js, packages/forms-web-app/src/services/user.service.js, packages/forms-web-app/src/views/rule-6/your-appeals.njk
=> feat(a2-1239): add rule 6 user middleware

packages/forms-web-app/__tests__/unit/controllers/rule-6/email-address.test.js, packages/forms-web-app/__tests__/unit/controllers/rule-6/enter-code.test.js, packages/forms-web-app/src/controllers/rule-6/email-address.js, packages/forms-web-app/src/controllers/rule-6/enter-code.js, packages/forms-web-app/src/views/rule-6/email-address.njk, packages/forms-web-app/src/views/rule-6/enter-code.njk, packages/forms-web-app/src/views/rule-6/request-new-code.njk
https://pins-ds.atlassian.net/browse/A2-1202
Updates the copy and error messages for rule 6 login pages
=> fix(a2-1202): fix copy on rule 6 log in pages

packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/comment-submitted/index.njk
[A2-1313 Comment on a planning appeal feedback form - October 2024 version](https://pins-ds.atlassian.net.mcas.ms/browse/A2-1313)
Feedback form on third party comments 'Comment submitted' page replaced
=> fix(A2-1313): comment feedback form updated

packages/forms-web-app/__tests__/unit/controllers/rule-6/enter-code.test.js, packages/forms-web-app/__tests__/unit/validators/common/enter-code.test.js, packages/forms-web-app/src/controllers/rule-6/enter-code.js, packages/forms-web-app/src/validators/common/enter-code.js
https://pins-ds.atlassian.net/browse/A2-1207
Updates error messages and page rendering when entering incorrect codes
=> fix(a2-1207): update enter code errors

.github/PULL_REQUEST_TEMPLATE.md, packages/forms-web-app/src/views/layouts/lpa-dashboard/main-no-back-link.njk, packages/forms-web-app/src/views/layouts/lpa-dashboard/main.njk
https://pins-ds.atlassian.net/browse/A2-1296
* update link URL in LPA Dashboard header, remove unnecessary serviceUrl param
* update the PR template (chore)
=> feat(a2-1296): change link in manage your appeals header

packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/planning-officer-details-rows.js, packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/planning-officer-details-rows.test.js
https://pins-ds.atlassian.net/browse/A2-748
Simple content updates.
=> feat(A2-748): update LPAQ content on dashboard

packages/common/src/document-types.js, packages/forms-web-app/src/dynamic-forms/middleware/redirect-middleware-conditions.js, packages/forms-web-app/src/dynamic-forms/proof-evidence-template.njk, packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s78-appellant-proof-evidence/journey.js, packages/forms-web-app/src/public/resources/upload-proof-evidence/witnesses-evidence.html, packages/forms-web-app/src/routes/appeals/proof-evidence/index.js
https://pins-ds.atlassian.net/browse/A2-1024
https://pins-ds.atlassian.net/browse/A2-1029
adds the witnesses questions for proof of evidence journey
=> Feat/a2 1024 PoE witnesses questions

packages/forms-web-app/src/views/rule-6/your-appeals.njk
https://pins-ds.atlassian.net/browse/A2-222 / A2-1409
Correct column header from 'Address' to 'Site address'
=> fix(a2-222): typo on rule 6 dashboard

packages/forms-web-app/src/views/layouts/lpa-dashboard/main-no-back-link.njk, packages/forms-web-app/src/views/layouts/lpa-dashboard/main.njk
https://pins-ds.atlassian.net/browse/A2-1257
Manage your appeals beta banner - add feedback form
=> feat(a2-1257): manage-your-appeals-banner-add-feedback

packages/forms-web-app/src/views/layouts/comment-planning-appeal/main-no-back-link.njk, packages/forms-web-app/src/views/layouts/comment-planning-appeal/main.njk
https://pins-ds.atlassian.net/browse/A2-1314
Comment on a planning appeal beta banner - add feedback form
=> feat(a2-1314): comment on a planning appeal beta banner add feedback

packages/forms-web-app/src/routes/error/index.js, packages/forms-web-app/src/routes/error/problem-with-service.js, packages/forms-web-app/src/views/error/unhandled-exception.njk
https://pins-ds.atlassian.net/browse/A2-1316
Update 'Sorry, there is a problem with the service' error message
- Replaced email link with "Submit a request - PINS" link in unhandled exception template
- Added a new route (not available in production) "/error/problem-with-service" that forces a 500 error to make the page easy to test
=> feat(a2-1316): update problem with service enquiries link

packages/forms-web-app/src/views/layouts/no-banner-link/main-no-back-link.njk
https://pins-ds.atlassian.net/browse/A2-1024
adds the error summary to the template
=> fix(A2-1024-add-witnesses): add error summary to template

packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/planning-officer-details-rows.js, packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/planning-officer-details-rows.test.js
https://pins-ds.atlassian.net/browse/A2-748
Reverting some content
=> feat(a2-748): amend planning officer rows content on has lpaq page

packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/A2-1496
Correct caption and error message for section in has lpaq
=> fix(has lpaq): correct copy errors

packages/forms-web-app/src/dynamic-forms/middleware/redirect-middleware-conditions.js, packages/forms-web-app/src/routes/lpa-dashboard/proof-evidence.js
=> refactor(A2-1074): add missing middleware condition

packages/common/src/frontend/pins/components/footer.njk, packages/forms-web-app/src/app.js, packages/forms-web-app/src/config.js, packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/not-found.njk, packages/forms-web-app/src/views/accessibility-statement/accessibility-statement.njk, packages/forms-web-app/src/views/appeal-householder-decision/enter-code.njk, packages/forms-web-app/src/views/components/footer/footer.njk, packages/forms-web-app/src/views/error/firewall-error.njk, packages/forms-web-app/src/views/error/not-found.njk, packages/forms-web-app/src/views/error/service-unavailable.njk, packages/forms-web-app/src/views/error/unhandled-exception.njk, packages/forms-web-app/src/views/guidance-pages/start-appeal.njk, packages/forms-web-app/src/views/includes/enter-security-code.njk, packages/forms-web-app/src/views/rule-6/enter-code.njk
=> fix: update support email address

packages/forms-web-app/src/dynamic-forms/dynamic-components/add-more/index.njk, packages/forms-web-app/src/dynamic-forms/questions.js
=> fix(a2-1099): fix missing list add more template

packages/forms-web-app/src/dynamic-forms/dynamic-components/submission-screen/appeal-statement.njk, packages/forms-web-app/src/dynamic-forms/dynamic-components/submission-screen/rule-6-statement.njk
https://pins-ds.atlassian.net/browse/A2-1647
Add feedback survey link to bottom of appeal statement submitted screen
=> feat(a2-1647): add feedback link

packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/index.js
https://pins-ds.atlassian.net/browse/A2-1576
Fix redirect for ip landing page
=> fix(a2-1576): fix landing page redirect for interested  parties

packages/appeals-service-api/data/lpa-list.csv
https://pins-ds.atlassian.net/browse/A2-823
Update lpa emails
=> fix(A2-823): update lpa emails

test-packages/platform-feature-tests/cypress/support/flows/sections/initialiseFullPlanning.js, test-packages/platform-feature-tests/cypress/support/flows/sections/initialiseHouseHolderPlanning.js
=> list of documents url change fixed

docker-compose.yml, packages/common/src/lib/getAzureBlobPathFromUri.js, packages/common/src/lib/getAzureBlobPathFromUri.test.js, packages/document-service-api/.env.example
https://pins-ds.atlassian.net/browse/A2-1179
- Trims trailing slash from host if present
- Adds slash to back office storage url in local dev to align with prod
=> fix(a2-1179): trim trailing slash from blob host if present

azure-pipelines-build.yml, azure-pipelines-deploy.yml, packages/appeals-service-api/Dockerfile, packages/appeals-service-api/src/configuration/config.js, packages/appeals-service-api/src/routes/index.js, packages/auth-server/Dockerfile, packages/auth-server/src/app.js, packages/auth-server/src/configuration/config.js, packages/auth-server/src/configuration/schema.js, packages/document-service-api/Dockerfile, packages/document-service-api/src/configuration/config.js, packages/document-service-api/src/routes/index.js, packages/forms-web-app/Dockerfile, packages/forms-web-app/src/config.js, packages/forms-web-app/src/routes/index.js, packages/pdf-service-api/Dockerfile, packages/pdf-service-api/src/config.js, packages/pdf-service-api/src/routes/index.js, scripts/verify_commit_hash.sh
https://pins-ds.atlassian.net/browse/A2-1616
Adds health check endpoints with current gitsha hash
Pipelines ping this endpoint to check when docker container has been pulled from registry
=> feat(a2-1616): add health check endpoint with gitsha

packages/appeals-service-api/src/routes/v2/events/repo.js, packages/database/src/migrations/20241128120133_add_event_address_fields/migration.sql, packages/database/src/schema.prisma
Store event site address data when receiving event from BO
=> chore: update Event to include address details

packages/database/src/seed/data-dev.js
Add inquiry event to seed data for case 1010101
=> chore: update seed data to include inquiry event

packages/common/src/view-model-maps/appeal-headline.js
https://pins-ds.atlassian.net/browse/A2-864
Show applicant and lpa in appeal details etc headlines for rule 6 parties
=> fix(a2-864): amend headline data for rule 6 parties

packages/database/src/seed/data-dev.js
Updating seed data events as hearing/inquiries only available for s78, not HAS, appeals.
=> chore: connect seed data hearing and inquiry events to s78 appeals

packages/common/src/view-model-maps/events.js, packages/common/src/view-model-maps/events.test.js, packages/database/src/seed/data-dev.js
https://pins-ds.atlassian.net/browse/A2-1816
Prevent unaccompanied site visit from erroring because of lack of startDate/endDate
=> fix(A2-1816): fix unaccompanied siteVisit date bug

packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/representations/controller.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/representations/index.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/representations/repo.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/representations/service.js, packages/appeals-service-api/src/spec/api-types.d.ts, packages/appeals-service-api/src/spec/document.yaml, packages/appeals-service-api/src/spec/representation-document.yaml, packages/appeals-service-api/src/spec/representation.yaml, packages/common/src/client/appeals-api-client.js, packages/common/src/constants.js, packages/database/src/migrations/20241210143606_add_representation_documents/migration.sql, packages/database/src/schema.prisma
https://pins-ds.atlassian.net/browse/A2-1749
Add RepresentationDocuments db table, representations api routes
=> feat(a2-1749): add representation documents table, api routes

packages/forms-web-app/src/dynamic-forms/controller.js, packages/forms-web-app/src/dynamic-forms/controller.test.js
https://pins-ds.atlassian.net/browse/A2-1823
- Download url was incorrect
=> fix: fix lpaq bulk download url

package-lock.json, package.json
https://pins-ds.atlassian.net/browse/A2-1910
Update clamscan due to ECONNRESET in prod
=> chore(a2-1910): update clamscan npm package

packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/comment-submitted/index.njk
https://pins-ds.atlassian.net/browse/A2-1013
updates the content of the submitted page for ip comment journey
=> refactor(A2-1013): update submitted page content

packages/forms-web-app/__tests__/unit/validators/full-appeal/email-address.test.js, packages/forms-web-app/__tests__/unit/validators/interested-parties/add-comments.test.js, packages/forms-web-app/__tests__/unit/validators/interested-parties/email-address.test.js, packages/forms-web-app/__tests__/unit/validators/interested-parties/enter-address.test.js, packages/forms-web-app/__tests__/unit/validators/interested-parties/your-name.test.js, packages/forms-web-app/src/controllers/selected-appeal/final-comments-details/index.test.js, packages/forms-web-app/src/controllers/selected-appeal/index.test.js, packages/forms-web-app/src/controllers/selected-appeal/ip-comment-details/index.test.js, packages/forms-web-app/src/controllers/selected-appeal/planning-obligation-details/index.test.js, packages/forms-web-app/src/controllers/selected-appeal/statements/index.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/utils/numeric-fields.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/utils/persisted-number-answer.test.js, packages/forms-web-app/src/lib/array-has-items.test.js, packages/forms-web-app/src/lib/arrays-equal.test.js, packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/add-comments/comment.test.js, packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/appeal-search-no-results/controller.test.js, packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/appeals/_appealNumber/controller.test.js, packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/appeals/controller.test.js, packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/check-answers/controller.test.js, packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/comment-submitted/controller.test.js, packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/email-address/controller.test.js, packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/enter-address/controller.test.js, packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/enter-appeal-reference/controller.test.js, packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/enter-postcode/controller.test.js, packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/your-name/controller.test.js, packages/forms-web-app/src/utils/appeal-sorting.test.js, packages/forms-web-app/src/utils/appeal-status.test.js, packages/forms-web-app/src/utils/filters/map-to-error-summary.test.js, packages/forms-web-app/src/utils/format-headline-text.test.js
Bumping test coverage in web for https://github.com/Planning-Inspectorate/appeal-planning-decision/pull/4005
=> chore: bump test coverage in web

packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
https://pins-ds.atlassian.net/browse/A2-1982
copy update
=> feat(a2-1982): update lpaq section title

packages/appeals-service-api/data/lpa-list.csv, packages/common/src/utils.js, packages/common/src/utils.test.js
=> feat: add 2nd test lpa

packages/common/src/document-types.js, packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-details-rows.js, packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-details-rows.test.js, packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-documents-rows.js, packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-documents-rows.test.js, packages/forms-web-app/src/controllers/selected-appeal/appeal-details/index.js, packages/forms-web-app/src/controllers/selected-appeal/appeal-details/index.test.js
https://pins-ds.atlassian.net/browse/A2-1797
Minor amends to display of appeal details, links to corresponding BO ticket A2-1915
=> feat(a2-1797): update appeal details display logic

package-lock.json, package.json, packages/appeals-service-api/__tests__/developer/globalSetup.js, packages/appeals-service-api/src/services/back-office-v2/validate.js
updates to latest data model version
=> chore: bump data model to 1.9.9

packages/appeals-service-api/src/routes/v2/documents/index.spec.js, packages/appeals-service-api/src/routes/v2/documents/repo.js
Deadletter in prod for document
This handles a simple retry if we get a unique constraint error in the upsert
This should only occur if an update happens while the create is still running
=> fix: handle race with document put calls

package-lock.json, package.json
=> chore: bump data model to latest

azure-pipelines-build.yml
=> fix: remove missing dependsOn check in pipeline

packages/common/src/client/blob-storage-client.js, packages/document-service-api/src/routes/v2/back-office/_id/controller.js
https://pins-ds.atlassian.net/browse/A2-1613
uses current filename for downloading docs
=> feat(A2-1613): align doc download name to renamed version

package-lock.json, package.json
=> fix: bump data model to 1.9.14

packages/forms-web-app/__tests__/unit/controllers/appeal-householder-decision/email-address-confirmed.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/email-address-confirmed.test.js, packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/list-of-documents.test.js, packages/forms-web-app/src/controllers/appeal-householder-decision/email-address-confirmed.js, packages/forms-web-app/src/controllers/appeal-householder-decision/list-of-documents.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/email-address-confirmed.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/list-of-documents.js
Use helper function to avoid code duplication when checking LPA against feature flag
=> chore: use feature flag helper function

packages/forms-web-app/src/views/full-appeal/can-use-service.njk, packages/forms-web-app/src/views/full-appeal/prior-approval/can-use-service.njk, packages/forms-web-app/src/views/full-appeal/removal-or-variation-of-conditions/can-use-service.njk, packages/forms-web-app/src/views/householder-planning/eligibility/can-use-service.njk, packages/forms-web-app/src/views/householder-planning/eligibility/prior-approval/can-use-service.njk, packages/forms-web-app/src/views/householder-planning/eligibility/removal-or-variation-of-conditions/can-use-service.njk
https://pins-ds.atlassian.net/browse/A2-2155
Move the enforcement notice row to reflect its new position in the BYS journey.
=> fix(a2-2155): move enforcement notice row

packages/integration-functions/__tests__/functions/appeal-event.test.js, packages/integration-functions/__tests__/functions/appeal-has.test.js, packages/integration-functions/src/common/api-client.test.js
- Fix event tests copy issue
- Bump coverage elsewhere
=> fix: improve function tests

packages/forms-web-app/src/dynamic-forms/s20-appeal-form/journey.js
https://pins-ds.atlassian.net/browse/A2-2183
removal of grant or loan question from s20 appeal form journey as will be asked in the questionnaire instead
=> fix(A2-2183): remove question from s20 appeal form journey

dev/data/Dockerfile
Resolves the workspace lookup issue in dev/data dockerfile
=> fix: fix dev data dockerfile

package-lock.json, package.json, packages/appeals-service-api/__tests__/developer/fixtures/appeals-S78-data-model.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/submit/index.spec.js, packages/appeals-service-api/src/routes/v2/appellant-submissions/_id/submit/controller.js, packages/appeals-service-api/src/routes/v2/appellant-submissions/_id/submit/index.spec.js, packages/appeals-service-api/src/services/back-office-v2/formatters/s78/appeal.js, packages/appeals-service-api/src/services/back-office-v2/formatters/s78/appeal.test.js, packages/appeals-service-api/src/services/back-office-v2/formatters/s78/questionnaire.test.js, packages/appeals-service-api/src/services/back-office-v2/formatters/utils.js, packages/common/src/constants.js, packages/database/src/schema.prisma
=> chore(chore - bump data model to 1.9.15): bump data model to 1.9.15

packages/forms-web-app/src/dynamic-forms/dynamic-components/unit-option-entry/question.js
https://pins-ds.atlassian.net/browse/A2-1994
converts the site area saved answer to a number to maintain correct persistence
=> fix(A2-1994): convert saved answer to a number

packages/common/src/database/data-static.js
=> fix(update static case status): add event related case statuses

packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/A2-1996
ended up only being one ticket to be corrected.
other tickets had back link nav handled by a separate bug ticket or nav to questions that are not included in s20 so no changes needed and special character validation will also be handled in a separate ticket
=> fix(A2-1996): correct ownsAllLand content

package-lock.json, package.json
Removes unused dep to resolve: https://github.com/Planning-Inspectorate/appeal-planning-decision/pull/4106
=> chore: remove unused dependency

packages/appeals-service-api/src/routes/v2/appellant-submissions/controller.js, packages/appeals-service-api/src/routes/v2/appellant-submissions/index.js, packages/appeals-service-api/src/routes/v2/appellant-submissions/repo.js, packages/appeals-service-api/src/routes/v2/appellant-submissions/service.js
https://pins-ds.atlassian.net/browse/A2-1107
Refactor ownership check on appellant submissions
=> feat(1107): refactor appeal submission ownership check

packages/forms-web-app/src/views/appeal-householder-decision/list-of-documents.njk, packages/forms-web-app/src/views/full-appeal/submit-appeal/list-of-documents.njk
A2-504
https://pins-ds.atlassian.net/browse/A2-504
Added full stop at the end of the sentences
=> fix: added full stop at the ennd of sentence

packages/appeals-service-api/src/spec/api-types.d.ts, packages/appeals-service-api/src/spec/lpa-questionnaire-submission.yaml, packages/database/src/migrations/20250310131829_removed_duplicate_and_reused_existing_property/migration.sql, packages/database/src/schema.prisma, packages/forms-web-app/src/dynamic-forms/dynamic-components/boolean/index.njk, packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/dynamic-forms/s20-lpa-questionairre/journey.js
A2-2372
https://pins-ds.atlassian.net/browse/A2-2372
Fixed hint bug on booleans
Removed duplicate question and used the existing question in its place
=> feat: a2-2372 fixed boolean hint bug and removed duplicate question

packages/appeals-service-api/src/spec/api-types.d.ts, packages/appeals-service-api/src/spec/appeal-case.yaml, packages/common/src/lib/format-appeal-details.js, packages/common/src/lib/format-appeal-details.test.js, packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-details-rows.js, packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-details-rows.test.js, packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-documents-rows.js, packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-documents-rows.test.js
https://pins-ds.atlassian.net/browse/A2-2544
=> feat(a2-2544): display development type on dashboards

package-lock.json, package.json, packages/appeals-service-api/src/services/back-office-v2/formatters/utils.js, packages/appeals-service-api/src/services/back-office-v2/formatters/utils.test.js
https://pins-ds.atlassian.net/browse/A2-2609
Sends the address to back office if provided
=> feat(a2-2609): send ip comment address to back office

packages/forms-web-app/src/views/includes/head.njk
this fixes POST requests with Easy Auth enabled on non-live environments
=> chore: add referrer meta tag

packages/database/src/migrations/20250313125446_add_indexes/migration.sql, packages/database/src/schema.prisma
https://pins-ds.atlassian.net/browse/A2-2598
Adds indexes to foreign key refs and some other known common lookups
=> feat(a2-2598): add indexes to common lookups in sql

packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/submit/index.spec.js, packages/appeals-service-api/src/services/back-office-v2/formatters/has/questionnaire.test.js, packages/appeals-service-api/src/services/back-office-v2/formatters/s78/questionnaire.test.js, packages/appeals-service-api/src/services/back-office-v2/formatters/utils.js
https://pins-ds.atlassian.net/browse/A2-2590
Map reason for neighbour visits
=> fix(a2-2590): map reason for neighbour visits

azure-pipelines-deploy.yml
updating common pipeline tag version in deploy pipeline to 3.20.3
comparison between current and updating version : https://github.com/Planning-Inspectorate/common-pipeline-templates/compare/release/3.20.1...release/3.20.3 
=> fix(tooling): updating pipeline version to 3.20.3

packages/appeals-service-api/src/services/back-office-v2/formatters/utils.js, packages/appeals-service-api/src/services/back-office-v2/formatters/utils.test.js
Update mapped address fields to match data model
=> fix: update ip address mapping

package-lock.json, package.json, packages/appeals-service-api/src/routes/v2/appellant-submissions/_id/submit/index.spec.js, packages/appeals-service-api/src/services/back-office-v2/formatters/s78/appeal.test.js, packages/appeals-service-api/src/services/back-office-v2/formatters/utils.js
Brings command version in line with https://github.com/Planning-Inspectorate/data-model/pull/96
=> feat: updated command field name

packages/forms-web-app/src/app.js, packages/forms-web-app/src/config.js, packages/forms-web-app/src/views/layouts/comment-planning-appeal/main-no-back-link.njk, packages/forms-web-app/src/views/layouts/comment-planning-appeal/main.njk
https://pins-ds.atlassian.net/browse/A2-1686
Update feedback link for IP comment area
=> fix(a2-1686): update feedback link for IP comments

packages/appeals-service-api/__tests__/developer/fixtures/appeals-HAS-data-model.js, packages/appeals-service-api/__tests__/developer/fixtures/appeals-S78-data-model.js, packages/appeals-service-api/src/routes/v2/appeal-cases/service.js, packages/appeals-service-api/src/routes/v2/appellant-submissions/_id/submit/index.spec.js, packages/appeals-service-api/src/services/back-office-v2/formatters/has/appeal.test.js, packages/appeals-service-api/src/services/back-office-v2/formatters/s78/appeal.test.js, packages/appeals-service-api/src/services/back-office-v2/formatters/utils.js, packages/database/src/migrations/202503131127202_add_type_of_planning_application_to_appellant_submission/migration.sql, packages/database/src/schema.prisma, packages/forms-web-app/src/controllers/appeal-householder-decision/list-of-documents.js, packages/forms-web-app/src/controllers/full-appeal/submit-appeal/list-of-documents.js, packages/forms-web-app/src/dynamic-forms/controller.js
Store typeOfPlanningApplication from before you start and map to back office
=> Store and map application type

packages/common/src/lib/format-questionnaire-details.js, packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/constraints-details-rows.js, packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/constraints-details-rows.test.js, packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/environmental-details-rows.js, packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/environmental-details-rows.test.js
https://pins-ds.atlassian.net/browse/A2-2590
- Fix EIA display on dashboards
- Fix listed building display on dashboards
=> fix(a2-2590): fix eia display

packages/forms-web-app/src/public/resources/upload-appeal-statement/content.html
https://pins-ds.atlassian.net/browse/A2-2579
Small copy fix, adding sensitive information details
=> feat(a2-2579): upload statement page copy fix

docker-compose.yml
Specifies platform for a couple of images in docker-compose
Forces ARM machines to use emulation for these
=> chore: specify platform in docker-compose

azure-pipelines-deploy.yml
Adding adding app registration details for deploy web which is required for git verify to be successful after adding Microsoft authentication 
=> fix(tooling): adding app registration details for deploy web

packages/forms-web-app/src/dynamic-forms/dynamic-components/radio/index.njk
=> feat(a2-2616): hide empty paragraph on radio page

packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/public/resources/supplementary-planning-documents/content.html
https://pins-ds.atlassian.net/browse/A2-1852
Copy update - add examples of supplementary docs, update error message
=> feat(a2-1852): copy update for supplementary planning documents page

packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/enter-appeal-reference/index.njk
A2-2292
https://pins-ds.atlassian.net/browse/A2-2292
Updated template as per copy deck
=> fix: a2-2292 updated template as per copy deck

packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/A2-2580
corrects url for upload question that follows new boolean question
=> fix(A2-2580): correct upload question url

packages/forms-web-app/src/dynamic-forms/questions.js
https://pins-ds.atlassian.net/browse/A2-2820
https://pins-ds.atlassian.net/browse/A2-2822
https://pins-ds.atlassian.net/browse/A2-2823
https://pins-ds.atlassian.net/browse/A2-2824
update error messages for questions in lpaq
=> feat(A2-2820): update error messages for lpaq

packages/forms-web-app/src/dynamic-forms/questions.js
A2-2815
A2-2816
https://pins-ds.atlassian.net/browse/A2-2815
https://pins-ds.atlassian.net/browse/A2-2816
Updated Error messages
=> fix: a2-2816 and a2-2816 updated error messages

packages/forms-web-app/src/views/layouts/comment-planning-appeal/main-no-back-link.njk, packages/forms-web-app/src/views/layouts/comment-planning-appeal/main.njk, packages/forms-web-app/src/views/layouts/full-appeal-banner/main-no-back-link.njk, packages/forms-web-app/src/views/layouts/full-appeal-banner/main.njk, packages/forms-web-app/src/views/layouts/householder-banner/main-no-back-link.njk, packages/forms-web-app/src/views/layouts/householder-banner/main.njk, packages/forms-web-app/src/views/layouts/lpa-dashboard/main-no-back-link.njk, packages/forms-web-app/src/views/layouts/lpa-dashboard/main.njk, packages/forms-web-app/src/views/layouts/main-no-back-link.njk, packages/forms-web-app/src/views/layouts/main.njk, packages/forms-web-app/src/views/layouts/no-banner-link/main-no-back-link.njk, packages/forms-web-app/src/views/layouts/no-banner-link/main.njk
A2-2658
https://pins-ds.atlassian.net/browse/A2-2658
added role attributes for phase banner
=> fix: a2-2658 added role attributes for phase banner

packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/enter-appeal-reference/index.njk
A2-2292
https://pins-ds.atlassian.net/browse/A2-2292
Updated page content
=> fix: updated title and paragraph of the page

packages/forms-web-app/src/dynamic-forms/questions.js
A2-2575
https://pins-ds.atlassian.net/browse/A2-2575
Updated Error message to match CD
=> fix: a2-2575 - changed error message to match cd

packages/appeals-service-api/__tests__/developer/back-office.test.js, packages/appeals-service-api/__tests__/developer/external-dependencies/rest-apis/interactions/notify-interaction.js, packages/appeals-service-api/src/configuration/config.js, packages/appeals-service-api/src/lib/notify.js, packages/appeals-service-api/src/services/back-office.service.js, packages/common/src/lib/notify/notify-service.js, packages/common/src/lib/notify/notify-service.test.js, packages/common/src/lib/notify/templates/appeal-submission/v1-follow-up-email.md, packages/common/src/lib/notify/templates/appeal-submission/v1-lpa-notification.md
https://pins-ds.atlassian.net/browse/A2-2876
https://pins-ds.atlassian.net/browse/A2-2891
https://pins-ds.atlassian.net/browse/A2-2947
Generic email templates for v1 submission follow up + lpa emails
=> v1 generic emails

packages/appeals-service-api/__tests__/setup-jest.js, packages/appeals-service-api/src/configuration/config.js, packages/appeals-service-api/src/lib/notify.js, packages/appeals-service-api/src/routes/v2/appeal-cases/appeal-cases.spec.js, packages/appeals-service-api/src/routes/v2/appellant-submissions/_id/submit/index.spec.js, packages/appeals-service-api/src/services/back-office-v2/index.js, packages/appeals-service-api/src/services/back-office-v2/index.test.js, packages/common/src/lib/notify/notify-service.js, packages/common/src/lib/notify/notify-service.test.js, packages/common/src/lib/notify/templates/appeal-submission/v2-follow-up-email.md, packages/common/src/lib/notify/templates/appeal-submission/v2-lpa-notification.md, packages/common/src/lib/notify/templates/appeal-submission/v2-submission-email.md
https://pins-ds.atlassian.net/browse/a2-2877
https://pins-ds.atlassian.net/browse/a2-2878
https://pins-ds.atlassian.net/browse/a2-2880
Using generic templates for v2 submission emails
=> feat: v2 submission emails generic

packages/forms-web-app/src/dynamic-forms/controller.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/list-add-more/question.js
https://pins-ds.atlassian.net/browse/A2-3082
=> fix(a2-3082): fix fallback for next question

packages/appeals-service-api/src/lib/notify.js, packages/appeals-service-api/src/routes/v2/interested-party-submissions/index.spec.js, packages/common/src/lib/notify/notify-service.js, packages/common/src/lib/notify/notify-service.test.js, packages/common/src/lib/notify/templates/representations/v2-ip-comment-submitted.md
https://pins-ds.atlassian.net/browse/A2-2894
Added email template for IP comments submission and updated relevant tests
=> feat(A2-2894): added template for IP comment submission

packages/appeals-service-api/src/spec/api-types.d.ts, packages/appeals-service-api/src/spec/appeal-case.yaml, packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/constraints-details-rows.js, packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/constraints-details-rows.test.js
A2-2996
https://pins-ds.atlassian.net/browse/A2-2996
Ensured the appeal type description is a variable
=> fix: changed message on questionnaire details with variable

package-lock.json, packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/index.js, packages/forms-web-app/src/lib/pdf-api-wrapper.js, packages/pdf-service-api/package.json, packages/pdf-service-api/src/config.js, packages/pdf-service-api/src/routes/pdf.js, packages/pdf-service-api/src/routes/pdf.test.js
A2-3152
https://pins-ds.atlassian.net/browse/A2-3152
Restored multer and updated unit tests etc to resolve PDF download issue
=> fix: readded multer to fix pdf download issue

packages/forms-web-app/src/controllers/selected-appeal/representations/index.js, packages/forms-web-app/src/controllers/selected-appeal/representations/representations-controller.test.js
A2-1664
https://pins-ds.atlassian.net/browse/A2-1664
Ensure all published documents are downloadable in zip
=> fix: included redacted documents in zip download

packages/appeals-service-api/__tests__/unit/repositories/sql/service-user-repository.test.js, packages/appeals-service-api/src/lib/notify.js, packages/appeals-service-api/src/repositories/sql/service-user-repository.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/rule-6-proof-evidence-submission/submit/index.spec.js, packages/appeals-service-api/src/services/back-office-v2/index.js, packages/appeals-service-api/src/services/back-office-v2/index.test.js, packages/common/src/lib/notify/notify-service.js, packages/common/src/lib/notify/notify-service.test.js, packages/common/src/lib/notify/templates/representations/v2-r6-proofs-evidence.md
https://pins-ds.atlassian.net/browse/A2-2888
adds the rule 6 proof evidence email generic template
=> feat(A2-2888): add r6 proofs generic template

packages/appeals-service-api/src/lib/notify.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/rule-6-statement-submission/submit/index.spec.js, packages/common/src/lib/notify/notify-service.js, packages/common/src/lib/notify/notify-service.test.js, packages/common/src/lib/notify/templates/representations/v2-rule6-statement-submission.md
A2-2889
https://pins-ds.atlassian.net/browse/A2-2889
added template and tests for rule 6 statement submisson
=> feat(A2-2889): added template for rule 6 statement submission

packages/forms-web-app/src/dynamic-forms/questions.js
A2-1837
https://pins-ds.atlassian.net/browse/A2-1837
Updated Error message
=> fix: updated error message

packages/forms-web-app/src/dynamic-forms/questions.js
A2-1837
https://pins-ds.atlassian.net/browse/A2-1837
Updated Error message
=> fix: updated validation message

packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/appeals/index.njk
A2-503
https://pins-ds.atlassian.net/browse/A2-503
Added new class to ensure changes are like design
=> fix: ensured columns have fixed with except for the last column

packages/forms-web-app/src/routes/appeals/selected-appeal/selected-appeal.js
A2-1644
https://pins-ds.atlassian.net/browse/A2-1644
Added route for appellant zip download
=> fix: add zip document download for appellant user

packages/forms-web-app/__tests__/unit/controllers/cookies.test.js, packages/forms-web-app/__tests__/unit/lib/client-side/cookie/cookie-jar.test.js, packages/forms-web-app/__tests__/unit/lib/flash-message.test.js, packages/forms-web-app/src/controllers/cookies.js, packages/forms-web-app/src/lib/client-side/cookie/cookie-jar.js, packages/forms-web-app/src/lib/flash-message.js, packages/forms-web-app/src/middleware/remove-unwanted-cookies.js
=> fix: fix cookie options page

packages/common/package.json
Ticket: https://pins-ds.atlassian.net/browse/A2-
=> fix(a2-3208): add nunjucks to common package

packages/forms-web-app/src/dynamic-forms/questions.js
Fixed page title for Scoping opinion page
Ticket: https://pins-ds.atlassian.net/browse/A2-2941
=> fix(A2-2941): fixed scpoing opinion boolean page title

packages/appeals-service-api/__tests__/developer/back-office.test.js, packages/appeals-service-api/__tests__/developer/external-dependencies/rest-apis/interactions/notify-interaction.js, packages/appeals-service-api/src/lib/notify.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/appellant-final-comment-submission/repo.js, packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-final-comment-submission/repo.js, packages/common/src/lib/notify/notify-service.test.js, packages/common/src/lib/notify/templates/appeal-submission/v1-follow-up-email.md, packages/common/src/lib/notify/templates/appeal-submission/v1-lpa-notification.md, packages/common/src/lib/notify/templates/appeal-submission/v1-submission-email.md, packages/common/src/lib/notify/templates/appeal-submission/v2-follow-up-email.md, packages/common/src/lib/notify/templates/appeal-submission/v2-registration-confirmation.md, packages/common/src/lib/notify/templates/appeal-submission/v2-submission-email.md, packages/common/src/lib/notify/templates/lpaq/v2-lpaq-submitted.md, packages/common/src/lib/notify/templates/representations/v2-appellant-final-comments.md, packages/common/src/lib/notify/templates/representations/v2-lpa-final-comments.md, packages/common/src/lib/notify/templates/representations/v2-lpa-proofs-evidence.md, packages/common/src/lib/notify/templates/representations/v2-lpa-statement.md, packages/common/src/lib/notify/templates/representations/v2-proof-of-evidence-submitted.md, packages/common/src/lib/notify/templates/representations/v2-r6-proofs-evidence.md, packages/common/src/lib/notify/templates/representations/v2-rule6-statement-submission.md
Ticket:
[A2-3276](https://pins-ds.atlassian.net/browse/A2-3276)
Minor content fixes for notify templates
[A2-3276]: https://pins-ds.atlassian.net/browse/A2-3276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(a2-3276): final copy and formatting adjustments for front office templates

packages/appeals-service-api/src/routes/v2/appellant-submissions/appellant-submissions.spec.js, packages/appeals-service-api/src/spec/appellant-submission.yaml
Ticket: https://pins-ds.atlassian.net/browse/A2-3359
=> fix(a2-3359): allow decimals for site area for api

package-lock.json, package.json
=> fix: bump nunjucks to latest version for cve fixes

packages/forms-web-app/src/middleware/create-api-clients.js, packages/forms-web-app/src/middleware/create-api-clients.test.js, packages/integration-functions/src/common/api-client.js
=> fix(a2-3639): handle openid-client expiry breaking change

infrastructure/.pre-commit-config.yaml, infrastructure/.terraform.lock.hcl, infrastructure/.tflint.hcl, infrastructure/data.tf, infrastructure/environments/dev.tfvars, infrastructure/environments/prod.tfvars, infrastructure/environments/test.tfvars, infrastructure/environments/training.tfvars, infrastructure/front-door.tf, infrastructure/locals.tf, infrastructure/pipelines/terraform-cd.yaml, infrastructure/pipelines/terraform-ci-commit.yaml, infrastructure/pipelines/terraform-ci.yaml, infrastructure/providers.tf, infrastructure/terraform.tfvars, infrastructure/variables.tf
[DEV-338](https://pins-ds.atlassian.net/browse/DEV-338)
Migrating Front Door Classic to Front door Premium
Adding Front door configuration files 
[DEV-338]: https://pins-ds.atlassian.net/browse/DEV-338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(infrastructure): adding front door premium 

packages/forms-web-app/__tests__/unit/lib/string-functions.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/boolean/question.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/text-entry/question.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/unit-option-entry/question.test.js, packages/forms-web-app/src/dynamic-forms/dynamic-components/utils/question-has-answer.test.js, packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response-for-appellant-final-comments.test.js, packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response-for-appellant-proof-evidence.js, packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response-for-appellant-proof-evidence.test.js, packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response-for-appellant.test.js, packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response-for-lpa-final-comments.test.js, packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response-for-lpa-proof-evidence.test.js, packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response-for-lpa-statement.test.js, packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response-for-rule-6-proof-evidence.test.js, packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response-for-rule-6-statement.test.js, packages/forms-web-app/src/dynamic-forms/middleware/get-journey.test.js, packages/forms-web-app/src/dynamic-forms/middleware/set-default-section.test.js, packages/forms-web-app/src/dynamic-forms/s78-lpa-final-comments/journey.test.js, packages/forms-web-app/src/lib/build-zip-filename.test.js, packages/forms-web-app/src/lib/determine-user.test.js
Bumps up some test coverage as part of a refactor
Caught a typo breaking middleware
=> fix: increase test coverage and fix proof of evidence middleware

packages/common/src/database/data-static.js
=> feat: update cas case letters to be unique

packages/appeals-service-api/__tests__/developer/back-office.test.js, packages/appeals-service-api/__tests__/developer/external-dependencies/rest-apis/interactions/notify-interaction.js, packages/appeals-service-api/src/routes/v2/appellant-submissions/_id/submit/index.spec.js, packages/common/src/database/data-static.js, packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/constraints-details-rows.js, packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js, packages/forms-web-app/src/lib/dashboard-functions.js, packages/forms-web-app/src/lib/full-appeal/map-planning-application.js, packages/forms-web-app/src/routes/appellant-submission/submission-form.js
Ticket: https://pins-ds.atlassian.net/browse/A2-3462
=> feat(a2-3462): consolidate appeal type naming

packages/appeals-service-api/data/lpa-list.csv
Updating csv with correct email - already in use in prod
=> fix: update north york moors email in csv

.github/CODEOWNERS
Notify tech leads about any PR with a migration
=> feat: raw sql code owners for migrations

packages/appeals-service-api/data/lpa-list.csv
Ticket: https://pins-ds.atlassian.net/browse/A2-
=> fix: update malvern email in csv

packages/forms-web-app/src/dynamic-forms/questions.js
- increasing char limit for lpa and appellant final comments
Ticket: https://pins-ds.atlassian.net/browse/A2-3994
=> feat(web): increasing char limit for final comments

packages/appeals-service-api/data/lpa-list.csv
update email for telford and wrekin council
=> feat(A2-4252): update email for telford and wrekin council

docs/before-you-start.md
Updating and simplifying the before you start documentation
=> docs: update BYS flow chart docs

infrastructure/front-door.tf
Ticket: https://pins-ds.atlassian.net/browse/A2-4440
=> fix(a2-4440): switch false positive rules in WAF to logging mode

packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/constraints-details-rows.js, packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/constraints-details-rows.test.js, packages/forms-web-app/src/dynamic-forms/adverts-questionnaire/journey.test.js, packages/forms-web-app/src/dynamic-forms/docs/adverts-lpaq-journey.md, packages/forms-web-app/src/dynamic-forms/docs/cas-adverts-lpaq-journey.md, packages/forms-web-app/src/dynamic-forms/docs/s20-lpaq-journey.md, packages/forms-web-app/src/dynamic-forms/docs/s78-lpaq-journey.md, packages/forms-web-app/src/dynamic-forms/questions.js, packages/forms-web-app/src/journeys/__snapshots__/index.test.js.snap
Ticket: https://pins-ds.atlassian.net/browse/A2-4084
=> feat(a2-4084): update wording for aonb

docker-compose.yml, packages/appeals-service-api/Dockerfile, packages/auth-server/Dockerfile, packages/document-service-api/Dockerfile, packages/forms-web-app/Dockerfile, packages/pdf-service-api/Dockerfile
Updates to alpine 3.22 to resolve security vulnerabilities
Ticket: https://pins-ds.atlassian.net/browse/a2-1841
=> fix(a2-1841): update to latest alpine image

packages/appeals-service-api/data/lpa-list.csv
Update domain restriction for Halton
Ticket: https://pins-ds.atlassian.net/browse/A2-4684
=> fix: update halton domain restriction

packages/appeals-service-api/data/lpa-list.csv
update cambridge city council lpa email
Ticket: https://pins-ds.atlassian.net/browse/A2-4686
=> fix: update cambridge city council lpa email
