.github/actions/docker/action.yml
.github/actions/semantic-release/action.yml
.github/workflows/api-microservice.yml
api-microservice/.releaserc
api-microservice/Dockerfile
api-microservice/docker-compose.yml
api-microservice/package-lock.json
api-microservice/package.json

Configure the CI/CD pipeline for the API microservice in a way that will work for future microservices
- Add CI/CD pipeline
- Build/Publish Docker images
- Generate Semantic Release version number for builds on the `master` branch - I've renamed this from `main` as the Semantic Release library doesn't yet support `main` as the [default branch](https://github.com/semantic-release/semantic-release/issues/1581)
- Generate Changelog and commit to repo
The releases are configured as a monorepo, so versions will be incremented on a per-folder (application) process. This means you can have multiple things at `v1.0.0`, which is what we want for a monorepo.
Tags/releases are tagged in format "<name>-<version>" with the name coming from `package.json`.
Docker image releases are slightly more …

Configure github actions for api microservice

---

docker-compose.yml

The use of "install then run" in docker-compose isn't suitable for production, but
this exists to make development on a machine without NodeJS possible whilst still
maintaining the ability to run volumes

chore(setup): add "npm ci" to the data run command

---

.editorconfig
Makefile
README.md
docker-compose.yml

This was working on Linux, but killing Macs

chore(setup): remove the npm ci from the docker run commands

---

forms-web-app/src/app.js

The `path.join` is designed to be used with n arguments and then puts them together
with the appropriate path separator for the operating system. Even though this will
only ever run on Linux, we should use the functions how they're designed
This commit isn't much of an issue. It really exists to trigger a new release of the
form-web-app after all the problems we've had with getting it working.

fix(assets): change how assets are linked

---

.github/actions/flux/action.yml
.github/workflows/appeals-service-api.yml
.github/workflows/forms-web-app.yml

The semantic release mechanism does not allow for tags to be clobbered locally. This breaks the flux tag, which changes dependent upon what's detected by flux on the cluster(s)

Fix git pull tag in set version

---

forms-web-app/src/controllers/eligibility.js
forms-web-app/src/views/eligibility/decision-date.njk

- Added a condition in the decision-date nunjucks template to render a date input differently if errors have been found.

fix(invalid-date): added condtional rendering of dateInput macro to show errors

---

appeals-service-api/.eslintignore
forms-web-app/.eslintignore

Eslint not ignoring node_modules on Macs

chore: add eslintignore to each package

---

forms-web-app/src/validators/eligibility/listed-building.js
forms-web-app/tests/unit/validators/eligibility/listed-building.test.js

Change to match the error message in the MS Word error doc

fix(forms-web-app): change listed building error wording when no option selected

---

forms-web-app/.eslintrc
forms-web-app/jest.config.js
forms-web-app/package.json

No ticket for this one
Adds Jest minimum coverage numbers as a baseline. Open to discussion as this may break when adding new routes. 

build(jest): add minimum coverage threshhold and reporting

---

e2e-tests/README.md
e2e-tests/cypress.json
e2e-tests/cypress/integration/PageObjects/PO_EligibilityDecisionDate.js

Introduced config (env var) to set wait interval for use in cypress e2e tests to help generate videos
suitable for demos etc. Also updated viewport height so that whole pages are captured in the videos.
UCD-988
Small refactoring step to support configuration of waiting/pausing in e2e tests.

refactor(e2e-tests): added wait config for cypress tests

---

forms-web-app/jest.config.js
forms-web-app/src/app.js
forms-web-app/src/routes/home.js
forms-web-app/src/routes/index.js
forms-web-app/tests/unit/controllers/confirmation.test.js
forms-web-app/tests/unit/controllers/index.test.js
forms-web-app/tests/unit/controllers/submission.test.js
forms-web-app/tests/unit/lib/appeals-api-wrapper.test.js
forms-web-app/tests/unit/routes/confirmation.test.js
forms-web-app/tests/unit/routes/home.test.js
forms-web-app/tests/unit/routes/index.test.js
forms-web-app/tests/unit/routes/submission.test.js

Extract routes to separate file, add missing coverage to controllers
NA - fixup previous PR order merging issue with jest minimums
Extract routes to separate file, add missing coverage to controllers

fix(forms-web-app): add further coverage to meet new jest minimums

---

.github/workflows/infra-environments.yml
infrastructure/environments/README.md
infrastructure/environments/applications.tf
infrastructure/environments/key_vault.tf
infrastructure/environments/mongodb.tf
infrastructure/environments/output.tf
infrastructure/environments/redis.tf
infrastructure/environments/storage.tf
infrastructure/k8s/setup.sh

n/a
As the Key Vault networking is limited to Azure, the VNet and the IP of the machine running Terraform, secrets cannot be read during Terraform refresh. By moving it outside of Terraform and doing it as an upsert, this avoids this failing on future runs

fix(key-vault): remove secrets from terraform

---

e2e-tests/cypress/integration/eligibility-listed-building-status.feature
e2e-tests/cypress/integration/eligibility-listed-building-status/eligibility-listed-building-status.js
e2e-tests/cypress/integration/eligibility-local-planning-department.feature
e2e-tests/cypress/integration/eligibility-local-planning-department/eligibility-local-planning-department.js
e2e-tests/cypress/support/commands.js
e2e-tests/cypress/support/eligibility-listed-building-status/confirmListedBuildingStatementIsRequired.js
e2e-tests/cypress/support/eligibility-listed-building-status/confirmListedBuildingsCannotProceed.js
e2e-tests/cypress/support/eligibility-listed-building-status/confirmUserCanProceedWithNonListedBuilding.js
e2e-tests/cypress/support/eligibility-listed-building-status/provideNoListedBuildingStatement.js
e2e-tests/cypress/support/eligibility-listed-building-status/stateCaseDoesNotInvolveAListedBuilding.js
e2e-tests/cypress/support/eligibility-listed-building-status/stateCaseInvolvesListedBuilding.js
e2e-tests/cypress/support/eligibility-local-planning-department/confirmLocalPlanningDepartmentIsNotParticipating.js
e2e-tests/cypress/support/eligibility-local-planning-department/confirmLocalPlanningDepartmentIsRequired.js
e2e-tests/cypress/support/eligibility-local-planning-department/confirmProviedLocalPlanningDepartmentWasAccepted.js
e2e-tests/cypress/support/eligibility-local-planning-department/confirmRedirectToExternalService.js
e2e-tests/cypress/support/eligibility-local-planning-department/provideLocalPlanningDepartment.js
forms-web-app/src/views/eligibility/listed-out.njk
forms-web-app/src/views/eligibility/planning-department-out.njk

Tickets from sprint 2 that are already in 'done'
retrofitting tests for:
* local planning department eligibility
* listed building eligibility

test: eligibility tests re listed building and local planning dept

---

forms-web-app/tests/unit/controllers/appellant-submission/upload-decision.test.js

The build did not get run against the previous PR which has been merged to master. This broken test
slipped through in that merge.
UCD-752
Fixes broken test for upload-decision controller.

fix(forms-web-app): fix broken test for upload-decision controller

---

docker-compose.yml
e2e-tests/create-large-test-files.sh
e2e-tests/cypress/support/appeal-statement-submission/checkNoSensitiveInformation.js
forms-web-app/src/views/appellant-submission/appeal-statement.njk
forms-web-app/src/views/appellant-submission/upload-decision.njk

UCD-1107
test(e2e-tests): updated tests to use 50MB file size limit for uploads
This affected appeal statement and decision letter file uploads.
Also fixed typo in checking sensitive information checkbox for appeal statement.

test(e2e-tests): updated tests to use 50MB file size limit for uploads

---

infrastructure/environments/kubernetes.tf

UCD-872
Remove HTTP app routing from K8S cluster - prevents incoming traffic bypassing the load balancer by going directly to the node IP Address. 

fix(security): remove http application routing from the k8s stack

---

infrastructure/k8s/nginx-ingress/configMaps/response-headers.yaml

UCD-1139
This drops the SecurityHeaders.com down to A from A+ which is still acceptable. A future piece of work should be done to put the accessibleAutocomplete inside a JS file that can be loaded from a URL or secured in [some other way](https://content-security-policy.com/examples/allow-inline-script/)

fix(security): allow unsafe-inline on script-src to allow the accessibleAutocomplete

---

forms-web-app/jest.config.js
forms-web-app/src/controllers/appellant-submission/appeal-statement.js
forms-web-app/src/controllers/appellant-submission/application-number.js
forms-web-app/src/controllers/appellant-submission/upload-application.js
forms-web-app/src/controllers/appellant-submission/upload-decision.js
forms-web-app/src/views/appellant-submission/application-number.njk
forms-web-app/tests/unit/controllers/appellant-submission/appeal-statement.test.js
forms-web-app/tests/unit/controllers/appellant-submission/application-number.test.js
forms-web-app/tests/unit/controllers/appellant-submission/upload-application.test.js
forms-web-app/tests/unit/controllers/appellant-submission/upload-decision.test.js
forms-web-app/tests/unit/validators/appellant-submission/application-number.test.js

UCD-892
add validation error message output for planning application number
fixes some missing `appeal` objects on the re-display of form views

fix(forms-web-app): add validation error message output for planning application number

---

e2e-tests/cypress/integration/appellant-confirms-ts-and-cs.feature

UCD-793 / UCD-1006
retrofitting e2e-tests for a ticket that went through under 'old rules'
- [ x ] New features have tests

test: retrofit feature file for Terms+Conditions

---

forms-web-app/src/lib/appeals-api-wrapper.js

The log level should be debug rather than warn
n/a
Change log level. Noticed error during demo

fix(appeals-api-wrapper): change log level

---

.github/workflows/infra-environments.yml

This was removed temporarily so there was always a live environment running
UCD-1174
Add the dev environment back into GitHub Actions

chore: add the dev environment back in

---

e2e-tests/cypress/integration/appellant-confirms-ts-and-cs.feature
e2e-tests/cypress/integration/appellant-confirms-ts-and-cs/appellant-confirms-ts-and-cs.js
e2e-tests/cypress/support/appellant-confirms-ts-and-cs/acceptTermsAndConditions.js
e2e-tests/cypress/support/appellant-confirms-ts-and-cs/confirmAppealNotSubmitted.js
e2e-tests/cypress/support/appellant-confirms-ts-and-cs/confirmAppealSubmitted.js
e2e-tests/cypress/support/appellant-confirms-ts-and-cs/confirmTermsAndConditionsAreRequired.js
e2e-tests/cypress/support/appellant-confirms-ts-and-cs/doNotAcceptTermsAndConditions.js
e2e-tests/cypress/support/commands.js
forms-web-app/src/views/submission.njk

UCD-793
retrofit stepdefs for UI change that is already in master

test: stepdefs for terms-and-conditions feature

---

e2e-tests/cypress/integration/appellant-submission-check-your-answers.feature

UCD-1205 / UCD-766
Feature file showing navigation from check-your-answers -> Ts+Cs page
need for this identified while trying to sgn off 766 and realising we had no proof of this
note - i don't believe we have any validation in place yet, so the actual implementation of 'given enough data/not-enough data' is a little moot at this point..

test: basic shell of Feature file for Check Your Answers

---

clusters/dev/app.yml

The forms webapp is now compatible with the appeal service api. 
Is this correct ?

chore: change forms-webapp to v2 range

---

e2e-tests/cypress/integration/appellant-submission-planning-application-number.feature
e2e-tests/cypress/integration/appellant-submission-planning-application-number/appellant-submission-planning-application-number.js
e2e-tests/cypress/support/appellant-submission-planning-application-number/confirmPlanningApplicationNumberHasNotUpdated.js
e2e-tests/cypress/support/appellant-submission-planning-application-number/confirmPlanningApplicationNumberHasUpdated.js
e2e-tests/cypress/support/appellant-submission-planning-application-number/confirmPlanningApplicationNumberRejectedBecause.js
e2e-tests/cypress/support/appellant-submission-planning-application-number/promptUserToProvidePlanningApplicationNumber.js
e2e-tests/cypress/support/appellant-submission-planning-application-number/providePlanningApplicationNumber.js
e2e-tests/cypress/support/commands.js
forms-web-app/src/views/appellant-submission/application-number.njk

UCD-1041
glue for proving validation around planning application reference number
NB these are superficial UI tests until we have a place we can prove persistence; that is noted in the @UI-ONLY tag on the feature and as //TODOs in the relevant cypress command..

test:glue code for application number; //TODO prove via API/check-your-answers

---

appeals-service-api/Dockerfile
appeals-service-api/package-lock.json
appeals-service-api/package.json
appeals-service-api/src/__tests__/appeals.spec.js
appeals-service-api/src/controllers/appeals.js
appeals-service-api/src/db/db.js
appeals-service-api/src/lib/config.js
appeals-service-api/src/lib/healthchecks.js
appeals-service-api/src/routes/api-docs.js
docker-compose.yml

UCD-985
- Include the /api folder in the Dockerfile.
- Control the location of Swagger docs via envvar
- Put the `mongo.db()` selection inside the mongodb wrapper `.get()` method
- Fix health checks

fix: include the swagger docs in the dockerfile

---

e2e-tests/cypress/support/appellant-confirms-ts-and-cs/confirmAppealNotSubmitted.js
e2e-tests/package-lock.json
e2e-tests/package.json

UCD-753
bump cypress version to fix video output; also fix demo-delay setup

ci: fix cypress delay when producing video proof on merge->master

---

appeals-service-api/src/__tests__/appeals.spec.js
appeals-service-api/src/middleware/validateAppeal.js

UCD-1057
Updated the appeals API to validate the original planning application file upload 

feat(ucd-1057): planning-file-appeals-api-validation

---

e2e-tests/cypress/integration/appeal-submission-tasklist-planningApplicationForm.feature
e2e-tests/cypress/integration/appeal-submission-tasklist-planningApplicationForm/appeal-submission-tasklist-planningApplicationForm.js
e2e-tests/cypress/support/appeal-submission-tasklist/confirmUserPresentedWithUploadAppealSubmissionDocument.js
e2e-tests/cypress/support/appeal-submission-tasklist/selectToUploadAppealSubmissionDocument.js
e2e-tests/cypress/support/commands.js

UCD-1237
retrofit e2e tests showing navigation from tasklist page -> appeal submission doc upload page

test: retrofit test for navigating->appeal-doc-upload

---

docker-compose.yml
e2e-tests/create-large-test-files.sh
forms-web-app/src/lib/file-size-display-helper.js
forms-web-app/tests/unit/lib/file-size-display-helper.test.js

UCD-880
file size display helper - 1000, not 1024

fix(forms-web-app): file size display helper - 1000, not 1024

---

forms-web-app/src/lib/documents-api-wrapper.js
forms-web-app/tests/unit/lib/documents-api-wrapper.test.js

UCD-830
Throw an error if the document API service returns an object missing an `id`
The only way I can recreate the error raised by Karuna during testing is if the `id` is either `null` or `undefined`. The only way that could happen is when the document API call returns an object that is missing an `id`. The call is wrapped in a try / catch which throws anyway.
I'm confident the unit tests cover all the outcomes here. The situation as best I can see was a hazard of having the document service in a transitional state during dev, and should not be possible moving forwards. 

fix(forms-web-app): throw if created document is missing id

---

.releaserc
README.md

UCD-1283
This configures the `develop` branch as a release candidate branch. This will require most in-sprint pull requests being raised against the `develop` branch (not the `master`). The dev cluster will track rapid changes as-is, and then pre-prod (and later, prod) will be able to track the slower changes.
The intention is that there will be fewer PRs against `master` per sprint and the minor semver number will  typically only increment once per sprint.

Configure develop branch as release candidate branch

---

e2e-tests/cypress/integration/appellant-submission-planning-application-number.feature
e2e-tests/cypress/integration/appellant-submission-planning-application-number/appellant-submission-planning-application-number.js
e2e-tests/cypress/support/appellant-submission-planning-application-number/confirmPlanningApplicationNumberHasUpdated.js
forms-web-app/src/views/appellant-submission/application-number.njk

fix(forms-web-app): use appeal.requiredDocumentsSection.applicationNumber as field value
UCD-892/UCD-1291
Improved test shows that we're not displaying the application-number properly when we re-visit the screen.

fix(forms-web-app): application number page should show value if there is one

---

forms-web-app/src/lib/count-task.js
forms-web-app/src/views/appellant-submission/task-list.njk
forms-web-app/tests/unit/controllers/appellant-submission/task-list.test.js
forms-web-app/tests/unit/lib/count-task.test.js

UCD-
Prototype: You have completed 0 of 5 sections.
Ours: You have completed 0 of 12 sections.
Sections competition is based on all sub items being complete.

fix(forms-web-app): collated section count rather than items in section

---

appeals-service-api/src/__tests__/appeals.spec.js
appeals-service-api/src/middleware/validateAppeal.js

UCD-1166
Appeals site access validation in the appeals api

feat(ucd-1166): access-appeal-site-validation-appeals-api

---

infrastructure/clusters/dev.tfvars
infrastructure/clusters/preprod.tfvars
infrastructure/common/README.md
infrastructure/environments/README.md
infrastructure/environments/horizon.tf
infrastructure/environments/local.tf
infrastructure/environments/main.tf
infrastructure/environments/variables.tf

UCD-1071
Create a VPN Link connection between our infrastructure and the infrastructure that the Horizon API lives in. This is optional (defaulting to `false`) as the VPN gateway can take up to 60 mins to provision. It's also not required in the production instance as that will be in the same subscription.

VPN Link for Horizon API

---

packages/forms-web-app/jest.config.js
packages/forms-web-app/src/controllers/appellant-submission/your-details.js
packages/forms-web-app/src/services/task-status/status-your-details.js
packages/forms-web-app/src/services/task.service.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/appeal-statement.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/applicant-name.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/application-number.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/site-access-safety.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/site-access.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/site-location.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/site-ownership-certb.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/site-ownership.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/upload-application.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/upload-decision.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/who-are-you.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/your-details.test.js
packages/forms-web-app/tests/unit/services/task-status/status-your-details.test.js
packages/forms-web-app/tests/unit/services/task.service.test.js

NA
Fixes the testing of `createOrUpdatedAppeal` payload to explicitly validate what is being passed. 

test(forms-web-app): explicit testing of createOrUpdateAppeal payload

---

charts/app/templates/ingress.yaml
charts/app/values.yaml

N/A
Adds the ability to provide redirection at the nginx level. Works with both internal and external URLs

feat(ingress): configure ingress redirects

---

packages/forms-web-app/jest.config.js
packages/forms-web-app/src/controllers/appellant-submission/upload-application.js
packages/forms-web-app/src/controllers/appellant-submission/upload-decision.js
packages/forms-web-app/src/controllers/eligibility/decision-date.js
packages/forms-web-app/src/lib/appeals-api-wrapper.js
packages/forms-web-app/src/lib/session.js
packages/forms-web-app/src/validators/appellant-submission/your-details.js
packages/forms-web-app/src/validators/eligibility/decision-date.js

N/A
Simplify the coverage configuration. Everything set to 100% and then ignored things we had excluded. It saves having to update the numbers if we add code that then changes the coverage calculations

chore(coverage): update jest config to achieve 100 coverage

---

clusters/dev/app.yml

Reverts foundry4/appeal-planning-decision#338

Revert "chore: disable http basic from dev"

---

charts/app/templates/formsWebApp.yaml
charts/app/values.yaml
packages/forms-web-app/src/lib/healthchecks.js
packages/forms-web-app/src/server.js
packages/forms-web-app/tests/unit/lib/healthchecks.test.js

UCD-1453
Change k8s so we use a health check for the forms web app, rather than the homepage. The ingress controller is configured so as to not publicly expose the /health endpoint (as per the /metrics).
The reason for this change is to avoid lots of spurious data being collected in Google Analytics

fix(healthchecks): configure forms web app for /health endpoint

---

packages/forms-web-app/src/controllers/appellant-submission/appeal-statement.js
packages/forms-web-app/src/controllers/appellant-submission/applicant-name.js
packages/forms-web-app/src/controllers/appellant-submission/application-number.js
packages/forms-web-app/src/controllers/appellant-submission/site-access-safety.js
packages/forms-web-app/src/controllers/appellant-submission/site-access.js
packages/forms-web-app/src/controllers/appellant-submission/site-location.js
packages/forms-web-app/src/controllers/appellant-submission/site-ownership-certb.js
packages/forms-web-app/src/controllers/appellant-submission/site-ownership.js
packages/forms-web-app/src/controllers/appellant-submission/supporting-documents.js
packages/forms-web-app/src/controllers/appellant-submission/upload-application.js
packages/forms-web-app/src/controllers/appellant-submission/upload-decision.js
packages/forms-web-app/src/controllers/appellant-submission/your-details.js
packages/forms-web-app/src/lib/empty-appeal.js
packages/forms-web-app/src/services/task.service.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/appeal-statement.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/applicant-name.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/application-number.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/site-access-safety.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/site-access.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/site-location.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/site-ownership-certb.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/site-ownership.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/supporting-documents.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/upload-application.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/upload-decision.test.js
packages/forms-web-app/tests/unit/controllers/appellant-submission/your-details.test.js
packages/forms-web-app/tests/unit/services/task.service.test.js

UCD-754
Extends the appeal for save and navigation feature : 
We are only skipping CANNOT START YET tasks while redirection and not COMPLETED as it used to be.

feat(forms-web-app): extends the appeal for save and navigation feature

---

.github/workflows/e2e-tests-on-PR.yml
charts/app/values.yaml
docker-compose.yml
e2e-tests/create-large-test-files.sh

UCD-1366
max file size -> 15MB instead of 50MB
note this requires the local test files to be rebuilt; this happens as a result of make install

feat: all filesize limites to 15MB not 50MB

---

clusters/dev/app.yml

Reverts foundry4/appeal-planning-decision#440
Was done for the demo. Revert once we have the correct URL pointing to the DNS - a ticket is raised, so will be done over the next few days I expect

Put the LPA Questionnaire Dev URL back to correct

---

clusters/prod/app.yml

UCD-1428
Removes the HTTP Basic password from the prod cluster. This is the last job to be done before we [push the button](https://www.youtube.com/watch?v=ZY3bcc-cKwo)

chore: remove http basic auth from prod cluster

---

infrastructure/k8s/setup.sh

UCD-1664
Apply a rolling restart to the nginx-ingress config after the `helm upgrade` has been run. This is to force the pods to restart in the event of there being a change to a ConfigMap. Helm does not detect if there has been a change to an external ConfigMap, so does not trigger a reload as part of `helm upgrade` - see issues [3868](https://github.com/kubernetes/ingress-nginx/issues/3868) and [5238](https://github.com/kubernetes/ingress-nginx/issues/5238)
By doing a rolling restart, we maintain at least 1 running pod at all times as there are 2 replicas.

fix(nginx-ingress): restart the pods after deployment to pick up configmap changes

---

packages/lpa-questionnaire-web-app/src/middleware/fetch-appeal.js
packages/lpa-questionnaire-web-app/tests/unit/middleware/fetch-appeal.test.js

AS-71
Fixes an issue where if an appeal was retrieved, but the ID in the path was changed, the system would not fetch the new ID. This has been added, the logic made a little clearer and additional test cases created.

fix(appeal-data-panel): data would not update when id changed

---

e2e-tests/cypress/integration/eligibility-appeal-householder-planning-permission.feature
packages/forms-web-app/src/config.js
packages/forms-web-app/src/controllers/index.js
packages/forms-web-app/src/views/eligibility/householder-planning-permission-out.njk
packages/forms-web-app/tests/unit/controllers/index.test.js

adds kick out page for householder planning permission
UCD-1635

feat(forms-web-app): adds kick out page for householder planning permission

---

packages/lpa-questionnaire-web-app/src/controllers/other-appeals.js
packages/lpa-questionnaire-web-app/src/controllers/placeholder.js
packages/lpa-questionnaire-web-app/src/controllers/task-list.js
packages/lpa-questionnaire-web-app/src/views/placeholder.njk
packages/lpa-questionnaire-web-app/tests/unit/controllers/other-appeals.test.js
packages/lpa-questionnaire-web-app/tests/unit/controllers/placeholder.test.js
packages/lpa-questionnaire-web-app/tests/unit/controllers/task-list.test.js

AS-83
Added backlink to session to be passed to templates later for back button functionality.

feat(lpa-questionnaire): add backlink to session for back button usage

---

charts/app/templates/lpaQuestionnaireWebApp.yaml
charts/app/values.yaml

AS-1125
Had missed out the Reply Service config URL from the questionnaire config object

chore(appeals-reply-service): add reply service url to lpq questionnaire config

---

e2e-tests/cypress/integration/appeal-submission-creation-of-submission-information-file.feature

This has already been approved - but has been lost in rebase
https://github.com/foundry4/appeal-planning-decision/pull/529

feat(e2e-tests): adds FF for Creation of submission information file

---

infrastructure/environments/README.md
infrastructure/environments/variables.tf

This is SKU doesn't work with a VMScaleSet deployment - looks like to do with multiple nodes in the K8S cluster. Switching to the Availability Zone version of the SKU fixes that.
UCD-831

fix(infrastructure): change default vpn sku to VpnGw1AZ

---

e2e-tests/cypress/integration/common/appeal-header-footer.js
e2e-tests/cypress/support/appeal-header-footer/confirmHomepageLinkIsDisplayed.js
e2e-tests/cypress/support/commands.js
packages/forms-web-app/src/views/layouts/main-no-back-button.njk
packages/forms-web-app/src/views/layouts/main.njk

AS-983
Changed link for logo in header to gov uk homepage instead of app root

fix(appeal-header): fix homepage link in layout header

---

.github/workflows/infra-environments.yml
infrastructure/k8s/setup.sh

AS-1296
Specified the versions of public Helm charts. Noticed this wasn't being set when AKV2K8S wouldn't deploy last week because they changed major versions.

chore: specify versions for the public Helm charts

---

infrastructure/clusters/dev.tfvars
infrastructure/clusters/preprod.tfvars
infrastructure/clusters/prod.tfvars
infrastructure/environments/README.md
infrastructure/environments/horizon.tf
infrastructure/environments/networks.tf
infrastructure/environments/variables.tf

This is required to avoid having a conflict with the connections on the PINS side
AS-1309
Prevents the subnets causing conflicts when connected to the Horizon VPN gateway

fix(horizon): make the horizon gateway subnet a configurable parameter

---

e2e-tests/cypress/integration/cookies-consent-bar-without-javascript-enabled.feature
e2e-tests/cypress/integration/cookies-consent-bar-without-javascript-enabled/cookies-consent-bar-without-javascript-enabled.js
e2e-tests/cypress/support/cookies/commands.js
e2e-tests/cypress/support/cookies/viewCookiePageUsingCookieConsentBannerLink.js
packages/forms-web-app/src/views/macros/cookie-banner.njk
packages/forms-web-app/tests/unit/views/macros/__snapshots__/cookie-banner.njk.test.js.snap

AS-98
adds non-JS cookie consent banner
All of this functionality was in a standalone PR: https://github.com/Planning-Inspectorate/appeal-planning-decision/pull/597
That PR was not merged, but used as a starting point for https://github.com/Planning-Inspectorate/appeal-planning-decision/pull/604/files
PR 604 *has* been merged.
PR 597 should have been incorporated into those later changes, however there have been several changes to master since then that make for a messy / conflicting history.
These changes are a small set of bug fixes and FF / glue fixes to ensure the e2e behave as expected. 
Please speak to me if unsure.
Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear …

feat(forms-web-app): adds non-JS cookie consent banner

---

packages/horizon-create-contact/handler.js
packages/horizon-create-contact/handler.spec.js

AS-1313
Horizon has validation to ensure first and last name's are completed. The form is not (correctly) in the form first name and last name so this is something that we need to generate.

fix(as-1313): add a default value if first/last name not present

---

.github/workflows/infra-environments.yml
README.md
infrastructure/clusters/prod.tfvars
infrastructure/environments/README.md
infrastructure/environments/key_vault.tf
infrastructure/environments/kubernetes.tf
infrastructure/environments/local.tf
infrastructure/environments/message_queue.tf
infrastructure/environments/mongodb.tf
infrastructure/environments/monitoring.tf
infrastructure/environments/networks.tf
infrastructure/environments/storage.tf
infrastructure/environments/variables.tf
infrastructure/k8s/rbac/README.md
infrastructure/k8s/rbac/common/namespaces.yaml
infrastructure/k8s/rbac/common/user.yaml
infrastructure/k8s/rbac/dev/openfaas.yaml
infrastructure/k8s/setup.sh
infrastructure/modules/resource-group-aad-roles/README.md
infrastructure/modules/resource-group-aad-roles/main.tf
infrastructure/modules/resource-group-aad-roles/variables.tf

AS-196
- AS-1328 - allow users to view Kubernetes logs in Azure Portal
- AS-1312 - allow users to view resource monitoring in Azure Portal
- AS-1329 - allow users to list Kubernetes namespaces
- AS-1330 - allow users to get secrets in OpenFaaS namespace. Improved OpenFaaS development docs
- AS-1343 - ping website(s) from Azure Monitor and alert on failures

Monitoring and alerting

---

e2e-tests/cypress.json
e2e-tests/cypress/integration/appeal-submission-to-horizon/appeal-submission-to-horizon.js
e2e-tests/cypress/plugins/queue.js
e2e-tests/package.json

AS-1215 / AS-190
in e2e-tests
`CYPRESS_BASE_URL=http://<user>:<password>@appeals-dev.planninginspectorate.gov.uk npm run test:e2e:horizon:script`
-> executes our horizon tests but without queue validation; so we can run these against a deployed environment to generate appeals->horizon.

test: provide easy scripts for sending appeals to horizon via cypress

---

packages/forms-web-app/src/views/eligibility/decision-date.njk

AS-117
Fixed error message not being visible on component
Added handling for when there is whole date error to select day when click link

fix(forms-web-app): add error handling and link to day focus

---

packages/forms-web-app/src/views/appellant-submission/site-access-safety.njk
packages/forms-web-app/src/views/appellant-submission/site-access.njk
packages/forms-web-app/src/views/includes/scripts.njk

AS-1245
Fixes auto highlighting as JS file for Gov UK FE not included

fix(forms-web-app): inclue and init govuk js file

---

packages/forms-web-app/src/controllers/cookies.js
packages/forms-web-app/src/lib/client-side/cookie/cookie-jar.js
packages/forms-web-app/tests/unit/controllers/cookies.test.js
packages/forms-web-app/tests/unit/lib/client-side/cookie/cookie-jar.test.js

AS-1459
change cookie expiry from 100 to 1 year

fix(forms-web-app): change cookie expiry from 100 to 1 year

---

packages/forms-web-app/webpack.dev.js
packages/forms-web-app/webpack.prod.js

removes webpack define config - not needed, misleading
AS-1490
Added for a previous PR, not used now. Needs removing.

build(forms-web-app): removes webpack define config - not needed, misleading

---

e2e-tests/cypress/integration/appeal-submission-creation-of-submission-information-file.feature
e2e-tests/cypress/integration/appeal-submission-creation-of-submission-information-file/appeal-submission-creation-of-submission-information-file.js
e2e-tests/cypress/integration/common/cookies.js
e2e-tests/cypress/integration/cookie-consent-save-preferences.feature
e2e-tests/cypress/integration/cookies-consent-bar-without-javascript-enabled.feature
e2e-tests/cypress/support/appeal-submission-information/submission-information-commands.js
e2e-tests/cypress/support/commands.js
e2e-tests/cypress/support/common/assertRadioButtonState.js
e2e-tests/cypress/support/cookies/confirmCookieConsentBannerDoesNotExist.js
e2e-tests/cypress/support/cookies/cookies-commands.js
packages/forms-web-app/src/controllers/appellant-submission/submission-information.js
packages/forms-web-app/src/controllers/cookies.js
packages/forms-web-app/src/lib/client-side/cookie/cookie-consent.js
packages/forms-web-app/src/views/includes/cookie-banner.njk
packages/forms-web-app/tests/unit/controllers/appellant-submission/submission-information.test.js
packages/forms-web-app/tests/unit/controllers/cookies.test.js
packages/forms-web-app/tests/unit/lib/client-side/cookie/cookie-consent.test.js

AS-1441
Do not display cookie banner on certain pages.
This also un-WIP's the submission information feature, which flagged several sub issues. 
This includes a fix for the issue of JS console errors (which blew up cypress) when the cookie banner was entirely removed from the page. 

fix(forms-web-app): do not display cookie banner on certain pages

---

README.md
charts/app/templates/keyVault.yaml
charts/app/values.yaml
infrastructure/environments/kubernetes.tf
releases/dev/app.yml
releases/preprod/app.yml

AS-1483
Configure import of secrets of PINS Key Vault. This is used so that PINS staff can inject tokens (eg, Notify) into the cluster without ever having to distribute in an insecure manner

feat(keyvault): configure k8s to be able to read from pins internal key vault

---

releases/dev/app.yml

AS-1497
set ga tag to correct value in dev

fix: sets GA tag to dev value

---

packages/appeals-service-api/src/controllers/local-planning-authorities.js
packages/appeals-service-api/tests/unit/controllers/local-planning-authorities.test.js

N/A
Remove use of `req.param` function in the local planning authority controller which is now deprecated by Express.

fix(lpa): remove dependency on deprecated req.params fn

---

e2e-tests/cypress/integration/cookie-consent-save-preferences/cookie-consent-save-preferences.js
e2e-tests/cypress/support/cookies/confirmHasGoogleAnalyticsCookies.js
e2e-tests/cypress/support/cookies/cookies-commands.js
packages/forms-web-app/src/app.js
packages/forms-web-app/src/controllers/cookies.js
packages/forms-web-app/src/lib/remove-unwanted-cookies.js
packages/forms-web-app/src/middleware/remove-unwanted-cookies.js
packages/forms-web-app/tests/unit/controllers/cookies.test.js
packages/forms-web-app/tests/unit/lib/remove-unwanted-cookies.test.js
packages/forms-web-app/tests/unit/middleware/remove-unwanted-cookies.test.js
packages/forms-web-app/tests/unit/mocks.js

ensure third party cookies are removed when setting usage to inactive
AS-1318
Remove any `_ga` cookies when toggling third party cookie usage to 'off'.

fix(forms-web-app): ensure third party cookies are removed

---

packages/forms-web-app/src/app.js
packages/forms-web-app/src/lib/remove-unwanted-cookies.js

AS-1230
removes verbose cookie logging

fix(forms-web-app): removes verbose cookie logging for AS-1230

---

packages/horizon-add-document/handler.js
packages/horizon-add-document/handler.spec.js
packages/horizon-householder-appeal-publish/handler.js
packages/horizon-householder-appeal-publish/handler.spec.js

AS-1561
Add `documentType` field to add document function and implement it in the householder appeal publish function

fix(document-types): add document types into horizon documents

---

e2e-tests/cypress/support/commands.js
e2e-tests/cypress/support/cookies/confirmHasGoogleAnalyticsCookies.js
e2e-tests/package-lock.json
e2e-tests/package.json

AS-1564
Since switching from `G-xxx` to `UA-xxx` analytics code, the cypress test would fail due to an increased delay in executing the GA code + setting the cookie. Cypress was too fast ... this adds a wait function that is not an out-of-the-box feature for `cy.cookie`.

fix(e2e-tests): allow waiting for GA code to execute so expected cookie is set

---

packages/horizon-add-document/handler.js
packages/horizon-add-document/handler.spec.js

AS-1604
Remove `maxBodyLength` limitation. This is required to allow file uploads via the HTTP body, which is how Horizon requires them

fix(add-document): remove the maxBodyLength limitation

---

.github/workflows/e2e-tests-on-PR.yml
e2e-tests/cypress.json
e2e-tests/package.json
package.json

resolve issues with cypress and gha reruns
AS-1696
resolve issues with cypress and gha reruns

feat(as-1695): resolve issues with cypress and gha reruns

---

packages/forms-web-app/src/views/appellant-submission/submission-information.njk

AS-1768
remove gray colour from bottom of generated appeal PDF

fix(forms-web-app): remove gray colour from bottom of generated appeal PDF

---

.github/workflows/e2e-tests-on-PR.yml

cypress docker cache
AS-1782
Cypress Docker cache

feat(as-1782): cypress docker cache

---

e2e-tests/cypress/support/visit-without-javascript-enabled.js

https://pins-ds.atlassian.net/browse/AS-1925
allow cookies inside cypress non-js iframe hack.
Somehow the non JS tests have broken locally. This is a poorly understood hack, and this 'fix' doesn't directly address the root cause which is using a JS testing tool to fudge testing pages without JS is always going to be flaky.

fix(e2e-tests): allow cookies inside cypress non-js iframe hack

---

lpa-submissions-e2e-tests/README.md
lpa-submissions-e2e-tests/cypress.json
lpa-submissions-e2e-tests/cypress/integration/uploadThePlansToReachDecision/uploadPlansToReachDecisionSteps.js
packages/lpa-questionnaire-web-app/src/controllers/upload-plans.js
packages/lpa-questionnaire-web-app/src/lib/documents-api-wrapper.js
packages/lpa-questionnaire-web-app/src/lib/file-upload-helpers.js
packages/lpa-questionnaire-web-app/src/views/includes/head.njk
packages/lpa-questionnaire-web-app/tests/unit/controllers/upload-plans.test.js
packages/lpa-questionnaire-web-app/tests/unit/lib/documents-api-wrapper.test.js
packages/lpa-questionnaire-web-app/tests/unit/lib/file-upload-helpers.test.js

https://pins-ds.atlassian.net/browse/AS-1900
prove we have deleted the document from document service when we say we have

test: validate against document service when uploading and deleting

---

charts/app/templates/appealsServiceApi.yaml
charts/app/values.yaml
packages/appeals-service-api/src/lib/config.js
packages/appeals-service-api/src/lib/notify.js
packages/appeals-service-api/tests/unit/lib/notify.test.js
releases/prod/app.yml

https://pins-ds.atlassian.net/browse/AS-1864
fix helm lint issue with overly long config variable name

fix(appeals-service-api): fix helm lint issue with overly long config variable name

---

lpa-submissions-e2e-tests/README.md
lpa-submissions-e2e-tests/cypress/support/common/completeQuestionnaire.js

https://pins-ds.atlassian.net/browse/AS-2000
Added manual steps to tests to allow running of e2e tests on deployed environments (as can't call APIs directly).

test(questionnaire-web-app): update tests to work in deployed environments

---

packages/lpa-questionnaire-web-app/src/lib/file-upload-helpers.js

https://pins-ds.atlassian.net/browse/AS-2107
Fix to upload files method to ensure errors get exported

fix(questionnaire-web-app): ensure error exported in upload files method

---

packages/appeals-service-api/src/lib/notify.js
packages/appeals-service-api/tests/unit/lib/notify.test.js

Fixes issues discovered on windows machines using appeals service. Notify common module was being called relatively to a different package. This now uses the common package as it ideally should do. Resolves the error seen.

fix(appeals-service): fix notify to use package not relative route

---

packages/forms-web-app/.eslintrc
packages/forms-web-app/src/views/your-planning-appeal/index.njk
packages/forms-web-app/tests/fixtures/appeal.js
packages/forms-web-app/tests/fixtures/lpd.js
packages/forms-web-app/tests/unit/views/nunjucks-render-helper.js
packages/forms-web-app/tests/unit/views/your-planning-appeal/index.njk.test.js

https://pins-ds.atlassian.net/browse/AS-1606
Ensure that the appellant name is always shown irrespective of who submitted the appeal
Add tests to ensure view shows all correct dynamic data in all scenarios

fix(forms-web-app): view-my-appeal - ensure correct name displayed

---

.github/actions/semantic-release/action.yml

https://pins-ds.atlassian.net/browse/AS-2275
Currently we are unable to view the output log generated by semantic-release. In order to debug recent deployment issues, we need to inspect exactly what semantic-release is doing. This change runs it in dry-run mode so that the output will appear in the CI pipeline logs. 

chore: run a semantic release dry run

---

packages/appeal-reply-service-api/api/openapi.yaml
packages/appeal-reply-service-api/src/__tests__/reply.spec.js
packages/appeal-reply-service-api/src/controllers/reply.js
packages/appeal-reply-service-api/src/routes/reply.js

https://pins-ds.atlassian.net/browse/AS-2316
Added new endpoint to API to get reply by appeal ID

feat(appeal-reply-service-api): add endpoint to lookup by appeal id

---

.github/workflows/appeal-reply-service-api.yml
.github/workflows/appeals-service-api.yml
.github/workflows/document-service-api.yml
.github/workflows/forms-web-app.yml
.github/workflows/horizon-add-document.yml
.github/workflows/horizon-create-case.yml
.github/workflows/horizon-householder-appeal-publish.yml
.github/workflows/lpa-questionnaire.yml
.github/workflows/openfaas-amqp-connector.yml
.github/workflows/pdf-service-api.yml
.github/workflows/ping.yml
.github/workflows/queue-retry.yml

https://pins-ds.atlassian.net/browse/AS-2326
Tag git before tagging the image on Docker. Full write-up in the ticket

chore: as-2326 run semantic-release at the start of the CI pipeline

---

.github/workflows/e2e-tests-on-PR.yml
lpa-submissions-e2e-tests/cypress.json

https://pins-ds.atlassian.net/browse/AS-2556
Enable parallelisation for lpa cypress tests

fix(as-2556): enable parallelisation for lpa cypress tests

---

lpa-submissions-e2e-tests/cypress/fixtures/completedAppealReply.json
lpa-submissions-e2e-tests/cypress/integration/common/booleanQuestion.js
lpa-submissions-e2e-tests/cypress/integration/common/checkYourAnswers.js
lpa-submissions-e2e-tests/cypress/integration/common/common.js
lpa-submissions-e2e-tests/cypress/integration/common/pdf.js
lpa-submissions-e2e-tests/cypress/integration/common/taskList.js
lpa-submissions-e2e-tests/cypress/integration/siteSeenPublicLand.feature
lpa-submissions-e2e-tests/cypress/integration/siteSeenPublicLand/siteSeenPublicLand.step.js

https://pins-ds.atlassian.net/browse/AS-2301
- Feature and steps for public land question
- Started move to typed questions - means actions are shared by type

test(questionnaire-e2e): feature file and tests

---

releases/dev/app.yml
releases/dev/functions.yml
releases/preprod/app.yml
releases/preprod/functions.yml
releases/prod/app.yml
releases/prod/functions.yml

https://pins-ds.atlassian.net/browse/AS-2541
Flux automated commits to master give rise to race conditions, when used in the current setup of a monorepo, github actions and semantic-release. These conditions result in an unstable system. This change removes flux automation.

chore: as-2541 disable flux automation

---

.github/actions/flux/action.yml
.github/workflows/appeals-service-api.yml
.github/workflows/document-service-api.yml
.github/workflows/forms-web-app.yml
.github/workflows/horizon-add-document.yml
.github/workflows/horizon-create-case.yml
.github/workflows/horizon-householder-appeal-publish.yml
.github/workflows/lpa-questionnaire.yml
.github/workflows/openfaas-amqp-connector.yml
.github/workflows/pdf-service-api.yml
.github/workflows/ping.yml
.github/workflows/queue-retry.yml

https://pins-ds.atlassian.net/browse/AS-2590
Add some documentation and remove the redundant flux action at the end of each workflow.

chore: as-2590 document flux sync tags

---

releases/dev/app.yml

chore: force build to 1.16.1, and 1.6.0 for appeals APIs

---

releases/dev/app.yml

Build PR for site access question

chore: force build to 1.26, and 1.8.0 for reply api

---

.github/actions/semantic-release/action.yml
.github/workflows/appeal-reply-service-api.yml
.github/workflows/appeals-service-api.yml
.github/workflows/document-service-api.yml
.github/workflows/forms-web-app.yml
.github/workflows/horizon-add-document.yml
.github/workflows/horizon-create-case.yml
.github/workflows/horizon-householder-appeal-publish.yml
.github/workflows/lpa-questionnaire.yml
.github/workflows/openfaas-amqp-connector.yml
.github/workflows/pdf-service-api.yml
.github/workflows/ping.yml
.github/workflows/queue-retry.yml

As DevOps, I want to reduce the number of runs of semantic-release from 3 to 1, so that we can reduce race condition errors.

chore: as-2663 run semantic release once only

---

.github/actions/semantic-release/action.yml
packages/forms-web-app/Dockerfile

Adjust to grab the new version from the semantic-release output, as it is no longer grabbing it from a dry-run.

fix: as-2663 adjust for different output

---

.github/actions/semantic-release/action.yml
packages/forms-web-app/Dockerfile

Run semantic-release on master only.

fix: as-2663 run semantic-release on master only

---

packages/lpa-questionnaire-web-app/src/controllers/files.js
packages/lpa-questionnaire-web-app/src/controllers/upload-question.js
packages/lpa-questionnaire-web-app/tests/unit/controllers/files.test.js
packages/lpa-questionnaire-web-app/tests/unit/controllers/upload-question.test.js

https://pins-ds.atlassian.net/browse/AS-2726
Fixes incident when user could not delete file when it is invalid

fix(lpa-questionnaire-web-app): fix deletion event for invalid files

---

lpa-submissions-e2e-tests/cypress/fixtures/completedAppealReply.json
packages/lpa-questionnaire-web-app/src/services/task-status/check-your-answers.js

https://pins-ds.atlassian.net/browse/AS-1688
Adds enter appeal site question to required questions

fix(lpa-questionnaire-web-app): add enter appeal site to required validator

---

e2e-tests/cypress/integration/appeal-submission-appeal-site-address.feature
e2e-tests/cypress/integration/appeal-submission-appeal-site-address/appeal-submission-appeal-site-address.js
packages/appeals-service-api/src/services/appeal.service.js
packages/appeals-service-api/tests/unit/lib/notify.test.js
packages/appeals-service-api/tests/unit/services/appeal.service.test.js
packages/forms-web-app/src/services/task-status/status-appeal-site-address.js
packages/forms-web-app/src/services/task.service.js
packages/forms-web-app/src/validators/appellant-submission/site-location.js
packages/forms-web-app/src/views/appellant-submission/site-location.njk
packages/forms-web-app/tests/unit/services/task-status/status-appeal-site-address.test.js
packages/forms-web-app/tests/unit/validators/appellant-submission/site-location.test.js

https://pins-ds.atlassian.net/browse/AS-2483
Address county is no longer mandatory
Updates to FWA, Appeals Service API, and the e2e tests.

fix(forms-web-app): address county is no longer mandatory

---

charts/functions/templates/horizon-ping.yaml
releases/dev/functions.yml

https://pins-ds.atlassian.net/browse/AS-2845
The ping was setup to check the availability of the Horizon REST API Wrapper and trigger an alert if it was down. It had been intended that it would ping the wrapper once a minute, but it also pings it once every 10 seconds. The frequent pings are made by the readinessProbe which I have consequently removed from the horizon-ping.yaml file.
Also, sometimes the /horizon endpoint can be unavailable but the /status endpoint still is, meaning messages won't be received from the Appeal Service and we're not alerted to it until a message fails. Therefore, I have changed the endpoint to /horizon on Dev initially.
Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). …

fix(ping-horizon): Changes horizon ping endpoint and frequency

---

charts/functions/templates/horizon-ping.yaml

https://pins-ds.atlassian.net/browse/AS-2845
Removing the readinessProbe triggered horizon-ping-test alerts, so I have reintroduced it but with a 60 second period.

chore(k8s-envvars): reintroduce readinessProbe to ping service

---

releases/dev/functions.yml

https://pins-ds.atlassian.net/browse/AS-2845
Changing the destination endpoint for the ping service on Dev back to /status rather than /horizon, due to PreProd Horizon being offline overnight.

chore(k8s-envvars): revert destination of ping service [ci skip]

---

charts/app/templates/formsWebApp.yaml
charts/app/values.yaml
packages/forms-web-app/src/app.js
packages/forms-web-app/src/config.js
packages/forms-web-app/src/lib/client-side/google-analytics.js
packages/forms-web-app/src/views/includes/body-start.njk
packages/forms-web-app/src/views/includes/head.njk
packages/forms-web-app/src/views/layouts/main.njk
packages/forms-web-app/tests/unit/lib/client-side/__snapshots__/google-analytics.test.js.snap
packages/forms-web-app/tests/unit/lib/client-side/google-analytics.test.js
packages/forms-web-app/tests/unit/views/includes/__snapshots__/body-start.njk.test.js.snap
packages/forms-web-app/tests/unit/views/includes/__snapshots__/head.njk.test.js.snap
packages/forms-web-app/tests/unit/views/includes/body-start.njk.test.js
packages/forms-web-app/tests/unit/views/nunjucks-helper-functions.js

https://pins-ds.atlassian.net/browse/AS-2819
Add Google Tag Manager code behind a feature flag. 
Initially this is for testing the Google Tag Manager functionality so will be toggled on in Dev and off in PreProd and Prod.
The feature flag is set with an env var so it can be toggled on/off in each env. When the flag is toggled on the new Tag Manager code is used and the original Google Analytics code is not used and when the flag is toggled off the new Tag Manager code is not used and the original Google Analytics code is used.
Unit tests have been updated to check that the correct code is used when the flag is toggled on and off.
E2E tests are unchanged as we can't toggle the env var on/off whilst the tests are running and they currently reflect the state of the code in Prod so they can …

feat(as-2819): add google tag manager code behind a feature flag

---

releases/dev/app.yml

https://pins-ds.atlassian.net/browse/AS-2819
Adds env vars for Google Tag Manager in dev to activate the feature flag and set the id for the tracking codes.

feat(as-2819): add env vars for the google tag manager feature flag in dev

---

e2e-tests/cypress/integration/common/appellant-submission-your-details.js
e2e-tests/cypress/support/appellant-submission-your-details/confirmWhoAreYouRejectedBecause.js

https://pins-ds.atlassian.net/browse/AS-2754
fix to cypress test code

fix(as-2754): fix cypress test code

---

lpa-submissions-e2e-tests/cypress/integration/accessNeighboursLand/accessNeighboursLand.step.js
lpa-submissions-e2e-tests/cypress/integration/enterAppealSite/enterAppealSite.step.js
lpa-submissions-e2e-tests/cypress/integration/siteSeenPublicLand/siteSeenPublicLand.step.js

Update the integration test mock data to be the same as the real data. Capitalise the inspector word
inside theLPA questionnaire.

fix(e2e-tests): update the integration test mock data

---

.github/workflows/terraform-validate.yml

https://pins-ds.atlassian.net/browse/AS-3005
Increases the terraform-security-scan version because the tfsec GitHub location changed, causing the terraform-validate Workflow to fail.

fix(terraform-validate): increases terraform-security-scan version

---

docker-compose.yml
e2e-tests/cypress/integration/appellant-submission-header.feature
e2e-tests/cypress/integration/eligibility-decision-date.feature
e2e-tests/cypress/integration/eligibility-decision-date/eligibility-decision-date.js
e2e-tests/cypress/support/commands/eligibility-commands.js
e2e-tests/cypress/support/eligibility-decision-date-passed/clickReEnterTheDecisionDate.js
packages/forms-web-app/package-lock.json
packages/forms-web-app/package.json
packages/forms-web-app/src/controllers/eligibility/decision-date.js
packages/forms-web-app/src/middleware/check-decision-date-deadline.js
packages/forms-web-app/src/routes/index.js
packages/forms-web-app/src/views/eligibility/decision-date-passed.njk
packages/forms-web-app/tests/unit/controllers/eligibility/decision-date.test.js
packages/forms-web-app/tests/unit/middleware/check-decision-date-deadline.test.js
packages/forms-web-app/tests/unit/routes/index.test.js

https://pins-ds.atlassian.net/browse/AS-2836
Update the Forms Web App to use validation and rules from the business-rules package. This is a like for like swap so if we decide that we need to change the way the validation is done then this can be done in a later ticket.
This change also includes a check for if the deadline date has passed on each page (except the Decision Date page) and if so then the user is taken to the Decision Date Passed end page. To cover the scenario that the user may accidentally enter an incorrect date, the Decision Date Passed end page now as a link to return to the Decision Date page (this page is excluded from the deadline date check).
E2E tests have been updated/added to cover this new scenario as follows:
1. Update the E2E test for the user entering a date …

feat(as-2836): change forms web app to use the business rules for decision date

---

packages/document-service-api/src/controllers/documents.js
packages/document-service-api/src/controllers/documents.spec.js
packages/document-service-api/src/lib/deleteLocalFile.spec.js

adding filename into response header
https://pins-ds.atlassian.net/browse/AS-2696
adding filename into response header

feat(adding filename into response header): document download

---

packages/forms-web-app/__tests__/unit/controllers/appellant-submission/submission.test.js
packages/forms-web-app/src/controllers/appellant-submission/submission.js

https://pins-ds.atlassian.net/browse/AS-3432
disable pdf service in appeals

fix(as-3432): disable pdf in appeals

---

packages/document-service-api/src/lib/blobStorage.js

https://pins-ds.atlassian.net/browse/AS-3452
It appears that when tested locally the metadata is automatically returned in the blob properties response but in Dev its not so we need to set the `includeMetadata` option in the request so we get it in the response.
This should fix the issue with deleting documents and also the issue with fetching the document in the Horizon function, which are both failing for this same reason.
More info at https://github.com/Azure/azure-sdk-for-js/issues/12708

fix(as-3452): specify that metadata should be included in the blob properties response

---

packages/appeal-reply-service-api/azure-appeal-reply-service-api-build.yml
packages/document-service-api/azure-document-service-api-build.yml
packages/forms-web-app/azure-forms-web-app-build.yml
packages/lpa-questionnaire-web-app/azure-lpa-questionnaire-web-app-build.yml
packages/pdf-service-api/azure-pdf-service-api-build.yml

https://pins-ds.atlassian.net/browse/AS-3486
only store build in acr if merge to master

fix(as-3486): only store build in acr if merge to master

---

e2e-tests/cypress/integration/appellant-submission-footer.feature
e2e-tests/cypress/integration/appellant-submission-header.feature
packages/forms-web-app/__tests__/unit/controllers/eligibility/planning-department.test.js
packages/forms-web-app/src/controllers/eligibility/planning-department.js
packages/forms-web-app/src/views/eligibility/costs-out.njk
packages/forms-web-app/src/views/eligibility/enforcement-notice-out.njk
packages/forms-web-app/src/views/eligibility/householder-planning-permission-out.njk
packages/forms-web-app/src/views/eligibility/listed-out.njk
packages/forms-web-app/src/views/eligibility/planning-department-out.njk

https://pins-ds.atlassian.net/browse/AS-3308
Removing backing from -out pages under /eligibility

feat(back link): removed from -out pages

---

docker-compose.yml
packages/pdf-service-api/Dockerfile
packages/pdf-service-api/src/server.js

https://pins-ds.atlassian.net/browse/AS-3426
Re-enable pdf service api healthchecks

fix(as-3426): re-enable pdf servce api healthchecks

---

Makefile
docker-compose.yml

https://pins-ds.atlassian.net/browse/AS-3494
The PDF Service in the local dev env wasn't building on M1 Macs because of an issue with Chromium on the M1. This change fixes that by building the PDF Service first and then running it with the docker-compose file.
The key was to pass the `--platform=linux/amd64` flag when building the image and this doesn't seem to affect it building on other platforms, it's been tested on Linux Mac M1 and Windows.

fix(as-3494): update the local dev env to work with M1 Macs

---

packages/e2e-tests/cypress/cucumber-json/appeal-form-task-list.cucumber.json
packages/e2e-tests/cypress/integration/full-planning/appeals-service/appeal-form-task-list.feature
packages/e2e-tests/cypress/integration/full-planning/appeals-service/appeal-form-task-list/appeal-form-task-list.js
packages/e2e-tests/cypress/support/full-planning/appeals-service/page-objects/appeal-form-task-list-po.js

adding cypress test for full planning task list page
https://pins-ds.atlassian.net/browse/AS-4187
Add cypress tests
- [ X] My commit history in this PR is linear

feat: adding cypress tests for full planning

---

packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/application-form.test.js
packages/forms-web-app/__tests__/unit/validators/common/file-upload.test.js
packages/forms-web-app/__tests__/unit/validators/common/schemas/file-upload.test.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/application-form.js
packages/forms-web-app/src/validators/common/file-upload.js
packages/forms-web-app/src/validators/common/schemas/file-upload.js
packages/forms-web-app/src/views/full-appeal/submit-appeal/application-form.njk

https://pins-ds.atlassian.net/browse/AS-4301
Update the full appeals application form page
- Add `If you do not have your planning application form, you can find it by searching for your planning application on your local planning department's website.` text under the page title
- Update the 'no files uploaded' error message  from `Select a file to upload` to `Select your planning application form`. Since this is a common validation component, the component has been changed so that the custom error message can be passed in when called in the route. The old message will be used as a default if no error message is passed in.
Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history …

fix(as-4301): add text and error message to application form page

---

packages/e2e-tests/cypress/integration/eligibility/householder-planning/date-decision-due.feature
packages/e2e-tests/cypress/integration/eligibility/householder-planning/date-decision-due/date-decision-due-steps.js
packages/e2e-tests/cypress/support/eligibility/date-decision-due-householder/enter-date-decision-due-householder.js
packages/e2e-tests/cypress/support/eligibility/page-objects/date-decision-due-householder-po.js

https://pins-ds.atlassian.net/browse/AS-4245
Added E2E tests for date decision due for householder appeal

test: added E2E tests for date decision due for householder appeal

---

packages/e2e-tests/cypress/integration/full-appeal/appeals-service/upload-decision-letter.feature
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/upload-decision-letter/upload-decision-letter.js

https://pins-ds.atlassian.net/browse/AS-4205
Add e2e tests for Decision Letter file upload page

feat: add e2e tests for decision letter file upload

---

packages/appeals-service-api/__tests__/integration/appeals.test.js
packages/appeals-service-api/__tests__/unit/controllers/appeals.test.js
packages/appeals-service-api/src/models/appeal.js
packages/business-rules/src/schemas/full-appeal/insert.js
packages/business-rules/src/schemas/full-appeal/insert.test.js
packages/business-rules/src/schemas/full-appeal/update.js
packages/business-rules/src/schemas/full-appeal/update.test.js
packages/business-rules/test/data/full-appeal.js
packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/own-some-of-the-land.test.js
packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/own-some-of-the-land.test.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/own-some-of-the-land.js
packages/forms-web-app/src/lib/full-appeal/views.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/own-some-of-the-land.js
packages/forms-web-app/src/views/full-appeal/submit-appeal/own-some-of-the-land.njk

https://pins-ds.atlassian.net/browse/AS-4230
Adds the Full Appeal page for 'Do you own some of the land involved in the appeal? '

feat(as-4230): add full appeal own some of the land page

---

packages/appeals-service-api/__tests__/integration/appeals.test.js
packages/appeals-service-api/__tests__/unit/controllers/appeals.test.js
packages/appeals-service-api/src/models/appeal.js
packages/business-rules/src/schemas/full-appeal/insert.js
packages/business-rules/src/schemas/full-appeal/insert.test.js
packages/business-rules/src/schemas/full-appeal/update.js
packages/business-rules/src/schemas/full-appeal/update.test.js
packages/business-rules/test/data/full-appeal.js
packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/agricultural-holding.test.js
packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/agricultural-holding.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/agricultural-holding.js
packages/forms-web-app/src/lib/full-appeal/views.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/agricultural-holding.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js
packages/forms-web-app/src/services/task.service.js
packages/forms-web-app/src/views/full-appeal/submit-appeal/agricultural-holding.njk

https://pins-ds.atlassian.net/browse/AS-4231
Add Full Appeal Agricultural Holding page

feat(as-4231): add full appeal agricultural holding page

---

packages/appeals-service-api/__tests__/integration/appeals.test.js
packages/appeals-service-api/__tests__/unit/controllers/appeals.test.js
packages/appeals-service-api/src/models/appeal.js
packages/business-rules/src/lib/pins-yup.js
packages/business-rules/src/lib/pins-yup.test.js
packages/business-rules/src/schemas/full-appeal/insert.js
packages/business-rules/src/schemas/full-appeal/insert.test.js
packages/business-rules/src/schemas/full-appeal/update.js
packages/business-rules/src/schemas/full-appeal/update.test.js
packages/business-rules/src/validators/appeal/index.js
packages/business-rules/src/validators/appeal/index.test.js
packages/business-rules/src/validators/common/conditional-text.js
packages/business-rules/src/validators/index.js
packages/business-rules/src/validators/index.test.js
packages/business-rules/test/data/full-appeal.js
packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/visible-from-road.test.js
packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/visible-from-road.test.js
packages/forms-web-app/__tests__/unit/validators/common/conditional-text.test.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/visible-from-road.js
packages/forms-web-app/src/lib/full-appeal/views.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/visible-from-road.js
packages/forms-web-app/src/services/task.service.js
packages/forms-web-app/src/validators/common/conditional-text.js
packages/forms-web-app/src/views/full-appeal/submit-appeal/visible-from-road.njk

https://pins-ds.atlassian.net/browse/AS-4306
Add Full Appeal Visible From Road page.
Also added a common Conditional Text validator for both the UI and JSON Schema that can be used to validate that any text field is required and has a max length based on the selection of another field.

feat(as-4306): add full appeal visible from road page

---

packages/e2e-tests/cypress/integration/eligibility/householder-planning/claiming-costs/claiming-costs-steps.js
packages/forms-web-app/__tests__/unit/controllers/householder-planning/eligibility/claiming-costs-householder.test.js
packages/forms-web-app/src/controllers/householder-planning/eligibility/claiming-costs-householder.js

https://pins-ds.atlassian.net/browse/AS-4478
Fixed back link issue at householder claiming cost page

fix(as-4478): fixed back link issue at householder claiming cost page

---

packages/appeals-service-api/__tests__/unit/lib/full-appeal/notify.test.js
packages/appeals-service-api/src/lib/full-appeal/notify.js

https://pins-ds.atlassian.net/browse/AS-4476
appeal.planningApplicationDocumentsSection.applicationNumber is used for lpa email

fix(full appeal): appeal.planningApplicationDocumentsSection.applicationNumber is used for lpa email

---

packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/health-safety-issues.feature
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/health-safety-issues/health-safety-issues.js
packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/health-safety-issues-po.js

https://pins-ds.atlassian.net/browse/AS-4308
Add E2E tests for the Full Appeal Health and Safety Issues page

feat(as-4308): add e2e tests for the full appeal health and safety issues page

---

packages/clamav-rest-server/__tests__/unit/lib/clamd.test.js
packages/clamav-rest-server/src/lib/clamd.js

https://pins-ds.atlassian.net/browse/AS-4338
Fixing typo that prevented ClamAV REST Client from working correctly

fix(as-4338): Fix clamd syntax for ClamAV

---

packages/appeals-service-api/src/validators/appeals/appeals.validator.js
packages/business-rules/src/schemas/householder-appeal/update.js
packages/business-rules/src/schemas/householder-appeal/update.test.js
packages/business-rules/src/schemas/validate.js
packages/business-rules/src/schemas/validate.test.js

Stop defaulting the appeal type to Householder so we can keep backwards compatible with the old Householder flow
This means that we'll know the user is on the old Householder flow as the appeal type won't be set and this can be used during the flow when the new flow differs from the old flow.
To help this the update schema has been changed from the appeal type being required to validating the appeal type if it's present in the payload otherwise allowing it to be null.
Also the Householder schema is now used as a default for the old Householder flow as the appeal type won't b set to select the schema.
Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps …

feat(business-rules): stop defaulting the appeal type to householder to help be backwards compatible

---

packages/forms-web-app/src/views/full-appeal/submit-appeal/identifying-the-owners.njk

https://pins-ds.atlassian.net/browse/AS-4505
identifying-the-owners 'other' word removed

fix(full appeal): identifying-the-owners 'other' word removed

---

packages/appeal-reply-service-api/azure-appeal-reply-service-api-build.yml
packages/appeals-service-api/azure-appeals-service-api-build.yml
packages/document-service-api/azure-document-service-api-build.yml
packages/forms-web-app/azure-forms-web-app-build.yml
packages/horizon-functions/azure-functions-pipeline.yml
packages/lpa-questionnaire-web-app/azure-lpa-questionnaire-web-app-build.yml
packages/pdf-service-api/azure-pdf-service-api-build.yml

None
Added branch name as a tag on docker images and artifacts published from Azure pipelines.  The latest tag will only be published from the mainline branch - master.  Critically, this resolves the issue of having the "latest" version of an image being overwritten with a build from branches other than the mainline, e.g. feature branches, hotfixes, etc.
For deployments it will now be possible to use the slugified version of a branch name as an image tag in order to deploy the latest build from a particular branch, e.g. images from branch `feature/abc-123` will be published with the tag `feature_abc-123`
> Importantly, the pipeline for Horizon Functions has been changed to no longer automatically deploy to dev but rather publish artifacts which can be used in subsequent deployments.
This …

Feature: Branch tags for docker images

---

packages/forms-web-app/src/views/full-appeal/submit-appeal/identifying-the-owners.njk

https://pins-ds.atlassian.net/browse/AS-4505
revert removing 'other' from telling-the-landowners page

revert(full appeal): revert removing 'other' from telling-the-landowners page

---

package.json
packages/business-rules/src/schemas/full-appeal/insert.js
packages/business-rules/src/schemas/full-appeal/insert.test.js
packages/business-rules/src/schemas/full-appeal/update.js
packages/business-rules/src/schemas/full-appeal/update.test.js
packages/business-rules/test/data/full-appeal.js
packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/supporting-documents.test.js
packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/supporting-documents.test.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/declaration.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/supporting-documents.js
packages/forms-web-app/src/lib/full-appeal/views.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/supporting-documents.js
packages/forms-web-app/src/views/full-appeal/submit-appeal/supporting-documents.njk

https://pins-ds.atlassian.net/browse/AS-4335
Add Full Appeal Supporting Documents page

feat(as-4335): add full appeal supporting documents page

---

packages/appeals-service-api/src/validators/appeals/appeals.validator.js
packages/business-rules/src/config.js
packages/business-rules/src/schemas/validate.js
packages/business-rules/src/schemas/validate.test.js

https://pins-ds.atlassian.net/browse/AS-4389
Pass new journey feature flag into the business rules rather then getting from an environment variable as this seems to be causing issues in Dev.

feat(as-4389): pass new journey feature flag into the business rules

---

packages/appeals-service-api/__tests__/unit/controllers/appeals.test.js
packages/appeals-service-api/src/controllers/appeals.js
packages/business-rules/src/schemas/full-appeal/insert.js
packages/business-rules/src/schemas/full-appeal/insert.test.js
packages/business-rules/src/schemas/full-appeal/update.js
packages/business-rules/src/schemas/full-appeal/update.test.js
packages/business-rules/test/data/full-appeal.js
packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/new-plans-drawings.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/appeal-statement.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/new-plans-drawings.test.js
packages/forms-web-app/__tests__/unit/validators/common/schemas/file-upload.test.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/new-plans-drawings.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/new-plans-drawings.js
packages/forms-web-app/src/validators/common/schemas/file-upload.js
packages/forms-web-app/src/views/full-appeal/submit-appeal/new-plans-drawings.njk

https://pins-ds.atlassian.net/browse/AS-4328
Add the Full Appeal New Plans and Drawings page

feat(as-4328): add full appeal new plans and drawings page

---

packages/business-rules/src/schemas/full-appeal/insert.js
packages/business-rules/src/schemas/full-appeal/insert.test.js
packages/business-rules/src/schemas/full-appeal/update.js
packages/business-rules/src/schemas/full-appeal/update.test.js
packages/business-rules/test/data/full-appeal.js
packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/new-supporting-documents.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js
packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/new-supporting-documents.test.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/new-supporting-documents.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js
packages/forms-web-app/src/routes/full-appeal/submit-appeal/new-supporting-documents.js
packages/forms-web-app/src/views/full-appeal/submit-appeal/new-supporting-documents.njk
packages/forms-web-app/src/views/full-appeal/submit-appeal/supporting-documents.njk

https://pins-ds.atlassian.net/browse/AS-4334
Add the Full Appeal New Supporting Documents page

feat(as-4334): add full appeal new supporting documents page

---

packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/appeal-site-address.feature
packages/forms-web-app/src/views/full-appeal/submit-appeal/appeal-site-address.njk

https://pins-ds.atlassian.net/browse/AS-4497
Add hidden label to site address line 2 field and other accessibility updates

feat(as-4497): update accessibility for full appeal site address page

---

packages/forms-web-app/__tests__/unit/middleware/check-appeal-type-exists.test.js
packages/forms-web-app/src/middleware/check-appeal-type-exists.js

https://pins-ds.atlassian.net/browse/AS-4537
Fix the Internal Server Error caused when a user submits an appeal then returns the beginning to start a new appeal.

fix(as-4537): fix the appeal type redirection for entering a second appeal

---

packages/e2e-tests/cypress/integration/common/full-appeal/completeEligibilityJourney.js
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/telling-the-landowners.feature
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/telling-the-landowners/telling-the-landowners.js
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/telling-the-tenants.feature
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/telling-the-tenants/telling-the-tenants.js
packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/own-the-land-po.js

https://pins-ds.atlassian.net/browse/AS-4358
Cypress tests for Telling the tenants and telling the other tenants (AS-4358 and AS-4300)

test: added tests for telling the tenants and telling the other tenants

---

packages/business-rules/src/schemas/householder-appeal/update.js
packages/business-rules/src/schemas/householder-appeal/update.test.js

https://pins-ds.atlassian.net/browse/AS-4537
Change the Householder schema validation to make the Householder Planning Permission question nullable as it is not in the new Householder journey and when it's a required field it prevents the appeal from being submitted.
We need to keep the field for backwards compatibility and it could be removed with the old Householder journey.

fix(as-4537): update householder schema to not require the planning permission to be complete

---

packages/forms-web-app/src/views/full-appeal/submit-appeal/check-your-answers.njk

Added two missing `data-cy` attributes on the Full Appeal Check Your Answers page

fix(as-4505): add two missing data-cy attributes on full appeal check your answers page

---

packages/business-rules/src/schemas/full-appeal/insert.js
packages/business-rules/src/schemas/full-appeal/insert.test.js
packages/business-rules/src/schemas/full-appeal/update.js
packages/business-rules/src/schemas/full-appeal/update.test.js
packages/business-rules/src/schemas/householder-appeal/insert.js
packages/business-rules/src/schemas/householder-appeal/insert.test.js
packages/business-rules/src/schemas/householder-appeal/update.js
packages/business-rules/src/schemas/householder-appeal/update.test.js
packages/business-rules/test/data/full-appeal.js
packages/business-rules/test/data/householder-appeal.js

https://pins-ds.atlassian.net/browse/AS-4540
Add `createdAt` and `updatedAt` dates to both schemas for both Full Appeal and Householder to ensure that these dates are saved and in the correct format and at the top level

feat(as-4540): update the schemas to ensure createdAt and updatedAt dates are at the top level

---

packages/forms-web-app/src/views/full-appeal/submit-appeal/check-your-answers.njk

Update the Change link hidden text on the Full Appeal Check Your Answers page to remove the 'Change' word to prevent it being duplicated as it is already part of the link text.

fix(as-4504): update change link hidden text on full appeal check your answers page

---

packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/identifying-the-other-landowners.feature
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/identifying-the-other-landowners/identifying-the-other-landowners.js
packages/e2e-tests/cypress/support/full-appeal/appeals-service/page-objects/own-the-land-po.js

https://pins-ds.atlassian.net/browse/AS-4280
Cypress tests for Identifying the Other Landowners

feat: cypress tests for Identifying the other Land owners

---

packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/part-of-agricultural-holding.feature
packages/e2e-tests/cypress/integration/full-appeal/appeals-service/appeal-site-section/part-of-agricultural-holding/part-of-agricultural-holding.js

https://pins-ds.atlassian.net/browse/AS-4543
add back link tests for agricultural holing page all the 7 journeys

fix: bug fixes for back links in agricultural holding page

---

packages/business-rules/src/schemas/householder-appeal/update.js
packages/business-rules/src/schemas/householder-appeal/update.test.js

https://pins-ds.atlassian.net/browse/AS-4524
Update `hasPriorApprovalForExistingHome` field in the Householder schema nullable as it's not a required field

fix(as-4524): update householder schema to make hasPriorApprovalForExistingHome field nullable

---

packages/appeals-service-api/package-lock.json
packages/business-rules/package-lock.json

https://pins-ds.atlassian.net/browse/AS-4588
Update appeals-service-api and business-rules package lock files to fix the remaining appeals-service-api package vulnerability

fix(as-4588): update appeals-service-api and business-rules package lock files

---

packages/business-rules/src/schemas/full-appeal/insert.js
packages/business-rules/src/schemas/full-appeal/insert.test.js
packages/business-rules/src/schemas/full-appeal/update.js
packages/business-rules/src/schemas/full-appeal/update.test.js
packages/business-rules/src/schemas/householder-appeal/update.test.js
packages/business-rules/test/data/full-appeal.js

https://pins-ds.atlassian.net/browse/AS-4582
Add `submissionDate` to the Full Appeal schema

fix(as-4582): add submission date to the full appeal schema

---

packages/forms-web-app/src/views/full-appeal/submit-appeal/declaration-information.njk

https://pins-ds.atlassian.net/browse/AS-4636
Update the Full Appeal Declaration Information page so the application type is correctly displayed rather than being hard-coded to Full Appeal. This is required because appeal types other than Full Appeal go through the Full Appeal journey.
Also changed the setting of `planningDecision` to use a `switch` statement rather than an `if` statement.

fix(as-4636): update full appeal pdf to show the correct planning application type

---

packages/appeals-service-api/__tests__/integration/appeals.test.js
packages/appeals-service-api/__tests__/unit/controllers/appeals.test.js

https://pins-ds.atlassian.net/browse/AS-4581
Update appeals-service-api integration tests
- Remove fixes from when a single model was being used for both appeal types
- Add an additional tests for the controller to check the correct data is saved when the `newAppealJourney` feature flag is not set

fix(as-4581): update appeals-service-api integration tests

---

pipelines/horizon-functions/horizon-functions-cd.yml
pipelines/horizon-functions/horizon-functions-ci.yml

- Node isn't installed on the custom agent yet. So for the time being I'm just using the MS Hosted agents
- Updated name of CI pipeline (matches what's in Azure DevOps)
- Added a branch tag to the CI builds so the CD pipeline can deploy based on branch
- Fix name of function app

Horizon functions CI agent pool

---

.github/PULL_REQUEST_TEMPLATE.md
.releaserc
README.md
azure-pipelines-commit-lint.yml
packages/appeal-reply-service-api/pipelines/azure-pipelines-build.yml
packages/appeal-reply-service-api/pipelines/azure-pipelines-release.yml
packages/appeals-service-api/pipelines/azure-pipelines-build.yml
packages/appeals-service-api/pipelines/azure-pipelines-release.yml
packages/business-rules/pipelines/azure-pipelines-build.yml
packages/clamav-rest-server/pipelines/azure-pipelines-build.yml
packages/clamav-rest-server/pipelines/azure-pipelines-release.yml
packages/common/pipelines/azure-pipelines-build.yml
packages/document-service-api/README.md
packages/document-service-api/pipelines/azure-pipelines-build.yml
packages/document-service-api/pipelines/azure-pipelines-release.yml
packages/e2e-tests/pipelines/azure-pipelines-cypress-e2e.yml
packages/forms-web-app/pipelines/azure-pipelines-build.yml
packages/forms-web-app/pipelines/azure-pipelines-release.yml
packages/horizon-functions/pipelines/azure-pipelines-build.yml
packages/horizon-functions/pipelines/azure-pipelines-release.yml
packages/pdf-service-api/pipelines/azure-pipelines-build.yml
packages/pdf-service-api/pipelines/azure-pipelines-release.yml
packages/ping/pipelines/azure-pipelines-build.yml
packages/queue-retry/pipelines/azure-pipelines-build.yml

- Default branch update to `main` and upgrade pipeline template version so Cypress E2E tests skip the publish artifact step if there is nothing to publish

fix(pipelines): update pipeline version and change references to deault branch to 'main'

---

packages/e2e-tests/pipelines/azure-pipelines-cypress-e2e.yml

- Incorrect ref used for pipeline templates in e2e tests pipeline

fix(pipelines): fix ref for templates repo in e2e tests pipeline

---

azure-pipelines-commit-lint.yml
azure-pipelines-variables.yml
packages/appeal-reply-service-api/pipelines/azure-pipelines-build.yml
packages/appeal-reply-service-api/pipelines/azure-pipelines-release.yml
packages/appeal-reply-service-api/pipelines/azure-pipelines-variables.yml
packages/appeals-service-api/pipelines/azure-pipelines-build.yml
packages/appeals-service-api/pipelines/azure-pipelines-release.yml
packages/appeals-service-api/pipelines/azure-pipelines-variables.yml
packages/business-rules/pipelines/azure-pipelines-build.yml
packages/clamav-rest-server/pipelines/azure-pipelines-build.yml
packages/clamav-rest-server/pipelines/azure-pipelines-release.yml
packages/clamav-rest-server/pipelines/azure-pipelines-variables.yml
packages/common/pipelines/azure-pipelines-build.yml
packages/document-service-api/pipelines/azure-pipelines-build.yml
packages/document-service-api/pipelines/azure-pipelines-release.yml
packages/document-service-api/pipelines/azure-pipelines-variables.yml
packages/e2e-tests/pipelines/azure-pipelines-cypress-e2e.yml
packages/forms-web-app/pipelines/azure-pipelines-build.yml
packages/forms-web-app/pipelines/azure-pipelines-release.yml
packages/forms-web-app/pipelines/azure-pipelines-variables.yml
packages/horizon-functions/pipelines/azure-pipelines-build.yml
packages/horizon-functions/pipelines/azure-pipelines-release.yml
packages/horizon-functions/pipelines/azure-pipelines-variables.yml
packages/pdf-service-api/pipelines/azure-pipelines-build.yml
packages/pdf-service-api/pipelines/azure-pipelines-release.yml
packages/pdf-service-api/pipelines/azure-pipelines-variables.yml
packages/ping/pipelines/azure-pipelines-build.yml
packages/queue-retry/pipelines/azure-pipelines-build.yml

Updated pipelines to use the latest version of the templates. This version requires less parameters
to be passed into the wrapper templates. It also makes a specific wrapper template for web and
functions apps redundant and we can now use the generic wrapper_cd.yml template.
https://pins-ds.atlassian.net/browse/DBO-38

refactor(pipelines): update pipelines to use latest version

---

azure-pipelines-commit-lint.yml
packages/appeal-reply-service-api/pipelines/azure-pipelines-build.yml
packages/appeal-reply-service-api/pipelines/azure-pipelines-release.yml
packages/appeals-service-api/pipelines/azure-pipelines-build.yml
packages/appeals-service-api/pipelines/azure-pipelines-release.yml
packages/business-rules/pipelines/azure-pipelines-build.yml
packages/clamav-rest-server/pipelines/azure-pipelines-build.yml
packages/clamav-rest-server/pipelines/azure-pipelines-release.yml
packages/common/pipelines/azure-pipelines-build.yml
packages/document-service-api/pipelines/azure-pipelines-build.yml
packages/document-service-api/pipelines/azure-pipelines-release.yml
packages/e2e-tests/pipelines/azure-pipelines-cypress-e2e.yml
packages/forms-web-app/pipelines/azure-pipelines-build.yml
packages/forms-web-app/pipelines/azure-pipelines-release.yml
packages/horizon-functions/pipelines/azure-pipelines-build.yml
packages/horizon-functions/pipelines/azure-pipelines-release.yml
packages/pdf-service-api/pipelines/azure-pipelines-build.yml
packages/pdf-service-api/pipelines/azure-pipelines-release.yml
packages/ping/pipelines/azure-pipelines-build.yml
packages/queue-retry/pipelines/azure-pipelines-build.yml

N/A
Remove unused "deploymentTag" param from release pipelines and bump templates version.

 chore(pipelines): bump templates version and remove unused params

---

packages/forms-web-app/__tests__/unit/controllers/save-and-return.test.js
packages/forms-web-app/src/controllers/save-and-return.js

https://pins-ds.atlassian.net/browse/AS-4951
* remove the `/save-and-return` POST page from the navigation history, so that back functionality from 'your appeal has been saved page' will work as intended

feat(as-4951): remove s&r post page from navigation history

---

azure-pipelines-build.yml

Fixes build steps being skipped when `main` branch pipelines were running.

ci: stop skipping build steps on automatic runs on main branch

---

azure-pipelines-release.yml

- Stop release pipeline skipping deployments as the dependency reference for each job was in the wrong format

ci: fix dependency reference in release pipeline

---

packages/appeals-service-api/__tests__/developer/developer.test.js
packages/appeals-service-api/src/mappers/horizon-mapper.js

https://pins-ds.atlassian.net/browse/AS-5721

fix(as-5721): escape xml characters in document filenames

---

packages/appeals-service-api/__tests__/developer/developer.test.js
packages/appeals-service-api/__tests__/developer/fixtures/finalComments.js
packages/appeals-service-api/src/errors/apiError.js
packages/appeals-service-api/src/repositories/final-comments-repository.js
packages/appeals-service-api/src/repositories/mongo-repository.js
packages/appeals-service-api/src/routes/final-comments.js
packages/appeals-service-api/src/routes/index.js
packages/appeals-service-api/src/services/final-comments.service.js

this has been future proofed to allow not-only appellants to submit final comments but also any other usertype as required. The code does a scan of the database to check if any final comments exist for a certain horizonId (note this should possibly be renamed??), if one or more exists it checks if any of them have the same email as the one being submitted. If there is then it rejects submission with a 409 conflict, otherwise it submits the data to the appeals beta's database. This is is then ready for submission to horizon/the backend
#as-5788
https://pins-ds.atlassian.net/browse/AS-5868

feat(as-5868): add submission of data to database api

---

packages/forms-web-app/__tests__/unit/lib/client-side/javascript-requiring-consent.test.js
packages/forms-web-app/__tests__/unit/views/includes/__snapshots__/head.njk.test.js.snap
packages/forms-web-app/__tests__/unit/views/includes/head.njk.test.js
packages/forms-web-app/src/lib/client-side/javascript-requiring-consent.js
packages/forms-web-app/src/views/includes/head.njk
packages/forms-web-app/webpack.common.js

https://pins-ds.atlassian.net/browse/AS-5870
Google tag manager needs a default cookie consent value set before the script is run, this has been added to head.njk
The js that sets consent then needs to have access to the gtm id so that has been passed through in compilation using webpack.
javascript-requiring-consent.js is refactored with the intention of having a clearer distinction of what occurs when the feature flag is toggled

fix: set google tag manager default consent setting

---

packages/forms-web-app/src/views/full-appeal/check-your-answers.njk

https://pins-ds.atlassian.net/browse/AS-5905

fix(as-5905): show multifile for planning obligation on cya page

---

packages/appeals-service-api/src/gateway/horizon-gateway.js

https://pins-ds.atlassian.net/browse/AS-5922
Updated the error handling of makeRequestAndHandleAnyErrors that makes requests to horizon wrapper
Previously only handled scenarios that conformed to a specific SOAP format.
It should now log an error of any failure helping to avoid duplicates.
Separate work to improve process to be handled in AS-5923

fix(as-5922): handle errors without response in horizon requests

---

packages/forms-web-app/src/app.js
packages/forms-web-app/src/server.js
packages/pdf-service-api/src/app.js
packages/pdf-service-api/src/main.js

AS-5774
https://pins-ds.atlassian.net/browse/AS-5774
The application insights sdk needs to be initialised as early as possible in the application lifecycle, for the forms web app and the pdf service this wasn't the case

[AS-5774] Refactor bootstrap sequence for application insights

---

packages/document-service-api/src/main.js

AS-5774
https://pins-ds.atlassian.net/browse/AS-5774
Additional refactor of the app insights bootstrap logic to ensure initialisation before mongo db connection initialisation.

[AS-5774] Refactor app insights bootstrap logic to enforce startup before mongo db connection initialisation

---

packages/appeals-service-api/src/main.js
packages/clamav-rest-server/src/main.js
packages/document-service-api/src/main.js
packages/forms-web-app/src/server.js
packages/lpa-questionnaire-web-app/src/app.js

AS-5774
https://pins-ds.atlassian.net/browse/AS-5774
Pass in true to force usage of the experimental async hooks module to provide correlation, otherwise it relies on patching to provide log correlation for async calls. See here for more info setAutoDependencyCorrelation

(feat AS-5774) for usage of async hooks module for correlation

---

packages/forms-web-app/__tests__/unit/controllers/common/enter-code.test.js
packages/forms-web-app/__tests__/unit/controllers/common/need-new-code.test.js
packages/forms-web-app/src/controllers/common/enter-code.js
packages/forms-web-app/src/controllers/common/need-new-code.js

https://pins-ds.atlassian.net/browse/AS-5914
Enter code page was not creating or sending a token so the need new code feature did not have a token to check against.
Enter code page now sends a token on the get request to be in line with confirm email and save/return

fix(as-5914): send token to user on get of enter code page

---

packages/common/src/utils.js
packages/common/src/utils.test.js
packages/forms-web-app/__tests__/unit/controllers/common/enter-code.test.js
packages/forms-web-app/__tests__/unit/services/lpa-user.service.test.js
packages/forms-web-app/src/controllers/common/enter-code.js
packages/forms-web-app/src/lib/is-token-valid.js
packages/forms-web-app/src/services/lpa-user.service.js

Allows test code to be used to log into LPA dashboard if user belongs to test council

feat(lpa-dashboard): allow test security code to be used for lpa login

---

data/init.js
data/package-lock.json
data/package.json

Any string in seed data that gets parsed by the date-fns parseIso function will be added as a date object rather than a string

chore(seed-data): add dates from seed data as date objects in mongo

---

packages/appeals-service-api/__tests__/developer/appeals-case-data.test.js
packages/appeals-service-api/__tests__/developer/fixtures/appeals-case-data.js
packages/appeals-service-api/__tests__/unit/lib/encode.test.js
packages/appeals-service-api/__tests__/unit/services/appeals-case-data.service.test.js
packages/appeals-service-api/src/lib/encode.js
packages/appeals-service-api/src/services/appeals-case-data.service.js
packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/your-appeals.test.js
packages/forms-web-app/src/controllers/lpa-dashboard/your-appeals.js
packages/forms-web-app/src/views/manage-appeals/your-appeals.njk

https://pins-ds.atlassian.net/browse/AAPD-24
Encoded url slug at api level, with a function to decode if needed, slightly nervous around the suggestion to replace '/' with '\_' as it'll break if a ref already has an '\_'

feat(aapd-24): add appeal num to your appeals page

---

packages/appeals-service-api/__tests__/developer/developer.test.js
packages/appeals-service-api/src/repositories/appeals-case-data-repository.js
packages/appeals-service-api/src/services/appeals-case-data.service.js
packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/appeal-details.test.js
packages/forms-web-app/src/app.js
packages/forms-web-app/src/controllers/lpa-dashboard/appeal-details.js
packages/forms-web-app/src/dynamic-forms/controller.js
packages/forms-web-app/src/dynamic-forms/controller.test.js
packages/forms-web-app/src/dynamic-forms/dynamic-components/boolean/index.njk
packages/forms-web-app/src/dynamic-forms/dynamic-components/boolean/question.js
packages/forms-web-app/src/dynamic-forms/dynamic-components/boolean/validation.js
packages/forms-web-app/src/dynamic-forms/dynamic-components/task-list/index.njk
packages/forms-web-app/src/dynamic-forms/dynamic-components/views.js
packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js
packages/forms-web-app/src/dynamic-forms/has-questionnaire/route.js
packages/forms-web-app/src/dynamic-forms/journey.js
packages/forms-web-app/src/dynamic-forms/question.js
packages/forms-web-app/src/dynamic-forms/section.js
packages/forms-web-app/src/lib/views.js
packages/forms-web-app/src/routes/lpa-dashboard/index.js
packages/forms-web-app/src/views/manage-appeals/appeal-details.njk
packages/forms-web-app/src/views/manage-appeals/your-appeals.njk

https://pins-ds.atlassian.net/browse/aapd-105
Have added a folder structure for the dynamic questionnaire + the initial page
Have kept views alongside the component, which I think means we need to be careful to avoid folder-name clashes so have put in a folder called dynamic-components instead of just components - any smarter way to avoid that?

feat(aapd-105): add basic folder and routing structure for dynamic forms

---

packages/appeals-service-api/src/repositories/document-metadata-repository.js

We tried to make the getDocumentMetadata query a bit more readable however this wasn't the right direction with the current mongo sdk. We could look to pass this in a string in the format of a mongo query but for now it's just easier to pass it in as an inline object in method parameter
AAPD-69
AAPD-69
https://pins-ds.atlassian.net/browse/AAPD-69
We tried to make the getDocumentMetadata query a bit more readable however this wasn't the right direction with the current mongo sdk. We could look to pass this in a string in the format of a mongo query but for now it's just easier to pass it in as an inline object in method parameter
Please do not merge from `main` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history …

fix(AAPD-69): fix syntax on mongo query

---

packages/appeals-service-api/__tests__/developer/appeals-document-meta-data.test.js
packages/appeals-service-api/src/errors/apiError.js
packages/appeals-service-api/src/routes/documentMetadata.js
packages/appeals-service-api/src/services/document-metadata.service.js
packages/forms-web-app/__tests__/unit/controllers/lpa-dashboard/appeal-details.test.js
packages/forms-web-app/src/controllers/lpa-dashboard/appeal-details.js
packages/forms-web-app/src/lib/appeals-api-wrapper.js

https://pins-ds.atlassian.net/browse/aapd-177

fix(aapd-177): appeals details page handles null document metadata

---

packages/forms-web-app/src/dynamic-forms/controller.js
packages/forms-web-app/src/dynamic-forms/controller.test.js
packages/forms-web-app/src/dynamic-forms/dynamic-components/task-list/index.njk
packages/forms-web-app/src/dynamic-forms/dynamic-components/task-list/questionnaire.njk
packages/forms-web-app/src/dynamic-forms/section.js
packages/forms-web-app/src/dynamic-forms/section.test.js

https://pins-ds.atlassian.net/browse/aapd-148
- Calculate section statuses and number of completed sections
- relies on each section having at least one required section

feat(aapd-148): calculate journey section states

---

packages/forms-web-app/src/dynamic-forms/dynamic-components/task-list/index.njk

https://pins-ds.atlassian.net/browse/aapd-148
Used macros for status tags and used correct colours

fix(aapd-148): set colour on task list status tags

---

packages/forms-web-app/src/dynamic-forms/controller.js
packages/forms-web-app/src/dynamic-forms/controller.test.js
packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-file-upload/question.js
packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-file-upload/question.test.js
packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js
packages/forms-web-app/src/dynamic-forms/has-questionnaire/questions.js

* update URL for report-upload page
* change multifile upload save action to handle situations where user is attempting to upload valid and invalid files (i.e. valid files will be uploaded and displayed on re-rendered file upload page, together with error message(s) about invalid file(s))

feat(aapd-262): change url for report-upload page and fix file upload

---

packages/integration-functions/appeals-case-data-fo-integration/function.json

Fix proeprty names and values on function config for inbound appeals case data integration
AAPD-45
Fix function json config for appeals case data ingestion

chore(AAPD-45): fix naming conventions on function config

---

packages/appeals-service-api/src/db/setup.js

fix(db-indexes): make failing caseref index not unique

---

package-lock.json
packages/integration-functions/appeals-case-data-fo-integration/index.js
packages/integration-functions/package-lock.json
packages/integration-functions/package.json

The last version of got that supports the require syntax is 11.8.3
AAPD-45
Downgrade got package so it supports require syntax

build(AAPD-45): downgrade got to support require

---

packages/appeals-service-api/src/routes/appeals-case-data.js
packages/integration-functions/appeals-case-data-fo-integration/index.js

Incorrect API route for appeals case data post
AAPD-45
Incorrect api route for appleas case dat post

feat(AAPD-45): change api route for appeals case data post

---

data/init.js
packages/appeals-service-api/__tests__/unit/services/appeals-case-data.service.test.js
packages/appeals-service-api/src/repositories/appeals-case-data-repository.js

Appeals case data that comnes from the back office will use UTC ISO date string format, we don't need or want keep converting that. Mongo sort can handle date strings as long as they are ISO 8601
No need to use iso date object for appeals case data, mongo can support valid iso 8601 date strings for querying and sorting purposes

feat(AAPD-45): don't use date object for appeals case data

---

packages/forms-web-app/src/dynamic-forms/dynamic-components/address-add-more/question.js
packages/forms-web-app/src/dynamic-forms/dynamic-components/list-add-more/index.njk
packages/forms-web-app/src/dynamic-forms/dynamic-components/list-add-more/question.js
packages/forms-web-app/src/dynamic-forms/dynamic-components/macros/answer-list.njk
packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js
packages/forms-web-app/src/dynamic-forms/middleware/utils.js
packages/forms-web-app/src/dynamic-forms/question.js
packages/forms-web-app/src/dynamic-forms/questions.js

Adds the ability to add neighbouring properties to a questionnaire response. Fixes a bug with list add more questions that causes a rendering failure when there is only on item in a list for a list add more question
https://pins-ds.atlassian.net/browse/AAPD-291
Adds the ability to add neighbouring properties to a questionnaire response. 
Fixes a bug with list add more questions that causes a rendering failure when there is only on item in a list for a list add more question. 
Custom format option on base question class

feat(AAPD-291): add neighbouring properties

---

data/data/appeals-service-api/006-listedBuilding.json
data/init.js
packages/appeals-service-api/src/db/setup.js

https://pins-ds.atlassian.net/browse/AAPD-371
Have added the collections with shard keys manually in azure, shard keys are not automatically indexed
parseISO apparently accepts strings like 1010101 as a valid date

feat(aapd-371): listed building indexes and local data

---

packages/forms-web-app/src/dynamic-forms/dynamic-components/identifier/index.njk
packages/forms-web-app/src/dynamic-forms/dynamic-components/identifier/question.js
packages/forms-web-app/src/dynamic-forms/dynamic-components/identifier/question.test.js
packages/forms-web-app/src/dynamic-forms/questions.js

https://pins-ds.atlassian.net/browse/AAPD-359
Inverts the identifier class to specify using a custom label rather than a custom pageHeading
This allows the visually hidden text on task list to use the question property, as it currently reads out 'Seven digit number'
Think it keeps the use of the question property more consistent

feat(aapd-359): change identifier to use label instead of pageHeading

---

packages/forms-web-app/src/dynamic-forms/dynamic-components/add-more/question.js
packages/forms-web-app/src/dynamic-forms/dynamic-components/identifier/index.njk
packages/forms-web-app/src/dynamic-forms/dynamic-components/list-add-more/question.js
packages/forms-web-app/src/dynamic-forms/dynamic-components/list-add-more/question.test.js
packages/forms-web-app/src/dynamic-forms/dynamic-components/listed-building-add-more/question.js
packages/forms-web-app/src/dynamic-forms/dynamic-components/listed-building-add-more/question.test.js
packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js
packages/forms-web-app/src/dynamic-forms/questions.js

https://pins-ds.atlassian.net/browse/AAPD-95
Added the functionality of adding more than 1 listed building

feat(aapd-95): enable adding more listed buildings

---

packages/appeals-service-api/src/mappers/questionnaire-submission/has-mapper.js

Typo in other appeals refs field name on has
mapper

fix(AAPD-313): typo on appeals ref field name

---

packages/appeals-service-api/src/mappers/questionnaire-submission/has-mapper.js

Use undefined to pass schema validation on back office and json stringy to convert object payload to json

fix(AAPD-313): use undefined and json stringify in has mapper

---

packages/appeals-service-api/src/mappers/questionnaire-submission/has-mapper.js

We should add the notified reasons to the array if they exist instead of adding undefined
Instead of adding undefined into the array for how people were notified we should only add the items if they exist

feat(AAPD-313): map notified who values

---

azure-pipelines-build.yml

N/A
Change to the Build pipeline trigger to avoid multiple runs per PR. Run build on:
- commit to main
- PR

chore(ci): only trigger build on PR and main branch

---

azure-pipelines-build.yml
azure-pipelines-pr.yml

[AS-5891](https://pins-ds.atlassian.net/browse/AS-5891)
Add in a PR pipeline which does linting & tests, to avoid building on every PR when the artefacts are not used.
**Note: this will require a rules change as Build checks won't run on PR**

ci(as-5891): add pr pipeline, without build steps

---

packages/forms-web-app/__tests__/unit/lib/session.test.js
packages/forms-web-app/src/lib/session.js

Allows session secrets to be rotated by using an array.
Session secrets to be added as new||old1||old2

feat(session): allow session secrets to be rotated by using an array

---

packages/appeals-service-api/src/mappers/questionnaire-submission/has-mapper.js
packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js

AAPD-589
Removes pages from HAS Questionnaire - pages will be covered by new checkbox page

feat(aapd-589): remove questions from HAS journey

---

packages/appeals-service-api/src/mappers/appeal-submission/has-mapper.js

HAS mapper for appeal submissions had incorrect casing for lpa code.

fix(AAPD-582): fix lpaCode propertty name on appeal submissions

---

packages/appeals-service-api/src/mappers/appeal-submission/has-mapper.js

The schema validation for back office doesn't handle nulls, so pass undefined instead

fix(AAPD-582): handle condtional appeal response for has mapper

---

azure-pipelines-deploy.yml

https://pins-ds.atlassian.net/browse/AAPD-809
Horizon function deploy was broken. Not required anymore but cleaner to fix it.

fix(aapd-809): reference correct horizon-functions artifact

---

README.md
packages/appeals-service-api/README.md
packages/appeals-service-api/src/repositories/back-office-repository.js

Direct integration with horizon is the desired behaviour and there is currently no other mechanism to do this so removing the now redundant feature flag
https://pins-ds.atlassian.net/browse/AAPD-803

chore(AAPD-803): removes the feature flag for horizon integration

---

packages/appeals-service-api/Dockerfile
packages/appeals-service-api/package.json

https://pins-ds.atlassian.net/browse/AAPD-617
Move prisma generate to Docker build to fix
` Can't write to /opt/node_modules/prisma please make sure you install "prisma" with the right permissions.`
error

fix(aapd-617): move generate to docker build

---

packages/forms-web-app/src/dynamic-forms/questions.js

still needs another validator class to only run given a specific answer is selected. StringValidator currently always runs regardless of which option is selected

fix(AAPD-663): hotfix regex validation to allow blank string

---

docker-compose.yml

https://pins-ds.atlassian.net/browse/AAPD-617
Forgot to update `docker-compose` env vars.

fix(aapd-617): add connection strings to docker-compose

---

docker-compose.yml
packages/appeals-service-api/src/configuration/config.js
packages/appeals-service-api/src/lib/logger.js

N/A
API should log in JSON unless configured to pretty print for local dev.

fix(api): only pretty print logs for local dev

---

azure-pipelines-deploy.yml

The deployment pipeline is slow (particularly zip deploying integration functions), this PR stops the auto deployment of less frequently changed apps
It would be preferable to trigger the deployment of the apps only when they have been changed, this is a simple workaround until that can be figured out

ci(pipeline): don't auto-deploy all apps

---

jsconfig.json
packages/appeals-service-api/jsconfig.json
packages/appeals-service-api/package.json
packages/appeals-service-api/src/routes/appeal-users.js
packages/appeals-service-api/src/routes/appeals.spec.yaml
packages/appeals-service-api/src/routes/index.js
packages/appeals-service-api/src/routes/v2/index.js
packages/appeals-service-api/src/routes/v2/users/controller.js
packages/appeals-service-api/src/routes/v2/users/index.js
packages/appeals-service-api/src/routes/v2/users/service.js
packages/appeals-service-api/src/routes/v2/users/spec.yaml
packages/appeals-service-api/src/spec/appeal-submission.yaml
packages/appeals-service-api/src/spec/appeal-user.yaml
packages/appeals-service-api/src/spec/errors.yaml
packages/appeals-service-api/src/spec/gen-api-spec.js

N/A
Move the new /v2/users route to a new folder structure. Based off the work done in `web-comment` to load routes dynamically from the file structure. Moves controllers, services, routers, and spec into a single folder per route.

feat(api): v2 folder structure

---

packages/appeals-service-api/src/db/migrations/20231212112838_service_user/migration.sql
packages/appeals-service-api/src/db/schema.prisma
packages/appeals-service-api/src/db/seed/data-dev.js
packages/appeals-service-api/src/repositories/sql/service-user-repository.js
packages/appeals-service-api/src/routes/v2/appeal-cases/controller.js
packages/appeals-service-api/src/routes/v2/appeal-cases/repo.js
packages/appeals-service-api/src/routes/v2/appeal-cases/service.js
packages/appeals-service-api/src/routes/v2/appeal-cases/spec.yaml
packages/appeals-service-api/src/spec/appeal-case.yaml
packages/appeals-service-api/src/spec/service-user.yaml

https://pins-ds.atlassian.net/browse/AAPD-977
- added ServiceUser table
- return appellant if found and query param set, with appeal-case data
(aware we want some tests for this and appeal-case endpoint. Still on the list, just unblocking other work for now)

feat(api): return appellant data with appeal-case

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

Removed helm from PR template
Removed some redundant docs, infra documentation can be handled by that repo, may become out of date otherwise
I don't think the group info is relevant anymore
Deployment we are documenting in confluence

docs(docs): remove unused docs and PR template check

---

packages/appeals-service-api/src/controllers/save.js
packages/forms-web-app/__tests__/unit/controllers/document.test.js
packages/forms-web-app/src/controllers/common/enter-code.js
packages/forms-web-app/src/controllers/document.js

https://pins-ds.atlassian.net/browse/AAPD-974
This is intended as a temporary fix for appeal pdf downloads until appeal dashboard is complete
If a user tries to access a document from their appeal when the session is ended:
- create a save and return entry in mongo, without sending an email
- store doc url in session
- redirect to enter code page
- after user enters code redirect back to doc url - downloading file

fix(aapd-974): allow download of pdf after losing session

---

packages/appeals-service-api/__tests__/unit/lib/duration.test.js
packages/appeals-service-api/src/configuration/config.js
packages/appeals-service-api/src/controllers/appeals-for-submission-to-horizon-scheduler.js
packages/appeals-service-api/src/gateway/horizon-gateway.js
packages/appeals-service-api/src/lib/duration.js
packages/appeals-service-api/src/services/back-office.service.js

https://pins-ds.atlassian.net/browse/AAPD-1041
Changes to the scheduled submission to Horizon:
- try/catch for each submission so appeals don't get 'stuck' behind a failing submission
- update/delete submissions after all have been processed rather than one at a time
- return complete/failed/error counts
- log complete/failed/error counts

fix(aapd-1041): catch errors for each submission to horizon

---

packages/forms-web-app/src/controllers/appeals/your-appeals.js
packages/forms-web-app/src/controllers/appeals/your-appeals/decided-appeals.js

https://pins-ds.atlassian.net/browse/AAPD-987
Allow your appeals and decided appeals page display with no users in session to allow testing

feat(aapd-987): make your appeals and decided appeals page display with no user found

---

packages/common/src/lib/appeal-sorting.js
packages/common/src/lib/appeal-sorting.test.js
packages/forms-web-app/src/controllers/lpa-dashboard/decided-appeals.js

https://pins-ds.atlassian.net/browse/AAPD-938
Add sort-appeal functions to common package, uses these in sorting lpaUser decided dashboard

fix(aapd-938): fix lpaUser decided list order

---

packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js
packages/forms-web-app/src/dynamic-forms/section.js
packages/forms-web-app/src/dynamic-forms/section.test.js

https://pins-ds.atlassian.net/browse/AAPD-791
- Bug fix: remove an extra question condition.
- Section change: don't allow multiple conditions to be added sequentially

fix(aapd-791): remove extra question condition

---

Makefile
README.md
dev/mock-clamav/index.js
dev/mock-clamav/package.json
dev/mock-pdf/index.js
dev/mock-pdf/package.json
docker-compose.full.yml
docker-compose.slim.yml
docker-compose.yml
package-lock.json
package.json

**Profiles:**
Setup 3 docker profiles and a make script to run them
- all
- appeals (forms web app and dependencies)
- comment  (web comment and dependencies, guessed with these having not worked on it)
**Service Mocks**
Mock clam av and pdf service to have slimmer option for running locally
Use these mocks with docker-compose.slim.yml

chore(local-dev): setup docker profiles and mock services

---

packages/forms-web-app/src/controllers/appeal/new-saved-appeal.js
packages/forms-web-app/src/lib/views.js
packages/forms-web-app/src/routes/appeal/new-saved-appeal.js
packages/forms-web-app/src/views/appeals/your-appeals.njk

https://pins-ds.atlassian.net/browse/AAPD-1109
/appeal/new-saved-appeal sets a session variable to know where to redirect you after entering code
Currently the journey asks you to confirm email on each new appeal
This PR stops a long loop of a user clicking on start new and ending up back on the appeal list page

fix(aapd-1109): fix start new link

---

packages/appeals-service-api/src/db/migrations/20240112150421_view_appeal_new_fields/migration.sql
packages/appeals-service-api/src/db/schema.prisma

https://pins-ds.atlassian.net/browse/AAPD-1187
Added data model fields to prisma schema

feat(aapd-1187): add data model fields to appealcase and schema

---

packages/appeals-service-api/src/routes/v2/users/_id/appeals/service.js

We noticed on dev/test that an appeal was coming back `null` because there was a SQL entry but no corresponding Cosmos entry.

fix(api): filter out submission drafts not found in the db

---

packages/business-rules/src/utils/decision-outcome.js
packages/forms-web-app/src/lib/dashboard-functions.js
packages/forms-web-app/src/views/appeals/your-appeals/decided-appeals.njk
packages/forms-web-app/src/views/manage-appeals/decided-appeals.njk
packages/web-comment/src/routes/decided-appeals/controller.js
packages/web-comment/src/routes/decided-appeals/index.njk

https://pins-ds.atlassian.net/browse/AAPD-922
https://pins-ds.atlassian.net/browse/AAPD-939
https://pins-ds.atlassian.net/browse/AAPD-995
Consolidate the appeal decision colour logic - we had three slightly different approaches.

fix(aapd-939): use shared function for decision colour

---

packages/forms-web-app/__tests__/unit/lib/file-size-display-helper.test.js
packages/forms-web-app/__tests__/unit/validators/common/multifile-upload.test.js
packages/forms-web-app/__tests__/unit/validators/common/schemas/file-upload.test.js
packages/forms-web-app/__tests__/unit/validators/common/schemas/multifile-upload-schema.test.js
packages/forms-web-app/src/config.js
packages/forms-web-app/src/dynamic-forms/validator/multifile-upload-validator.test.js
packages/forms-web-app/src/lib/file-size-display-helper.js
packages/forms-web-app/src/validators/common/schemas/file-upload.js
packages/forms-web-app/src/validators/common/schemas/multifile-upload-schema.js
packages/forms-web-app/src/views/appellant-submission/appeal-statement.njk
packages/forms-web-app/src/views/appellant-submission/supporting-documents.njk
packages/forms-web-app/src/views/appellant-submission/upload-application.njk
packages/forms-web-app/src/views/appellant-submission/upload-decision.njk
packages/forms-web-app/src/views/full-appeal/submit-appeal/appeal-statement.njk
packages/forms-web-app/src/views/full-appeal/submit-appeal/application-form.njk
packages/forms-web-app/src/views/full-appeal/submit-appeal/certificates.njk
packages/forms-web-app/src/views/full-appeal/submit-appeal/decision-letter.njk
packages/forms-web-app/src/views/full-appeal/submit-appeal/design-access-statement.njk
packages/forms-web-app/src/views/full-appeal/submit-appeal/draft-statement-common-ground.njk
packages/forms-web-app/src/views/full-appeal/submit-appeal/letter-confirming-application.njk
packages/forms-web-app/src/views/full-appeal/submit-appeal/original-decision-notice.njk
packages/forms-web-app/src/views/full-appeal/submit-final-comment/upload-documents.njk
packages/forms-web-app/src/views/layouts/multi-file-upload.njk

https://pins-ds.atlassian.net/browse/AAPD-654
Issues with max file size displayed to user,
Didn't know file-size-display-helper existed, have fixed that for binary sizes
Have made the hardcoded values use this filter
Have removed the file type size variations as it wasn't used in the actual file size check and we have no current variations

fix(aapd-654): standardise max file size logic

---

packages/common/src/frontend/pins/components/appeal-documents-block.njk
packages/common/src/frontend/pins/components/appeal-sections-block.njk
packages/forms-web-app/src/controllers/selected-appeal/selected-appeal.js
packages/forms-web-app/src/views/selected-appeal/appeal.njk

https://pins-ds.atlassian.net/browse/AAPD-946
Adds a reusable macro in common package - this builds the documents blocks which are seen on the view appeal page.

feat(946): add appeals documents block macro

---

packages/appeals-service-api/src/db/seed/data-dev.js
packages/appeals-service-api/src/routes/v2/users/_id/appeal-cases/_caseReference/repo.js
packages/appeals-service-api/src/routes/v2/users/_id/appeal-cases/_caseReference/spec.yaml

https://pins-ds.atlassian.net/browse/AAPD-1075
Fix API that returned cases even if no link to the user
Add some rule-6-parties to seed data, and link to some appeals. Also mark most seeded appeals as published.

chore: add rule-6-party seed data

---

packages/common/src/client/appeals-api-client.js
packages/common/src/client/appeals-api-client.test.js
packages/common/src/constants.js
packages/forms-web-app/src/lib/appeals-api-client.js
packages/forms-web-app/src/middleware/create-api-clients.js
packages/forms-web-app/src/middleware/create-api-clients.test.js
packages/forms-web-app/src/routes/index.js
packages/forms-web-app/src/services/appeal-user.service.js
packages/integration-functions/bo-appeal-case/index.js
packages/web-comment/src/utils/appeals-api-client.js

Adds api clients to all requests, authorized if user is present otherwise will use client credentials
Need to replace lib/appeals-api-client.js going forward, will do in a separate PR

feat: add authorized api clients via middleware

---

packages/appeals-service-api/src/errors/apiError.js
packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/address/controller.js
packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/address/index.js
packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/address/repo.js
packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/address/service.js
packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/document-upload/controller.js
packages/common/src/client/appeals-api-client.js
packages/forms-web-app/src/dynamic-forms/controller.js
packages/forms-web-app/src/dynamic-forms/controller.test.js
packages/forms-web-app/src/dynamic-forms/dynamic-components/list-add-more/question.js
packages/forms-web-app/src/dynamic-forms/dynamic-components/list-add-more/question.test.js

https://pins-ds.atlassian.net/browse/AAPD-1032
Adds functionality to ensure multiple addresses can be added and shown, and to remove addresses from sql
- X New features have tests

fix(1032): remove submission address

---

packages/forms-web-app/src/dynamic-forms/section.js
packages/forms-web-app/src/dynamic-forms/section.test.js

https://pins-ds.atlassian.net/browse/AAPD-1440
Amend the isComplete check for sections when displaying on the task list, now check is relevant uploaded files for question
- X New features have tests

fix(aapd-1440): amend section isComplete check to account for sql document upload

---

dev/release-util/src/commit-summary.js

allow choice of csv separator in release utils

chore: allow choice of csv separator in release utils

---

packages/forms-web-app/src/dynamic-forms/section.js

https://pins-ds.atlassian.net/browse/AAPD-1440
Makes an amendment to the getStatus check for displaying sections on the questionnaire task list to account for SQL storage of addresses.

fix(1440): amend section complete check for address questions

---

packages/appeals-service-api/src/repositories/appeals-repository.js
packages/appeals-service-api/src/routes/appeals.js
packages/appeals-service-api/src/services/appeal.service.js
packages/forms-web-app/src/controllers/appeal-householder-decision/list-of-documents.js
packages/forms-web-app/src/lib/appeals-api-wrapper.js

when creating a v2 appeal we need to delete the v1 created during before you start to avoid duplicates in the dashboard

fix: delete v1 appeal after creating a v2

---

packages/common/src/feature-flags.js
packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/list-of-documents.test.js
packages/forms-web-app/src/controllers/appeal-householder-decision/list-of-documents.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/list-of-documents.js
packages/forms-web-app/src/dynamic-forms/journey-factory.js
packages/forms-web-app/src/dynamic-forms/middleware/get-journey-response-for-appellant.js
packages/forms-web-app/src/dynamic-forms/s78-appeal-form/journey.js
packages/forms-web-app/src/dynamic-forms/s78-appeal-form/journey.test.js
packages/forms-web-app/src/routes/appeals/index.js
packages/forms-web-app/src/routes/appellant-submission/submission-form.js

https://pins-ds.atlassian.net/browse/AAPD-1724
Two new feature flags (HAS_APPEAL_FORM_V2, S78_APPEAL_FORM_V2) as well as removing defunct APPEAL_FORM_V2.
Add routes for new S78 V2 appeal form submission.
Creates S78 Appeal Journey.

feat(1728): add s78 and has appeal form v2 flags

---

packages/forms-web-app/src/dynamic-forms/dynamic-components/task-list/submission.njk

https://pins-ds.atlassian.net/browse/AAPD-1768
Change 'Appeal incomplete' into a bold paragraph rather than h2

fix(1768): convert h2 to p for Appeal incomplete

---

packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/submit/index.test.js
packages/appeals-service-api/src/services/back-office-v2/formatters/has/questionnaire.js

quick fix for lpaq submission
mappers expects an array
aligned the data to current model

fix: fix lpaq submission to an array, align to current model

---

packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-details-rows.js

https://pins-ds.atlassian.net/browse/AAPD-1772
If no contact details have been entered the the appeal details page currently displays 'null null'.  This fix prevents the contact details row being shown if there are not entries for contactFirstName and contactLastName.
An alternative approach would be to set default empty string values, but this would result in a blank column in the Contact Details row. 

fix(1772): avoid null displaying on appeal details page

---

packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/list-of-documents.test.js
packages/forms-web-app/src/controllers/appeal-householder-decision/list-of-documents.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/list-of-documents.js
packages/forms-web-app/src/views/appeal-householder-decision/list-of-documents.njk
packages/forms-web-app/src/views/full-appeal/submit-appeal/list-of-documents.njk

https://pins-ds.atlassian.net/browse/AAPD-1769
When showing list of documents page for HAS and s78 Appeals, checks to see if v2 routes active and if so will not show 'Save and Come Back Later' button.

feat(1769): hide save and continue button on list of documents for v2 routes

---

packages/forms-web-app/src/dynamic-forms/questions.js
packages/forms-web-app/src/dynamic-forms/s78-appeal-form/journey.js

correct error message, add condition to planning status question display
https://pins-ds.atlassian.net/browse/AAPD-1740
Correct error message copy, add display condition for s78 question

fix(1740): correct error message

---

packages/forms-web-app/src/dynamic-forms/dynamic-components/multi-file-upload/question.js

https://pins-ds.atlassian.net/browse/AAPD-1849
Fixes a bug - if a user uploaded the same document in respect of multiple questions, when removing from one question there was no consistency regarding which question's version of the document would be removed.  The fix means we filter by relevant question before deleting the document.

fix(1849): filter uploaded files when removing

---

packages/appeals-service-api/src/configuration/config.js
packages/appeals-service-api/src/services/back-office-v2/formatters/s78/appeal.js
packages/appeals-service-api/src/services/back-office-v2/index.js

https://pins-ds.atlassian.net/browse/AAPD-1808
Creates a placeholder s78 appeal formatter function in order to allow submission of s78 appeal v2.
The formatter will be expanded once the data model is finalised.

feat(1808): add s78 appeal formatter

---

azure-pipelines-pr.yml

Trigger the PR pipeline for merge-queue branches.
See [triggering-merge-group-checks-with-third-party-ci-providers)](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-third-party-ci-providers)

ci: trigger pr pipeline for merge-queue branches

---

packages/appeals-service-api/src/lib/notify.js

https://pins-ds.atlassian.net/browse/AAPD-1854
Corrects the pdf link sent to appellants on submission of appeal

fix(1854): correct pdf link url

---

packages/forms-web-app/src/dynamic-forms/dynamic-components/unit-option-entry/index.njk
packages/forms-web-app/src/dynamic-forms/question.js

https://pins-ds.atlassian.net/browse/AAPD-1809
Corrects errorMessage option being passed to njks component to ensure that error message appears above radio buttons as well as at top of page.  Due to complexity of field name options in this dynamic component the second display uses the errorSummary object rather than the errors object - the errorSummary always contains the correct error for this component.

fix(1809): add second error message above radios

---

packages/appeals-service-api/src/services/back-office-v2/formatters/has/appeal.js
packages/appeals-service-api/src/services/back-office-v2/formatters/s78/appeal.js

https://pins-ds.atlassian.net/browse/AS-461
Adds isGreenBelt fields to appeal submission formatters

fix(461): add required fields to appeal submission formatter

---

packages/forms-web-app/src/dynamic-forms/dynamic-components/checkbox/question.js
packages/forms-web-app/src/dynamic-forms/dynamic-components/unit-option-entry/question.js
packages/forms-web-app/src/dynamic-forms/dynamic-components/utils/question-has-answer.js
packages/forms-web-app/src/dynamic-forms/dynamic-components/utils/question-has-answer.test.js
packages/forms-web-app/src/dynamic-forms/options-question.js

https://pins-ds.atlassian.net/browse/A2-240
Options question used in a journey condition seems to sometimes come through as a joined string and sometimes an array
Have handled both scenarios here, but haven't looked into why this happens

fix: option question condition handles array and joined string

---

packages/appeals-service-api/src/routes/v2/appeals/repo.js
packages/forms-web-app/src/controllers/appeals/your-appeals.js
packages/forms-web-app/src/controllers/appeals/your-appeals/decided-appeals.js
packages/forms-web-app/src/lib/dashboard-functions.js

- Reduces the amount of data retrieved for appellant dashboard for efficiency
- stops dashboard breaking if one appeal cannot be mapped
this was occurring in dev/test due to [AppellantSubmission] records without an applicationDecisionDate set (old data, have fixed data in dev/test)

chore: sql select for appellant dashboard

---

packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-details-rows.js
packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-details-rows.test.js

The check for displaying agent details was backwards
- have inverted check
- added some initial tests for the appeal-details-rows.js

fix: handle agent on appeal-details page

---

package-lock.json
package.json
packages/appeals-service-api/package.json
packages/appeals-service-api/src/routes/v2/appeal-cases/appeal-cases.spec.js
packages/appeals-service-api/src/routes/v2/appeal-cases/repo.js
packages/appeals-service-api/src/routes/v2/appellant-submissions/_id/submit/index.test.js
packages/appeals-service-api/src/services/back-office-v2/formatters/has/appeal.js
packages/appeals-service-api/src/services/back-office-v2/formatters/s78/appeal.js
packages/business-rules/package.json
packages/common/package.json
packages/database/package.json
packages/forms-web-app/package.json
packages/integration-functions/package.json

- links an appeal case retrieved from back office to the initial appellant submission

feat: link appeal to initial submission

---

packages/database/src/migrations/20240726162321_add_submission_dates/migration.sql
packages/database/src/schema.prisma

updatedAt fields need to be nullable without a default
may require the deletion of the failed migration record in dev db

fix: submission updatedAt dates to allow nulls

---

packages/forms-web-app/src/controllers/appeals/your-appeals.js
packages/forms-web-app/src/controllers/common/enter-code.js

Draft appeals that have passed their deadline are displaying in the waiting for review section of your appeals

fix: don't display expired draft appeals on waiting for review page

---

packages/forms-web-app/src/controllers/selected-appeal/index.js

https://pins-ds.atlassian.net/browse/asi-135
don't show questionnaire link when submitted, use date field, boolean previously used doesn't exist

fix(asi-135): don't show questionnairre link when submitted

---

packages/common/src/client/appeals-api-client.js
packages/forms-web-app/src/dynamic-forms/middleware/redirect-to-unanswered-question.js
packages/forms-web-app/src/dynamic-forms/question.js
packages/forms-web-app/src/dynamic-forms/s78-lpa-statement/journey.js

https://pins-ds.atlassian.net/browse/A2-234
adds new journey type to saveResponseToDB function and associated api client

fix(A2-234): save data for new journey, refactor unanswered q middleware

---

docker-compose.yml
packages/common/src/router/readme.md
packages/common/src/router/v2/index.js
packages/common/src/router/v2/index.test.js
packages/common/src/router/v2/test-dir/not-live/index.js
packages/forms-web-app/__tests__/unit/routes/index.test.js
packages/forms-web-app/src/app.js
packages/forms-web-app/src/config.js
packages/forms-web-app/src/routes/index.js

Adds the ability to use feature flags to disable file-based-router routes
Adds new feature flags
Moves to central prop on config

feat: add feature flag for comments

---

packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/appeals/_appealNumber/controller.js
packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/appeals/_appealNumber/index.njk
packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/decided-appeals/index.njk
packages/forms-web-app/src/utils/appeal-status.js
packages/forms-web-app/src/utils/appeals-view.d.ts
packages/forms-web-app/src/utils/format-comment-decided-data.js
packages/forms-web-app/src/utils/format-headline-text.js

https://pins-ds.atlassian.net/browse/A2-598
Adds active links for decided appeals on Interested Party views.  At present appeal detail page only shows headlines, not full appeal details.

feat(a2-598): ip decided appeal page

---

packages/appeals-service-api/src/services/back-office-v2/formatters/has/questionnaire.js
packages/appeals-service-api/src/services/back-office-v2/formatters/s78/questionnaire.js
packages/appeals-service-api/src/services/back-office-v2/formatters/utils.js

Provides a default doc type in lpaq mapping to data model

fix: provide default doc type for lpaq

---

packages/common/src/document-types.js

https://pins-ds.atlassian.net/browse/a2-1049
https://pins-ds.atlassian.net/browse/a2-1050
- Fixes download of case decision by defining it as a doc type
- Allows download from web-comment of public docs

fix(a2-1050): add case decision doc type and allow access to public docs

---

packages/forms-web-app/src/dynamic-forms/validator/date-validator.js
packages/forms-web-app/src/dynamic-forms/validator/validation-error-handler.js
packages/forms-web-app/src/dynamic-forms/validator/validation-error-handler.test.js

https://pins-ds.atlassian.net/browse/a2-633
Empty error message is created by date validator
Simple fix here is to remove all errors with no message (they cause accessibility/usability issues)
We could look at some other way to refactor the date validator to handle shared errors between the 3 inputs without creating an empty message, perhaps with a custom rule

fix(a2-633): remove empty error messages from dynamic forms validation

---

packages/forms-web-app/src/dynamic-forms/s78-lpa-final-comments/journey.js

Small fix to ensure LPA Final Comments uses right template to display correct service name

fix(a2-248): amend service name

---

packages/forms-web-app/src/dynamic-forms/dynamic-components/submission-screen/lpa-final-comment.njk
packages/forms-web-app/src/dynamic-forms/middleware/redirect-middleware-conditions.js
packages/forms-web-app/src/dynamic-forms/middleware/redirect-middleware-conditions.test.js
packages/forms-web-app/src/routes/appeals/final-comments/index.js
packages/forms-web-app/src/routes/lpa-dashboard/final-comments.js

Adds the correct conditions for determining whether to skip a question in the journey for Appellant and LPA Final Comments.
The existing conditions in the journey file determine what is shown on the task list / check answers - these conditions are used in the actual journey when we redirect to the next unanswered question

Fix - Navigation conditions for Final Comments Journeys

---

packages/appeals-service-api/src/lib/notify.js
packages/appeals-service-api/src/repositories/sql/service-user-repository.js
packages/appeals-service-api/src/routes/v2/service-users/service.js
packages/appeals-service-api/src/services/back-office-v2/index.js
packages/database/src/seed/data-dev.js
packages/database/src/seed/lpa-appeal-case-data-dev.js

https://pins-ds.atlassian.net/browse/A2-273
Uses the serviceUserId to retrieve appellant name details and set them in notify email

fix(a2-273): retrieve appellant name via service user

---

packages/business-rules/src/rules/appeal/deadline-date.test.js

The following tests were used to prove how date-fns handled timezones
This is no longer required and the timezone is printed differently based on target machine's settings

test: remove date-fns tests

---

packages/common/src/document-types.js

https://pins-ds.atlassian.net/browse/A2-757
add planning obligation doc type to make file links function

fix(A2-757): add planning obligation doc type

---

docker-compose.full.yml

https://pins-ds.atlassian.net/browse/A2-1243
I've explicitly defined the platform for building the pdf service in docker compose - this fixes an issue whereby chromium would not install on m1 macs and prevent docker from building the image.
Before approving this PR, it would be useful if a windows-based dev could remove existing pdf service image from docker and check this still builds correctly for them using this branch. 
It would also be helpful if another mac-based developer could confirm this builds correctly - an example postman request is below:

fix: specify pdf service platform

---

packages/forms-web-app/__tests__/unit/mocks.js
packages/forms-web-app/src/controllers/selected-appeal/appeal-details/index.js
packages/forms-web-app/src/controllers/selected-appeal/appeal-details/index.test.js
packages/forms-web-app/src/views/selected-appeal/appeal-details.njk

https://pins-ds.atlassian.net.mcas.ms/jira/software/c/projects/A2/boards/264?selectedIssue=A2-1039
* add a download link to appeals details page when user is LPA User
* generate PDF from current page html and return it to user when download link clicked

feat(a2-1039): add pdf download link to lpa appeal details page

---

packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/planning-officer-details-rows.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/planning-officer-details-rows.test.js

Fix typo to use correct constant for development plan policies appeal documents.
Update unit test.

fix: correct constant for appeal document type

---

packages/forms-web-app/__tests__/unit/lib/selected-appeal-page-setup.test.js
packages/forms-web-app/src/lib/selected-appeal-page-setup.js

https://pins-ds.atlassian.net/browse/A2-469
display appellant final comment when trying to view from lpa view

fix(A2-469): correct displaying of appellant final comments for lpa view

---

packages/appeals-service-api/__tests__/developer/repositories/appeal-user-repository.test.js
packages/appeals-service-api/src/repositories/sql/appeal-user-repository.js
packages/appeals-service-api/src/routes/v2/users/controller.js
packages/appeals-service-api/src/routes/v2/users/index.js
packages/appeals-service-api/src/routes/v2/users/service.js
packages/appeals-service-api/src/routes/v2/users/spec.yaml
packages/appeals-service-api/src/routes/v2/users/users.spec.js
packages/common/src/client/appeals-api-client.js
packages/forms-web-app/src/services/user.service.js

Amend functions and api calls which check whether user is a rule 6 user.  Now uses count to check for Rule6Party role on AppealToUser array on AppealUser.

fix(a2-1236): amend call to confirm whether user is rule 6 user

---

packages/forms-web-app/__tests__/unit/middleware/navigation-history.test.js
packages/forms-web-app/src/middleware/navigation-history.js

https://pins-ds.atlassian.net/browse/A2-1395
when a user clicks a doc link it gets added the nav history so breaks the back button working properly.
this stops the doc link being added to the nav history

fix(A2-1395): stop doc links being added to nav history

---

packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/appeal-final-comments/repo.js
packages/appeals-service-api/src/routes/v2/appeal-cases/repo.js
packages/appeals-service-api/src/routes/v2/documents/index.spec.js
packages/appeals-service-api/src/routes/v2/documents/repo.js
packages/common/src/lib/format-appeal-documents.js
packages/common/src/lib/format-appeal-documents.test.js
packages/database/src/migrations/20241023174115_allow_null_redaction/migration.sql
packages/database/src/schema.prisma
packages/database/src/seed/appeal-documents-dev.js
packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-documents-rows.test.js
packages/forms-web-app/src/controllers/selected-appeal/planning-obligation-details/planning-obligation-details-rows.test.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/constraints-details-rows.test.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/consultation-details-rows.test.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/environmental-details-rows.test.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/planning-officer-details-rows.test.js
packages/integration-functions/__tests__/functions/appeal-document.test.js
packages/integration-functions/src/functions/appeal-document.js

https://pins-ds.atlassian.net/browse/a2-1271
- Makes redacted nullable
- Allows through null/not redacted statuses from service bus
- Displays awaiting review next to documents if they are not redacted yet

feat(a2-1271): show awaiting review documents on dashboards

---

package-lock.json
package.json
packages/appeals-service-api/__tests__/developer/appeals.test.js
packages/appeals-service-api/__tests__/unit/repositories/sql/appeal-user-repository.test.js
packages/appeals-service-api/__tests__/unit/repositories/sql/service-user-repository.test.js
packages/appeals-service-api/src/repositories/sql/appeal-user-repository.js
packages/appeals-service-api/src/repositories/sql/service-user-repository.js
packages/appeals-service-api/src/routes/v2/events/repo.js
packages/appeals-service-api/src/routes/v2/service-users/index.spec.js
packages/database/src/migrations/20241028153215_update_appeal_user_pk/migration.sql
packages/database/src/schema.prisma
packages/database/src/seed/data-dev.js

https://pins-ds.atlassian.net/browse/A2-1352
- Update the PK of AppealToUser table to a uuid
- Need to allow users to have more than 1 role on an appeal to allow for rule6, (change from what was initially expected)
- Warning was given when trying to add role to the key, due to length, so changed to uuid

feat: change primary key to uuid for appeal-user relation

---

packages/forms-web-app/__tests__/unit/lib/client-side/prevent-multiple-submit.test.js
packages/forms-web-app/src/lib/client-side/index.js
packages/forms-web-app/src/lib/client-side/prevent-multiple-submit.js

https://pins-ds.atlassian.net/browse/A2-651
Double click on continue button uploads duplicate files for both full and HAS appeals
- Added client-side code to block multiple submit events to prevent duplicate files being uploaded

fix(a2-651): prevent duplicate submits in fo

---

packages/appeals-service-api/src/lib/notify.js
packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/rule-6-proof-evidence-submission/repo.js
packages/appeals-service-api/src/services/back-office-v2/index.js
packages/appeals-service-api/src/spec/api-types.d.ts
packages/appeals-service-api/src/spec/rule-6-proof-of-evidence-submission.yaml

https://pins-ds.atlassian.net/browse/A2-1085
Fixes the sending of notify email to rule 6 on submission of proofs:
- gets correct proofsDueDate on repo call
- removes unused variables

fix(a2-1085): fix send email to rule 6 on proofs submission

---

packages/common/src/lib/format-appeal-details.js
packages/common/src/lib/format-appeal-details.test.js
packages/common/src/lib/format-questionnaire-details.js
packages/common/src/lib/format-questionnaire-details.test.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/site-access-details-rows.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/site-access-details-rows.test.js

https://pins-ds.atlassian.net/browse/A2-1562
* amend logic to display only LPA user-provided site access / site risk details on LPA questionnaire details page, and only appellant-provided site access / site risk details on appeal details page (on dashboards)

feat(a2-1562): update site access and safety details logic on dashboards

---

packages/forms-web-app/src/lib/client-side/prevent-multiple-submit.js
packages/forms-web-app/src/middleware/cache-busting.js
packages/forms-web-app/src/routes/index.js
packages/forms-web-app/src/views/includes/head.njk

https://pins-ds.atlassian.net/browse/A2-1656
Submit button does nothing after using browser back
- Fixed client-side code to unblock the submission button on browser back
- Added middleware to cache-bust the javascript based on the application start timestamp

fix(a2-1656): allow submit button to work when page loads

---

packages/common/src/client/documents-api-client.js
packages/document-service-api/src/db/repos/repository.js
packages/document-service-api/src/routes/v2/submission/_caseReference/case_stage/_caseStage/controller.js
packages/document-service-api/src/routes/v2/submission/_caseReference/case_stage/_caseStage/controller.test.js
packages/document-service-api/src/routes/v2/submission/_caseReference/case_stage/_caseStage/index.js
packages/forms-web-app/src/controllers/selected-appeal/downloads/documents.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/index.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/index.test.js
packages/forms-web-app/src/dynamic-forms/controller.js
packages/forms-web-app/src/dynamic-forms/dynamic-components/submission-screen/lpa.njk
packages/forms-web-app/src/lib/build-zip-filename.js
packages/forms-web-app/src/routes/lpa-dashboard/questionnaire.js
packages/forms-web-app/src/routes/lpa-dashboard/selected-appeal.js

https://pins-ds.atlassian.net/browse/A2-1179
document-service-api:
- Added a new route to the document-service-api to build a zip file for the specified case reference and case stage: 
- "/v2/submission/{caseReference}/case_stage/{caseStage}" 
- Updated unit tests to the document-service-api   
forms-web-app:
- Amended dashboard route to the forms-web-app as a pass-through endpoint to retrieve the zip file via document-service-api
- "/{appealNumber}/download/back-office/documents/{appealCaseStage}"
- Added submission route to the forms-web-app as a pass-through endpoint to retrieve the zip file via document-service-api
- "/{appealNumber}/download/submission/documents/{appealCaseStage}"
- Updated unit test
Please do not merge from `main` (please only …

feat(a2-1179): add submission documents end point

---

packages/common/src/client/blob-storage-client.js
packages/common/src/lib/getAzureBlobPathFromUri.js
packages/document-service-api/src/routes/v2/back-office/_caseReference/case_stage/_caseStage/controller.js
packages/document-service-api/src/routes/v2/back-office/_caseReference/case_stage/_caseStage/controller.test.js
packages/document-service-api/src/routes/v2/submission/_caseReference/case_stage/_caseStage/controller.js
packages/document-service-api/src/routes/v2/submission/_caseReference/case_stage/_caseStage/controller.test.js

https://pins-ds.atlassian.net/browse/A2-1179
document-service-api:
- Created a reusable function to correctly convert the blob uri supplied by back-office to the correct blob uri for download
- Updated unit tests to the document-service-api   
- Tested manually via front office web

fix(a2-1179): correctly convert stored blob storage uri

---

packages/forms-web-app/src/journeys/question-overrides/multi-file-upload.js

https://pins-ds.atlassian.net/browse/A2-1790
Amends the check when removing files - now makes sure that not all files removed rather than just one (potentially of many)

fix(a2-1790): amend check on removed files to prevent api error

---

packages/appeals-service-api/src/spec/api-types.d.ts
packages/appeals-service-api/src/spec/appeal-case.yaml
packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/appeals/_appealNumber/controller.js
packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/appeals/_appealNumber/index.njk
packages/forms-web-app/src/utils/format-comment-inquiry-text.js
packages/forms-web-app/src/utils/format-comment-inquiry-text.test.js

https://pins-ds.atlassian.net/browse/A2-1198
Adds inquiry date (formatted) on the appeal page for interested parties (if an inquiry event exists for that appeal).
Have updated api spec to reflect that Events related to an appeal case consists of an array of Event types.
Also fixed a small content error in the page title. 

feat(a2-1198): add inquiry date to appeal page for interested party

---

packages/common/src/view-model-maps/events.js
packages/common/src/view-model-maps/events.test.js

https://pins-ds.atlassian.net/browse/A2-1194
Show inquiry data on rule 6 appeal page if it exists.

feat(a2-1194): add inquiry info to rule 6 party selected appeal page

---

azure-pipelines-deploy.yml

https://pins-ds.atlassian.net/browse/A2-1616
- Front end web app has different networking restrictions from other apps, (blocks connections that don't come from front door), this uses the public facing url to route through front door
- variables added to existing group in devops pipeline library

fix(a2-1616): use public url for web verify check

---

docker-compose.yml
packages/appeals-service-api/Dockerfile
packages/auth-server/Dockerfile
packages/document-service-api/Dockerfile
packages/forms-web-app/Dockerfile

- Node alpine released a breaking change that has impacted prisma - (unable to find an ssl library, believe the path has changed)
- Specifying the last working version of alpine in the dockerfile
- Intended as a temporary measure until either alpine reverts the change or prisma updates how it searches for the sll lib 

fix: specify alpine version due to breaking change in latest

---

packages/appeals-service-api/src/routes/v2/appeals/_id/appeals.spec.js
packages/appeals-service-api/src/routes/v2/appeals/_id/controller.js
packages/appeals-service-api/src/routes/v2/appeals/_id/index.js
packages/appeals-service-api/src/routes/v2/appeals/_id/service.js
packages/appeals-service-api/src/routes/v2/appeals/repo.js
packages/appeals-service-api/src/routes/v2/appeals/spec.yaml
packages/appeals-service-api/src/spec/api-types.d.ts
packages/appeals-service-api/src/spec/appeal.yaml
packages/common/src/client/appeals-api-client.js
packages/forms-web-app/src/dynamic-forms/controller.js

https://pins-ds.atlassian.net/browse/A2-1105
sets legacy appeal data to null on v2 appeal once v1 appeal deleted at the end of before you start journey

fix(A2-1105): remove legacy v1 data from v2 appeal

---

packages/appeals-service-api/src/spec/api-types.d.ts
packages/appeals-service-api/src/spec/appellant-final-comment-submission.yaml
packages/appeals-service-api/src/spec/appellant-proof-of-evidence-submission.yaml
packages/appeals-service-api/src/spec/appellant-submission.yaml
packages/appeals-service-api/src/spec/lpa-final-comment-submission.yaml
packages/appeals-service-api/src/spec/lpa-proof-of-evidence-submission.yaml
packages/appeals-service-api/src/spec/lpa-questionnaire-submission.yaml
packages/appeals-service-api/src/spec/lpa-statement-submission.yaml
packages/appeals-service-api/src/spec/rule-6-proof-of-evidence-submission.yaml
packages/appeals-service-api/src/spec/rule-6-statement-submission.yaml
packages/forms-web-app/src/dynamic-forms/controller.js
packages/forms-web-app/src/journeys/question-overrides/multi-file-upload.js

https://pins-ds.atlassian.net/browse/A2-183
Make upload[documents] fields nullable in spec files in order to prevent api errors if deleted uploaded files.
Following the call to remove files (in the getDataToSave function) the array of SubmissionDocumentUploads on the journeyResponse is now updated - this fixes and issue where the removed file continued to be shown on the upload page and the action on the task list remained at change rather than upload, even if the doc was removed.  This was caused by the fact that the journeyResponse was not updated until the next page was called and the previouslyUploadedDocuments array did not take account of the removed files.
Please do not merge from `main` (please only [rebase](https://github.com/Planning-Inspectorate/appeal-planning-decision/wiki/An- …

fix(a2-183): make upload booleans nullable

---

packages/forms-web-app/src/middleware/navigation-history.js

https://pins-ds.atlassian.net/browse/A2-1905
when lpa user is on the questionnaire details page and clicks the download documents zip, stops the link being added to nav history:
/manage-appeals/1000014/download/back-office/documents/lpa-questionnaire
should stop other future links being added if they use a similar format

fix(A2-1905): stop zip download link being added to nav history

---

packages/database/src/migrations/20241216112517_allow_max_comments_in_interested_party_submissions/migration.sql
packages/database/src/schema.prisma
packages/forms-web-app/src/validators/interested-parties/add-comments.js

https://pins-ds.atlassian.net/browse/A2-1793
Increase character count for interested party comments
Forms:
- Updated add-comment validator to allow up to 8000 characters
- Amended the error message to change the limit from 1000 to 8000
API:
- Updated the prisma schema for comments in the InterestedPartySubmission model
- Generated a migration for the update above
Note, I was unable to test as I was unable to reach the specified page with my test data locally but I'm confident this will work.

fix(a2-1793): increase character count for interested party comments

---

packages/database/src/migrations/20241216162049_increase_rule6_statement_to_max/migration.sql
packages/database/src/schema.prisma
packages/forms-web-app/src/config.js
packages/forms-web-app/src/dynamic-forms/questions.js

https://pins-ds.atlassian.net/browse/A2-1792
Increase character count for rule6 statements
Forms:
- Updated rule6 statement validator to allow up to 32500 characters
- Amended the error message to change the limit from 1000 to 32500
API:
- Updated the prisma schema for statements in the Rule6StatementSubmission model
- Generated a migration for the update above
Test:
- Tested manually in browser

fix(a2-1792): increase max character count for rule6 statements

---

packages/forms-web-app/src/dynamic-forms/dynamic-components/utils/format-number.js
packages/forms-web-app/src/dynamic-forms/dynamic-components/utils/format-number.test.js
packages/forms-web-app/src/dynamic-forms/questions.js
packages/forms-web-app/src/validators/interested-parties/add-comments.js

https://pins-ds.atlassian.net/browse/A2-1776
https://pins-ds.atlassian.net/browse/A2-1789
https://pins-ds.atlassian.net/browse/A2-1791
https://pins-ds.atlassian.net/browse/A2-1792
https://pins-ds.atlassian.net/browse/A2-1793
Fix character count for appellant final comments and add commas to the error message for all the above character counts.
Forms:
- Updated appellant final comments validator to only allow up to 8000 characters
- Amended the error message to change the limit to 8,000
- Added a formatNumber function to insert commas where required
- Updated the above character count error messages so the limit contains commas
Test:
- Created unit tests for formatNumber
- Tested manually in browser
Please do not merge from `main` (please only …

fix(a2-1791): fix max character count for lpa statements

---

packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/appeals/controller.js
packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/appeals/controller.test.js

https://pins-ds.atlassian.net/browse/A2-1973
Removes invalid path from navigation history to ensure back button works if no postcodes returned by search.

fix(a2-1973): fix backlink if no postcode search results

---

packages/common/src/document-types.js
packages/document-service-api/src/db/repos/repository.js
packages/document-service-api/src/routes/v2/back-office/_id/access-rules.js
packages/document-service-api/src/routes/v2/back-office/_id/access-rules.test.js
packages/document-service-api/src/routes/v2/back-office/_id/controller.js

Plans drawings doc type is owned by different user group depending on the appeal type

fix: vary document type owner by case type for PLANS_DRAWINGS

---

packages/forms-web-app/src/dynamic-forms/journey.js
packages/forms-web-app/src/dynamic-forms/journey.test.js

https://pins-ds.atlassian.net/browse/A2-1770
Adds check for subquestion fieldname when getting previous question url.

fix(a2-1770): fix backlink for subquestions

---

packages/appeals-service-api/src/routes/v2/appeal-cases/appeal-cases.spec.js
packages/appeals-service-api/src/routes/v2/appeal-cases/repo.js
packages/appeals-service-api/src/routes/v2/users/_id/appeal-cases/_caseReference/repo.js
packages/appeals-service-api/src/spec/api-types.d.ts
packages/appeals-service-api/src/spec/appeal-case.yaml
packages/common/src/database/data-static.js
packages/database/src/migrations/20250115131138_/migration.sql
packages/database/src/schema.prisma
packages/document-service-api/test/developer/developer.test.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/constraints-details-rows.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/constraints-details-rows.test.js

https://pins-ds.atlassian.net/browse/A2-2074
Handling s78 cases from back office - we need to handle a different listed building array
Adds a type field to the database relation and propagates that throughout the codebase
Handles adding relations on put, currently this will be unused until we receive s78 cases

feat(a2-2074): handle multiple listed building relationship types

---

packages/database/src/seed/data-dev.js
packages/database/src/seed/lpa-appeal-case-data-dev.js

Update Q1111 to be the main LPA used for seed data for v2 appeals

chore: switch lpa for seed data

---

packages/forms-web-app/src/controllers/selected-appeal/action-banners.js
packages/forms-web-app/src/controllers/selected-appeal/action-banners.test.js

https://pins-ds.atlassian.net/browse/A2-2363
Expands trigger logic for action banners to include check for existence of relevant date
-  X New features have tests

feat(a2-2363): expand action banner triggers

---

packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-details-rows.js

https://pins-ds.atlassian.net/browse/A2-1798
Changes the lookup for nearby appeals for HAS cases - looks for a 'nearby' relation rather than a 'linked' relation

fix(a2-1798): amend nearby appeals check for HAS

---

package-lock.json
package.json

fix(data model 1.9.16): bump data model to 1.9.16

---

packages/business-rules/test/data/full-appeal.js
packages/forms-web-app/__tests__/unit/controllers/before-you-start/can-use-service.test.js
packages/forms-web-app/__tests__/unit/controllers/full-appeal/listed-building.test.js
packages/forms-web-app/__tests__/unit/controllers/full-appeal/prior-approval-existing-home.test.js
packages/forms-web-app/__tests__/unit/controllers/full-appeal/type-of-planning-application.test.js
packages/forms-web-app/src/controllers/before-you-start/can-use-service.js
packages/forms-web-app/src/controllers/full-appeal/listed-building.js
packages/forms-web-app/src/controllers/full-appeal/prior-approval-existing-home.js
packages/forms-web-app/src/controllers/full-appeal/type-of-planning-application.js
packages/forms-web-app/src/lib/get-next-page-from-can-use-service-page.js
packages/forms-web-app/src/lib/get-next-page-from-can-use-service-page.test.js
packages/forms-web-app/src/views/full-appeal/can-use-service.njk
packages/forms-web-app/src/views/full-appeal/prior-approval/can-use-service.njk
packages/forms-web-app/src/views/householder-planning/eligibility/can-use-service.njk
packages/forms-web-app/src/views/householder-planning/eligibility/prior-approval/can-use-service.njk

https://pins-ds.atlassian.net/browse/A2-2286
* when s20 flag on, do not show 'listed building' y/n question unless removal or variation of conditions selected on type of application page
* when s20 flag on, do not show listed building q on can-use-service page, unless removal or variation of conditions selected on type of application page

feat(a2-2286): remove listed building question for s20 v2

---

packages/appeals-service-api/src/spec/api-types.d.ts
packages/appeals-service-api/src/spec/lpa-questionnaire-submission.yaml
packages/common/src/document-types.js
packages/database/src/migrations/20250219101331_add_appeal_notification_flag/migration.sql
packages/database/src/schema.prisma
packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js
packages/forms-web-app/src/dynamic-forms/questions.js
packages/forms-web-app/src/dynamic-forms/s78-questionnaire/journey.js

[A2-1899](https://pins-ds.atlassian.net/browse/A2-1899)
https://pins-ds.atlassian.net/browse/A2-1899
Added functionality to upload the appeal notification letter and list
[A2-1899]: https://pins-ds.atlassian.net/browse/A2-1899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: added new appeal notification letter question

---

packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/check-answers/controller.js
packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/check-answers/controller.test.js
packages/forms-web-app/src/services/interested-party.service.js

https://pins-ds.atlassian.net/browse/A2-2070
Removes searchPostcode (which is used for navigation and backlinks) from submitted IP comment)

fix(a2-2070): remove searchPostcode from submitted object

---

packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-details-rows.js
packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-details-rows.test.js
packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-documents-rows.js

https://pins-ds.atlassian.net/browse/A2-1797
https://pins-ds.atlassian.net/browse/A2-1798
Small change to add conditional All Owners Known row to appeal details and to amend display logic for display of uploaded new development description

fix(a2-1798): add in knows all owners row

---

packages/appeals-service-api/__tests__/developer/fixtures/representation-data.js
packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/representations/repo.js
packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/representations/representations.spec.js

Representation documents delete many failing as it's using the wrong id

fix: fix representation document transaction

---

packages/forms-web-app/src/views/layouts/comment-planning-appeal/main-no-back-link.njk
packages/forms-web-app/src/views/layouts/comment-planning-appeal/main.njk

https://pins-ds.atlassian.net/browse/A2-1686
Corrects the link in the IP comments page heading 

feat(a2-1686): correct link for ip comments page heading

---

azure-pipelines-deploy.yml
azure-pipelines-variables.yml

With template 3.20.1, in git verify pipeline a condition is added to verify if Microsoft Easy authentication is enabled or not. Using which token needs to generated and used to get a successful HTTP response.
By default, all the values are set as below in https://github.com/Planning-Inspectorate/common-pipeline-templates/blob/main/steps/azure_web_app_verify_git_hash.yml 
- appRegistrationClientId: ""
- auth_enabled: "false"
- env: "dev"
auth_enabled must be set as true only for web application and for all backend applications it is set as false

fix(tooling): updating to common pipeline template 3.20.1

---

packages/appeals-service-api/__tests__/unit/repositories/sql/service-user-repository.test.js
packages/appeals-service-api/src/repositories/sql/service-user-repository.js
packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/appellant-final-comment-submission/submit/index.spec.js
packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/appellant-proof-evidence-submission/submit/index.spec.js
packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/representations/representations.spec.js
packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/rule-6-proof-evidence-submission/submit/index.spec.js
packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/rule-6-statement-submission/submit/index.spec.js
packages/appeals-service-api/src/routes/v2/service-users/index.spec.js
packages/appeals-service-api/src/routes/v2/service-users/service.js
packages/appeals-service-api/src/services/back-office-v2/index.js
packages/appeals-service-api/src/services/back-office-v2/index.test.js
packages/appeals-service-api/src/spec/api-types.d.ts
packages/appeals-service-api/src/spec/appeal-user.yaml
packages/database/src/migrations/20250312114533_drop_serviceuserid_from_appealuser/migration.sql
packages/database/src/schema.prisma
packages/database/src/seed/data-dev.js
packages/forms-web-app/src/lib/selected-appeal-page-setup.js
packages/forms-web-app/src/services/user.service.js

- Removes service user from appeal user, it cannot be relied upon
- Updates service user only if type is the same, should have a different record for each role on a case

fix: remove service user from appealUser and lookup via email and type

---

package-lock.json
package.json

Reverts https://github.com/Planning-Inspectorate/appeal-planning-decision/pull/4141
Due to conflict with commitizen

fix: revert commit lint due to conflict with commitizen

---

packages/common/src/lib/format-appeal-documents.js
packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-documents-rows.js
packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-documents-rows.test.js

https://pins-ds.atlassian.net/browse/A2-2544
Removes row - data handled in appeal details rows

fix(a2-2544): remove old row in appeal details

---

packages/forms-web-app/src/routes/lpa-dashboard/questionnaire.js

https://pins-ds.atlassian.net/browse/A2-2588
Allow submitted pages to be accessed after submission is complete

fix(a2-2588): allow submitted page access after submission

---

packages/appeals-service-api/data/populate-db.sh
packages/appeals-service-api/src/errors/apiError.js
packages/appeals-service-api/src/mappers/lpa-mapper.js
packages/appeals-service-api/src/routes/v2/lpa/controller.js
packages/appeals-service-api/src/routes/v2/lpa/index.js
packages/appeals-service-api/src/routes/v2/lpa/index.spec.js
packages/appeals-service-api/src/routes/v2/lpa/repo.js
packages/appeals-service-api/src/routes/v2/lpa/service.js
packages/appeals-service-api/src/routes/v2/lpa/spec.yaml
packages/appeals-service-api/src/spec/api-types.d.ts
packages/appeals-service-api/src/spec/lpa-record.yaml
packages/common/src/database/chunk-array.js
packages/database/src/migrations/20250318091501_add_lpa_collection_table/migration.sql
packages/database/src/schema.prisma
packages/database/src/seed/data-dev.js
packages/database/src/seed/lpa-dev.js

A2-1217
https://pins-ds.atlassian.net/browse/A2-1217
Create an LPA model prisma model + migration that uses the same fields as Mongo
V2 API endpoint that returns retrieves all lpas from sql
V2 API endpoint that fetches single LPA by lpaCode
V2 API endpoint that fetches single LPA by lpa19CD
V2 API endpoint that replaces the existing list of lpas with a new one
POST, takes a semi colon separated csv file, deletes all records and adds all new ones

feat: A2-1217 added lpa table and endpoints including seeding

---

packages/appeals-service-api/src/services/back-office-v2/formatters/utils.js

- Address with empty strings ended up in back office and led to case being stuck as the rebroadcast failed

fix: filter out blank addresses before sending

---

packages/forms-web-app/__tests__/unit/lib/remove-unwanted-cookies.test.js
packages/forms-web-app/__tests__/unit/middleware/remove-unwanted-cookies.test.js
packages/forms-web-app/src/consts.js
packages/forms-web-app/src/lib/remove-unwanted-cookies.js
packages/forms-web-app/src/middleware/remove-unwanted-cookies.js

The easy auth in dev is not working because subsequent requests to the service (include all assets) don't include the auth session cookie. This is because they were explicitly removed. This PR adds `AppServiceAuthSession` to the list of "cookies to keep".

fix(forms-web-app): don't remove easy-auth cookie (AppServiceAuthSession)

---

packages/common/src/constants.js
packages/common/src/frontend/pins/components/appeal-sections-block.njk
packages/common/src/lib/format-appeal-details.js
packages/common/src/lib/representations.js
packages/common/src/lib/representations.test.js
packages/common/src/view-model-maps/sections/def.d.ts
packages/common/src/view-model-maps/sections/index.js
packages/forms-web-app/src/controllers/selected-appeal/lpa-user-sections.js

https://pins-ds.atlassian.net/browse/A2-2429
Amends the sections used for generating the appeal details page (and appeal-sections-block macro) in order to display submission date for lpa submissions

feat(a2-2429): add submission date display to lpa appeal details page

---

packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/own-all-the-land.test.js
packages/forms-web-app/src/controllers/full-appeal/submit-appeal/own-all-the-land.js

A2-2242
https://pins-ds.atlassian.net/browse/A2-2242

Fix/a2 2242 ensuring unused field are made null when ownsAllLand is set to YES

---

packages/forms-web-app/src/config.js
packages/forms-web-app/src/dynamic-forms/question-props.d.ts
packages/forms-web-app/src/dynamic-forms/questions.js
packages/forms-web-app/src/dynamic-forms/validator/unit-option-entry-validator.js

A2-2575
https://pins-ds.atlassian.net/browse/A2-2575
Added additional validators for the unit option types. This is just opening the floor for a discussion on how we implement this.

feat: a2-2575 added new validation per option type

---

packages/appeals-service-api/src/configuration/config.js
packages/appeals-service-api/src/gateway/horizon-gateway.js

https://pins-ds.atlassian.net/browse/A2-2648
- Sets a timeout on the axios calls to the horizon wrapper
- Will update wrapper timeout manually when I have approval

fix(a2-2648): sets axios timeout for horizon calls

---

packages/forms-web-app/__tests__/unit/validators/full-appeal/local-planning-department.test.js
packages/forms-web-app/src/validators/full-appeal/local-planning-department.js
packages/forms-web-app/src/views/full-appeal/local-planning-department.njk

A2-2652
https://pins-ds.atlassian.net/browse/A2-2652
Fixed validation on the LPA selection to ensure we have multiple error messages depending on the error

fix: A2-2652 fixed validation on the LPA selection

---

packages/forms-web-app/src/lib/add-css-to-html.js
packages/forms-web-app/src/lib/add-css-to-html.test.js

https://pins-ds.atlassian.net/browse/A2-2959
https://pins-ds.atlassian.net/browse/A2-2960
Pdf generation inlines css, this updates it to not make a web request which is unreliable generally + fails with easy auth

fix(a2-2959): use file lookup rather than web request for rendering css

---

packages/forms-web-app/src/controllers/selected-appeal/appeal-details/index.js
packages/forms-web-app/src/controllers/selected-appeal/appeal-details/index.test.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/index.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/index.test.js
packages/forms-web-app/src/controllers/selected-appeal/representations/index.js
packages/forms-web-app/src/controllers/selected-appeal/representations/representations-controller.test.js

https://pins-ds.atlassian.net/browse/A2-3205
https://pins-ds.atlassian.net/browse/A2-3206
req.app.render doesn't pass through res.locals to the view so is missing csp nonce on scripts
switching to res.render

fix(a2-3205): fix routes using req.app.render - no res.locals

---

packages/forms-web-app/src/controllers/selected-appeal/representations/index.js

A2-1644
https://pins-ds.atlassian.net/browse/A2-1644
Removed the published check because the flag is not returned in the query but all documents returned are all published. So there is no need for the flag and if we include it, it returns published=false.

fix: removed published flag check

---

.prettierignore
packages/common/src/lib/notify/notify-service.js
packages/common/src/lib/notify/notify-service.test.js
packages/common/src/lib/notify/templates/appeal-submission/v1-follow-up-email.md
packages/common/src/lib/notify/templates/appeal-submission/v1-lpa-notification.md
packages/common/src/lib/notify/templates/appeal-submission/v1-save-and-return-continue-appeal.md
packages/common/src/lib/notify/templates/appeal-submission/v1-submission-email.md
packages/common/src/lib/notify/templates/appeal-submission/v2-follow-up-email.md
packages/common/src/lib/notify/templates/appeal-submission/v2-lpa-notification.md
packages/common/src/lib/notify/templates/appeal-submission/v2-registration-confirmation.md
packages/common/src/lib/notify/templates/appeal-submission/v2-submission-email.md
packages/common/src/lib/notify/templates/lpaq/v2-lpaq-submitted.md
packages/common/src/lib/notify/templates/representations/v2-appellant-final-comments.md
packages/common/src/lib/notify/templates/representations/v2-ip-comment-submitted.md
packages/common/src/lib/notify/templates/representations/v2-lpa-final-comments.md
packages/common/src/lib/notify/templates/representations/v2-lpa-proofs-evidence.md
packages/common/src/lib/notify/templates/representations/v2-lpa-statement.md
packages/common/src/lib/notify/templates/representations/v2-proof-of-evidence-submitted.md
packages/common/src/lib/notify/templates/representations/v2-r6-proofs-evidence.md
packages/common/src/lib/notify/templates/representations/v2-rule6-statement-submission.md

https://pins-ds.atlassian.net/browse/A2-3208
Switches to uses nunjucks templating engine for notify template construction
Based off of: https://github.com/Planning-Inspectorate/appeals-back-office/pull/1301/files

chore(a2-3208): use nunjucks template engine for notify templates

---

azure-pipelines-pr.yml

Run PR pipeline only when npm package or source code changes
To reduce run costs on agents when not required

chore: skip PR pipeline outside of npm/src code changes

---

packages/forms-web-app/src/dynamic-forms/has-questionnaire/journey.js

Adds relevant policies from statutory development plan boolean and upload pages to HAS LPAQ
Ticket: https://pins-ds.atlassian.net.mcas.ms/jira/software/c/projects/A2/boards/246?assignee=712020%3A04186e0f-84cf-4604-835a-10ec7cfafa90&selectedIssue=A2-3421

Relevant policies from statutory development plan boolean and upload pages missing from HAS LPAQ

---

packages/auth-server/__tests__/tests.spec.js
packages/auth-server/src/account/account.js
packages/common/src/client/auth-client.js
packages/common/src/client/auth-client.test.js
packages/common/src/constants.js
packages/forms-web-app/__tests__/unit/controllers/common/enter-code.test.js
packages/forms-web-app/__tests__/unit/lib/is-token-valid.test.js
packages/forms-web-app/src/controllers/common/enter-code.js
packages/forms-web-app/src/lib/is-token-valid.js

Ticket: https://pins-ds.atlassian.net/browse/A2-3237

fix(a2-3237): only provide lpa details for lpa dashboard login

---

packages/common/src/view-model-maps/events.js
packages/common/src/view-model-maps/events.test.js

Added hearing event cancellation message to be displayed to users.
Ticket: https://pins-ds.atlassian.net/browse/A2-3633

Feature/a2 3633 - Added hearing event cancellation message to be displayed to the users

---

packages/forms-web-app/src/middleware/create-api-clients.js
packages/forms-web-app/src/middleware/create-api-clients.test.js
packages/integration-functions/src/common/api-client.js

Ticket: https://pins-ds.atlassian.net/browse/A2-3639
OpenId client used to provide a relative expiry, it is now just the expires_in from the token, meaning we never know it's expired
This restores the expiry checking functionality
We don't share code between the app and functions which is why there is duplication

fix(a2-3639): handle openid-client expiry breaking change

---

package-lock.json
package.json

Forgot to bump this with prisma client dependabot update

chore: bump prisma to match prisma client

---

packages/forms-web-app/__tests__/unit/controllers/before-you-start/can-use-service.test.js
packages/forms-web-app/src/lib/get-appeal-props-for-can-use-service-page.js
packages/forms-web-app/src/lib/get-next-page-from-can-use-service-page.js
packages/forms-web-app/src/lib/get-next-page-from-can-use-service-page.test.js

- Redirecting to email-address page instead
- Ensured that for V1 versions, the user still gets redirected to application number page since this isn't asked inside the appeal form
- Updated tests since now checking feature flags so function has become async
Ticket: https://pins-ds.atlassian.net/browse/A2-3744

feat(A2-3744): removing application-reference from BYS journey

---

package-lock.json
packages/appeals-service-api/package.json
packages/auth-server/package.json
packages/business-rules/README.md
packages/business-rules/package.json
packages/common/README.md
packages/database/package.json
packages/document-service-api/package.json
packages/forms-web-app/package.json
packages/integration-functions/package.json

Use workspace imports instead of file references
Tested in [dev](https://dev.azure.com/planninginspectorate/appeal-planning-decision/_build/results?buildId=120528&view=results)

chore(deps): use workspace imports

---

packages/database/src/seed/seed-appeal.js

Overwritten lpaq date stops lpaq link from appearing on seeded data

fix: lpaq due date set in seeded data

---

packages/forms-web-app/__tests__/unit/controllers/common/enter-code.test.js
packages/forms-web-app/__tests__/unit/controllers/common/your-email-address.test.js
packages/forms-web-app/src/controllers/common/enter-code.js
packages/forms-web-app/src/controllers/common/your-email-address.js
packages/forms-web-app/src/lib/map-cache.js
packages/forms-web-app/src/lib/map-cache.test.js
packages/forms-web-app/src/routes/lpa-dashboard/your-email-address.js

Making it so that all emails entered for the LPA login redirect to the enter code page but only LPA emails get sent a code and are able to login, in order to obscure information about the database.
Emails not in the database are given a UUID which is cached for 5 minutes
Updated inconsistent error code message
Ticket: https://pins-ds.atlassian.net/browse/A2-1450

feat(web): removing error message for non user (A2-1450)

---

packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-documents-rows.js
packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-documents-rows.test.js

Updating the conditions on the document row fields so those that show for S78 show for S20 too
Updating the tests to cover the rows which have been included in this change
Ticket: https://pins-ds.atlassian.net/browse/A2-3849

feat: updating document rows to match S78 for S20 (A2-3849)

---

packages/forms-web-app/src/dynamic-forms/questions.js

Fixes copy issue in S20 preserve grant loan question
Ticket: https://pins-ds.atlassian.net/browse/A2-3937

fix(forms-web-app): error copy for preserve grant loan question a2-3426

---

structurizr/workspace.dsl

Fix structurizr tag definition

fix: structurizer tag

---

packages/appeals-service-api/src/routes/v2/appeal-cases/_caseReference/lpa-questionnaire-submission/submit/controller.js
packages/appeals-service-api/src/routes/v2/appeal-cases/service.js
packages/appeals-service-api/src/services/back-office-v2/formatters/cas-planning/questionnaire.js
packages/appeals-service-api/src/services/back-office-v2/formatters/cas-planning/questionnaire.test.js
packages/appeals-service-api/src/services/back-office-v2/formatters/utils.js

Adds integration mapping for cas planning lpaq 
Ticket: https://pins-ds.atlassian.net/browse/A2-3461

feat(appeals-service-api): cas planning lpaq integrations a2-3461

---

packages/common/src/dynamic-forms/journey-types.js
packages/forms-web-app/src/dynamic-forms/cas-adverts-appeal-form/journey.js
packages/forms-web-app/src/dynamic-forms/cas-adverts-appeal-form/journey.test.js

Adds cas adverts appeal form
Ticket: https://pins-ds.atlassian.net/browse/A2-3653

feat(forms-web-app): a2-3653 cas adverts appeal form

---

packages/appeals-service-api/src/routes/v2/appellant-submissions/_id/submit/controller.js

Makes use of cas planning appeal formatter to fix incorrect appeal type being broadcast to BO 
Ticket: https://pins-ds.atlassian.net/browse/A2-4133

fix: a2-4133 use cas planning appeal formatter

---

packages/forms-web-app/src/lib/representation-functions.js
packages/forms-web-app/src/lib/representation-functions.test.js

Truncation could happen in middle of `<br>` tag leading to broken html/read more button
Ticket: https://pins-ds.atlassian.net/browse/A2-4142

fix(a2-4142): avoid html line break in truncated text

---

packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-details-rows.js
packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-documents-rows.js

Displays relevant cas planning appeal details on dashboards
Ticket: https://pins-ds.atlassian.net/browse/A2-3748

feat: a2-3748 cas planning appeal details dashboard

---

packages/forms-web-app/src/dynamic-forms/docs/cas-adverts-appeal-form-journey.md
packages/forms-web-app/src/dynamic-forms/questions.js
packages/forms-web-app/src/journeys/__snapshots__/index.test.js.snap

There was an error when trying to answer the highway land question:
This fixes this and makes sure the behaviour is as in the ticket: https://pins-ds.atlassian.net/browse/A2-3770

fix: changing highway land question from radio to boolean

---

packages/appeals-service-api/data/lpa-list.csv

Removes Wycombe from the lpa picker for users
Ticket: https://pins-ds.atlassian.net/browse/A2-4228

fix: remove wycombe

---

packages/appeals-service-api/src/routes/v2/appeal-cases/service.js

Amends incorrect cas planning appeal type
Ticket: https://pins-ds.atlassian.net/browse/A2-4188

fix: a2-4188 cas planning integration appealType

---

packages/appeals-service-api/src/services/appeal.service.js
packages/business-rules/src/constants.js
packages/business-rules/src/schemas/validate.js
packages/common/src/dynamic-forms/journey-types.js
packages/forms-web-app/__tests__/unit/controllers/before-you-start/can-use-service.test.js
packages/forms-web-app/__tests__/unit/controllers/full-appeal/granted-or-refused.test.js
packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/email-address-confirmed.test.js
packages/forms-web-app/__tests__/unit/controllers/full-appeal/type-of-planning-application.test.js
packages/forms-web-app/src/controllers/before-you-start/can-use-service.js
packages/forms-web-app/src/controllers/full-appeal/granted-or-refused.js
packages/forms-web-app/src/controllers/full-appeal/type-of-planning-application.js
packages/forms-web-app/src/journeys/__snapshots__/index.test.js.snap
packages/forms-web-app/src/lib/get-next-page-from-can-use-service-page.js
packages/forms-web-app/src/lib/get-next-page-from-can-use-service-page.test.js
packages/forms-web-app/src/lib/type-of-planning-application-radio-items.js
packages/forms-web-app/src/lib/type-of-planning-application-radio-items.test.js

- Removing MINOR_COMMERCIAL_ADVERTISEMENT as a type of planning application
- Adding logic to set the appeal type depending on the answer to the 'granted or refused' question
- Making sure behaviour was correct when different combinations of cas advert and advert feature flags are enabled
- Making sure that both CAS advert and advert are able to access the appeal form
- Updating/adding relevant tests
Ticket: https://pins-ds.atlassian.net/browse/A2-3652
Updated various tests
Manual testing:
- CAS advert: false
- Advert: false
'Displaying an advertisement' does not show up as an option in the 'What type of application is your appeal about?' radio
- CAS advert: true
- Advert: false
'Displaying an advertisement' does show up as an option in the 'What type of application is your appeal about?' …

feat: cas advert and advert bys logic (A2-3652)

---

packages/appeals-service-api/__tests__/developer/fixtures/appeals-cas-planning-data-model.js
packages/appeals-service-api/src/routes/v2/appeal-cases/appeal-cases.spec.js
packages/appeals-service-api/src/services/back-office-v2/index.test.js

- Adding CAS planning to the test cases for the notify templates
- Updating the arrays passed into the loops to give clearer test titles
Ticket: https://pins-ds.atlassian.net/browse/A2-3664

test(api): adding tests for CAS planning notifies (A2-3664)

---

packages/common/src/constants.js
packages/forms-web-app/src/lib/dashboard-functions.js
packages/forms-web-app/src/lib/dashboard-functions.test.js

On dashboards child appeals should move in sync with lead appeals (and submissions are made against the lead), and so on dashboards we replace the child next journey due with the lead next journey due.  The exception is for Questionnaires, where an LPAQ is submitted in respect of each appeal.  This PR prevents child Questionnaire journeys updating.
Ticket: https://pins-ds.atlassian.net/browse/A2-4205

fix(a2-4205): amend update child next journey function for dashboards

---

packages/appeals-service-api/src/spec/api-types.d.ts
packages/appeals-service-api/src/spec/appeal-case.yaml
packages/common/src/view-model-maps/appeal-headline.js
packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-before-you-start-rows.js
packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-before-you-start-rows.test.js
packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-details-rows.js
packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-details-rows.test.js
packages/forms-web-app/src/controllers/selected-appeal/appeal-details/index.js
packages/forms-web-app/src/controllers/selected-appeal/appeal-details/index.test.js
packages/forms-web-app/src/controllers/selected-appeal/planning-obligation-details/index.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/index.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/index.test.js
packages/forms-web-app/src/controllers/selected-appeal/representations/index.js
packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/appeals/_appealNumber/controller.js
packages/forms-web-app/src/routes/file-based-router/comment-planning-appeal/appeals/_appealNumber/controller.test.js
packages/forms-web-app/src/views/selected-appeal/appeal-details.njk

- Added new BYSD section to the appeal details page
- Adding new field to AppealCase Model to map the typeOfApplication (we already collect this) 
- Making lpa name optional since this is not needed in selected-appeals appeal-details but used in other sections
Ticket: https://pins-ds.atlassian.net/browse/A2-4148

Feat(4148): Adding bys section to selected appeal details

---

packages/forms-web-app/src/controllers/selected-appeal/index.js

Sorts order of decision documents for display on appeal pages
Ticket: https://pins-ds.atlassian.net/browse/A2-4225

fix(A2-4225): sort display order of decision documents

---

packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/appeal-process-details.test.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/constraints-details-rows.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/constraints-details-rows.test.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/consultation-details-rows.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/consultation-details-rows.test.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/environmental-details-rows.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/environmental-details-rows.test.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/notified-details-rows.test.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/planning-officer-details-rows.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/planning-officer-details-rows.test.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/site-access-details-rows.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/site-access-details-rows.test.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/test-factory.js
packages/forms-web-app/src/controllers/selected-appeal/questionnaire-details/test-factory.test.js

Adds relevant cas planning questionnaire rows to the dashboards. Refactors generation of lpaq test data into factory function
Ticket: https://pins-ds.atlassian.net/browse/A2-3746

feat: a2-3746_cas_planning_questionnaire_dashboard

---

packages/appeals-service-api/src/spec/api-types.d.ts
packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-before-you-start-rows.js
packages/forms-web-app/src/controllers/selected-appeal/appeal-details/appeal-before-you-start-rows.test.js

- Toggling application data question for not_received outcome
- Added unit test for this scenario 
Ticket: https://pins-ds.atlassian.net/browse/A2-4149

feat(4149): toggle bys application decision question depending on original decision

---

infrastructure/front-door.tf

Further testing with prod example has found the other unix injection rule is also likely to be triggered by normal users
Ticket: https://pins-ds.atlassian.net/browse/A2-4244

fix(a2-4244): switch unix rule to logging mode

---

packages/business-rules/src/lib/filter-transferred-appeal.js
packages/business-rules/src/lib/filter-transferred-appeal.test.js
packages/forms-web-app/src/controllers/appeals/your-appeals.js
packages/forms-web-app/src/controllers/lpa-dashboard/your-appeals.js
packages/forms-web-app/src/controllers/rule-6/your-appeals.js

Add filter for transferred appeals and apply on dashboards
Ticket: https://pins-ds.atlassian.net/browse/A2-3882

feat(a2-3882): filter transferred cases from display on dashboards

---

packages/integration-functions/__tests__/functions/appeal-document.test.js
packages/integration-functions/src/functions/appeal-document.js

Ignore invalid messages for delete messages as they won't have been imported
Ticket: https://pins-ds.atlassian.net/browse/A2-4074

fix(a2-4074): ignore delete requests for invalid docs

---

packages/appeals-service-api/src/routes/v2/appeal-cases/repo.js
packages/appeals-service-api/src/routes/v2/appeals/repo.js

Add caseTransferredDate to data retrieved for purpose of dashboard displays.
Ticket: https://pins-ds.atlassian.net/browse/A2-3882

fix(a2-3882): add caseTransferredDate to dashboard display data

---

packages/forms-web-app/src/views/appeals/your-appeals/decided-appeals.njk
packages/forms-web-app/src/views/manage-appeals/decided-appeals.njk

Show 'Lead' and 'Child' tags on decided appeal dashboards for Appellant and LPA
Ticket: https://pins-ds.atlassian.net/browse/A2-4307

feat(a2-4307): show linked case status on decided appeals dashboard

---

packages/forms-web-app/src/dynamic-forms/questions.js
test-packages/platform-feature-tests/cypress/e2e/lpa-manage-appeals/full-appeal-questionnaire-validation.cy.js

Updates error message for national landscape page
Ticket: https://pins-ds.atlassian.net/browse/A2-4084

fix(a2-4084): update error message for national landscape
